:_module-type: CONCEPT

[id='new-file-test_{context}']
= New file test

ifdef::upstream,self-managed[]
If you have administrator access to {openshift-platform}, you can revoke a user's access to Jupyter and delete the user's resources from {productname-long}.
endif::[]

ifdef::cloud-service[]
If you have administrator access to OpenShift, you can revoke a user's access to Jupyter and delete the user's resources from {productname-long}.
endif::[]

Deleting a user and the user's resources involves the following tasks:

* Before you delete a user from {productname-short}, it is good practice to back up the data on your persistent volume claims (PVCs). 

* Stop notebook servers owned by the user.

* Revoke user access to Jupyter.

* Remove the user from the allowed group in your OpenShift identity provider.

ifdef::upstream,self-managed[]
* After you delete a user, delete their associated configuration files from {openshift-platform}.
endif::[]
ifdef::cloud-service[]
* After you delete a user, delete their associated configuration files from OpenShift.
endif::[]
