:_module-type: CONCEPT

[id='about-the-python-index_{context}']
= About the {org-name} Python index

{org-name} AI includes a maintained Python package index that provides secure and reliable access to supported libraries, with full support for disconnected environments.
ifdef::upstream[]
For details about {org-name} support for the Python package, see link:{odhdocshome}/customize-models-to-build-gen-ai-applications/#support-philosophy_custom-models[Support philosophy: A secure platform].
endif::[]
ifndef::upstream[]
For details about {org-name} support for the Python package index, see link:{rhoaidocshome}{default-format-url}/customize_models_to_build_gen_ai_applications/support-philosophy_custom-models[Support philosophy: A secure platform].
endif::[]

Table 2.1 lists the images that are configured to use the {org-name} Python index.

.Images configured to use the {org-name} Python index
[options="header", cols="1,2,2,2"]
|===
|Accelerator UBI9 | List of packages | Registry URL | Catalog URL

|CPU
|https://console.redhat.com/api/pypi/public-rhai/rhoai/3.3/cpu-ubi9/simple/
|registry.redhat.io/rhai/base-image-cpu-rhel9:3.3.0-1771879589
|https://catalog.redhat.com/en/software/containers/rhai/base-image-cpu-rhel9/690377f9d1c73dd1e81192f0

|CUDA 12.9
|https://console.redhat.com/api/pypi/public-rhai/rhoai/3.3/cuda12.9-ubi9/simple/
|registry.redhat.io/rhai/base-image-cuda-12.9-rhel9:3.3.0-1771879204
|https://catalog.redhat.com/en/software/containers/rhai/base-image-cuda-12.9-rhel9/697afa2896a99d8531fb3212

|CUDA 13.0
|https://console.redhat.com/api/pypi/public-rhai/rhoai/3.3/cuda13.0-ubi9/simple/
|registry.redhat.io/rhai/base-image-cuda-13.0-rhel9:3.3.0-1771879618
|https://catalog.redhat.com/en/software/containers/rhai/base-image-cuda-13.0-rhel9/697afa2871e1ee36cfe24ce5

|ROCm
|https://console.redhat.com/api/pypi/public-rhai/rhoai/3.3/rocm6.4-ubi9/simple/
|registry.redhat.io/rhai/base-image-rocm-6.4-rhel9:3.3.0-1771879436
|https://catalog.redhat.com/en/software/containers/rhai/base-image-rocm-6.4-rhel9/697afa29b684f43afdb760ef
|===

*Notes:*

* NVIDIA CUDA, AMD GPU, and AMD ROCm RPM repositories are configured, but disabled.
* The images listed in Table 2.1 have RHEL RPM repositories enabled. A RHEL RPM is a package file used for the {org-name} Package Manager system on {org-name} Enterprise Linux (RHEL). An RPM file contains all the necessary components for an application, such as executable files, configuration files, and documentation. It simplifies the process of distributing, installing, and managing software by bundling everything into a single, standalone file.
+
You can install additional RPMs, but you must have a {org-name} Extended Update Support (EUS) subscription and you must run your container image in root mode (for example, `podman run --user 0`).
+
For more information about {org-name} Package Manager, see link:https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/packaging_and_distributing_software/introduction-to-rpm_packaging-and-distributing-software[Introduction to RPM].
