:_module-type: CONCEPT

[id="about-the-model-serving-platform_{context}"]
= About the model serving platform

[role="_abstract"]
The model serving platform is based on link:https://github.com/opendatahub-io/kserve[KServe^], a Kubernetes custom resource definition (CRD) that orchestrates model serving for all types of models. It includes model-serving runtimes that implement the loading of given types of model servers. KServe handles the lifecycle of the deployment object, storage access, and networking setup.

To install the model serving platform, you have the following options:

Automated installation:: If you have not already created a `ServiceMeshControlPlane` or `KNativeServing` resource on your OpenShift cluster, you can configure the {productname-long} Operator to install KServe and configure its dependencies.

Manual installation:: If you have already created a `ServiceMeshControlPlane` or `KNativeServing` resource on your OpenShift cluster, you _cannot_ configure the {productname-long} Operator to install KServe and configure its dependencies. In this situation, you must install KServe manually.

When you have installed KServe, you can use the {productname-short} dashboard to deploy models using preinstalled or custom model-serving runtimes. 

ifdef::upstream[]
{productname-short} includes preinstalled runtimes for KServe. For more information, see link:{odhdocshome}/configuring-your-model-serving-platform/#ref-supported-runtimes_odh-admin[Supported model-serving runtimes].
endif::[]

ifndef::upstream[]
{productname-short} includes preinstalled runtimes for KServe. For more information, see link:{rhoaidocshome}{default-format-url}/configuring_your_model-serving_platform/configuring-your-model-serving-platform_rhoai-admin#supported-model-serving-runtimes_rhoai-admin[Supported model-serving runtimes].
endif::[]

You can also configure monitoring for the model serving platform and use Prometheus to scrape the available metrics.

// [role="_additional-resources"]
// .Additional resources
