:_module-type: CONCEPT

[id="about-pipeline-logs_{context}"]
= About pipeline logs

[role="_abstract"]
You can review and analyze step logs for each step in a triggered pipeline run.

To help you troubleshoot and audit your pipelines, you can review and analyze these step logs by using the log viewer in the {productname-short} dashboard. From here, you can search for specific log messages, stop or start the step log for pipeline runs that are in progress, and download the step logs to your local machine.

The log viewer refreshes every three seconds. Each step log displays the last 500 lines of log messages received. If the step log file exceeds 500 lines, a notification message appears above the log viewer informing you of this. You can view the full step log by downloading it, or by opening it in a separate browser window. 

Each step log can display a variety of messages, including the following:

* Error messages for failed pods and skipped nodes in a pipeline run
* The state of the container running the pipeline step
* The time limit of a pod clean-up (the duration that the pod remains active)

// [role="_additional-resources"]
// .Additional resources
