:_module-type: CONCEPT

[id='about-kserve-deployment-modes_{context}']
= About KServe deployment modes

You can deploy models in either **advanced** or **standard** deployment mode.

Advanced deployment mode uses Knative Serverless. By default, KServe integrates with {org-name} OpenShift Serverless and Red Hat OpenShift Service Mesh to deploy models on the single-model serving platform. {org-name} Serverless is based on the open source link:https://knative.dev/docs/[Knative^] project and requires the {org-name} OpenShift Serverless Operator.

Alternatively, you can use Standard deployment mode, which uses KServe RawDeployment mode and does not require the {org-name} OpenShift Serverless Operator or {org-name} OpenShift Service Mesh. 

If you configure KServe for **advanced** deployment mode, you can set up your data science project to serve models in both **advanced** and **standard** deployment mode. However, if you configure KServe for only **standard** deployment mode, you can only use **standard** deployment mode.

There are both advantages and disadvantages to using each of these deployment modes:

== Advanced mode

Advantages:

* Enables autoscaling based on request volume: 
** Resources scale up automatically when receiving incoming requests.
** Optimizes resource usage and maintains performance during peak times.

* Supports scale down to and from zero using Knative:
** Allows resources to scale down completely when there are no incoming requests.
** Saves costs by not running idle resources.

Disadvantages:

* Has customization limitations:
** Serverless is backed by Knative and implicitly inherits the same design choices, such as when mounting multiple volumes.
* Dependency on Knative for scaling:
** Introduces additional complexity in setup and management compared to traditional scaling methods.
* Cluster scoped component:
** If the cluster already has Serverless configured, you must manually configure the cluster to make it work with {productname-short}.

== Standard mode

Advantages:

* Enables deployment with Kubernetes resources, such as `Deployment`, `Service`, `Ingress`, and `Horizontal Pod Autoscaler`, without additional dependencies like {org-name} Serverless and {org-name} Service Mesh.

* Enables traditional Deployment/Pod configurations not available using Knative, such as being unable to mount multiple volumes:
** Beneficial for applications requiring complex configurations or multiple storage mounts.

Disadvantages:

* Does not support automatic scaling:
** Does not support automatic scaling down to zero resources when idle.
** Might result in higher costs during periods of low traffic.
