:_module-type: CONCEPT

[id="about-pipeline-logs_{context}"]
= About pipeline logs

[role="_abstract"]
You can review and analyze step logs for each step in a triggered pipeline run.

To help you troubleshoot and audit your pipelines, you can review and analyze these step logs by using the log viewer in the {productname-short} dashboard. From here, you can search for specific log messages, view the log for each step, and download the step logs to your local machine.

If the step log file exceeds its capacity, a warning appears above the log viewer stating that the log window displays partial content. Expanding the warning displays further information, such as how the log viewer refreshes every three seconds, and that each step log displays the last 500 lines of log messages received. In addition, you can click *download all step logs* to download all step logs to your local machine. 

Each step has a set of container logs. You can view these container logs by selecting a container from the *Steps* list in the log viewer. The `Step-main` container log consists of the log output for the step. The `step-copy-artifact` container log consists of output relating to artifact data sent to s3-compatible storage. If the data transferred between the steps in your pipeline is larger than 3 KB, five container logs are typically available. These logs contain output relating to data transferred between your persistent volume claims (PVCs).

// [role="_additional-resources"]
// .Additional resources
