:_module-type: PROCEDURE

[id='accessing-s3-compatible-object-storage-with-self-signed-certificates_{context}']
= Accessing S3-compatible object storage with self-signed certificates

[role='_abstract']
To securely connect {productname-short} components to object storage solutions or databases that are deployed within an OpenShift cluster that uses self-signed certificates, you must provide a certificate authority (CA) certificate. Each namespace includes a ConfigMap named `kube-root-ca.crt`, which contains the CA certificate of the internal API Server.

.Prerequisites
* You have cluster administrator privileges for your {openshift-platform} cluster.
* You have installed the OpenShift command-line interface (CLI). See link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI^].
* You have deployed an object storage solution or database in your OpenShift cluster.

.Procedure
. In a terminal window, log in to the OpenShift CLI as shown in the following example:
+
[source]
----
oc login api.<cluster_name>.<cluster_domain>:6443 --web
----
. Retrieve the current {productname-short} trusted CA configuration and store it in a new file:
+
[source]
----
oc get dscinitializations.dscinitialization.opendatahub.io default-dsci -o json | jq -r '.spec.trustedCABundle.customCABundle' > /tmp/my-custom-ca-bundles.crt
----
. Add the cluster's `kube-root-ca.crt` ConfigMap to the {productname-short} trusted CA configuration:
+
[source]
----
oc get configmap kube-root-ca.crt -o jsonpath="{['data']['ca\.crt']}" >> /tmp/my-custom-ca-bundles.crt
----
. Update the {productname-short} trusted CA configuration to trust certificates issued by the certificate authorities in `kube-root-ca.crt`:
+
[source]
----
oc patch dscinitialization default-dsci --type='json' -p='[{"op":"replace","path":"/spec/trustedCABundle/customCABundle","value":"'"$(awk '{printf "%s\\n", $0}' /tmp/my-custom-ca-bundles.crt)"'"}]'
----

.Verification

* You can successfully deploy components that are configured to use object storage solutions or databases that are deployed in the OpenShift cluster. For example, a pipeline server that is configured to use a database deployed in the cluster starts successfully.

ifndef::upstream[]
[NOTE]
====
You can verify your new certificate configuration by following the steps in the _{productname-short} tutorial - Fraud Detection example_. Run the script to install local object storage buckets and create connections, and then enable data science pipelines.

For more information about running the script to install local object storage buckets, see link:{rhoaidocshome}{default-format-url}/openshift_ai_tutorial_-_fraud_detection_example/setting-up-a-project-and-storage#running-a-script-to-install-storage[Running a script to install local object storage buckets and create connections]. 

For more information about enabling data science pipelines, see link:{rhoaidocshome}{default-format-url}/openshift_ai_tutorial_-_fraud_detection_example/setting-up-a-project-and-storage#enabling-data-science-pipelines[Enabling data science pipelines].
====
endif::[]

