:_module-type: PROCEDURE

[id='accessing-the-administration-interface-for-basic-workbenches_{context}']
= Accessing the administration interface for basic workbenches

[role='_abstract']
You can use the administration interface to control basic workbenches in your {productname-long} environment.

.Prerequisite

* You have logged in to {productname-short} as a user with {productname-short} administrator privileges. 

.Procedure
To access the administration interface for basic workbenches from {productname-short}, perform the following actions:

. In {productname-short}, in the *Applications* section of the left menu, click *Enabled*.
. Locate the *Start basic workbench* tile and click *Open application*.
. On the page that opens, click the *Administration* tab.
+
The *Administration* page opens.

////
Removing until RHOAIENG-31369 is resolved
** To access the administration interface for basic workbenches from JupyterLab, perform the following actions:
... Click *File* -> *Hub Control Panel*.
... On the page that opens in {productname-short}, click the *Administration* tab. 
+
The *Administration* page opens.
////

.Verification

* You can see the administration interface for basic workbenches.
