:_module-type: PROCEDURE

[id='accessing-the-notebook-administration-interface_{context}']
= Accessing the notebook administration interface

[role='_abstract']
You can use the notebook administration interface to control notebook servers in your {productname-long} environment.

.Prerequisite
ifdef::upstream[]
* You are part of the {openshift-platform} administrator group.
endif::[]

ifndef::upstream[]
* You are part of the {openshift-platform} administrator group. For more information, see link:{rhoaidocshome}{default-format-url}/installing_and_uninstalling_{url-productname-short}/installing-and-deploying-openshift-ai_install#adding-administrative-users-in-openshift_install[Adding administrative users in {openshift-platform}].
endif::[]

.Procedure
** To access the notebook administration interface from {productname-short}, perform the following actions:
... In {productname-short}, in the *Applications* section of the left menu, click *Enabled*.
... Locate the Jupyter tile and click *Launch application*.
... On the page that opens when you launch Jupyter, click the *Administration* tab.
+
The *Administration* page opens.

** To access the notebook administration interface from JupyterLab, perform the following actions:
... Click *File* -> *Hub Control Panel*.
... On the page that opens in {productname-short}, click the *Administration* tab. 
+
The *Administration* page opens.

.Verification

* You can see the notebook administration interface.
