:_module-type: PROCEDURE

[id="accessing-inference-endpoint-for-deployed-model_{context}"]
= Accessing the inference endpoint for a deployed model

[role='_abstract']
To make inference requests to your deployed model, you must know how to access the inference endpoint that is available.

ifdef::upstream[]
For a list of paths to use with the supported runtimes and example commands, see link:{odhdocshome}/serving-models/#inference-endpoints_serving-large-models[Inference endpoints].
endif::[]
ifndef::upstream[]
For a list of paths to use with the supported runtimes and example commands, see link:{rhoaidocshome}{default-format-url}/serving_models/serving-large-models_serving-large-models#inference-endpoints_serving-large-models[Inference endpoints].
endif::[]

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have deployed a model by using the single-model serving platform.
* If you enabled token authorization for your deployed model, you have the associated token value.

.Procedure
. From the {productname-short} dashboard, click *Model Serving*.
+
The inference endpoint for the model is shown in the *Inference endpoint* field.
. Depending on what action you want to perform with the model (and if the model supports that action), copy the inference endpoint and then add a path to the end of the URL.
. Use the endpoint to make API requests to your deployed model.

[role='_additional-resources']
.Additional resources
* link:https://github.com/IBM/text-generation-inference[Text Generation Inference Server (TGIS)^]
* link:https://caikit.readthedocs.io/en/latest/autoapi/caikit/index.html[Caikit API documentation^]
* link:https://github.com/markstur/caikit-embeddings[Caikit Text Embedding GitHub project^]
* link:https://docs.openvino.ai/2023.3/ovms_docs_rest_api_kfs.html[OpenVINO KServe-compatible REST API documentation^]
* link:https://platform.openai.com/docs/api-reference/introduction[OpenAI API documentation]
