:_module-type: PROCEDURE

[id='accessing-the-jupyter-administration-interface_{context}']
= Accessing the Jupyter administration interface

[role='_abstract']
You can use the Jupyter administration interface to control notebook servers in your {productname-long} environment.

.Prerequisite

* You have logged in to {productname-short} as a user with {productname-short} administrator privileges. 

.Procedure
** To access the Jupyter administration interface from {productname-short}, perform the following actions:
... In {productname-short}, in the *Applications* section of the left menu, click *Enabled*.
... Locate the Jupyter tile and click *Launch application*.
... On the page that opens when you launch Jupyter, click the *Administration* tab.
+
The *Administration* page opens.

** To access the Jupyter administration interface from JupyterLab, perform the following actions:
... Click *File* -> *Hub Control Panel*.
... On the page that opens in {productname-short}, click the *Administration* tab. 
+
The *Administration* page opens.

.Verification

* You can see the Jupyter administration interface.
