:_module-type: PROCEDURE

[id="adding-cluster-storage-to-your-data-science-project_{context}"]
= Adding cluster storage to your data science project

[role='_abstract']
For data science projects that require data to be retained, you can add cluster storage to the project. Additionally, you can also connect cluster storage to a specific project's workbench.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have created a data science project that you can add cluster storage to.

.Procedure
. From the {productname-short} dashboard, click *Data science projects*.
+
The *Data science projects* page opens.
. Click the name of the project that you want to add the cluster storage to.
+
A project details page opens.
. Click the *Cluster storage* tab.
. Click *Add cluster storage*.
+
The *Add cluster storage* dialog opens.
. In the *Name* field, enter a unique name for the cluster storage.
. Optional: In the *Description* field, enter a description for the cluster storage.
. Optional: From the *Storage class* list, select the type of cluster storage.
+
NOTE: You cannot change the storage class after you add the cluster storage to the project.
. Optional: From the admin enabled access modes, select the type of *Access mode*.
* ReadWriteOnce (RWO): Selected by default. The storage can be attached to a single workbench at a given time.
* ReadWriteMany (RWX): The storage can be attached to many workbenches simultaneously.
* ReadOnlyMany (ROX): The storage can be attached to many workbenches as read-only.
* ReadWriteOncePod (RWOP): The storage can be attached to a single pod on a single node as read-write.
+
NOTE: Only the access modes enabled by the admin will be visible.

. In the *Persistent storage size* section, specify a new size in gibibytes or mebibytes.
. Optional: If you want to connect the cluster storage to an existing workbench:
.. From the *Connected workbench* list, select a workbench.
.. In the *Mount folder name* field, enter the name of storage directory.
. Click *Add storage*.

.Verification
* The cluster storage that you added appears on the *Cluster storage* tab for the project.
* A new persistent volume claim (PVC) is created with the storage size that you defined.
* The persistent volume claim (PVC) is visible as an attached storage on the *Workbenches* tab for the project.

//[role='_additional-resources']
//.Additional resources
