:_module-type: PROCEDURE
//Self-managed only

[id="adding-a-ca-bundle-after-upgrading_{context}"]
= Adding a CA bundle after upgrading

[role='_abstract']
ifndef::upstream[]
{productname-long} {vernum} provides support for using self-signed certificates. If you have upgraded from {productname-short} 2.7 or earlier versions, you can add self-signed certificates to the {productname-short} deployments and Data Science Projects in your cluster. 
endif:[]

ifdef::upstream[]
{productname-long} provides support for using self-signed certificates. If you have upgraded {productname-short}, you can add self-signed certificates to the {productname-short} deployments and Data Science Projects in your cluster. 
endif:[]

.Prerequisites
* You have cluster administrator privileges for your {openshift-platform} cluster.
* You installed the OpenShift command line interface (`oc`) as described in link:https://docs.openshift.com/container-platform/{ocp-latest-version}/cli_reference/openshift_cli/getting-started-cli.html[Get Started with the CLI].
ifndef::upstream[]
* You upgraded {productname-long} from version 2.7 or earlier. If you are working in a new installation of {productname-long}, see xref:adding-a-ca-bundle_certs[Adding a CA bundle] instead.
endif:[]
ifdef::upstream[]
* You upgraded {productname-long}. If you are working in a new installation of {productname-long}, see xref:adding-a-ca-bundle_certs[Adding a CA bundle] instead.
endif:[]

.Procedure
. Log in to the {openshift-platform} as a cluster administrator.
. Use the following information to add your self-signed certificates to the cluster-wide trusted CA bundle, as described in link:https://docs.openshift.com/container-platform/{ocp-latest-version}/networking/configuring-a-custom-pki.html[Configuring a custom PKI]:
.. Create a new ConfigMap in the `openshift-config` namespace with the PEM(s) bundle stored in `.data.ca-bundle.crt`.
.. Edit the proxy/cluster object to set `.spec.trustedCA.name:<new ConfigMap name>`.
+ 
This ensures that any ConfigMap in the cluster with the label `config.openshift.io/inject-trusted-cabundle: "true"` is automatically updated to include your self-signed certificates.
. Click *Operators* → *Installed Operators* and then click the {productname-long} Operator.
. Click the *DSC Initialization* tab.
. Click the *default-dsci* object.
. Click the *YAML* tab.
. Add the following to the `spec` section, setting the `managementState` field to `Managed`:
+
[source]
----
spec:
  trustedCABundle:
    managementState: Managed
    customCABundle: ""
----

. To use a custom CA bundle that is not included in the {openshift-platform} cluster-wide trusted CA bundle, add the custom certificate to the `customCABundle` field, as shown in the following example:
+
[source]
----
spec:
  trustedCABundle:
    managementState: Managed
    customCABundle: |
      -----BEGIN CERTIFICATE-----
      examplebundle123
      -----END CERTIFICATE-----
----
.. Click *Save*.
+
The {productname-long} Operator creates a `odh-trusted-ca-bundle` ConfigMap containing the certificates in all new and existing non-reserved namespaces.

.Verification
. Run the following command to verify that all non-reserved namespaces contain the `odh-trusted-ca-bundle` ConfigMap:
+
[source]
----
$ oc get configmaps --all-namespaces | grep odh-trusted-ca-bundle
----
. If you are using a custom CA bundle, run the following command to verify that a non-reserved namespace (for example, _example-namespace_) contains the `odh-trusted-ca-bundle` ConfigMap and that the ConfigMap contains your customCABundle value (for example, _examplebundle123_):
+
[source]
----

$ oc get configmap odh-trusted-ca-bundle -n example-namespace -o yaml | grep examplebundle123
----

//.Next step
//Component specific customizations?