:_module-type: PROCEDURE

[id="adding-a-ca-bundle_{context}"]
= Adding a CA bundle

[role='_abstract']
For {openshift-platform} clusters that rely on self-signed certificates, you must add those self-signed certificates to a cluster-wide Certificate Authority (CA) bundle (ca-bundle.crt) and use the CA bundle in {productname-long}. You can also use self-signed certificates in a custom CA bundle (odh-ca-bundle.crt) that is separate from the cluster-wide bundle.

.Prerequisites
* You have cluster administrator privileges for your {openshift-platform} cluster.
* You installed the OpenShift command line interface (`oc`) as described in link:https://docs.openshift.com/container-platform/{ocp-latest-version}/cli_reference/openshift_cli/getting-started-cli.html[Get Started with the CLI].
* You are working in a new installation of {productname-long}. If you upgraded {productname-long}, see xref:adding-a-ca-bundle-after-upgrading_certs[Adding a CA bundle after upgrading] instead.

.Procedure
. Log in to the {openshift-platform} as a cluster administrator.
. Use the following information to add your self-signed certificates to the cluster-wide trusted CA bundle, as described in link:https://docs.openshift.com/container-platform/{ocp-latest-version}/networking/configuring-a-custom-pki.html[Configuring a custom PKI]:
.. Create a new ConfigMap in the `openshift-config` namespace with the PEM(s) bundle stored in `.data.ca-bundle.crt`.
.. Edit the proxy/cluster object to set `.spec.trustedCA.name:<new ConfigMap name>`.
+ 
This ensures that any ConfigMap in the cluster with the label `config.openshift.io/inject-trusted-cabundle: "true"` is automatically updated to include your self-signed certificates.
 
. To use a custom CA bundle that is not included in the {openshift-platform} cluster-wide trusted CA bundle, follow these steps:
.. Click *Operators* → *Installed Operators* and then click the {productname-long} Operator.
.. Click the *DSC Initialization* tab.
.. Click the *default-dsci* object.
.. Click the *YAML* tab.
.. In the `spec` section, add the custom certificate to the `customCABundle` field for `trustedCABundle`, as shown in the following example:
+
[source]
----
spec:
  trustedCABundle:
    managementState: Managed
    customCABundle: |
      -----BEGIN CERTIFICATE-----
      examplebundle123
      -----END CERTIFICATE-----
----
.. Click *Save*.

.Verification
. Run the following command to verify that all non-reserved namespaces contain the `odh-trusted-ca-bundle` ConfigMap:
+
[source]
----
$ oc get configmaps --all-namespaces | grep odh-trusted-ca-bundle
----
. If you are using a custom CA bundle, run the following command to verify that a non-reserved namespace (for example, _example-namespace_) contains the `odh-trusted-ca-bundle` ConfigMap and that the ConfigMap contains your `customCABundle` value (for example, _examplebundle123_):
+
[source]
----

$ oc get configmap odh-trusted-ca-bundle -n example-namespace -o yaml | grep examplebundle123
----

////
.. Click *Workloads* -> *ConfigMaps*.
.. Select a project from the project list.
.. Click the 'odh-trusted-ca-bundle' ConfigMap.
.. Click the *YAML* tab to see the certificates that have been added to this ConfigMap.
////


//.Next step
//Component specific customizations?