:_module-type: PROCEDURE

[id='adding-users-to-specialized-data-science-user-groups_{context}']
= Adding users to specialized {productname-short} user groups

By default, all OpenShift users have access to {productname-long}. 

Optionally, you can restrict user access to your {productname-short} instance by defining specialized user groups. You must grant users permission to access {productname-long} by adding user accounts to the {productname-long} user group, administrator group, or both. You can either use the default group name, or specify a group name that already exists in your identity provider.

The *user group* provides the user with access to developer functions in the {productname-long} dashboard, and associated services, such as Jupyter.

The *administrator group* provides the user with access to developer and administrator functions in the {productname-long} dashboard and associated services, such as Jupyter.

If you restrict access by using specialized user groups, users that are not in the {productname-short} user group or administrator group cannot view the dashboard and use associated services, such as Jupyter. They are also unable to access the *Cluster settings* page.

ifndef::self-managed[]
[IMPORTANT]
====
If you are using LDAP as your identity provider, you need to configure LDAP syncing to {openshift-platform}. See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{ocp-latest-version}/html/authentication_and_authorization/ldap-syncing[Syncing LDAP groups] for more information.
====
endif::[]

Follow the steps in this section to add users to your specialized {productname-short} administrator and user groups. 

Note: You can add users in {productname-short} but you must manage the user lists in the {openshift-platform} web console.

.Prerequisites
* You have configured a supported identity provider for {openshift-platform}.
ifndef::self-managed[]
* You are part of the `dedicated-admins` user group in {openshift-platform}.
endif::[]
ifdef::self-managed[]
* You are assigned the `cluster-admin` role in {openshift-platform}.
endif::[]
* You have defined an administrator group and user group for {productname-short}.

.Procedure
. In the {openshift-platform} web console, click *User Management* -> *Groups*.
. Click the name of the group you want to add users to.
** For administrative users, click the administrator group, for example, {oai-admin-group}.
** For normal users, click the user group, for example, {oai-user-group}.
+
The *Group details* page for that group appears.
. Click *Actions* -> *Add Users*.
+
The *Add Users* dialog appears.
. In the *Users* field, enter the relevant user name to add to the group.
. Click *Save*.

.Verification
* Click the *Details* tab for each group and confirm that the *Users* section contains the user names that you added.


