:_module-type: PROCEDURE

[id="adding-a-data-connection-to-your-data-science-project_{context}"]
= Adding a data connection to your data science project

[role='_abstract']
You can enhance your data science project by adding a connection to a data source. When you want to work with a very large data sets, you can store your data in an Amazon Web Services (AWS) Simple Storage Service (S3) bucket so that you do not fill up your local storage. You also have the option of associating the data connection with an existing workbench that does not already have a connection.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, `rhods-users` or `rhods-admin` ) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, `odh-users` or `odh-admins`) in OpenShift.
endif::[]
* You have created a data science project that you can add a data connection to.
* If you intend to add the data connection to an existing workbench, you have saved any data in the workbench to avoid losing work.

.Procedure
. From the {productname-short} dashboard, click *Data Science Projects*.
+
The *Data science projects* page opens.
. Click the name of the project that you want to add a data connection to.
+
A project details page opens.
. In the *Data connections* section of the page, click *Add data connection*.
+
The *Add data connection* dialog opens.
. Enter a *name* for the data connection.
. Enter your access key ID for Amazon Web Services in the *AWS_ACCESS_KEY_ID* field.
. Enter your secret access key for the account you specified in the *AWS_SECRET_ACCESS_KEY_ID* field.
. Enter the endpoint of your AWS S3 storage in the *AWS_S3_ENDPOINT* field.
. Enter the default region of your AWS account in the *AWS_DEFAULT_REGION* field.
. Enter the name of the AWS S3 bucket in the *AWS_S3_BUCKET* field.
. Click *Add data connection*.

.Verification
* The data connection that you added appears in the *Data connections* section on the *Details* page for the project.
* If you selected a workbench, the data connection is visible in the *Workbenches* section on your data science project page.

//[role='_additional-resources']
//.Additional resources
