:_module-type: PROCEDURE

[id='adding-users-to-user-groups_{context}']
= Adding users to {productname-short} user groups

By default, all OpenShift users have access to {productname-long}. 

Optionally, you can restrict user access to your {productname-short} instance by defining user groups. You must grant users permission to access {productname-long} by adding user accounts to the {productname-long} user group, administrator group, or both. You can either use the default group name, or specify a group name that already exists in your identity provider.

The *user group* provides the user with access to product components in the {productname-long} dashboard, such as data science pipelines, and associated services, such as Jupyter. By default, users in the *user group* have access to data science pipeline applications within data science projects that they created. 

The *administrator group* provides the user with access to developer and administrator functions in the {productname-long} dashboard, such as data science pipelines, and associated services, such as Jupyter. Users in the *administrator group* can configure data science pipeline applications in the {productname-short} dashboard for any data science project.

If you restrict access by using user groups, users that are not in the {productname-short} user group or administrator group cannot view the dashboard and use associated services, such as Jupyter. They are also unable to access the *Cluster settings* page.

ifdef::cloud-service[]
[IMPORTANT]
====
If you are using LDAP as your identity provider, you need to configure LDAP syncing to OpenShift. For more information, see link:https://docs.redhat.com/en/documentation/openshift_dedicated/{osd-latest-version}/html/authentication_and_authorization/ldap-syncing[Syncing LDAP groups in OpenShift Dedicated] or link:https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws/{rosa-latest-version}/html/authentication_and_authorization/ldap-syncing[Syncing LDAP groups in Red Hat OpenShift Service on AWS (ROSA)].
====
endif::[]

ifdef::upstream,self-managed[]
[IMPORTANT]
====
If you are using LDAP as your identity provider, you need to configure LDAP syncing to {openshift-platform}. For more information, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/authentication_and_authorization/ldap-syncing[Syncing LDAP groups].
====
endif::[]

Follow the steps in this section to add users to your {productname-short} administrator and user groups. 

ifdef::upstream,self-managed[]
Note: You can add users in {productname-short} but you must manage the user lists in the {openshift-platform} web console.
endif::[]

ifdef::cloud-service[]
Note: You can add users in {productname-short} but you must manage the user lists in the OpenShift web console.
endif::[]

.Prerequisites
ifdef::upstream,self-managed[]
* You have configured a supported identity provider for {openshift-platform}.
* You are assigned the `cluster-admin` role in {openshift-platform}.
endif::[]
ifdef::cloud-service[]
* You have configured a supported identity provider for your OpenShift cluster.
* You are part of the `cluster-admins` or `dedicated-admins` user group in your OpenShift cluster. The `dedicated-admins` user group applies only to OpenShift Dedicated.
endif::[]
* You have defined an administrator group and user group for {productname-short}.

.Procedure
. In the {openshift-platform} web console, click *User Management* -> *Groups*.
. Click the name of the group you want to add users to.
** For administrative users, click the administrator group, for example, {admin-group}.
** For normal users, click the user group, for example, {user-group}.
+
The *Group details* page for that group opens.
. Click *Actions* -> *Add Users*.
+
The *Add Users* dialog opens.
. In the *Users* field, enter the relevant user name to add to the group.
. Click *Save*.

.Verification
* Click the *Details* tab for each group and confirm that the *Users* section contains the user names that you added.


