:_module-type: PROCEDURE

[id="adding-notebook-pod-tolerations_{context}"]
= Adding notebook pod tolerations

[role='_abstract']
You can add a toleration to notebook pods to allow them to be scheduled on tainted nodes. This is useful if you want to dedicate specific worker nodes to running notebooks, as tainting them will prevent other workloads from running on them. 

////
For example, I might have 1-2 worker nodes that are large enough to accommodate an XL notebook server. I want to ensure when a user attempts to start an XL notebook server, it gets placed on a node with an appropriate taint to accept XL notebooks. Other smaller notebooks can share the resources across the other worker nodes that might not have a taint for an XL notebook. This can help ensure users that need to do work with large notebook sizes, the resources will be available to support them.
////

.Prerequisites
* You have logged in to {productname-long}.
* You are part of the administrator group for {productname-short} in {openshift-platform}.
//* You have added the toleration to the pods. For more information, see link:https://docs.openshift.com/container-platform/{ocp-latest-version}/nodes/scheduling/nodes-scheduler-taints-tolerations.html[Understanding taints and tolerations].

.Procedure
. From the {productname-short} dashboard, click *Settings* -> *Cluster settings*.
. Under *Notebook pod tolerations*, select *Add a toleration to notebook pods to allow them to be scheduled to tainted nodes*.
. Enter a *Toleration key for notebook pods*. This toleration key will be applied to all notebook pods when they are created.
. Click *Save changes*.

.Next step
In {openshift-platform}, add a matching taint key (with any value) to the machine pools that you want to dedicate to notebooks.

ifdef::self-managed[]
** link:https://access.redhat.com/documentation/en-us/red_hat_openshift_service_on_aws/4/html/cluster_administration/manage-nodes-using-machine-pools#rosa-adding-taints_rosa-managing-worker-nodes[Adding taints to a machine pool]
endif::[]
ifndef::self-managed[]
For more information, see link:https://access.redhat.com/documentation/en-us/openshift_dedicated/4/html/cluster_administration/nodes#rosa-adding-taints_osd-managing-worker-nodes[Adding taints to a machine pool].
endif::[]

.Verification

. In the {openshift-platform} console, for a pod that is running, click *Workloads* -> *Pods*. Otherwise, for a pod that is stopped, click *Workloads* -> *StatefulSet*.
. Search for your workbench pod name and then click the name to open the pod details page.
. Confirm that the assigned *Node* and *Tolerations* are correct.

//[role='_additional-resources']
//.Additional resources
