:_module-type: PROCEDURE

[id="adding-a-data-connection-to-your-data-science-project_{context}"]
= Adding a data connection to your data science project

[role='_abstract']
You can enhance your data science project by adding a connection to a data source. When you want to work with a very large data sets, you can store your data in an S3-compatible object storage bucket, so that you do not fill up your local storage. You also have the option of associating the data connection with an existing workbench that does not already have a connection.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group} ) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have created a data science project that you can add a data connection to.
* You have access to S3-compatible object storage.
* If you intend to add the data connection to an existing workbench, you have saved any data in the workbench to avoid losing work.

.Procedure
. From the {productname-short} dashboard, click *Data Science Projects*.
+
The *Data Science Projects* page opens.
. Click the name of the project that you want to add a data connection to.
+
A project details page opens.
. Click the *Data connections* tab.
. Click *Add data connection*.
+
The *Add data connection* dialog opens.
. Enter a *name* for the data connection.
. In the *Access key* field, enter the access key ID for your S3-compatible object storage provider.
. In the *Secret key* field, enter the secret access key for the S3-compatible object storage account you specified.
. In the *Endpoint* field, enter the endpoint of your S3-compatible object storage bucket.
. In the *Region* field, enter the default region of your S3-compatible object storage account.
. In the *Bucket* field, enter the name of your S3-compatible object storage bucket.
. Click *Add data connection*.

.Verification
* The data connection that you added appears in the *Data connections* tab for the project.
* If you selected a workbench, the data connection is visible in the *Workbenches* tab for the project.

//[role='_additional-resources']
//.Additional resources
