:_module-type: PROCEDURE

[id="adding-an-application-to-the-dashboard_{context}"]
= Adding an application to the dashboard

[role='_abstract']
If you have installed another application in your {openshift-platform} cluster, you can add a tile for that application to the {productname-short} dashboard (the *Applications* -> *Enabled* page) to make it easily accessible for users. 

.Prerequisites
* You have cluster administrator privileges for your {openshift-platform} cluster.

.Procedure
. Log in to the {openshift-platform} console as a cluster administrator.
. In the *Administrator* perspective, click *Home* -> *API Explorer*.
. In the search bar, enter `OdhDashboardConfig` to filter by kind.
. Click the `OdhDashboardConfig` custom resource (CR) to open the resource details page.
. Click the *Instances* tab.
. Click the default instance name to open the instance details page.
. Click the *YAML* tab.



.Verification
Log in to {productname-short} and verify that your dashboard configurations apply.