:_module-type: CONCEPT

[id='api-workbench-overview_{context}']
= Overview

[role="_abstract"]

In {productname-long}, a workbench is an isolated area where a data scientist can examine and work with ML models. When you create a workbench, you specify a workbench image. {productname-short} provides a selection of default workbench images that you can choose from. Each image is optimized with the tools and libraries that a data scientist needs for model development. To view a list of the {productname-short} default workbench images and their preinstalled packages, see link:https://access.redhat.com/articles/rhoai-supported-configs[Supported Configurations].

ifdef::upstream[]
As a cluster administrator, you can create a custom image, for example, if a data scientist on your team requires a specific version of a library that is different from the version provided in a default image. For information about {productname-short} custom images, see link:{odhdocshome}/managing-odh/#creating-custom-workbench-images[Creating a custom image from a default {productname-short} image].
endif::[]

ifndef::upstream[]
As a cluster administrator, you can create a custom image, for example, if a data scientist on your team requires a specific version of a library that is different from the version provided in a default image. For information about {productname-short} custom images, see link:{rhoaidocshome}{default-format-url}/managing_openshift_ai/creating-custom-workbench-images[Creating custom workbench images].
endif::[]

You have the following options for creating workbenches and custom images:

* As an OpenShift cluster administrator, you can create a custom image and a workbench by using {productname-short} Custom Resource Definitions (CRDs) and the OpenShift Command Line Interface (CLI) as described in this guide.

* As an OpenShift cluster administrator, you can use OpenShift APIs to create resources, such as a custom image. You can programmatically call the APIs through HTTP GET methods in your code, a Bash script, or a Python script. For more information about using the OpenShift APIs to create an ImageStream resource, see the link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/image_apis/image-apis#imagestream-image-openshift-io-v1-1[ImageStream entry^] in the _OpenShift API Reference_. 

ifdef::upstream[]
* As any {productname-short} user, you can use the {productname-short} dashboard to create workbenches and select images, as described in link:{odhdocshome}/working-on-data-science-projects/#using-project-workbenches_projects[Using project workbenches].
endif::[]

ifndef::upstream[]
* As any {productname-short} user, you can use the {productname-short} dashboard to create workbenches and select images, as described in link:{rhoaidocshome}{default-format-url}/working_on_data_science_projects/using-project-workbenches_projects[Using project workbenches].
endif::[]
