:_module-type: PROCEDURE

[id="archiving-a-model_{context}"]
= Archiving a model

[role='_abstract']
You can archive a model. The model and all of its versions will be archived and unavailable for use unless it is restored.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* An available model registry exists in your deployment.

.Procedure
. From the {productname-short} dashboard, click *Model Registry*.
. From the *Model registry* dropdown menu, select the model registry that you want to archive a model in.
. Click the action menu (*&#8942;*) beside the model that you want to archive.
. Click *Archive model*.
. In the *Archive model?* dialog that appears, enter the name of the model in the text field to confirm that you intend to archive it.
. Click *Archive*.

.Verification
* The model no longer appears on the *Model Registry* page.
* The model now appears on the archived models page for the model registry.

// [role="_additional-resources"]
// .Additional resources
// * TODO or delete
