:_module-type: PROCEDURE

[id="archiving-a-pipeline-experiment_{context}"]
= Archiving a pipeline experiment

[role='_abstract']
You can archive your pipeline experiments to store and retain records for future reference. If you need to reuse an archived experiment, you can restore it at any time. Deleting pipeline experiments is a separate action and happens only when you explicitly choose to delete them. Unarchived experiments remain stored unless you manually delete them.

.Prerequisites
* You have logged in to {productname-long}.
* You have previously created a project that is available and has a pipeline server.
* You have imported a pipeline to an active pipeline server.
* A pipeline experiment is available to archive.  

.Procedure
. From the {productname-short} dashboard, click *Develop & train* -> *Experiments*.
. On the *Experiments* page, from the *Project* drop-down list, select the project that contains the pipeline experiment that you want to archive.
. Click the action menu (*&#8942;*) beside the pipeline experiment that you want to archive, and then click *Archive*.
. In the *Archiving experiment* dialog, enter the pipeline experiment name in the text field to confirm that you intend to archive it.
. Click *Archive*.

.Verification
* The archived pipeline experiment does not appear on the *Experiments* tab, and instead is displayed on the *Archive* tab on the *Experiments* page for the pipeline experiment.

//[role='_additional-resources']
//.Additional resources
