:_module-type: PROCEDURE

[id="archiving-a-pipeline-run_{context}"]
= Archiving a pipeline run

[role='_abstract']
You can retain records of your pipeline runs by archiving them. If required, you can restore runs from your archive to reuse, or delete runs that are no longer required.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group} ) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have previously created a data science project that is available and has a pipeline server.
* You have imported a pipeline to an active and available pipeline server.
* You have previously executed a pipeline run that is available. 

.Procedure
. From the {productname-short} dashboard, click *Data Science Pipelines* -> *Runs*.
+
The *Runs* page opens.
. From the *Project* list, select the project whose pipeline run you want to archive. 
+
The *Run details* page opens displaying the *Active* tab.
. Click the action menu (*&#8942;*) beside run that you want to archive and click *Archive*.
+
The *Archiving run* dialog opens.
. Enter the run name in the text field to confirm that you intend to archive it.
. Click *Archive*.

.Verification
* The archived run does not appear in the *Active* tab and is instead displayed in the *Archived* tab on the *Runs* page.

//[role='_additional-resources']
//.Additional resources
