:_module-type: PROCEDURE

[id="archiving-a-model_{context}"]
= Archiving a model

[role='_abstract']
You can archive a model that you no longer require. The model and all of its versions will be archived and unavailable for use unless it is restored.

[IMPORTANT]
====
Models with deployed versions cannot be archived. To archive a model, you must first delete all deployments of its registered versions from the *AI hub* -> *Deployments* page.
====

.Prerequisites
* You have logged in to {productname-long}.
* An available model registry exists in your deployment, and contains at least 1 registered model.
* You have access to the model registry that contains the model that you want to archive.

.Procedure
. From the {productname-short} dashboard, click *AI hub* -> *Registry*.
. From the *Model registry* drop-down list, select the model registry that you want to archive a model in.
. Click the action menu (*&#8942;*) beside the model that you want to archive.
. Click *Archive model*.
. In the *Archive model?* dialog that is displayed, enter the name of the model in the text field to confirm that you intend to archive it.
. Click *Archive*.

.Verification
* The model is no longer visible on the *Model registry* page.
* The model is displayed on the archived models page for the model registry.

// [role="_additional-resources"]
// .Additional resources
// * TODO or delete
