:_module-type: PROCEDURE

[id="authenticating-trustyai-service_{context}"]
= Authenticating the TrustyAI service

[role='_abstract']
You can access TrustyAI service external endpoints only if you provide OAuth proxy (oauth-proxy) authentication. You must obtain a user token, or a token from a service account with sufficient privileges, and then pass the token to the TrustyAI service when using `curl` commands.

.Prerequisites

* You installed the OpenShift command line interface (`oc`) as described in link:https://docs.openshift.com/container-platform/{ocp-latest-version}/cli_reference/openshift_cli/getting-started-cli.html[Get Started with the CLI].

* Your OpenShift cluster administrator has installed {productname-short}, added you as a user to the OpenShift cluster, and enabled the TrustyAI service for the data science project where the models are deployed.

.Procedure

. In a terminal window, log in to {openshift-platform} where {productname-short} is deployed.
+
----
oc login
----

. Enter the following command to get the user token on {openshift-platform}.
+
----
TOKEN=$(oc whoami -t)
----

.Verification

* Enter the following command to check the user token variable:
+
----
echo $TOKEN
----

.Next step

When running `curl` commands, pass the token to the TrustyAI service using the Authorization header. For example:
----
curl -H "Authorization: Bearer $TOKEN" $TRUSTY_ROUTE
----