:_module-type: PROCEDURE

[id="authenticating-trustyai-service_{context}"]
= Authenticating the TrustyAI service

[role='_abstract']
To access TrustyAI service external endpoints, you need to provide OAuth proxy (oauth-proxy) authentication. You must obtain a user token, or a token from a service account with sufficient privileges, and then pass the token to the TrustyAI service when using `curl` commands.

.Prerequisites
ifdef::upstream,self-managed[]
* You installed the OpenShift command line interface (`oc`) as described in link:https://docs.openshift.com/container-platform/{ocp-latest-version}/cli_reference/openshift_cli/getting-started-cli.html[Get Started with the CLI].
endif::[]
ifdef::cloud-service[]
* You installed the OpenShift command line interface (`oc`) as described in link:https://docs.openshift.com/dedicated/cli_reference/openshift_cli/getting-started-cli.html[Getting started with the CLI] (OpenShift Dedicated) or link:https://docs.openshift.com/rosa/cli_reference/openshift_cli/getting-started-cli.html[Getting started with the CLI] (Red Hat OpenShift Service on AWS)
endif::[]
* Your OpenShift cluster administrator added you as a user to the {openshift-platform} cluster and has installed the TrustyAI service for the data science project where the models are deployed.

.Procedure

. Open a new terminal window.
. Follow these steps to log in to your {openshift-platform} cluster:
.. In the upper-right corner of the OpenShift web console, click your user name and select *Copy login command*. 
.. After you have logged in, click *Display token*.
.. Copy the *Log in with this token* command and paste it in the OpenShift command-line interface (CLI).
+
[source,subs="+quotes"]
----
$ oc login --token=__<token>__ --server=__<openshift_cluster_url>__
----

. Enter the following command to set a user token variable on {openshift-platform}:
+
----
export TOKEN=$(oc whoami -t)
----

.Verification

* Enter the following command to check the user token variable:
+
----
echo $TOKEN
----

.Next step

When running `curl` commands, pass the token to the TrustyAI service using the Authorization header. For example:
----
curl -H "Authorization: Bearer $TOKEN" $TRUSTY_ROUTE
----
