:_module-type: PROCEDURE

[id='auto-configuring-guardrails_{context}']

= Auto-configuring Guardrails

[role='_abstract']
Auto-configuration simplifies the Guardrails setup process by automatically handling TLS configuration and authentication, ensuring seamless and secure communication between components.  To integrate with detector services in your namespace, use the `autoConfig` specification in the `GuardrailsOrchestrator` custom resource (CR).
For example, if any of the detectors or generation services use HTTPS, their credentials are automatically discovered, mounted, and used. Additionally, the orchestrator is automatically configured to forward all necessary authentication token headers.

.Prerequisites
* Each detector server you intend to use has an OpenShift label applied in the resource metadata. For example, `metadata.labels.<label_name>: true`. Choose a descriptive name for the label as it is required for auto-configuration.
* You have set up the inference service to which you intend to apply guardrails.
* You have installed the {openshift-cli} as described in the appropriate documentation for your cluster:
ifdef::upstream,self-managed[]
** link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI^] for OpenShift Container Platform  
** link:https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws/{rosa-latest-version}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI^] for {rosa-productname}
endif::[]
ifdef::cloud-service[]
** link:https://docs.redhat.com/en/documentation/openshift_dedicated/{osd-latest-version}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI^] for OpenShift Dedicated  
** link:https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws_classic_architecture/{rosa-classic-latest-version}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI^] for {rosa-classic-productname}
endif::[]

.Procedure
. Create a  `GuardrailsOrchestrator` CR with the `autoConfig` configuration. For example, create a YAML file named `guardrails_orchestrator_auto_cr.yaml` with the following contents:
+
.Example `guardrails_orchestrator_auto_cr.yaml` CR
[source,yaml]
----
apiVersion: trustyai.opendatahub.io/v1alpha1
kind: GuardrailsOrchestrator
metadata:
  name: guardrails-orchestrator
  annotations:
    security.opendatahub.io/enable-auth: 'true'
spec:
  autoConfig:
      inferenceServiceToGuardrail: $INFERENCE_SERVICE_NAME
      detectorServiceLabelToMatch: $LABEL_NAME
  enableBuiltInDetectors: true
  enableGuardrailsGateway: true 
  replicas: 1
----
+
* `inferenceServiceToGuardrail`: Specifies the name of the vLLM inference service to be guardrailed.
* `detectorServiceLabelToMatch`: Specifies the label that you applied to each of your detector servers in the `metadata.labels` specification for the detector. The  Guardrails Orchestrator `ConfigMap` automatically updates to reflect detectors in your namespace that match the label set in the `detectorServiceLabelToMatch` field.

. Deploy the orchestrator custom resource. This step creates a service account, deployment, service, and route object in your namespace.
+
[source,terminal]
----
oc apply -f guardrails_orchestrator_auto_cr.yaml -n <your_namespace>
----

.Verification
You can verify that the `GuardrailsOrchestrator` CR and corresponding automatically generated configuration objects were successfully created in your namespace by running the following commands:

. Confirm that the `GuardrailsOrchestrator` CR was created:
+
[source,terminal]
----
$ oc get guardrailsorchestrator -n <your_namespace>
----

. View the automatically generated Guardrails Orchestrator `ConfigMap`:
+
[source,terminal]
----
$ oc get configmap -n <your_namespace> | grep auto-config
----
+
[source,terminal]
----
$ oc get configmap guardrails-orchestrator-auto-config -n <your_namespace> -o yaml
----

. If you enabled the Guardrails Gateway by using `enableGuardrailsGateway: true`, run the following command to verify the default gateway `ConfigMap`:
+
[source,terminal]
----
$ oc get configmap guardrails-orchestrator-gateway-auto-config -n <your_namespace> -o yaml
----
+
This ConfigMap defines default routes such as the following examples:
+

* `all`: Uses all available detectors
* `passthrough`: Uses no detectors
