:_module-type: CONCEPT

[id='backing-up-storage-data_{context}']
= Backing up storage data

[role='_abstract']
It is a best practice to back up the data on your persistent volume claims (PVCs) regularly.

Backing up your data is particularly important before you delete a user and before you uninstall {productname-short}, as all PVCs are deleted when {productname-short} is uninstalled.

ifdef::upstream,self-managed[]
For more information about backing up PVCs for your cluster platform, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/backup_and_restore/oadp-application-backup-and-restore.html[OADP Application backup and restore] in OpenShift Container Platform (OCP) documentation.
endif::[]

ifdef::cloud-service[]
For more information about backing up PVCs for your cluster platform, see link:https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws/{rosa-latest-version}/html/backup_and_restore/oadp-application-backup-and-restore[OADP Application backup and restore] in the Red Hat OpenShift Service on AWS (ROSA) documentation.
endif::[]

[role="_additional-resources"]
.Additional resources
ifdef::self-managed,upstream[]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/storage/understanding-persistent-storage[Understanding persistent storage]
endif::[]
ifdef::cloud-service[]
* link:https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws/{rosa-latest-version}/html/storage/understanding-persistent-storage[Understanding persistent storage].
endif::[]
