:_module-type: PROCEDURE

[id='backing-up-storage-data-from-google-persistent-disk_{context}']
= Backing up storage data from Google Persistent Disk

[role='_abstract']

ifndef::upstream[]
Red Hat recommends that you back up the data on your persistent volume claims (PVCs) regularly. 
endif::[]
ifdef::upstream[]
It is good practice to back up the data on your persistent volume claims (PVCs) regularly. 
endif::[]
Backing up your data is particularly important before deleting a user and before uninstalling {productname-short}, as all PVCs are deleted when {productname-short} is uninstalled.

.Prerequisites
* You have credentials for OpenShift Cluster Manager (link:https://console.redhat.com/openshift/[https://console.redhat.com/openshift/]).
* You have administrator access to the {openshift-platform} cluster.
* You have credentials for the Google Cloud Platform (GCP) account that the {openshift-platform} cluster is deployed under.

.Procedure

. Determine the IDs of the persistent volumes (PVs) that you want to back up.
.. In the {openshift-platform} web console, change into the *Administrator* perspective.
.. Click *Home* -> *Projects*.
.. Click the *rhods-notebooks* project.
+
The *Details* page for the project opens.
.. Click the *PersistentVolumeClaims* in the *Inventory* section.
+
The *PersistentVolumeClaims* page opens.
.. Note the ID of the persistent volume (PV) that you want to back up.
+
The persistent volume (PV) IDs are required to identify the correct persistent disk to back up in your GCP instance.

. Locate the persistent disk containing the PVs that you want to back up.

.. Log in to the Google Cloud console (link:https://console.cloud.google.com/[https://console.cloud.google.com]) and ensure that you are viewing the region that your {openshift-platform} cluster is deployed in.
.. Click the navigation menu (&equiv;) and then click *Compute Engine*.
+
.. From the side navigation, under *Storage*, click *Disks*.
+
The *Disks* page opens.
.. In the *Filter* query box, enter the ID of the persistent volume (PV) that you made a note of earlier.
+
The *Disks* page reloads to display the search results.
+
.. Click on the disk shown and verify that any `kubernetes.io/created-for/pvc/namespace` tags contain the value `rhods-notebooks`, and any  `kubernetes.io/created-for/pvc/name` tags match the name of the persistent volume that the persistent disk is being used for, for example, `jupyterhub-nb-user1-pvc`.

. Back up the persistent disk that contains your persistent volume (PV).
.. Select *CREATE SNAPSHOT* from the top navigation.
+
The *Create a snapshot* page opens.
.. Enter a unique *Name* for the snapshot.
.. Under *Source disk*, verify the persistent disk you want to back up is displayed.
.. Change any optional settings as needed.
.. Click *CREATE*.
+
The snapshot of the persistent disk is created.

.Verification
* The snapshot that you created is visible on the *Snapshots* page in GCP.

[role="_additional-resources"]
.Additional resources
* link:https://cloud.google.com/compute/docs/disks/create-snapshots[Google Cloud documentation: Create and manage disk snapshots]
