:_module-type: PROCEDURE

[id='cleaning-up-after-deleting-users_{context}']
= Cleaning up after deleting users

[role='_abstract']
After you remove a user's access to {productname-long}, you must also delete the configuration files for the user from {openshift-platform}.
{org-name} recommends that you back up the user's data before removing their configuration files.

.Prerequisites

* (Optional) If you want to completely remove the user's access to {productname-short}, you have removed their credentials from your identity provider.
ifdef::cloud-service[]
* You have backed up the user's storage data from Amazon EBS or Google Persistent Disk.
endif::[]
ifdef::self-managed[]
* You have backed up the user's storage data.
endif::[]
* You have logged in to the {openshift-platform} web console as a user with the `cluster-admin` role.

.Procedure

. Delete the user's persistent volume claim (PVC).
.. Click *Storage* -> *PersistentVolumeClaims*.
ifdef::cloud-service[]
.. If it is not already selected, select the `pass:attributes[{workbench-default-namespace}]` project from the project list.
endif::[]
ifdef::self-managed,upstream[]
.. If it is not already selected, select the default workbench project (`pass:attributes[{workbench-default-namespace}]` or your custom workbench namespace) from the project list.
endif::[]
.. Locate the  `jupyter-nb-<username>` PVC.
+
Replace `<username>` with the relevant user name.
.. Click the action menu (&#8942;) and select *Delete PersistentVolumeClaim* from the list.
+
The *Delete PersistentVolumeClaim* dialog appears.
.. Inspect the dialog and confirm that you are deleting the correct PVC.
.. Click *Delete*.
. Delete the user's ConfigMap.
.. Click *Workloads* -> *ConfigMaps*.
ifdef::cloud-service[]
.. If it is not already selected, select the `pass:attributes[{workbench-default-namespace}]` project from the project list.
endif::[]
ifdef::self-managed,upstream[]
.. If it is not already selected, select the default workbench project (`pass:attributes[{workbench-default-namespace}]` or your custom workbench namespace) from the project list.
endif::[]
.. Locate the `jupyterhub-singleuser-profile-<username>` ConfigMap.
+
Replace `<username>` with the relevant user name.
.. Click the action menu (&#8942;) and select *Delete ConfigMap* from the list.
+
The *Delete ConfigMap* dialog appears.
.. Inspect the dialog and confirm that you are deleting the correct ConfigMap.
.. Click *Delete*.

.Verification
* The user cannot access {productname-short} and sees an "Access permission needed" message if they try. 
* The user's single-user profile, persistent volume claim (PVC), and ConfigMap are not visible in {openshift-platform}.

