:_module-type: PROCEDURE

[id='clone-an-example-git-repository_{context}']
= Clone an example Git repository

Follow these steps to clone a Git repo from the JupyterLab environment provided with your {productname-short} workbench.

*Prerequisites*

* You created a workbench that references the Red Hat Python index.
* You have the https URL and branch for one of the example Git repositories listed in Table 2.

*Procedure*

. From the {productname-short} dashboard, go to the project where you created a workbench.

. Click the link for your workbench. If prompted, log in and allow JupyterLab to authorize your user.
+
Your JupyterLab environment window opens.
+
The file-browser window shows the files and directories that are saved inside your own personal space in {productname-short} .

. Bring the content of an example Git repo inside your JupyterLab environment:
.. On the toolbar, click the *Git Clone* icon.
.. Enter a Git https URL.
.. Select the *Include submodules* option, and then click *Clone*.

. If you want to use a branch other than `main` (for example, the data processing example repo uses the `stable-3.0` branch), change the branch:

.. In the left navigation bar, click the *Git* icon, and then click *Current Branch* to expand the branches and tags selector panel.

.. On the *Branches* tab, in the *Filter* field, enter the branch name.

.. Select the branch.
+
The current branch changes to the branch that you selected.

*Verification*

* In the file browser, double-click the newly-created directory to see the example files.