:_module-type: PROCEDURE

[id='comparing-experiment-runs_{context}']
= Comparing experiment runs

[role='_abstract']
You can compare the results of up to 10 runs within an experiment.
You can compare up to 10 experiment runs at one time. parameters, scalar metrics, confusion matrixes, and receiver operating characteristic (ROC) curve data for all selected runs.


.Prerequisites
*
*

.Procedure
. In the {productname-short} dashboard, select *Experiments > Experiments and runs*.
+ The *Experiments* page opens.
. From the *Project* drop-down list, select your data science project.
. In the *Experiments* column, click the experiment that you want to compare runs, or manage runs or schedules for.
+
The *Runs* page opens.
.  Select the checkbox next to each run that you want to compare, then click *Compare runs*. You can compare a maximum of 10 experiment runs at one time.
+ The *Compare runs* page opens.
. 

The *Run list* section, 
*Experiment*
*Pipeline version*
*Started*
*Duration*
*Status*

The *Parameters* section,

. Set the *Hide parameters with no differences* switch to on to hide parameters that are the same for all selected runs.

The *Metrics* section,

* *Scalar metrics* 
* *Confusion matrix* 
* *ROC curve*
*Execution name > Artifact name*, *Run name*, *Curve legend*
You can search for artifacts using the *Artifacts* search field.
. Deselect the checkbox next to each artifact that you do not want to display on the ROC curve chart.
. Select the checkbox next to each run that you want to add to your comparison.

. Set the *Hide parameters with no differences* switch to hide parameters that are the same for all selected runs.

. To update the runs that are selected for comparison, click *Manage runs*.
+ The **Manage runs* dialog opens.


*Run* search field

. Filter by run, experiment, pipeline version, start date, duration, or status by entering the column name in the *Filters* field.
. Deselect the checkbox next to each run that you want to remove from your comparison.
. Select the checkbox next to each run that you want to add to your comparison.