:_module-type: PROCEDURE

[id="configuring-a-recommended-accelerator-for-notebook-images_{context}"]
= Configuring a recommended accelerator for notebook images

[role='_abstract']
To help you indicate the most suitable accelerators to your data scientists, you can configure a recommended tag to appear on the dashboard. 

.Prerequisites
ifdef::upstream,self-managed[]
* You have logged in to {openshift-platform}.
* You have the `cluster-admin` role in {openshift-platform}.
endif::[]
ifdef::cloud-service[]
* You have logged in to OpenShift.
* You have the `cluster-admin` role in OpenShift.
endif::[]
* You have existing notebook images in your deployment.

.Procedure
. From the {productname-short} dashboard, click *Settings* -> *Notebook image settings*.
+
The *Notebook image settings* page appears. Previously imported notebook images are displayed. 
. Click the action menu (&#8942;) and select *Edit* from the list.
+
The *Update notebook image* dialog opens.
. From the *Accelerator identifier* list, select an identifier to set its accelerator as recommended with the notebook image. If the notebook image contains only one accelerator identifier, the identifier name displays by default.
. Click *Update*.
+
[NOTE]
====
If you have already configured an accelerator identifier for a notebook image, you can specify a recommended accelerator for the notebook image by creating an associated accelerator profile. To do this, click *Create profile* on the row containing the notebook image and complete the relevant fields. If the notebook image does not contain an accelerator identifier, you must manually configure one before creating an associated accelerator profile.  
====

.Verification
* When your data scientists select an accelerator with a specific notebook image, a tag appears next to the corresponding accelerator indicating its compatibility. 

//[role='_additional-resources']
//.Additional resources
