:_module-type: PROCEDURE

[id="configuring-the-training-operator_{context}"]
= Configuring the Training Operator

[role='_abstract']
If you want to run a PyTorch training job in an environment where Kueue is not installed, you must create a service account and apply access permissions to it.

If you use Kueue to run PyTorch jobs, you can skip this section. 


.Prerequisites
ifdef::upstream,self-managed[]
* You have logged in to {openshift-platform} with the `cluster-admin` role.
endif::[]
ifdef::cloud-service[]
* You have logged in to OpenShift with the `cluster-admin` role.
endif::[]

ifndef::upstream[]
* You have access to a data science cluster that is configured to run distributed workloads as described in link:{rhoaidocshome}{default-format-url}/working_with_distributed_workloads/configuring-distributed-workloads_distributed-workloads[Configuring distributed workloads].
endif::[]
ifdef::upstream[]
* You have access to a data science cluster that is configured to run distributed workloads as described in link:{odhdocshome}/working-with-distributed-workloads/#configuring-distributed-workloads_distributed-workloads[Configuring distributed workloads].
endif::[]

ifndef::upstream[]
* You have created a data science project. 
For information about how to create a project, see link:{rhoaidocshome}{default-format-url}/working_on_data_science_projects/using-data-science-projects_projects#creating-a-data-science-project_projects[Creating a data science project].
endif::[]
ifdef::upstream[]
* You have created a data science project. 
For information about how to create a project, see link:{odhdocshome}/working-on-data-science-projects/#creating-a-data-science-project_projects[Creating a data science project].
endif::[]

* You have Admin access for the data science project.
** If you created the project, you automatically have Admin access. 
** If you did not create the project, your cluster administrator must give you Admin access.

* You have access to a model.
* You have access to data that you can use to train the model.

.Procedure
. In a terminal window, if you are not already logged in to your OpenShift cluster as a cluster administrator, log in to the OpenShift CLI as shown in the following example:
+
[source,subs="+quotes"]
----
$ oc login __<openshift_cluster_url>__ -u __<admin_username>__ -p __<password>__
----

. Create a cluster role with the required access permissions, as follows:
.. Create a YAML file named `pytorchjob_role.yaml`.
.. Add the following `ClusterRole` object definition:
+
[source]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pytorchjob-role
rules:
  - apiGroups:
      - "kubeflow.org"
    resources:
      - pytorchjobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - "kubeflow.org"
    resources:
      - pytorchjobs/status
    verbs:
      - get
----
.. Save your changes in the `pytorchjob_role.yaml` file.
.. Apply the configuration to create the `pytorchjob-role` object:
+
[source]
----
$ oc apply -f pytorchjob_role.yaml
----

. Create a service account, as follows:
.. Create a YAML file named `pytorchjob_serviceaccount.yaml`.
.. Add the following `ServiceAccount` object definition:
+
[source]
----
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pytorchjob-sa
  namespace: kfto
----
.. Replace the example namespace value `kfto` with the name of your project.
.. Save your changes in the `pytorchjob_serviceaccount.yaml` file.
.. Apply the configuration to create the `pytorchjob-sa` service account:
+
[source]
----
$ oc apply -f pytorchjob_serviceaccount.yaml
----

. Assign the cluster role to the service account, as follows:
.. Create a YAML file named `pytorchjob_rolebinding.yaml`.
.. Add the following `ClusterRoleBinding` object definition:
+
[source]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pytorchjob-rolebinding
subjects:
- kind: ServiceAccount
  name: pytorchjob-sa
  namespace: kfto
roleRef:
  kind: ClusterRole
  name: pytorchjob-role
  apiGroup: rbac.authorization.k8s.io
----
.. Replace the example namespace value `kfto` with the name of your project.
.. Save your changes in the `pytorchjob_rolebinding.yaml` file.
.. Apply the configuration to assign the `pytorchjob-role` cluster role to the `pytorchjob-sa` service account:
+
[source]
----
$ oc apply -f pytorchjob_rolebinding.yaml
----


.Verification
ifdef::upstream,self-managed[]
. In the {openshift-platform} console, select your project from the *Project* list. 
endif::[]
ifdef::cloud-service[]
. In the OpenShift console, select your project from the *Project* list.
endif::[]
. Click *User Management -> ServiceAccounts* and verify that `pytorchjob-sa` is listed.
. Click *User Management -> Roles* and verify that `pytorchjob-role` is correctly created and assigned.
. Click *User Management -> RoleBindings* and verify that `pytorchjob-rolebinding` is correctly created and assigned.

////
[role='_additional-resources']
.Additional resources
<Do we want to link to additional resources?>


* link:https://url[link text]
////
