:_module-type: PROCEDURE

[id="configuring-workload-management-with-kueue_{context}"]
= Configuring workload management with Kueue

[role="_abstract"]
To use workload queuing in {productname-short}, install the {rhbok-productname} Operator and activate the Kueue integration in {productname-short}.

.Prerequisites
* You have cluster administrator privileges for your {openshift-platform} cluster.
* You are using {openshift-platform} 4.18 or later.
* You have installed and configured the *cert-manager Operator for {org-name} OpenShift* for your cluster.
* You have installed the OpenShift command-line interface (CLI). See link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI^].

.Procedure

. In a terminal window, log in to the OpenShift CLI as shown in the following example:
+
[source,subs="+quotes"]
----
oc login __<openshift_cluster_url>__ -u __<admin_username>__ -p __<password>__
----

. Install the {rhbok-productname} Operator on your {openshift-platform} cluster as described in link:https://docs.redhat.com/en/documentation/red_hat_build_of_kueue/latest/html/installing_on_openshift_container_platform/install-kueue[Installing Red Hat build of Kueue].

. Activate the Kueue integration and optionally specify custom default names for the cluster queue and local queue.
+
* To activate Kueue with the default cluster queue and local queue names, use the following command. Replace `<operator-namespace>` with your operator namespace (the default is `pass:attributes[{operator-default-namespace}]`).
+
[source,terminal]
----
oc patch datasciencecluster default-dsc --type='merge' -p '{"spec":{"components":{"kueue":{"managementState":"Unmanaged"}}}}' -n <operator-namespace>
----
+
* To activate Kueue with custom default cluster queue and local queue names, use the following command. Replace `<example-cluster-queue>` and `<example-local-queue>` with your custom queue names, and replace `<operator-namespace>` with your operator namespace (the default is `pass:attributes[{operator-default-namespace}]`).
+
[source,terminal]
----
oc patch datasciencecluster default-dsc --type='merge' -p '{"spec":{"components":{"kueue":{"managementState":"Unmanaged","defaultClusterQueueName":"<example-cluster-queue>","defaultLocalQueueName":"<example-local-queue>"}}}}' -n <operator-namespace>
----

.Verification

. Verify that the default `ClusterQueue` was created:
+
[source,terminal]
----
oc get clusterqueue
----

. Verify that a default `LocalQueue` exists in the {productname-short} applications namespace; the default namespace is `pass:attributes[{dbd-config-default-namespace}]`.
+
[source,terminal]
----
oc get localqueue -n <applications-namespace>
----

.Next steps
* Configure quotas by creating and modifying `ResourceFlavor`, `ClusterQueue`, and `LocalQueue` objects. For details, see the link:https://docs.redhat.com/en/documentation/red_hat_build_of_kueue[{rhbok-productname}] documentation.
* Enable Kueue in the dashboard so that users can select Kueue-enabled options when creating workloads. This also enables Kueue management for all new projects created from the dashboard. See _Enabling Kueue in the dashboard_.
* Cluster administrators and {productname-short} administrators can create hardware profiles so that users can submit workloads from the {productname-short} dashboard. 
ifdef::upstream[]
See link:{odhdocshome}/working-with-accelerators/#working-with-hardware-profiles_accelerators[Working with hardware profiles].
endif::[]
ifndef::upstream[]
See link:{rhoaidocshome}{default-format-url}/working_with_accelerators/working-with-hardware-profiles_accelerators[Working with hardware profiles].
endif::[]