:_module-type: PROCEDURE

[id="configuring-monitoring-for-your-model-serving-platform_{context}"]
= Configuring monitoring for your model serving platform

[role="_abstract"]

{productname-short} provides single-model and multi-model serving platforms.


Single-model serving platform::
For deploying large models such as large language models (LLMs), {productname-short} includes a single-model serving platform.
+
ifdef::upstream[]
For more information, see: link:{odhdocshome}/managing-and-monitoring-models/#configuring-monitoring-for-the-single-model-serving-platform_cluster-admin[Configuring monitoring for the single-model serving platform].
endif::[]
ifndef::upstream[]
For more information, see: link:{rhoaidocshome}{default-format-url}/managing_and_monitoring_models/cluster-admin_cluster-admin#configuring-monitoring-for-the-single-model-serving-platform_cluster-admin[Configuring monitoring for the single-model serving platform].
endif::[]


Multi-model serving platform::
For deploying small and medium-sized models, {productname-short} includes a multi-model serving platform. 
+
ifdef::upstream[]
For more information, see link:{odhdocshome}/managing-and-monitoring-models/#configuring-monitoring-for-the-multi-model-serving-platform_cluster-admin[Configuring monitoring for the multi-model serving platform].
endif::[]
ifndef::upstream[]
For more information, see: link:{rhoaidocshome}{default-format-url}/managing_and_monitoring_models/index#configuring-monitoring-for-the-multi-model-serving-platform_cluster-admin[Configuring monitoring for the multi-model serving platform].
endif::[]

