:_module-type: PROCEDURE

[id="configuring-a-recommended-accelerator-for-workbench-images_{context}"]
= Configuring a recommended accelerator for workbench images

[role='_abstract']
To help you indicate the most suitable accelerators to your data scientists, you can configure a recommended tag to appear on the dashboard. 

.Prerequisites
* You have logged in to {productname-short} as a user with {productname-short} administrator privileges.
* You have existing workbench images in your deployment.
ifndef::upstream[]
* You have enabled GPU support in {productname-short}. This includes installing the Node Feature Discovery Operator and NVIDIA GPU Operator. For more information, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/specialized_hardware_and_driver_enablement/psap-node-feature-discovery-operator#installing-the-node-feature-discovery-operator_psap-node-feature-discovery-operator[Installing the Node Feature Discovery Operator^] and link:{rhoaidocshome}{default-format-url}/managing_openshift_ai/enabling-accelerators#enabling-nvidia-gpus_managing-rhoai[Enabling NVIDIA GPUs^].
endif::[]
ifdef::upstream[]
* You have enabled GPU support. This includes installing the Node Feature Discovery and NVIDIA GPU Operators. For more information, see link:https://docs.nvidia.com/datacenter/cloud-native/openshift/latest/index.html[NVIDIA GPU Operator on {org-name} OpenShift Container Platform^] in the NVIDIA documentation. 
endif::[]

.Procedure
. From the {productname-short} dashboard, click *Settings* -> *Environment setup* -> *Workbench images*.
+
The *Workbench images* page opens. Previously imported workbench images are displayed. 
. Click the action menu (&#8942;) and select *Edit* from the list.
+
The *Update workbench image* dialog opens.
. From the *Accelerator identifier* list, select an identifier to set its accelerator as recommended with the workbench image. If the workbench image contains only one accelerator identifier, the identifier name displays by default.
. Click *Update*.
+
[NOTE]
====
If you have already configured an accelerator identifier for a workbench image, you can specify a recommended accelerator for the workbench image by creating an associated accelerator profile or hardware profile. To do this, click *Create profile* on the row containing the workbench image and complete the relevant fields. If the workbench image does not contain an accelerator identifier, you must manually configure one before creating an associated accelerator profile or hardware profile.  
====
+
[IMPORTANT]
====
By default, hardware profiles are hidden in the dashboard navigation menu and user interface, while accelerator profiles remain visible. In addition, user interface components associated with the deprecated accelerator profiles functionality are still displayed. If you enable hardware profiles, the *Hardware profiles* list is displayed instead of the *Accelerator profiles* list. To show the *Settings -> Hardware profiles* option in the dashboard navigation menu, and the user interface components associated with hardware profiles, set the `disableHardwareProfiles` value to `false` in the `OdhDashboardConfig` custom resource (CR) in {openshift-platform}. 
ifdef::upstream[]
For more information about setting dashboard configuration options, see link:{odhdocshome}/managing-resources/#customizing-the-dashboard[Customizing the dashboard].
endif::[]
ifndef::upstream[]
For more information about setting dashboard configuration options, see link:{rhoaidocshome}{default-format-url}/managing_resources/customizing-the-dashboard[Customizing the dashboard].
endif::[]
====

.Verification
* When your data scientists select an accelerator with a specific workbench image, a tag is displayed next to the corresponding accelerator indicating its compatibility. 

//[role='_additional-resources']
//.Additional resources
