:_module-type: PROCEDURE

[id='configuring-the-opentelemetry-exporter_{context}']

= Configuring the OpenTelemetry exporter

[role='_abstract']
Enable traces and metrics that are provided for the observability of the `GuardrailsOrchestrator` service with the OpenTelemetry exporter.

.Prerequisites
* You have installed the {productname-long} distributed tracing platform from the link:https://operatorhub.io/[OperatorHub] and created a Jaeger instance using the default settings.
* You have installed the {org-name} build of OpenTelemetry from the OperatorHub and created an OpenTelemetry instance.

.Procedure
. Define a `GuardrailsOrchestrator` custom resource object to specify the `otelExporter` configurations in a YAML file named `orchestrator_otel_cr.yaml`:
+
.Example of a `orchestrator_otel_cr.yaml` object that has OpenTelemetry configured:
[source,yaml]
----
apiVersion: trustyai.opendatahub.io/v1
kind: GuardrailsOrchestrator
metadata:
  name: gorch-test
spec:
  orchestratorConfig: "fms-orchestr8-config-nlp"    <1>
  replicas: 1
  otelExporter:
    protocol: "http"
    otlpEndpoint: "localhost:4318"
    otlpExport: "metrics"
----
<1> This references the config map that was created in Step 1 of "Deploying the Guardrails Orchestrator service".

. Deploy the orchestrator custom resource:
+
[source,terminal]
----
$ oc apply -f orchestrator_otel_cr.yaml
----

. Observe Jaeger traces:
.. In the {openshift-platform} web console, change your perspective from *Administrator* to *Developer*.
.. Navigate to *Topology* and click on the Jaeger url.
.. Under *Service*, select *jaeger-all-in-one* and click on the *Find Traces* button.