:_module-type: PROCEDURE

[id="configuring-monitoring-for-the-multi-model-serving-platform_{context}"]
= Configuring monitoring for the multi-model serving platform

[role="_abstract"]
The multi-model serving platform includes model and model server metrics for the ModelMesh component. ModelMesh generates its own set of metrics and does not rely on the underlying model-serving runtimes to provide them. The set of metrics that ModelMesh generates includes metrics for model request rates and timings, model loading and unloading rates, times and sizes, internal queuing delays, capacity and usage, cache state, and least recently-used models. For more information, see link:https://github.com/kserve/modelmesh-serving/blob/main/docs/monitoring.md[ModelMesh metrics^]. 

After you have configured monitoring, you can view metrics for the ModelMesh component. 

.Prerequisites
* You have cluster administrator privileges for your {openshift-platform} cluster.
* You have installed the {openshift-cli} as described in the appropriate documentation for your cluster:
ifdef::upstream,self-managed[]
** link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI^] for OpenShift Container Platform  
** link:https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws/{rosa-latest-version}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI^] for {rosa-productname}
endif::[]
ifdef::cloud-service[]
** link:https://docs.redhat.com/en/documentation/openshift_dedicated/{osd-latest-version}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI^] for OpenShift Dedicated  
** link:https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws_classic_architecture/{rosa-classic-latest-version}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI^] for {rosa-classic-productname}
endif::[]
* You are familiar with link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/monitoring/configuring-core-platform-monitoring#preparing-to-configure-the-monitoring-stack[creating a config map] for monitoring a user-defined workflow. You will perform similar steps in this procedure.
* You are familiar with link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/monitoring/configuring-user-workload-monitoring#enabling-monitoring-for-user-defined-projects-uwm_preparing-to-configure-the-monitoring-stack-uwm[enabling monitoring] for user-defined projects in OpenShift. You will perform similar steps in this procedure.
* You have link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/monitoring/configuring-user-workload-monitoring#granting-users-permission-to-monitor-user-defined-projects_preparing-to-configure-the-monitoring-stack-uwm[assigned] the `monitoring-rules-view` role to users that will monitor metrics.

.Procedure
. In a terminal window, if you are not already logged in to your OpenShift cluster as a cluster administrator, log in to the {openshift-cli} as shown in the following example:
+
[source,subs="+quotes"]
----
$ oc login __<openshift_cluster_url>__ -u __<admin_username>__ -p __<password>__
----

. Define a `ConfigMap` object in a YAML file called `uwm-cm-conf.yaml` with the following contents:
+
[source]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus:
      logLevel: debug 
      retention: 15d
----
+
The `user-workload-monitoring-config` object configures the components that monitor user-defined projects.  Observe that the retention time is set to the recommended value of 15 days.

. Apply the configuration to create the `user-workload-monitoring-config` object.
+
[source]
----
$ oc apply -f uwm-cm-conf.yaml
----

. Define another `ConfigMap` object in a YAML file called `uwm-cm-enable.yaml` with the following contents:

+
[source]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
----
+
The `cluster-monitoring-config` object enables monitoring for user-defined projects.

. Apply the configuration to create the `cluster-monitoring-config` object.
+
[source]
----
$ oc apply -f uwm-cm-enable.yaml
----

// [role="_additional-resources"]
// .Additional resources
