:_module-type: PROCEDURE

[id="configuring-the-default-pvc-size-for-your-cluster_{context}"]
= Configuring the default PVC size for your cluster

[role='_abstract']
To configure how resources are claimed within your {productname-short} cluster, you can change the default size of the cluster's persistent volume claim (PVC) ensuring that the storage requested matches your common storage workflow. PVCs are requests for resources in your cluster and also act as claim checks to the resource.

//Changing your cluster's default PVC size causes a redeployment of the Jupyter server launcher, making it temporarily unavailable. PVCs that were already assigned before the default size was changed are unaffected and retain their original size. Notebook servers created by users before the PVC size change are also unaffected.

//Users cannot access the Jupyter server launcher or create a new notebook server until redeployment is complete. {org-name} recommends that administrators consider the impact of these restrictions when determining the best time to change the default PVC size.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::self-managed[]
* You are part of the {productname-short} administrator group in {openshift-platform}.
endif::[]

NOTE: Changing the PVC setting restarts the Jupyter pod and makes Jupyter unavailable for up to 30 seconds. As a workaround, it is recommended that you perform this action outside of your organization's typical working day.

.Procedure
. From the {productname-short} dashboard, click *Settings* -> *Cluster settings*.
. Under *PVC size*, enter a new size in gibibytes. The minimum size is 1 GiB, and the maximum size is 16384 GiB.
. Click *Save changes*.

.Verification
* New PVCs are created with the default storage size that you configured.

[role='_additional-resources']
.Additional resources
* link:https://docs.openshift.com/container-platform/4.13/storage/understanding-persistent-storage.html[Understanding persistent storage]
//TEST
