:_module-type: PROCEDURE

[id='configuring-the-opentelemetry-exporter_{context}']

= Configuring the OpenTelemetry exporter

[role='_abstract']
Enable traces and metrics that are provided for the observability of the `GuardrailsOrchestrator` service with the OpenTelemetry exporter.

.Prerequisites
* You have installed the Tempo Operator from the link:https://operatorhub.io/[OperatorHub].
* You have installed the {org-name} build of OpenTelemetry from the OperatorHub.

.Procedure
. Enable user workload monitoring to observe telemetry data in {openshift-platform}:
+
[source,terminal]
----
$ oc -n openshift-monitoring patch configmap cluster-monitoring-config --type merge -p '{"data":{"config.yaml":"enableUserWorkload: true\n"}}'
----

. Deploy a MinIO instance to serve as the storage backend for Tempo:
+
[source,terminal]
----
$ oc apply -f minio.yaml
----
+
Wait for the `minio-xxx` pod to be running.

. Create a TempoStack instance:
+
[source,terminal]
----
$ oc apply -f tempo.yaml
----
+
Wait for the `<tempo_stack_name>-xxx` pods to be running.

. Configure the OpenTelemetry instance to send telemetry data to the Tempo distributor:
.. Create a YAML file named `opentelemetry.yaml` with the following content:
+
.Example `opentelemetry.yaml` configuration
[source,yaml]
----
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: <otelcol_name>
spec:
  observability:
    metrics:
      enableMetrics: true
  deploymentUpdateStrategy: {}
  config:
    exporters:
      debug: null
      otlp:
        endpoint: 'tempo-<tempo_stack_name>-distributor:4317'
        tls:
          insecure: true
      prometheus:
        add_metric_suffixes: false
        endpoint: '0.0.0.0:8889'
        resource_to_telemetry_conversion:
          enabled: true
    processors:
      batch:
        send_batch_size: 10000
        timeout: 10s
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: '0.0.0.0:4317'
          http:
            endpoint: '0.0.0.0:4318'
    service:
      pipelines:
        metrics:
          exporters:
            - prometheus
            - debug
          processors:
            - batch
          receivers:
            - otlp
        traces:
          exporters:
            - otlp
            - debug
          processors:
            - batch
          receivers:
            - otlp
      telemetry:
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: 0.0.0.0
                    port: 8888
  mode: deployment
----
+
The OpenTelemetry collector configuration defines the Tempo distributor and Prometheus services as exporters, which means that the OpenTelemetry collector sends telemetry data to these backends.

.. Apply the OpenTelemetry configuration:
+
[source,terminal]
----
$ oc apply -f opentelemetry.yaml
----
+
Wait for the `<otelcol_name>-collector-xxx` pod to be running.

. Define a `GuardrailsOrchestrator` custom resource object to specify the `otelExporter` configurations in a YAML file named `orchestrator_otel_cr.yaml`:
+
.Example `orchestrator_otel_cr.yaml` object with OpenTelemetry configured
[source,yaml]
----
apiVersion: trustyai.opendatahub.io/v1alpha1
kind: GuardrailsOrchestrator
metadata:
  name: gorch-test
spec:
  orchestratorConfig: "fms-orchestr8-config-nlp"    <1>
  replicas: 1
  otelExporter:
    protocol: "http"
    otlpEndpoint: "localhost:4318"
    otlpExport: "metrics"
----
<1> This references the config map that you created when deploying the Guardrails Orchestrator service.

. Deploy the orchestrator custom resource:
+
[source,terminal]
----
$ oc apply -f orchestrator_otel_cr.yaml
----

. Observe traces using the Jaeger UI:
.. Access the Jaeger UI by port-forwarding the Tempo traces service:
+
[source,terminal]
----
$ oc port-forward svc/tempo-<tempo_stack_name>-query-frontend 16686:16686
----
.. In a separate browser window, navigate to `http://localhost:16686` to access the Jaeger UI.
.. Under *Service*, select *fms_guardrails_orchestr8* and click on the *Find Traces* button.
