:_module-type: PROCEDURE

[id="configuring-storage-class-settings_{context}"]
= Configuring storage class settings 

[role='_abstract']
As an {productname-short} administrator, you can manage {openshift-platform} cluster storage class settings for usage within {productname-short}, including the display name, description, and whether users can use the storage class when creating or editing cluster storage. These settings do not impact the storage class within {openshift-platform}.

.Prerequisites
* You have logged in to {productname-short} as a user with {productname-short} administrator privileges. 

.Procedure
. From the {productname-short} dashboard, click *Settings* -> *Storage classes*.
+
The *Storage classes* page appears, displaying the storage classes for your cluster as defined in {openshift-platform}.
. To enable or disable a storage class for users, on the row containing the storage class, click the toggle in the *Enable* column.
. To edit a storage class, on the row containing the storage class, click the action menu (&#8942;) and then select *Edit*.
+
The *Edit storage class details* dialog opens.

. Optional: In the *Display Name* field, update the name for the storage class. This name is used only in {productname-short} and does not impact the storage class within {openshift-platform}.
. Optional: In the *Description* field, update the description for the storage class. This description is used only in {productname-short} and does not impact the storage class within {openshift-platform}.
. For storage classes that support multiple access modes, select an *Access mode* to define how the storage can be used. For more information, see __About storage classes__. 
+
The available access modes depend on what your cluster and {productname-short} administrators have enabled for the storage class:
+
* `ReadWriteOnce (RWO)`: (Default) The storage can be attached to a single workbench at a given time.
* `ReadWriteMany (RWX)`: The storage can be attached to many workbenches simultaneously.
* `ReadOnlyMany (ROX)`: The storage can be attached to many workbenches as read-only.
* `ReadWriteOncePod (RWOP)`: The storage can be attached to a single pod on a single node as read-write.
+
NOTE: Access mode is a Kubernetes concept that determines how nodes can interact with the volume. Users can create storage using enabled access modes. The OpenShift storage class determines which access modes (RWO, RWX, ROX and RWOP) are supported by default.
. Click *Save*.

.Verification
* If you enabled a storage class, the storage class is available for selection when a user adds cluster storage to a data science project or workbench.
* If you disabled a storage class, the storage class is not available for selection when a user adds cluster storage to a data science project or workbench.
* If you edited a storage class name, the updated storage class name is displayed when a user adds cluster storage to a data science project or workbench.

[role='_additional-resources']
.Additional resources
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/storage/understanding-persistent-storage#pvc-storage-class_understanding-persistent-storage[Storage classes in {openshift-platform}]

