:_module-type: PROCEDURE

[id="configuring-monitoring-for-the-multi-model-serving-platform_{context}"]
= Configuring monitoring for the multi-model serving platform

[role="_abstract"]
The multi-model serving platform includes per model and model server metrics for the ModelMesh component, such as loading and unloading rates, request rates, internal queueing delays and so on. ModelMesh generates its own metrics and does not rely on the underlying serving runtime to provide metrics. For more information, see link:https://github.com/kserve/modelmesh-serving/blob/main/docs/monitoring.md[ModelMesh metrics]. 

When you have configured monitoring, you can view available metrics for the ModelMesh component. 

.Prerequisites
* You have cluster administrator privileges for your {openshift-platform} cluster.
* You have downloaded and installed the OpenShift command-line interface (CLI). See link:https://docs.openshift.com/container-platform/{ocp-latest-version}/cli_reference/openshift_cli/getting-started-cli.html#installing-openshift-cli[Installing the OpenShift CLI].
* You are familiar with link:https://docs.openshift.com/container-platform/{ocp-latest-version}/monitoring/configuring-the-monitoring-stack.html#creating-user-defined-workload-monitoring-configmap_configuring-the-monitoring-stack[creating a config map] for monitoring a user-defined workflow. You will perform similar steps in this procedure.
* You are familiar with link:https://docs.openshift.com/container-platform/{ocp-latest-version}/monitoring/enabling-monitoring-for-user-defined-projects.html[enabling monitoring] for user-defined projects in OpenShift. You will perform similar steps in this procedure.
* You have link:https://docs.openshift.com/container-platform/{ocp-latest-version}/monitoring/enabling-monitoring-for-user-defined-projects.html#granting-users-permission-to-monitor-user-defined-projects_enabling-monitoring-for-user-defined-projects[assigned] the `monitoring-rules-view` role to users that will monitor metrics.

.Procedure
. In a terminal window, if you are not already logged in to your OpenShift cluster as a cluster administrator, log in to the OpenShift CLI as shown in the following example:
+
[source,subs="+quotes"]
----
$ oc login __<openshift_cluster_url>__ -u __<admin_username>__ -p __<password>__
----

. Define a `ConfigMap` object in a YAML file called `uwm-cm-conf.yaml` with the following contents:
+
[source]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus:
      logLevel: debug 
      retention: 15d
----
+
The `user-workload-monitoring-config` object configures the components that monitor user-defined projects.  Observe that the retention time is set to the recommended value of 15 days.

. Apply the configuration to create the `user-workload-monitoring-config` object.
+
[source]
----
$ oc apply -f uwm-cm-conf.yaml
----

. Define another `ConfigMap` object in a YAML file called `uwm-cm-enable.yaml` with the following contents:

+
[source]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
----
+
The `cluster-monitoring-config` object enables monitoring for user-defined projects.

. Apply the configuration to create the `cluster-monitoring-config` object.
+
[source]
----
$ oc apply -f uwm-cm-enable.yaml
----

// [role="_additional-resources"]
// .Additional resources
