:_module-type: PROCEDURE

[id="configuring-metrics-based-autoscaling_{context}"]
= Configuring metrics-based autoscaling

[role="_abstract"]
While Knative-based autoscaling features are not available in standard deployment modes, you can enable metrics-based autoscaling for an inference service in these deployments. This capability helps you efficiently manage accelerator resources, lower operational costs, and ensure that your inference services meet performance requirements.

To set up autoscaling for your inference service in standard deployments, you must install and configure the OpenShift Custom Metrics Autoscaler (CMA), which is based on Kubernetes Event-driven Autoscaling (KEDA). You can then utilize various model runtime metrics available in OpenShift Monitoring, such as KVCache utilization, Time to First Token (TTFT), and concurrency, to trigger autoscaling of your inference service. 

.Prerequisites
* You have cluster administrator privileges for your {openshift-platform} cluster.
* You have installed the CMA operator on your cluster. For more information, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/nodes/automatically-scaling-pods-with-the-custom-metrics-autoscaler-operator#nodes-cma-autoscaling-custom-install[Installing the custom metrics autoscaler].
+
[NOTE]
====
The `odh-controller` automatically creates the `TriggerAuthentication`, `ServiceAccount`, `Role`, `RoleBinding`, and `Secret` resources to allow CMA access to OpenShift Monitoring metrics.
====
* You have enabled User Workload Monitoring (UWM) for your cluster. For more information, see https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/monitoring/configuring-user-workload-monitoring[Configuring user workload monitoring].
* You have deployed a model on the single-model serving platform in standard deployment mode.

.Procedure

. Log in to the {openshift-platform} console as a cluster administrator.
. In the *Administrator* perspective, click *Home* -> *Search*.
. Select the project where you have deployed your model.
. From the *Resources* dropdown menu, select *InferenceService*.
. Click the `InferenceService` for your deployed model and then click *YAML*.
. Under `spec.predictor`, define a metric-based autoscaling policy similar to the following example:
+
[source,yaml]
----
spec:
  predictor:
    # …
    minReplicas: 1
    maxReplicas: 5
    autoscaling:
      metrics:
        - type: External
          external:
            metric:
              backend: "prometheus"
              serverAddress: "https://<thanos-service>.<monitoring-namespace>.svc.cluster.local:9091"
              query: vllm:num_requests_waiting
            authenticationRef:
              name: openshift-monitoring-metrics-auth
            target:
              type: Value
              value: 2
----
+
The example configures the inference service to autoscale between 1-5 replicas based on the number of requests waiting to be processed, as determined by the `vllm:num_requests_waiting` metric.
. Click *Save*.

//[role="_additional-resources"]
//.Additional resources
