:_module-type: PROCEDURE

[id="configuring-the-dashboard_{context}"]
= Configuring the dashboard

[role='_abstract']
In addition to the options under the *Settings* menu in {productname-short}, administrators can use {openshift-platform} to configure advanced options for the {productname-short} dashboard.

.Prerequisites
* You have cluster administrator privileges for your {openshift-platform} cluster.

.Procedure
. Log in to the {openshift-platform} console as a cluster administrator.
. In the *Administrator* perspective, click *Home* -> *API Explorer*.
. In the search bar, enter `OdhDashboardConfig` to filter by kind.
. Click the `OdhDashboardConfig` custom resource (CR) to open the resource details page.
. Click the *Instances* tab.
. Click the `odh-dashboard-config` instance to open the instance details page.
. Click the *YAML* tab.
. Change values as needed. For more information, see xref:dashboard-options[Dashboard options].

.Verification
Log in to {productname-short} and verify that your dashboard configurations apply.