:_module-type: PROCEDURE

[id="configuring-a-recommended-accelerator-for-notebook-images_{context}"]
= Configuring a recommended accelerator for notebook images

[role='_abstract']
To help you indicate the most suitable accelerators to your data scientists, you can configure a recommended tag to appear on the dashboard. 

.Prerequisites
* You have logged in to {productname-short} as a user with {productname-short} administrator privileges.
* You have existing notebook images in your deployment.
ifndef::upstream[]
* You have enabled GPU support in {productname-short}. This includes installing the Node Feature Discovery operator and NVIDIA GPU Operators. For more information, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/specialized_hardware_and_driver_enablement/psap-node-feature-discovery-operator#installing-the-node-feature-discovery-operator_psap-node-feature-discovery-operator[Installing the Node Feature Discovery operator^] and link:{rhoaidocshome}{default-format-url}/managing_openshift_ai/enabling_accelerators#enabling-nvidia-gpus_managing-rhoai[Enabling NVIDIA GPUs^].
endif::[]
ifdef::upstream[]
* You have enabled GPU support. This includes installing the Node Feature Discovery and NVIDIA GPU Operators. For more information, see https://docs.nvidia.com/datacenter/cloud-native/openshift/latest/index.html[NVIDIA GPU Operator on {org-name} OpenShift Container Platform^] in the NVIDIA documentation. 
endif::[]

.Procedure
. From the {productname-short} dashboard, click *Settings* -> *Notebook images*.
+
The *Notebook images* page appears. Previously imported notebook images are displayed. 
. Click the action menu (&#8942;) and select *Edit* from the list.
+
The *Update notebook image* dialog opens.
. From the *Accelerator identifier* list, select an identifier to set its accelerator as recommended with the notebook image. If the notebook image contains only one accelerator identifier, the identifier name displays by default.
. Click *Update*.
+
[NOTE]
====
If you have already configured an accelerator identifier for a notebook image, you can specify a recommended accelerator for the notebook image by creating an associated accelerator profile. To do this, click *Create profile* on the row containing the notebook image and complete the relevant fields. If the notebook image does not contain an accelerator identifier, you must manually configure one before creating an associated accelerator profile.  
====

.Verification
* When your data scientists select an accelerator with a specific notebook image, a tag appears next to the corresponding accelerator indicating its compatibility. 

//[role='_additional-resources']
//.Additional resources
