:_module-type: PROCEDURE

[id="configuring-the-default-storage-class-for-your-cluster_{context}"]
= Configuring the default storage class for your cluster

[role='_abstract']
As an {productname-short} administrator, you can configure the default storage class for {productname-short} to be different from the default storage class in {openshift-platform}.

.Prerequisites
* You have logged in to {productname-long}.
* You have {productname-short} administrator permissions.

.Procedure
. From the {productname-short} dashboard, click *Settings* -> *Storage classes*.
+
The *Storage classes* page appears, displaying the storage classes for your cluster as defined in {openshift-platform}.
. If the storage class that you want to set as the default is not enabled, on the row containing the storage class, click the toggle in the *Enable* column.
. To set a storage class as the default for {productname-short}, on the row containing the storage class, select *Set as default*.

.Verification
* When a user adds cluster storage to a data science project or workbench, the default storage class that you configured is automatically selected.

[role='_additional-resources']
.Additional resources
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/storage/understanding-persistent-storage#pvc-storage-class_understanding-persistent-storage[Storage classes]

