:_module-type: PROCEDURE

[id="configuring-a-storage-class-for-lab-tuning_{context}"]
= Configuring a storage class for LAB-tuning

[role='_abstract']
The InstructLab pipeline requires a storage class that supports dynamic provisioning with the `ReadWriteMany` access mode. This ensures that `PersistentVolumes` can be created automatically and shared across multiple pods.

.Prerequisites
* You have installed the required Operators and components for LAB-tuning. 
* You are logged in to {productname-short} as a user with administrator privileges.

.Procedure
. To configure a storage class, follow the steps described in link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/storage/configuring-persistent-storage[Configuring persistent storage] in the {openshift-platform} documentation.
+
TIP: To quickly configure a compatible storage class for a non-production environment, see link:https://github.com/opendatahub-io/ilab-on-ocp/blob/main/manifests/nfs_storage/nfs_storage.md[Set up NFS StorageClass]. The image provided in this example is for test purposes only. For production environments, you must use a production-ready storage class that supports `ReadWriteMany` access mode.

. Follow the steps described in _Configuring storage class settings_ to ensure that the new storage class is available for use in {productname-short}. 

//link:https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/latest/html/managing_resources/managing-storage-classes#configuring-storage-class-settings_resource-mgmt

