:_module-type: PROCEDURE

[id="configuring-storage-class-settings_{context}"]
= Configuring storage class settings 

[role='_abstract']
As an {productname-short} administrator, you can manage the following {openshift-platform} cluster storage class settings for use within {productname-short}:

* Display name
* Description
* Access modes
* Whether users can use the storage class when creating or editing cluster storage

These settings do not impact the storage class within {openshift-platform}.

.Prerequisites
* You have logged in to {productname-short} as a user with {productname-short} administrator privileges. 

.Procedure
. From the {productname-short} dashboard, click *Settings* -> *Storage classes*.
+
The *Storage classes* page appears, displaying the storage classes for your cluster as defined in {openshift-platform}.
. To enable or disable a storage class for users, on the row containing the storage class, click the toggle in the *Enable* column.
. To edit a storage class, on the row containing the storage class, click the action menu (&#8942;) and then select *Edit*.
+
The *Edit storage class details* dialog opens.

. Optional: In the *Display Name* field, update the name for the storage class. This name is used only in {productname-short} and does not impact the storage class within {openshift-platform}.
. Optional: In the *Description* field, update the description for the storage class. This description is used only in {productname-short} and does not impact the storage class within {openshift-platform}.
ifndef::[upstream]
. For storage classes that support multiple access modes, select an *Access mode* to define how the volume can be accessed. For more information, see link: link:{odhdocshome}/managing_resources/managing-storage-classes#about-persistent-storage_resource-mgmt[About persistent storage]. 
+
Only the access modes that have been enabled for the storage class by your cluster administrator are available for selection.
endif::[]
+
. Click *Save*.

.Verification
* If you enabled a storage class, the storage class is available for selection when a user adds cluster storage to a data science project or workbench.
* If you disabled a storage class, the storage class is not available for selection when a user adds cluster storage to a data science project or workbench.
* If you edited a storage class name, the updated storage class name is displayed when a user adds cluster storage to a data science project or workbench.

[role='_additional-resources']
.Additional resources
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/storage/understanding-persistent-storage#pvc-storage-class_understanding-persistent-storage[Storage classes in {openshift-platform}]

