:_module-type: PROCEDURE

[id="configuring-the-default-pvc-size-for-your-cluster_{context}"]
= Configuring the default PVC size for your cluster

[role='_abstract']
To configure how resources are claimed within your {productname-short} cluster, you can change the default size of the cluster's persistent volume claim (PVC) ensuring that the storage requested matches your common storage workflow. PVCs are requests for resources in your cluster and also act as claim checks to the resource.

//Changing your cluster's default PVC size causes a redeployment of the basic workbench launcher, making it temporarily unavailable. PVCs that were already assigned before the default size was changed are unaffected and retain their original size. Workbenches created by users before the PVC size change are also unaffected.

//Users cannot access the basic workbench launcher or create a new workbench until redeployment is complete. {org-name} recommends that administrators consider the impact of these restrictions when determining the best time to change the default PVC size.

.Prerequisites
* You have logged in to {productname-short} as a user with {productname-short} administrator privileges. 

NOTE: Changing the PVC setting restarts the workbench pod and makes it unavailable for up to 30 seconds. As a workaround, it is recommended that you perform this action outside of your organization's typical working day.

.Procedure
. From the {productname-short} dashboard, click *Settings* -> *Cluster settings*.
. Under *PVC size*, enter a new size in gibibytes or mebibytes.
. Click *Save changes*.

.Verification
* New PVCs are created with the default storage size that you configured.

When resizing a PVC backed by AWS EBS in {productname-short}, you might see the following error message:

[source,terminal]
----
VolumeModificationRateExceeded: You've reached the maximum modification rate per volume limit. Wait at least 6 hours between modifications per EBS volume.
----
This is an AWS EBS service limit, not specific to NVIDIA NIM, KServe, or any application. 
It applies to all workloads using EBS-backed PVCs. 
If a PVC resize is attempted before the cooldown expires, the AWS EBS CSI driver (ebs.csi.aws.com) will fail the operation with this error.

[role='_additional-resources']
.Additional resources
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/storage/understanding-persistent-storage[Understanding persistent storage]
