:_module-type: PROCEDURE

[id="configuring-a-recommended-accelerator-for-serving-runtimes_{context}"]
= Configuring a recommended accelerator for serving runtimes

[role='_abstract']
To help you indicate the most suitable accelerators to your data scientists, you can configure a recommended accelerator tag for your serving runtimes. 

.Prerequisites
* You have logged in to {productname-short} as a user with {productname-short} administrator privileges.
ifndef::upstream[]
* You have enabled GPU support in {productname-short}. This includes installing the Node Feature Discovery operator and NVIDIA GPU Operators. For more information, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/specialized_hardware_and_driver_enablement/psap-node-feature-discovery-operator#installing-the-node-feature-discovery-operator_psap-node-feature-discovery-operator[Installing the Node Feature Discovery operator^] and link:{rhoaidocshome}{default-format-url}/managing_openshift_ai/enabling_accelerators#enabling-nvidia-gpus_managing-rhoai[Enabling NVIDIA GPUs^].
endif::[]
ifdef::upstream[]
* You have enabled GPU support. This includes installing the Node Feature Discovery and NVIDIA GPU Operators. For more information, see link:https://docs.nvidia.com/datacenter/cloud-native/openshift/latest/index.html[NVIDIA GPU Operator on {org-name} OpenShift Container Platform^] in the NVIDIA documentation. 
endif::[] 

.Procedure
. From the {productname-short} dashboard, click *Settings* -> *Serving runtimes*.
+
The *Serving runtimes* page opens and shows the model-serving runtimes that are already installed and enabled in your {productname-short} deployment. By default, the OpenVINO Model Server runtime is pre-installed and enabled in {productname-short}.
. Edit your custom runtime that you want to add the recommended accelerator tag to, click the action menu (&#8942;) and select *Edit*.
+ 
A page with an embedded YAML editor opens.
+
NOTE: You cannot directly edit the OpenVINO Model Server runtime that is included in {productname-short} by default. However, you can _clone_ this runtime and edit the cloned version. You can then add the edited clone as a new, custom runtime. To do this, click the action menu beside the OpenVINO Model Server and select *Duplicate*.

. In the editor, enter the YAML code to apply the annotation `opendatahub.io/recommended-accelerators`. The excerpt in this example shows the annotation to set a recommended tag for an NVIDIA GPU accelerator:
+
[source,yaml]
metadata:
	annotations:
		opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
. Click *Update*.

.Verification
* When your data scientists select an accelerator with a specific serving runtime, a tag is displayed next to the corresponding accelerator indicating its compatibility. 


//[role='_additional-resources']
//.Additional resources
