:_module-type: PROCEDURE

[id="creating-a-data-science-project_{context}"]
= Creating a data science project

[role='_abstract']
To start your data science work, create a data science project. Creating a project helps you organize your work in one place. You can also enhance the capabilities of your data science project by adding workbenches, adding storage to your project's cluster, adding data connections, and adding model servers.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, `rhods-users`) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, `odh-users`) in OpenShift.
endif::[]

.Procedure
. From the {productname-short} dashboard, click *Data Science Projects*.
+
The *Data science projects* page opens.
. Click *Create data science project*.
+
The *Create a data science project* dialog opens.
. Enter a *name* for your data science project.
. Optional: Edit the *resource name* for your data science project. The resource name must consist of lowercase alphanumeric characters, '-', and must start and end with an alphanumeric character.
. Enter a *description* for your data science project.
. Click *Create*.
+
The *Project details* page opens. From here, you can create workbenches, add cluster storage, and add data connections to your project.

.Verification
* The data science project that you created is displayed on the *Data science projects* page.

//[role='_additional-resources']
//.Additional resources//
