:_module-type: PROCEDURE

[id="creating-internal-registry_{context}"]
= Creating an internal registry

[role='_abstract']
Before you can install the AMD GPU Operator, you must create an internal image registry in {openshift-platform} to store and manage container images, such as those required for the AMD GPU Operator.

.Prerequisites
* You have administrative access to the {openshift-platform}.
* You have a running OpenShift cluster.
* You have access to the OpenShift CLI (`oc`).

.Procedure
. Log in to your OpenShift cluster using the OpenShift CLI:
+
----
oc login --server=<api_server> --token=<token>
----
. Verify that the OpenShift internal image registry is enabled:
+
----
oc get configs.imageregistry.operator.openshift.io cluster
----
.. If the `ManagementState` is set to `Removed`, enable the registry:
+
----
oc patch configs.imageregistry.operator.openshift.io cluster --type merge -p '{"spec":{"managementState":"Managed"}}'
----
. Configure persistent storage for the registry to ensure it can retain data across restarts:
.. Create a persistent volume claim (PVC) for the registry:
+
----
cat <<EOF | oc apply -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-storage
  namespace: openshift-image-registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
EOF
----
.. Patch the registry configuration to use the created PVC:
+
----
oc patch configs.imageregistry.operator.openshift.io cluster --type merge -p '{"spec":{"storage":{"pvc":{"claim":"registry-storage"}}}}'
----
. Expose the registry to make it accessible to the cluster:
+
----
oc patch configs.imageregistry.operator.openshift.io cluster --type merge -p '{"spec":{"defaultRoute":true}}'
----
.. Retrieve the registry route to confirm it is accessible:
+
----
oc get route -n openshift-image-registry
----
. Log in to the internal registry using the OpenShift CLI:
+
----
REGISTRY_URL=$(oc get route default-route -n openshift-image-registry --template='{{ .spec.host }}')
podman login -u <username> -p <token> --tls-verify=false $REGISTRY_URL
----

.Verification
* The internal registry is enabled, and the status of `configs.imageregistry.operator.openshift.io` shows `Managed`.
* The registry is configured with persistent storage.
* The registry route is accessible and allows you to push and pull container images.

[role="_additional-resources"]
.Additional resources
* link:https://docs.openshift.com/container-platform/latest/registry/configuring-registry-storage.html[Configuring Registry Storage - OpenShift Documentation]
* link:https://github.com/ROCm/gpu-operator[AMD GPU Operator GitHub Repository]
