:_module-type: CONCEPT

[id='creating-a-bias-metric_{context}']
= Creating a bias metric

[role='_abstract']
To monitor a deployed model for bias, you must first create bias metrics. When you create a bias metric, you specify details relevant to your model such as a protected attribute, privileged and unprivileged groups, a model outcome and a value that you want to monitor, and the acceptable threshold for bias.

ifndef::upstream[]
For information about the specific bias metrics, see link:{rhoaidocshome}{default-format-url}/monitoring_data_science_models/monitoring-model-bias_bias-monitoring#using-bias-metrics_bias-monitoring[Using bias metrics]. 
endif::[]
ifdef::upstream[]
For information about the specific bias metrics, see link:{odhdocshome}/monitoring-data-science-models/#using-bias-metrics_bias-monitoring[Using bias metrics]. 
endif::[]

For the complete list of TrustyAI metrics, see link:https://trustyai.org/docs/main/trustyai-service-api-reference.html[TrustyAI service API].

You can create a bias metric for a model by using the {productname-short} dashboard or by using the {openshift-cli}.

include::creating-a-bias-metric-using-dashboard.adoc[leveloffset=+1]

include::creating-a-bias-metric-using-cli.adoc[leveloffset=+1]

