:_module-type: PROCEDURE

[id="creating-an-accelerator-profile_{context}"]
= Creating an accelerator profile

[role='_abstract']
To configure accelerators for your data scientists to use in {productname-short}, you must create an associated accelerator profile. 

.Prerequisites
* You have logged in to {productname-short} as a user with {productname-short} administrator privileges.

.Procedure
. From the {productname-short} dashboard, click *Settings* -> *Accelerator profiles*.
+
The *Accelerator profiles* page appears, displaying existing accelerator profiles. To enable or disable an existing accelerator profile, on the row containing the relevant accelerator profile, click the toggle in the *Enable* column.
. Click *Create accelerator profile*. 
+
The *Create accelerator profile* dialog appears.
. In the *Name* field, enter a name for the accelerator profile.
. In the *Identifier* field, enter a unique string that identifies the hardware accelerator associated with the accelerator profile.
. Optional: In the *Description* field, enter a description for the accelerator profile.
. To enable or disable the accelerator profile immediately after creation, click the toggle in the *Enable* column.
. Optional: Add a toleration to schedule pods with matching taints.
.. Click *Add toleration*. 
+
The *Add toleration* dialog opens.
.. From the *Operator* list, select one of the following options:
* *Equal* - The *key/value/effect* parameters must match. This is the default.
* *Exists* - The *key/effect* parameters must match. You must leave a blank value parameter, which matches any.
.. From the *Effect* list, select one of the following options:
* *None* 
* *NoSchedule* - New pods that do not match the taint are not scheduled onto that node. Existing pods on the node remain.
* *PreferNoSchedule* - New pods that do not match the taint might be scheduled onto that node, but the scheduler tries not to. Existing pods on the node remain.
* *NoExecute* - New pods that do not match the taint cannot be scheduled onto that node. Existing pods on the node that do not have a matching toleration are removed.
.. In the *Key* field, enter a toleration key. The key is any string, up to 253 characters. The key must begin with a letter or number, and may contain letters, numbers, hyphens, dots, and underscores.
.. In the *Value* field, enter a toleration value. The value is any string, up to 63 characters. The value must begin with a letter or number, and may contain letters, numbers, hyphens, dots, and underscores.
.. In the *Toleration Seconds* section, select one of the following options to specify how long a pod stays bound to a node that has a node condition. 
** *Forever* - Pods stays permanently bound to a node. 
** *Custom value* - Enter a value, in seconds, to define how long pods stay bound to a node that has a node condition.
.. Click *Add*.
. Click *Create accelerator profile*.

.Verification
* The accelerator profile appears on the *Accelerator profiles* page.
* The *Accelerator* list appears on the *Start a notebook server* page. After you select an accelerator, the *Number of accelerators* field appears, which you can use to choose the number of accelerators for your notebook server.
* The accelerator profile appears on the *Instances* tab on the details page for the `AcceleratorProfile` custom resource definition (CRD).

[role='_additional-resources']
.Additional resources
* link:https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#toleration-v1-core[Toleration v1 core]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/nodes/controlling-pod-placement-onto-nodes-scheduling#nodes-scheduler-taints-tolerations-about_nodes-scheduler-taints-tolerations[Understanding taints and tolerations]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/operators/understanding-operators#crd-managing-resources-from-crds[Managing resources from custom resource definitions]