:_module-type: PROCEDURE

[id='creating-a-drift-metric-using-cli_{context}']
= Creating a drift metric by using the CLI

[role='_abstract']
You can use the OpenShift command-line interface (CLI) to create a data drift metric for a model.

.Prerequisites

* You are familiar with the specific data set schema and understand the relevant inputs and outputs.

* Your OpenShift cluster administrator added you as a user to the {openshift-platform} cluster and has installed the TrustyAI service for the data science project that contains the deployed models.

ifdef::upstream[]
* You set up TrustyAI for your data science project, as described in link:{odhdocshome}/monitoring-data-science-models/#setting-up-trustyai-for-your-project_monitor[Setting up TrustyAI for your project].
endif::[]
ifndef::upstream[]
* You set up TrustyAI for your data science project, as described in link:{rhoaidocshome}{default-format-url}/monitoring_data_science_models/setting-up-trustyai-for-your-project_monitor[Setting up TrustyAI for your project].
endif::[]

.Procedure

. Open a new terminal window.
. Follow these steps to log in to your {openshift-platform} cluster:
.. In the upper-right corner of the OpenShift web console, click your user name and select *Copy login command*. 
.. After you have logged in, click *Display token*.
.. Copy the *Log in with this token* command and paste it in the OpenShift command-line interface (CLI).
+
[source,subs="+quotes"]
----
$ oc login --token=__<token>__ --server=__<openshift_cluster_url>__
----

. Set the `TRUSTY_ROUTE` variable to the external route for the TrustyAI service pod.
+
----
TRUSTY_ROUTE=https://$(oc get route/trustyai-service --template={{.spec.host}})
----

.  Optionally, get the full list of TrustyAI service endpoints and payloads.
+
----
curl -H "Authorization: Bearer $TOKEN" --location $TRUSTY_ROUTE/q/openapi
----

. Use `POST /metrics/drift/meanshift/request` to schedule a recurring drift monitoring metric with the following syntax and payload structure:
+
*Syntax*:
+
----
curl -k -H "Authorization: Bearer $TOKEN" -X POST --location $TRUSTY_ROUTE/metrics/drift/meanshift/request \
 --header 'Content-Type: application/json' \
 --data <payload>
----
+
*Payload structure*:

`modelId`:: The name of the model to monitor.
`referenceTag`:: The data to use as the reference distribution.

For example:

----
curl -k -H "Authorization: Bearer $TOKEN" -X POST --location $TRUSTY_ROUTE/metrics/drift/meanshift/request \
     --header 'Content-Type: application/json' \
     --data "{
                 \"modelId\": \"gaussian-credit-model\",
                 \"referenceTag\": \"TRAINING\"
             }"
----

//.Verification