:_module-type: PROCEDURE


[id="creating-a-kubeflow-trainer-TrainJob-resource-by-using-the-cli_{context}"]
= Creating a Kubeflow Trainer TrainJob resource by using the CLI


[role='_abstract']

You can use the OpenShift CLI (`oc`) to create a TrainJob resource to run a distributed PyTorch training job.

.Prerequisites
* You can access an OpenShift cluster that has multiple worker nodes with supported NVIDIA GPUs or AMD GPUs.
* Your cluster administrator has configured the cluster as follows:
** Installed {productname-long} with the required distributed training components, as described in https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.2/html/installing_and_uninstalling_openshift_ai_self-managed/installing-the-distributed-workloads-components_install[Installing the distributed workloads components].
** Configured the distributed training resources, as described in https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.2/html/working_with_distributed_workloads/index[Managing distributed workloads].
** Installed the JobSet Operator from OLM, as described in https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/ai_workloads/jobset-operator[Installing the JobSet Operator].
* A ClusterTrainingRuntime is available in your cluster (for example, `torch-distributed`). To verify, run:
+
[source,subs="+quotes"]
----
oc get clustertrainingruntime
----
+
* You have administrator access for the project.
** If you created the project, you automatically have administrator access.
** If you did not create the project, your cluster administrator must give you administrator access.
* You have installed the OpenShift CLI (`oc`) as described in the appropriate documentation for your cluster:
** Installing the OpenShift CLI for OpenShift Container Platform
** Installing the OpenShift CLI for Red Hat OpenShift Service on AWS

.Procedure 
. Log in to the OpenShift CLI (`oc`):
+
[source,bash,subs="+quotes"]
----
oc login --token=<token> --server=<server>
----
+ 

. Create a file named `train.py` and populate it with your training script, as follows:
+
[source,subs="+quotes"]
----
cat <<EOF > train.py
<paste your content here>
EOF
----
+

. Create a ConfigMap resource to store the training script, as follows:
+
[source,subs="+quotes"]
----
oc create configmap training-script-configmap 
--from-file=train.py -n <your-namespace>
----
+
Replace <your-namespace> with the name of your project.

. Create a file named trainjob.yaml to define the distributed training job setup, as follows:
+
[source,subs="+quotes"]
----
cat <<'EOF' > trainjob.yaml
apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainJob
metadata:
  name: pytorch-multi-node-job
  namespace: <your-namespace>
spec:
  runtimeRef:
    name: torch-distributed
    kind: ClusterTrainingRuntime
  trainer:
    command: ["python", "/workspace/scripts/train.py"]
    numNodes: 3
    resourcesPerNode:
      requests:
        cpu: "4"
        memory: "8Gi"
        nvidia.com/gpu: 2
      limits:
        cpu: "4"
        memory: "8Gi"
        nvidia.com/gpu: 2
  podTemplateOverrides:
    - targetJobs:
        - name: node
      spec:
        volumes:
          - name: training-script-volume
            configMap:
              name: training-script-configmap
        containers:
          - name: node
            volumeMounts:
              - name: training-script-volume
                mountPath: /workspace/scripts
EOF
----
+
Replace `<your-namespace>` with the name of your project. Update the numNodes, resource constraints, and image as needed for your environment.

. Create the distributed training job, as follows:
+
[source,subs="+quotes"]
----
oc apply -f trainjob.yaml
----
+

.Verification
. Monitor the running distributed training job, as follows:
+
[source,subs="+quotes"]
----
oc get trainjob -n <your-namespace>
----
+
Replace `<your-namespace>` with the name of your project.

. Check the pod status, as follows:
+
[source,subs="+quotes"]
----
oc logs <pod-name> -n <your-namespace>
----
+
. Replace `<pod-name>` with the name of the pod and `<your-namespace>` with the name of your project.


