:_module-type: PROCEDURE

[id="creating-a-pipeline-experiment_{context}"]
= Creating a pipeline experiment

[role='_abstract']
You can introduce repeatability to your pipeline configuration in {productname-short} by using pipeline experiments to group your pipeline runs. Pipeline experiments contain pipeline runs, including recurring runs.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have previously created a data science project that is available and contains a configured pipeline server.
* You have imported a pipeline to an active pipeline server.

.Procedure
. From the {productname-short} dashboard, click *Experiments* -> *Experiments and runs*.
. On the *Experiments* page, from the *Project* drop-down list, select the project to create the pipeline experiment in.
. Click *Create experiment*.
. In the *Create experiment* dialog, configure the pipeline experiment:
.. In the *Experiment name* field, enter a name for the pipeline experiment.
.. In the *Description* field, enter a description for the pipeline experiment.
.. Click *Create experiment*.

.Verification
* The pipeline experiment that you created appears on the *Experiments* tab.

//[role='_additional-resources']
//.Additional resources
