:_module-type: PROCEDURE

[id="creating-a-data-science-project_{context}"]
= Creating a data science project

[role='_abstract']
To start your data science work, create a data science project. Creating a project helps you organize your work in one place. You can also enhance your data science project by adding the following functionality:

* Workbenches
* Storage for your project's cluster
* Data connections
* Model servers
//* Bias monitoring for your models

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group} ) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]

.Procedure
. From the {productname-short} dashboard, click *Data Science Projects*.
+
The *Data science projects* page opens.
. Click *Create data science project*.
+
The *Create a data science project* dialog opens.
. Enter a *name* for your data science project.
. Optional: Edit the *resource name* for your data science project. The resource name must consist of lowercase alphanumeric characters, '-', and must start and end with an alphanumeric character.
. Enter a *description* for your data science project.
. Click *Create*.
+
A project details page opens. From this page, you can create workbenches, add cluster storage and data connections, import pipelines, and deploy models.

.Verification
* The project that you created is displayed on the *Data science projects* page.

//[role='_additional-resources']
//.Additional resources//
