:_module-type: PROCEDURE

[id="creating-a-taxonomy_{context}"]
= Creating a taxonomy

[role='_abstract']
To use LAB-tuning in {productname-short}, you need a taxonomy stored in a Git repository. Later, when you create your LAB-tuning run in {productname-short}, you will provide the Git repository URL and any necessary authentication details.

A taxonomy is a structured set of training data that defines the _skills_ and _knowledge_ your model should learn. For more information, see link:https://docs.redhat.com/en/documentation/red_hat_enterprise_linux_ai/latest/html/creating_skills_and_knowledge_yaml_files[Creating skills and knowledge YAML files] in the {rhelai-productname-long} documentation.

A taxonomy tree for LAB-tuning organizes training data using a cascading directory structure. Each branch ends in a leaf node, and each leaf node is a directory with a `qna.yaml` file focused on a specific knowledge area or skill. Your taxonomy tree for {productname-short} must include a `root` directory, a `knowledge` directory, and a `compositional_skills` directory, as shown in the following example:

[source,plaintext]
----
taxonomy_root/
  knowledge/
    topic_1/
      qna.yaml
    topic_2/
      qna.yaml
  compositional_skills/
    skill_1/
      qna.yaml
    skill_2/
      qna.yaml
----

ifndef::upstream[]
For a more detailed example, see the link:https://github.com/RedHatOfficial/rhelai-sample-taxonomy[{rhelai-productname-short} sample taxonomy].
endif::[]
ifdef::upstream[]
For more detailed examples, see the link:https://github.com/RedHatOfficial/rhelai-sample-taxonomy[{rhelai-productname-short} sample taxonomy] and the link:https://github.com/instructlab/taxonomy[InstructLab taxonomy].
endif::[]

.Prerequisites

* You have an account on a Git hosting platform, such as GitHub or GitLab.

.Procedure

Create a taxonomy by using one of the following methods:

[NOTE]
====
{productname-short} must be able to access and clone the Git repository during the LAB-tuning run. Have the Git repository URL and authentication details ready for when you configure your LAB-tuning run.
====

*Using {rhelai-productname-long}*

. Use {rhelai-productname-short} to create your taxonomy. See link:https://docs.redhat.com/en/documentation/red_hat_enterprise_linux_ai/latest/html/creating_skills_and_knowledge_yaml_files[Creating skills and knowledge YAML files] in the {rhelai-productname-long} documentation.

*Using the sample taxonomy repository*

. Create a Git repository on GitHub, GitLab, or another Git hosting platform.
. Locally clone the {rhelai-productname-short} sample taxonomy at link:https://github.com/RedHatOfficial/rhelai-sample-taxonomy[https://github.com/RedHatOfficial/rhelai-sample-taxonomy].
. Customize the taxonomy by creating or editing folders and their corresponding `qna.yaml` files. 
+
For more information, see link:https://docs.redhat.com/en/documentation/red_hat_enterprise_linux_ai/latest/html/creating_skills_and_knowledge_yaml_files/adding_knowledge[Adding knowledge to your taxonomy tree] and link:https://docs.redhat.com/en/documentation/red_hat_enterprise_linux_ai/latest/html/creating_skills_and_knowledge_yaml_files/adding_skills[Adding skills to your taxonomy tree] in the {rhelai-productname-long} documentation.
. Push the updated taxonomy to your Git repository.

*Manually creating a taxonomy*

. Create a Git repository on GitHub, GitLab, or another Git hosting platform.
. Locally clone your new repository.
. Set up the folder structure. For example:
+
[source,console]
----
mkdir -p taxonomy_root/knowledge/topic_1
mkdir -p taxonomy_root/compositional_skills/skill_1
----
. Add `qna.yaml` files to each folder, containing the questions and answers you want the model to learn. 
+
For more information, see link:https://docs.redhat.com/en/documentation/red_hat_enterprise_linux_ai/latest/html/creating_skills_and_knowledge_yaml_files/adding_knowledge[Adding knowledge to your taxonomy tree] and link:https://docs.redhat.com/en/documentation/red_hat_enterprise_linux_ai/latest/html/creating_skills_and_knowledge_yaml_files/adding_skills[Adding skills to your taxonomy tree] in the {rhelai-productname-long} documentation.

[role='_additional-resources']
.Additional resources

* link:https://github.com/RedHatOfficial/rhelai-sample-taxonomy[{rhelai-productname-short} sample taxonomy]
* link:https://docs.redhat.com/en/documentation/red_hat_enterprise_linux_ai/latest/html/creating_skills_and_knowledge_yaml_files[Creating skills and knowledge YAML files]