:_module-type: PROCEDURE

[id='creating-a-model-registry_{context}']
= Creating a model registry

[role='_abstract']
You can create a model registry...

.Prerequisites
* 
* 

.Procedure
. From the {productname-short} dashboard, click *Settings* -> *Model registry settings*.
. Click *Create model registry*.
+
The *Create model registry* page opens.
. In the *Name* field, enter
. In the *Resource Name* field, enter 
. Optional: In the *Description* field, enter a description for the model registry.
. In the *Connect to external MySQL database* section, enter the information for the external database where your model data is stored.
.. In the *Host* field, enter the database's host name.
.. In the *Port* field, enter the database's port.
.. In the *Username* field, enter the default user name that is connected to the database.
.. In the *Password* field, enter the password for the default user account.
.. In the *Database* field, enter the database name.
. Click *Create*.

.Verification
* The new model registry appears on the *Model Registry Settings* page.
* You can view the database configuration for the model by clicking the action menu (*&#8942;*) beside the model registry, and then clicking *View database configuration*.

// [role="_additional-resources"]
// .Additional resources
// * TODO or delete
