:_module-type: PROCEDURE

[id="creating-project-scoped-resources_{context}"]
= Creating project-scoped resources

[role='_abstract']
{productname-short} users can access _global resources_ in all {productname-short} projects. However, they can access _project-scoped resources_ only within projects that they have permissions to access.

As a cluster administrator, you can create the following types of project-scoped resources in any {productname-short} project:

* Workbench images
* Hardware profiles
* Model-serving runtimes for KServe

All resource names must be unique within a project.


[NOTE]
====
ifdef::upstream[]
A user with access permissions to a project can create project-scoped resources for that project, as described in link:{odhdocshome}/working-on-projects/#creating-project-scoped-resources-for-your-project_projects[Creating project-scoped resources for your project].
endif::[]
ifndef::upstream[]
A user with access permissions to a project can create project-scoped resources for that project, as described in link:{rhoaidocshome}{default-format-url}/working_on_projects/creating-project-scoped-resources-for-your-project_projects[Creating project-scoped resources for your project].
endif::[]
====

.Prerequisites

* You can access the {openshift-platform} console as a cluster administrator.

ifdef::upstream[]
* You have set the `disableProjectScoped` dashboard configuration option to `false`, as described in link:{odhdocshome}/managing-resources/#customizing-the-dashboard[Customizing the dashboard].
endif::[]
ifndef::upstream[]
* You have set the `disableProjectScoped` dashboard configuration option to `false`, as described in link:{rhoaidocshome}{default-format-url}/managing_resources/customizing-the-dashboard[Customizing the dashboard].
endif::[]


.Procedure

. Log in to the {openshift-platform} console as a cluster administrator.
. Copy the YAML code to create the resource.
+
You can get the YAML code from a trusted source, such as an existing resource, a Git repository, or documentation.
+
For example, you can copy the YAML code from an existing resource, as follows:

.. In the *Administrator* perspective, click *Home* -> *Search*.
.. From the *Project* list, select the appropriate project.
+
ifdef::upstream[]
To limit the search to global {productname-short} resources only, select the `opendatahub` project.
endif::[]
ifndef::upstream[]
To limit the search to global {productname-short} resources only, select the `redhat-ods-applications` project.
endif::[]
.. In the *Resources* list, search for the relevant resource type:

* For workbench images, search for `ImageStream`.
* For hardware profiles, search for `HardwareProfile`.
* For serving runtimes, search for `Template`. 
From the resulting list, find the templates that have the `objects.kind` specification set to `ServingRuntime`. 

.. Select a resource, and then click the *YAML* tab. 
.. Copy the YAML content, and then click *Cancel*.

. From the *Project* list, select the target project name.
. From the toolbar, click the *+* icon to open the *Import YAML* page.
. Paste the relevant YAML content into the code area.
. Edit the `metadata.namespace` value to specify the name of the target project.
. If necessary, edit the `metadata.name` value to ensure that the resource name is unique within the specified project.
. Optional: Edit the resource name that is displayed in the {productname-short} console:

* For workbench images, edit the `metadata.annotations.opendatahub.io/notebook-image-name` value.
* For hardware profiles, edit the `spec.displayName` value.
* For serving runtimes, edit the `objects.metadata.annotations.openshift.io/display-name` value.

. Click *Create*.  


.Verification
. Log in to the {productname-short} console as a regular user.
. Verify that the project-scoped resource is shown in the specified project:

ifdef::upstream[]
* For workbench images and hardware profiles, see link:{odhdocshome}/working-on-projects/#creating-a-project-workbench_projects[Creating a workbench].
endif::[]
ifndef::upstream[]
* For workbench images and hardware profiles, see link:{rhoaidocshome}{default-format-url}/working_on_projects/using-project-workbenches_projects#creating-a-project-workbench_projects[Creating a workbench].
endif::[]

ifdef::upstream[]
* For serving runtimes, see link:{odhdocshome}/deploying-models/#deploying-models-on-the-model-serving-platform_odh-user[Deploying models].
endif::[]
ifndef::upstream[]
* For serving runtimes, see link:{rhoaidocshome}{default-format-url}/deploying_models/deploying_models_on_the_single_model_serving_platform#deploying-models-on-the-model-serving-platform_rhoai-user[Deploying models].
endif::[]


////
[role='_additional-resources']
.Additional resources
////
