:_module-type: PROCEDURE

[id='creating-a-custom-ray-image_{context}']
= Creating a custom Ray image

You can create a custom Ray image by adding packages to a base Ray cluster image.

.Prerequisites

* You have chosen a Ray cluster image to use as the base for your custom image. 
ifndef::upstream[]
+
See link:https://access.redhat.com/articles/rhoai-supported-configs[Supported Configurations] for a list of the {productname-short} base Ray cluster images and their preinstalled packages.
endif::[]

* You can access the base Ray cluster image.
* You have Podman installed in your local environment, and you can access a container registry.
For more information about Podman and container registries, see link:https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/building_running_and_managing_containers/index[Building, running, and managing containers].


.Procedure

. In a terminal window, create a directory for your work, and change to that directory. 
In the example commands in this section, `ray-torch` is the name of the working directory.
+
.Create a working directory
[source,bash]
----
export IMG=ray-torch
mkdir $IMG
cd $IMG
----

. Create a file named `Dockerfile` with the following content:

.. Use the `FROM` instruction to specify the base image location.

* To create a CUDA-compatible Ray cluster image, specify the CUDA base image location:
+
[source,bash]
----
FROM quay.io/modh/ray:2.35.0-py39-cu121
----

* To create a ROCm-compatible Ray cluster image, specify the Developer Preview ROCm base image location:
+
[source,bash]
----
FROM quay.io/modh/ray:2.35.0-py39-rocm61
----
+
[IMPORTANT]
====
The ROCm-compatible Ray cluster image is Developer Preview software only. 
Developer Preview software is not supported by Red{nbsp}Hat in any way and is not functionally complete or production-ready. 
Do not use Developer Preview software for production or business-critical workloads. 
Developer Preview software provides early access to upcoming product software in advance of its possible inclusion in a Red{nbsp}Hat product offering. 
Customers can use this software to test functionality and provide feedback during the development process. 
This software might not have any documentation, is subject to change or removal at any time, and has received limited testing. 
Red{nbsp}Hat might provide ways to submit feedback on Developer Preview software without an associated SLA.

For more information about the support scope of Red{nbsp}Hat Developer Preview software, see link:https://access.redhat.com/support/offerings/devpreview/[Developer Preview Support Scope].
====


.. Use the `RUN` instruction to install additional packages.
You can add comments to the Dockerfile by prefixing the comment lines with a number sign (`#`).
+
The following example shows how to install a specific version of the Python PyTorch package:
+
.Install additional packages
[source,bash]
----
# Install PyTorch
RUN python3 -m pip install torch==2.4.0
----


. Build the image file. 
Use the `-t` option to create an image tag that specifies the image name and version, to make it easier to reference and manage the image: 
+
.Build the image
[source,subs="+quotes"]
----
podman build -t _<image-name>_:_<version>_ -f Dockerfile
----
+
Example:
+
[source,bash]
----
podman build -t ${IMG}:0.0.1 -f Dockerfile
----
+
The build output indicates when the build process is complete.

. Display a list of your images:
+
.List your images
[source,subs="+quotes"]
----
podman images
----
+
If your new image was created successfully, it is included in the list of images.

. Push the image to your container registry:
+
.Push the image
[source,bash]
----
podman push ${IMG}:0.0.1
----

. Optional: If you want to make your image available to users in your OpenShift cluster, register the image in the integrated OpenShift container registry, as described in link:{rhoaidocshome}{default-format-url}/working_with_distributed_workloads/registering-an-image-in-the-integrated-openshift-container-registry_distributed-workloads[Registering an image in the integrated OpenShift container registry].

