:_module-type: PROCEDURE

[id="customizing-parameters-serving-runtime{context}"]
= Customizing the parameters of a deployed model-serving runtime

[role='_abstract']
You can modify the parameters of an existing runtime to suit your business requirements.

NOTE: Customizing the parameters of a runtime only affects the model deployment selected.

.Prerequisites
* You have logged in to {productname-short} as a user with {productname-short} administrator privileges.
* You have deployed a model on the single model-serving platform.

.Procedure
. From the {productname-short} AI dashboard, click *Data Science Projects* in the left menu.
+
The *Data Science Projects* page opens.
. Click the name of the project that you want to deploy a model in.
+
A project details page opens.
. Click the *Models* tab.
. Click the action menu (⋮) and select *Edit*.
. Customize the runtime parameters in the *Configuration parameters* section:
.. Modify the values in *Additional serving runtime arguments* to define how the deployed model behaves.
.. Modify the values in *Additional environment variables* to define variables in the model's environment.
+
NOTE: Do not modify the `port` or `-–model` serving runtime arguments, because they require specific values to be set. Overwriting these parameters can cause the deployment to fail.
. After you are done customizing the runtime parameters, click *Redeploy* to save and deploy the model with your changes.

// .Verification
// <How do they verify that the parameters were customized successfully? Where would they see errors if it failed?>

// .Additional resources
// <Link to reference with info on parameters that can be customized>
