:_module-type: PROCEDURE

[id="customizing-component-deployment-resources-using-web-console_{context}"]
= Customizing component deployment resources by using the web console

[role='_abstract']
You can customize component deployment resources by updating the YAML file for the component deployment.

.Prerequisites
* You have cluster administrator privileges for your {openshift-platform} cluster.
* You have admin access to the `DSCInitialization` resources in the {openshift-platform} cluster.

.Procedure
. Log in to the {openshift-platform} console as a cluster administrator.
. In the *Administrator* perspective, click *Workloads* > *Deployments*.
. In the *Name* column, click the name of the deployment for the component that you want to customize resources for. For example, to customize Codeflare resources, click *codeflare-operator-manager*.
. On the *Deployment details* page that appears, click the *YAML* tab.
. Find the `?` section.
. Update the value of the field that you want to customize. For example, to customize x for y, make the following changes:
+
[source]
----
----
. Click *Save*.
. Click *Reload*.

.Verification

//[role='_additional-resources']
//.Additional resources