:_module-type: PROCEDURE

[id="customzing-the-dashboard-navigation-menu-options_{context}"]
= Customzing the dashboard navigation menu options

[role='_abstract']
Administrators can configure options for the {productname-short} dashboard interface by using {openshift-platform}. 

.Prerequisites
* You have cluster administrator privileges for your {openshift-platform} cluster.

.Procedure
. Log in to the {openshift-platform} console as a cluster administrator.
. In the *Administrator* perspective, click *Home* -> *API Explorer*.
. In the search bar, enter `OdhDashboardConfig` to filter by kind.
. Click the `OdhDashboardConfig` custom resource (CR) to open the resource details page.
. Select the `redhat-ods-applications` project from the *Project* list.
. Click the *Instances* tab.
. Click the `odh-dashboard-config` instance to open the details page.
. Click the *YAML* tab.
. In the `spec` section, change the following values as needed. 
+
* `disableAcceleratorProfiles`: Shows (false) or hides (true) the *Accelerator profiles* option in the *Settings* navigation menu.
* `disableBYONImageStream`: Shows (false) or hides (true) the *Notebook image settings* option in the *Settings* navigation menu.
* `disableClusterManager`: Shows (false) or hides (true) the *Cluster settings* option in the *Settings* navigation menu.
* `disableCustomServingRuntimes`: Shows (false) or hides (true) the *Serving runtimes* option in the *Settings* navigation menu.
* `disableISVBadges`: Shows (false) or hides (true) the badge in *Applications* -> *Explore* that indicates whether a product is from an Independent software vendor (ISV).
* `disableInfo`: Shows (false) or hides (true) the information panel in *Applications* -> *Explore*.
* `disableKServe`: Shows (false) or hides (true) the *Single-model serving platform* (KServe) option when adding a serving runtime in *Settings* > *Serving runtimes*.
* `disableModelMesh`: Shows (false) or hides (true) the *Multi-model serving platform* (ModelMesh) option when adding a serving runtime in *Settings* > *Serving runtimes*.
* `disableModelServing`: Shows (false) or hides (true) the *Model Serving* option in the navigation menu and in *Data Science Projects*.
* `disablePerformanceMetrics`: Shows (false) or hides (true) the *Endpoint performance* tab for a model in *Model Serving*.
* `disablePipelines`: Shows (false) or hides (true) the *Data Science Pipelines* option in the navigation menu.
* `disableProjectSharing`: Shows (false) or hides (true) the *Permissions* tab (project sharing) of a project in *Data Science Projects*.
* `disableProjects`: Shows (false) or hides (true) the *Data Science Projects* option in the navigation menu.
* `disableSupport`: Shows (false) or hides (true) components related to support.
* `disableTracking`: Shows (false) or hides (true) telemetry UI data. Note that you must have woopra and segement.io configured to use this feature.
* `disableUserManagement`: Shows (false) or hides (true) the *User management* option in the *Settings* navigation menu.
* `enablement`: Disables (false) or enables (true) the ability to add Independent software vendor (ISV) applications to the dashboard.







. Click *Save*.

.Verification
Log in to {productname-short} and verify that your dashboard configurations apply.

//[role="_additional-resources"]
//.Additional resources