:_module-type: REFERENCE

[id='dashboard-options_{context}']
= Dashboard options

[role='_abstract']
The {productname-short} dashboard includes a set of core features enabled by default that are designed to work for most scenarios. Administrators can configure the {productname-short} dashboard from the `OdhDashboardConfig` custom resource (CR) in {openshift-platform}. For more information, see xref::configuring-the-dashboard[Configuring the dashboard].

== Features
[cols="1,1,1",header]
|===
| Feature | Default | Description  

| enablement
| true
| Enables the ability to enable ISVs to the dashboard

| disableInfo
| false
| Removes the information panel in Explore Application section

| disableSupport
| false
| Disables components related to support.

| disableClusterManager	
| false
| Disables cluster management section for admins

| disableTracking	
| true
| Disables telemetry UI data. Note for this feature to work you need woopra and segement.io configured

| disableBYONImageStream	
| false
| Disables custom notebook images that are created via image streams

| 
| 
| 

| 
| 
| 

| 
| 
| 

| 
| 
| 

| 
| 
| 

| 
| 
| 

| 
| 
| 

| 
| 
| 

| 
| 
| 

|===

* `dashboardConfig`: Enable or disable certain features in {productname-short}. For example, you can hide Model Serving for your users or prevent users from importing custom images.
* `groupsConfig`: Control access to dashboard features, such as the spawner for allowed users and the *Cluster settings* page for administrators.
* `modelServerSizes`: Customize names and resources for model servers.
* `notebookController`: Customize settings related to workbenches and how they are launched.
* `notebookSizes`: Customize names and resources for notebooks.
. Click *Save*.




//[role="_additional-resources"]
//.Additional resources

