:_module-type: CONCEPT

[id='defining-a-pipeline_{context}']
= Defining a pipeline

[role='_abstract']
The Kubeflow Pipelines SDK enables you to define end-to-end machine learning and data pipelines. Use the Kubeflow Pipelines SDK to build your data science pipeline in Python code. After you have built your pipeline, compile it into YAML code by using the KubeFlow Pipelines compiler. After defining the pipeline, you can import the YAML file to the {productname-short} dashboard to enable you to configure its execution settings. 

ifdef::upstream[]
You can also use the Elyra JupyterLab extension to create and run data science pipelines within JupyterLab. For more information about the Elyra JupyterLab extension, see link:https://elyra.readthedocs.io/en/stable/getting_started/overview.html[Elyra Documentation].
endif::[]

ifndef::upstream[]
You can also use the Elyra JupyterLab extension to create and run data science pipelines within JupyterLab. For more information about creating pipelines in JupyterLab, see link:{rhoaidocshome}{default-format-url}/working_on_data_science_projects/working-with-data-science-pipelines_ds-pipelines#working_with_pipelines_in_jupyterlab[Working with pipelines in JupyterLab]. For more information about the Elyra JupyterLab extension, see link:https://elyra.readthedocs.io/en/stable/getting_started/overview.html[Elyra Documentation].
endif::[]

[role="_additional-resources"]
.Additional resources
* link:https://elyra.readthedocs.io/en/stable/getting_started/overview.html[Elyra Documentation]
