:_module-type: CONCEPT

[id='defining-a-pipeline_{context}']
= Defining a pipeline

[role='_abstract']
The Kubeflow Pipelines SDK enables you to define end-to-end machine learning and data pipelines. Use the Kubeflow Pipelines SDK to build your data science pipeline in Python code. After you have built your pipeline, compile it into Tekton-formatted YAML code using kfp-tekton SDK (version 1.5.x only). After defining the pipeline, you can import the YAML file to the {productname-short} dashboard to enable you to configure its execution settings. For more information about installing and using Kubeflow Pipelines SDK for Tetkon, see link:https://kubeflow.org/docs/components/pipelines/v1/sdk/pipelines-with-tekton/[Kubeflow Pipelines SDK for Tekton].

ifdef::upstream[]
You can also use the Elyra JupyterLab extension to create and run data science pipelines within JupyterLab. For more information on the Elyra JupyterLab extension, see link:https://elyra.readthedocs.io/en/stable/getting_started/overview.html[Elyra Documentation].
endif::[]

ifndef::upstream[]
You can also use the Elyra JupyterLab extension to create and run data science pipelines within JupyterLab. For more information on creating pipelines in JupyterLab, see link:{rhodsdocshome}{default-format-url}/working_on_data_science_projects/working-with-data-science-pipelines_ds-pipelines#working_with_pipelines_in_jupyterlab[Working with pipelines in JupyterLab]. For more information on the Elyra JupyterLab extension, see link:https://elyra.readthedocs.io/en/stable/getting_started/overview.html[Elyra Documentation].
endif::[]

[role="_additional-resources"]
.Additional resources
* link:https://github.com/kubeflow/kfp-tekton/tree/master/sdk[Kubeflow Pipelines SDK for Tekton]
* link:https://github.com/kubeflow/kfp-tekton/tree/master/samples[KFP Tekton samples and compiler samples]
* link:https://www.kubeflow.org/docs/components/pipelines/v1/[Kubeflow Pipelines v1 Documentation]
* link:https://elyra.readthedocs.io/en/stable/getting_started/overview.html[Elyra Documentation]
