:_module-type: CONCEPT

[id='defining-a-pipeline_{context}']
= Defining a pipeline

[role='_abstract']
The Kubeflow Pipelines SDK enables you to define end-to-end machine learning and data pipelines. Use the latest Kubeflow Pipelines 2.0 SDK to build your data science pipeline in Python code. After you have built your pipeline, use the SDK to compile it into an Intermediate Representation (IR) YAML file. For more information about compiling pipelines, see _Compiling the pipeline YAML with the Kubeflow Pipelines SDK_ and _Compiling Kubernetes-native manifests with the Kubeflow Pipelines SDK_. Compiling to Kubernetes-native manifests is optional and applies only when your pipeline server is configured to use Kubernetes API storage. After defining the pipeline, you can import the YAML file to the {productname-short} dashboard to enable you to configure its execution settings.

[IMPORTANT]
====
If you are using {productname-short} on a cluster running in FIPS mode, any custom container images for data science pipelines must be based on UBI 9 or RHEL 9. This ensures compatibility with FIPS-approved pipeline components and prevents errors related to mismatched OpenSSL or GNU C Library (glibc) versions.
====

ifdef::upstream[]
You can also use the Elyra JupyterLab extension to create and run data science pipelines within JupyterLab. For more information about the Elyra JupyterLab extension, see link:https://elyra.readthedocs.io/en/stable/getting_started/overview.html[Elyra Documentation].
endif::[]

ifndef::upstream[]
You can also use the Elyra JupyterLab extension to create and run data science pipelines within JupyterLab. For more information about creating pipelines in JupyterLab, see link:{rhoaidocshome}{default-format-url}/working_with_data_science_pipelines/working-with-pipelines-in-jupyterlab_ds-pipelines[Working with pipelines in JupyterLab]. For more information about the Elyra JupyterLab extension, see link:https://elyra.readthedocs.io/en/stable/getting_started/overview.html[Elyra Documentation].
endif::[]

[role="_additional-resources"]
.Additional resources
* link:https://www.kubeflow.org/docs/components/pipelines/[Kubeflow Pipelines 2.0 Documentation]
* link:https://elyra.readthedocs.io/en/stable/getting_started/overview.html[Elyra Documentation]
