:_module-type: PROCEDURE

[id="deleting-cluster-storage-from-a-data-science-project_{context}"]
= Deleting cluster storage from a data science project

[role='_abstract']
You can delete cluster storage from your data science projects to help you free up resources and delete unwanted storage space.

.Prerequisites
* You have logged in to {productname-long}.
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, `rhods-users`) in OpenShift.
* You have created a data science project with cluster storage.

.Procedure
. From the {productname-short} dashboard, click *Data Science Projects*.
+
The *Data science projects* page opens.
. Click the name of the project that you want to delete the storage from.
+
The *Details* page for the project opens.
. Click the action menu (*&#8942;*) beside the storage that you want to delete in the *Cluster storage* section and click *Delete storage*.
+
The *Delete storage* dialog opens.
. Enter the name of the storage in the text field to confirm that you intend to delete it.
. Click *Delete storage*.

.Verification
* The storage that you deleted is no longer displayed in the *Cluster storage* section on the project *Details* page.
* The persistent volume (PV) and persistent volume claim (PVC) associated with the cluster storage are both permanently deleted. This data is not recoverable.

//[role='_additional-resources']
//.Additional resources
