:_module-type: PROCEDURE

[id="deleting-a-data-science-pipeline_{context}"]
= Deleting a data science pipeline

[role='_abstract']
If you no longer require access to your data science pipeline on the dashboard, you can delete it so that it does not appear on the *Data Science Pipelines* page.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* There are active pipelines available on the *Pipelines* page.
* The pipeline that you want to delete does not contain any pipeline versions. 
ifndef::upstream[]
* The pipeline that you want to delete does not contain any pipeline versions. For more information, see link:{rhoaidocshome}{default-format-url}/working_with_data_science_pipelines/managing-data-science-pipelines_ds-pipelines#deleting-a-pipeline-version_ds-pipelines[Deleting a pipeline version].
endif::[]
ifdef::upstream[]
* The pipeline that you want to delete does not contain any pipeline versions. For more information, see link:{odhdocshome}/working-with-data-science-pipelines/#deleting-a-pipeline-version_ds-pipelines[Deleting a pipeline version].
endif::[]

.Procedure
. From the {productname-short} dashboard, click *Data Science Pipelines* -> *Pipelines*.
. On the *Pipelines* page, select the project that contains the pipeline that you want to delete from the *Project* list.
. Click the action menu (*&#8942;*) beside the pipeline that you want to delete and click *Delete pipeline*.
. In the *Delete pipeline* dialog, enter the pipeline name in the text field to confirm that you intend to delete it.
. Click *Delete pipeline*.

.Verification
* The data science pipeline that you deleted no longer appears on the *Pipelines* page.

//[role='_additional-resources']
//.Additional resources
