:_module-type: PROCEDURE

[id="Deleting-files-on-your-object-store_{context}"]
= Deleting files from your bucket

[role='_abstract']
To delete files from your bucket from your workbench, use the `delete_file()` method. 

.Prerequisites
* You have cloned the `odh-doc-examples` repository to your workbench.
* You have opened the `s3client_examples.ipynb` file in your workbench.
* You have installed Boto3 and configured an S3 client.
* You know the key of the file you want to delete and the bucket that the file is located in.

.Procedure
. In the Jupyter notebook, locate the following instructions to delete files from a bucket:
+
[source]
----
#Delete files from bucket
s3_client.delete_object(Bucket='<bucket_name>', Key='<object_key>') 
----
. Replace `<bucket_name>`  with the name of your bucket and `<key>` with the key of the file you want to delete, as shown in the example. Run the code cell. 
+
[source]
----
#Delete object from bucket
s3_client.delete_object(Bucket='aqs971-image-registry', Key='/tmp/series43-image12-086.csv')
----
+
The output displays a HTTP response status code of `204`, which indicates that the request was successful.

.Verification

* Locate the following instructions to list files in a bucket:
+
[source]
----
#Delete Object Verification
bucket_name = '<bucket_name>' 
for key in s3_client.list_objects_v2(Bucket=bucket_name)['Contents']:
print(key['Key']) 
----
* Replace `_<bucket_name>_` with the name of your bucket, as shown in the example and run the code cell.
+
[source]
----
#Delete Object Verification
bucket_name = 'aqs971-image-registry' 
for key in s3_client.list_objects_v2(Bucket=bucket_name)['Contents']:
print(key['Key'])
----
+
The deleted file does not appear in the output.

//[role="_additional-resources"]
//.Additional resources
//* link:{rhoaidocshome}{default-format-url}/integrating_data_from_amazon_s3/creating-an-amazon-s3-client-using-notebook-cells_s3[Creating an Amazon S3 client using notebook cells]
//* link:https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.upload_file[Amazon Web Services upload file command reference]
