:_module-type: PROCEDURE

[id="deleting-an-archived-pipeline-experiment_{context}"]
= Deleting an archived pipeline experiment

[role='_abstract']
You can delete pipeline experiments from the {productname-short} experiment archive. 

.Prerequisites
* You have logged in to {productname-long}.

* You have previously created a data science project that is available and contains a configured pipeline server.
* You have imported a pipeline to an active pipeline server.
* A pipeline experiment is available in the pipeline archive. 

.Procedure
. From the {productname-short} dashboard, click *Experiments* -> *Experiments and runs*.
. On the *Experiments* page, from the *Project* drop-down list, select the project that contains the archived pipeline experiment that you want to delete.
. Click the *Archive* tab.
. Click the action menu (*&#8942;*) beside the pipeline experiment that you want to delete, and then click *Delete*.
. In the *Delete experiment?* dialog, enter the pipeline experiment name in the text field to confirm that you intend to delete it.
. Click *Delete*.

.Verification
* The pipeline experiment that you deleted no longer appears on the *Archive* tab on the *Experiments* page.

//[role='_additional-resources']
//.Additional resources
