:_module-type: PROCEDURE

[id="deleting-an-archived-pipeline-run_{context}"]
= Deleting an archived pipeline run

[role='_abstract']
You can delete pipeline runs that you no longer require from the {productname-short} run archive. 

.Prerequisites

* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group} ) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have previously created a data science project that is available and has a pipeline server.
* You have imported a pipeline to an active and available pipeline server.
* You have previously archived a pipeline run that is available to delete. 

.Procedure
. From the {productname-short} dashboard, click *Data Science Pipelines* -> *Runs*.
+
The *Runs* page opens.
. From the *Project* list, select the project whose archived pipeline run you want to delete. 
+
The *Run details* page opens.
. Click the *Archived* tab.
+
A table opens that shows list of archived runs.
. Click the action menu (*&#8942;*) beside the run that you want to delete and click *Delete*.
+
The *Delete run* dialog opens.
. Enter the run name in the text field to confirm that you intend to delete it.
. Click *Delete*.

.Verification
* The archived run that you deleted is no longer displayed in the *Archived* tab on the *Runs* page.

//[role='_additional-resources']
//.Additional resources
