:_module-type: PROCEDURE

[id='deleting-a-bias-metric-using-dashboard_{context}']
= Deleting a bias metric by using the dashboard

[role='_abstract']
The following procedure describes how to use the {productname-short} dashboard to delete a bias metric for a model.

.Prerequisites
* You have logged in to {productname-long}.

* There is an existing bias metric that you want to delete.

.Procedure
. In the left menu of the {productname-short} dashboard, click *Model Serving*.
. On the *Deployed models* page, click the name of the model with the bias metric that you want to delete.
. On the metrics page for the model, click the *Model bias* tab.
. Click *Configure*.
. Click the action menu (&#8942;) next to the metric that you want to delete and then click *Delete*.
. In the *Delete bias metric* dialog, type the metric name to confirm the deletion. 
+
[NOTE]
====
You cannot undo deleting a bias metric.
====
. Click *Delete bias metric*.

.Verification
* The *Bias metric configuration* page does not show the bias metric that you deleted.

