:_module-type: PROCEDURE

[id="deleting-a-data-science-project_{context}"]
= Deleting a data science project

[role='_abstract']
You can delete data science projects so that they do not appear on the {productname-short} *Projects* page when you no longer want to use them.

.Prerequisites
* You have logged in to {productname-long}.
* You have created a data science project.

.Procedure
. From the {productname-short} dashboard, click *Projects*.
+
The *Projects* page opens.
. Click the action menu (*&#8942;*) beside the project that you want to delete and then click *Delete project*.
+
The *Delete project* dialog opens.
. Enter the project name in the text field to confirm that you intend to delete it.
. Click *Delete project*.

.Verification
* The project that you deleted is no longer displayed on the *Projects* page.
* Deleting a project deletes any associated workbenches, AI pipelines, cluster storage, and connections. This data is permanently deleted and is not recoverable.

//[role='_additional-resources']
//.Additional resources
