:_module-type: PROCEDURE

[id="deleting-a-data-connection_{context}"]
= Deleting a data connection

[role='_abstract']
You can delete data connections from your data science projects to help you remove connections that are no longer relevant to your work.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, `rhods-users` or `rhods-admin` ) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, `odh-users` or `odh-admins`) in OpenShift.
endif::[]
* You have created a data science project with a data connection.

.Procedure
. From the {productname-short} dashboard, click *Data Science Projects*.
+
The *Data science projects* page opens.
. Click the name of the project that you want to delete the data connection from.
+
The *Details* page for the project opens.
. Click the action menu (*&#8942;*) beside the data connection that you want to delete in the *Data connections* section and click *Delete data connection*.
+
The *Delete data connection* dialog opens.
. Enter the name of the data connection in the text field to confirm that you intend to delete it.
. Click *Delete data connection*.

.Verification
* The data connection that you deleted is no longer displayed in the *Data connections* section on the project *Details* page.

//[role='_additional-resources']
//.Additional resources
