:_module-type: PROCEDURE

[id="deleting-cluster-storage-from-a-data-science-project_{context}"]
= Deleting cluster storage from a data science project

[role='_abstract']
You can delete cluster storage from your data science projects to help you free up resources and delete unwanted storage space.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group} ) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have created a data science project with cluster storage.

.Procedure
. From the {productname-short} dashboard, click *Data Science Projects*.
+
The *Data Science Projects* page opens.
. Click the name of the project that you want to delete the storage from.
+
A project details page opens.
. Click the *Cluster storage* tab.
. Click the action menu (*&#8942;*) beside the storage that you want to delete and then click *Delete storage*.
+
The *Delete storage* dialog opens.
. Enter the name of the storage in the text field to confirm that you intend to delete it.
. Click *Delete storage*.

.Verification
* The storage that you deleted is no longer displayed in the *Cluster storage* tab for the project.
* The persistent volume (PV) and persistent volume claim (PVC) associated with the cluster storage are both permanently deleted. This data is not recoverable.

//[role='_additional-resources']
//.Additional resources
