:_module-type: PROCEDURE

[id="deleting-a-model-server_{context}"]
= Deleting a model server

[role='_abstract']
When you no longer need a model server to host models, you can remove it from your data science project. 

NOTE: When you remove a model server, you also remove the models that are hosted on that model server. As a result, the models are no longer available to applications.

.Prerequisites
* You have created a data science project and an associated model server.
* You have notified the users of the applications that access the models that the models will no longer be available.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]

.Procedure
. From the {productname-short} dashboard, click *Data Science Projects*.
+
The *Data science projects* page opens.
. Click the name of the project from which you want to delete the model server.
+
A project details page opens.
. Click the action menu (*&#8942;*) beside the project whose model server you want to delete in the *Models and model servers* section and then click *Delete model server*.
+
The *Delete model server* dialog opens.
. Enter the name of the model server in the text field to confirm that you intend to delete it.
. Click *Delete model server*.

.Verification
* The model server that you deleted is no longer displayed in the *Models and model servers* section on the project details page.

//[role='_additional-resources']
//.Additional resources
