:_module-type: PROCEDURE

[id="deleting-a-workbench-from-a-data-science-project_{context}"]
= Deleting a workbench from a data science project

[role='_abstract']
You can delete workbenches from your data science projects to help you remove Jupyter notebooks that are no longer relevant to your work.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have created a data science project with a workbench.

.Procedure
. From the {productname-short} dashboard, click *Data science projects*.
+
The *Data science projects* page opens.
. Click the name of the project that you want to delete the workbench from.
+
A project details page opens.
. Click the *Workbenches* tab.
. Click the action menu (*&#8942;*) beside the workbench that you want to delete and then click *Delete workbench*.
+
The *Delete workbench* dialog opens.
. Enter the name of the workbench in the text field to confirm that you intend to delete it.
. Click *Delete workbench*.

.Verification
* The workbench that you deleted is no longer displayed on the *Workbenches* tab for the project.
* The custom resource (CR) associated with the workbench's Jupyter notebook is deleted.

//[role='_additional-resources']
//.Additional resources
