:_module-type: PROCEDURE

[id="deleting-an-active-pipeline-run_{context}"]
= Deleting an active pipeline run

[role='_abstract']
To discard pipeline runs that you previously executed, but no longer require a record of, you can delete them so that they do not appear on the *Active* tab on the *Runs* page.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have previously created a data science project that is available and contains a configured pipeline server.
* You have imported a pipeline to an active pipeline server.
* You have previously executed a run that is available to delete.

.Procedure
. From the {productname-short} dashboard, click *Data Science Pipelines* -> *Runs*.
+
The *Runs* page opens.
. From the *Project* list, select the project that contains the pipeline whose active run you want to delete.
+
The page refreshes to show the pipeline's active runs on the *Active* tab.
. Click the action menu (*&#8942;*) beside the active run that you want to delete and click *Delete*.
+
The *Delete active run* dialog opens.
. Enter the run's name in the text field to confirm that you intend to delete it.
. Click *Delete active run*.

.Verification
* The run that you deleted is no longer displayed on the *Active* tab.

//[role='_additional-resources']
//.Additional resources
