:_module-type: PROCEDURE

[id="deleting-a-data-science-pipeline_{context}"]
= Deleting a data science pipeline

[role='_abstract']
If you no longer require access to your data science pipeline on the dashboard, you can delete it so that it does not appear on the *Data Science Pipelines* page.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* There are active pipelines available on the *Pipelines* page.
* The pipeline that you want to delete does not contain any pipeline versions. 

.Procedure
. From the {productname-short} dashboard, click *Data Science Pipelines* -> *Pipelines*.
+
The *Pipelines* page opens.
. From the *Project* list, select the project that contains the pipeline that you want to delete.
. Click the action menu (*&#8942;*) beside the pipeline that you want to delete and click *Delete pipeline*.
+
The *Delete pipeline* dialog opens.
. Enter the pipeline name in the text field to confirm that you intend to delete it.
. Click *Delete pipeline*.

.Verification
* The data science pipeline that you deleted is no longer displayed on the *Pipelines* page.
* Pipelines previously assigned to the pipeline server no longer appear on the *Pipelines* tab of the *Data Science Projects* page for the relevant data science project.

//[role='_additional-resources']
//.Additional resources
