:_module-type: PROCEDURE

[id="deleting-a-pipeline-server_{context}"]
= Deleting a pipeline server

[role='_abstract']
After you have finished running your data science pipelines, you can delete the pipeline server. Deleting a pipeline server automatically deletes all of its associated pipelines, pipeline versions, and runs. If your pipeline data is stored in a database, the database is also deleted along with its meta-data. In addition, after deleting a pipeline server, you cannot create new pipelines or pipeline runs until you create another pipeline server.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have previously created a data science project that is available and contains a pipeline server.

.Procedure
. From the {productname-short} dashboard, click *Data Science Pipelines*.
. On the *Pipelines* page, from the *Project* drop-down list, select the project that contains the pipeline server that you want to delete.
. From the *Pipeline server actions* list, select *Delete pipeline server*.
. In the *Delete pipeline server* dialog, enter the name of the pipeline server in the text field to confirm that you intend to delete it.
. Click *Delete*.

.Verification
* Pipelines previously assigned to the deleted pipeline server no longer appear on the *Pipelines* page for the relevant data science project.
* Pipeline runs previously assigned to the deleted pipeline server no longer appear on the *Runs* page for the relevant data science project.

//[role='_additional-resources']
//.Additional resources
