:_module-type: PROCEDURE

[id="deleting-an-accelerator-profile_{context}"]
= Deleting an accelerator profile

[role='_abstract']
To discard accelerator profiles that you no longer require, you can delete them so that they do not appear on the dashboard.

.Prerequisites
* You have logged in to {productname-short} as a user with {productname-short} administrator privileges. 
* The accelerator profile that you want to delete exists in your deployment. 

.Procedure
. From the {productname-short} dashboard, click *Settings* -> *Environment setup* -> *Hardware profiles*.
+
The *Accelerator profiles* page opens, displaying existing accelerator profiles.
. Click the action menu (*&#8942;*) beside the accelerator profile that you want to delete and click *Delete*.
+
The *Delete accelerator profile* dialog opens.
. Enter the name of the accelerator profile in the text field to confirm that you intend to delete it.
. Click *Delete*. 

.Verification
* The accelerator profile is no longer displayed on the *Accelerator profiles* page.

[role='_additional-resources']
.Additional resources
* link:https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#toleration-v1-core[Toleration v1 core]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/nodes/controlling-pod-placement-onto-nodes-scheduling#nodes-scheduler-taints-tolerations-about_nodes-scheduler-taints-tolerations[Understanding taints and tolerations]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/operators/understanding-operators#crd-managing-resources-from-crds[Managing resources from custom resource definitions]