:_module-type: PROCEDURE

[id="deleting-an-archived-pipeline-run_{context}"]
= Deleting an archived pipeline run

[role='_abstract']
You can delete pipeline runs from the {productname-short} run archive. 

.Prerequisites

* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group} ) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have previously created a data science project that is available and has a pipeline server.
* You have imported a pipeline to an active pipeline server.
* You have previously archived a pipeline run. 

.Procedure
. From the {productname-short} dashboard, click *Data science pipelines* -> *Runs*.
. On the *Runs* page, from the *Project* drop-down list, select the project that you want to delete an archived pipeline run from.
. Click the *Archive* tab.
. Click the action menu (*&#8942;*) beside the pipeline run that you want to delete, and then click *Delete*.
. In the *Delete run?* dialog, enter the run name in the text field to confirm that you intend to delete it.
. Click *Delete*.

.Verification
* The archived run that you deleted no longer appears on the *Archive* tab on the *Runs* page.

//[role='_additional-resources']
//.Additional resources