:_module-type: PROCEDURE

[id='deploying-a-model-version-from-a-model-registry_{context}']
= Deploying a model version from a model registry 

[role='_abstract']
You can deploy a version of a registered model directly from a model registry.

.Prerequisites
* An available model registry exists in your deployment, and contains at least one registered model.
ifdef::upstream[]
* To deploy a model version by using the model serving platform, you have fulfilled the prerequisites described in link:{odhdocshome}/deploying-models/#deploying-models-on-the-model-serving-platform_odh-admin[Deploying models on the model serving platform].
endif::[]
ifndef::upstream[]
* To deploy a model version by using the model serving platform, you have fulfilled the prerequisites described in link:{rhoaidocshome}{default-format-url}/deploying_models/deploying_models#deploying-models-on-the-model-serving-platform_rhoai-user[Deploying models on the model serving platform].
endif::[]

.Procedure
. From the {productname-short} dashboard, click *AI hub* -> *Registry*.
. From the *Model registry* list, select the model registry from which you want to deploy a model version.
. In the *Model name* column, click the name of the model that contains the version that you want to deploy.
+
The details page for the model version opens.
. Click the action menu (*&#8942;*) beside the model version that you want to deploy.
. Click *Deploy* for the model version. 
. In the *Deploy model* dialog, configure properties for deploying the model:
.. From the *Project* list, select a target project. 
+
When you select a project, {productname-short} scans through any connections the project has and checks if any match the connections that the model was registered with. If any connections match, they are displayed next in the *Connection* field.  
.. Optional: From the *Connection* list, select the connection that you want to use when deploying the model. 
+
This will autofill the deployment wizard with the details for your connection. If you do not have a connection, you can create one in the next steps. 
.. Click *Deploy*. 
+
This displays the deployment wizard. 

. On the *Model details* page, provide information about the model:
.. From the *Model location* list, specify where your model is stored and complete the appropriate details for your connection. The details for the matching connection selected in the previous step are autofilled. 
+
ifndef::upstream[]
For more information about connections, see link:{rhoaidocshome}{default-format-url}/working_on_projects/using-connections_projects#adding-a-connection-to-your-project_projects[Adding a connection to your project].
ifdef::upstream[]
For more information about connections, see link:{odhdocshome}/working-on-data-science-projects/#adding-a-connection-to-your-data-science-project_projects[Adding a connection to your project].
endif::[]

.. Optional: In the *Model deployment name* field, enter a unique name for your model deployment. This field is autofilled with a value that contains the model name by default. 
+
This will be the name of the inference service that is created when the model is deployed.
ifdef::upstream[]
. Click *Next*.
. On the *Model deployment* and *Advanced settings* pages, configure the remaining properties for deploying your model, as described in link:{odhdocshome}/deploying-models/#deploying-models-on-the-model-serving-platform_odh-user[Deploying models on the model serving platform].
endif::[]
ifndef::upstream[]
. On the *Model deployment* and *Advanced settings* pages, configure the remaining properties for deploying your model, as described in link:{rhoaidocshome}{default-format-url}/deploying_models/deploying_models#deploying-models-on-the-model-serving-platform_rhoai-user[Deploying models on the model serving platform].
endif::[]
. On the *Review* page, review the settings that you have selected before deploying the model. 
. Click *Deploy*.			 

.Verification
* The model deployment is displayed on the *AI hub* -> *Deployments* page.
* The model deployment is displayed in the *Latest deployments* section of the model details page.
* The model version is displayed on the *Deployments* tab for the model.
* You can edit the model version deployment by clicking the action menu (*&#8942;*) beside it, and then clicking *Edit*.
* You can delete the model version deployment by clicking the action menu (*&#8942;*) beside it, and then clicking *Delete*.

// [role="_additional-resources"]
// .Additional resources
// * TODO or delete
