:_module-type: PROCEDURE

[id='deploying-a-model-version-from-a-model-registry_{context}']
= Deploying a model version from a model registry

[role='_abstract']
You can deploy a version of a registered model...

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* An available model registry exists in your deployment.

.Procedure
. From the {productname-short} dashboard, click *Model Registry*.
. From the *Model registry* dropdown menu, select the model registry from which you want to deploy a model version.
. In the *Model name* column, click the name of the model that contains the version that you want to deploy.
+
The details page for the model version opens.
. Click the action menu (*&#8942;*) beside the model version that you want to deploy.
. Click *Deploy*.
. In the *Deploy model* dialog, configure properties for deploying the model.
.. From the *Project* drop-down list, select a target project.
.. Click *Deploy*.

.Verification
* The 

// [role="_additional-resources"]
// .Additional resources
// * TODO or delete