:_module-type: PROCEDURE

[id="disabling-component-resource-customization_{context}"]
= Disabling component resource customization

[role='_abstract']
You can disable customization of component deployment resources, and restore default  values, by adding the `opendatahub.io/managed: true` annotation to the YAML file for the component deployment.

[IMPORTANT]
====
Manually removing or setting the `opendatahub.io/managed: true` annotation to `false` after manually adding it to the YAML file for a component deployment might cause unexpected cluster issues. 

ifdef::upstream[]
To remove the annotation from a deployment, use the steps described in link:{odhdocshome}/managing-resources/#reenabling-component-resource-customization_managing-resources[Re-enabling component resource customization].
endif::[]
ifndef::upstream[]
To remove the annotation from a deployment, use the steps described in link:{rhoaidocshome}{default-format-url}/managing_openshift_ai/customizing-component-deployment-resources_resource-mgmt#reenabling-component-resource-customization_resource-mgmt[Re-enabling component resource customization].
endif::[]
====

.Prerequisites
* You have cluster administrator privileges for your {openshift-platform} cluster.

.Procedure
. Log in to the {openshift-platform} console as a cluster administrator.
. In the *Administrator* perspective, click *Workloads* -> *Deployments*.
ifdef::upstream[]
. From the *Project* drop-down list, select `opendatahub`.
. In the *Name* column, click the name of the deployment for the component to which you want to add the annotation.
+
[NOTE]
====
For more information about the deployment names for each component, see link:{odhdocshome}/managing-resources/#overview-of-component-resource-customization_managing-resources[Overview of component resource customization].
====
endif::[]
ifndef::upstream[]
. From the *Project* drop-down list, select `redhat-ods-applications`.
. In the *Name* column, click the name of the deployment for the component to which you want to add the annotation.
+
[NOTE]
====
For more information about the deployment names for each component, see link:{rhoaidocshome}{default-format-url}/managing_openshift_ai/customizing-component-deployment-resources_resource-mgmt#reenabling-component-resource-customization_resource-mgmt[Overview of component resource customization].
====
endif::[]
. On the *Deployment details* page that appears, click the *YAML* tab.
. Find the `metadata.annotations:` section.
. Add the `opendatahub.io/managed: true` annotation.
+
[source]
----
metadata:
  annotations:
     opendatahub.io/managed: true
----
. Click *Save*.
. Click *Reload*.

.Verification
* The `opendatahub.io/managed: true` annotation appears in the YAML file for the component deployment.

//[role='_additional-resources']
//.Additional resources