:_module-type: PROCEDURE

[id="disable-node-caching-in-elyra_{context}"]
= Disabling node caching in Elyra

[role='_abstract']
Elyra automatically caches the ouputs of your components, or "nodes". You can also disable this feature if you want to ensure a fresh execution for each component instead of resuing outputs from previous runs.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]

* You have created a data science project.
* You have created and configured a pipeline server within the data science project that contains your workbench.
+
[IMPORTANT]
====
To ensure that the runtime configuration is created automatically, you must create the pipeline server before you create the workbench.
====
ifndef::upstream[]
* You have created a workbench with a workbench image that contains the Elyra extension (Standard Data Science, TensorFlow, TrustyAI, ROCm-PyTorch, ROCm-TensorFlow, or PyTorch), as described in link:{rhoaidocshome}{default-format-url}/working_on_data_science_projects/using-project-workbenches_projects#creating-a-workbench-select-ide_projects[Creating a workbench and selecting an IDE].
* You have started the workbench and opened the JupyterLab interface, as described in link:{rhoaidocshome}{default-format-url}/working_in_your_data_science_ide/accessing-your-workbench-ide_ide[Accessing your workbench IDE].
endif::[]
ifdef::upstream[]
* You have created a workbench with a workbench image that contains the Elyra extension (Standard Data Science, TensorFlow, TrustyAI, ROCm-PyTorch, ROCm-TensorFlow, or PyTorch), as described in link:{odhdocshome}/working-on-data-science-projects/#creating-a-workbench-select-ide_projects[Creating a workbench and selecting an IDE].
* You have started the workbench and opened the JupyterLab interface, as described in link:{odhdocshome}/working-in-your-data-science-ide/#accessing-your-workbench-ide_ide[Accessing your workbench IDE].
endif::[]
+
[IMPORTANT]
====
The Elyra pipeline editor is available in specific workbench images only. To use Elyra, the workbench must be based on a JupyterLab image. The Elyra extension is not available in code-server or RStudio IDEs. The workbench must also be derived from the Standard Data Science image. It is not available in Minimal Python or CUDA-based workbenches. All other supported JupyterLab-based workbench images have access to the Elyra extension.
====
* You have access to S3-compatible storage.

.Procedure
. After you open JupyterLab, confirm that the JupyterLab launcher is automatically displayed.
. Open a pipeline to have access to the nodes that you want to modify.
. Right-click on the node that you want to edit, and click on *Open Properties*.
. Click on the *Node Properties* tab in the slide-out menu on the right.
. Under *Additional Properties*, click on the option bar under *Disable node caching* that is automatically populated with *Use runtime default*
. Select *True*.

.Verification
* Your component runs are re-executed in your target runtime environment.
