:_module-type: PROCEDURE

[id="disabling-component-resource-customization-using-cli_{context}"]
= Disabling component resource customization by using the CLI

[role='_abstract']
You can disable customization of component deployment resources by adding the `opendatahub.io/managed: true` annotation to the YAML file for the component deployment.

.Prerequisites
* You have cluster administrator privileges for your {openshift-platform} cluster.
* You have admin access to the `DSCInitialization` resources in the {openshift-platform} cluster.

.Procedure
. Open a new terminal window.
. Follow these steps to log in to your {openshift-platform} cluster as a cluster administrator:
.. In the upper-right corner of the OpenShift web console, click your user name and select *Copy login command*. 
.. After you have logged in, click *Display token*.
.. Copy the *Log in with this token* command and paste it in the OpenShift command-line interface (CLI).
+
[source,subs="+quotes"]
----
$ oc login --token=__<token>__ --server=__<openshift_cluster_url>__
----
.

.Verification


//[role='_additional-resources']
//.Additional resources