:_module-type: PROCEDURE

[id='disabling-feast-component_{context}']
= Disabling the {component} component

[role='_abstract']
You can disable the {component} component in {productname-short}.

.Prerequisites
* You have cluster administrator privileges for your {openshift-platform} cluster.
* You have access to the data science cluster.
* You have installed {productname-long}.

.Procedure
. In the {openshift-platform} console, click *Operators* -> *Installed Operators*.
ifdef::self-managed,cloud-service[]
. Search for the *Red Hat OpenShift AI* Operator, and then click the Operator name to open the Operator details page.
endif::[]
ifdef::upstream[]
. Search for the *Open Data Hub Operator*, and then click the Operator name to open the Operator details page.
endif::[]
. Click the *Data Science Cluster* tab.
. Click the default instance name (for example, *default-dsc*) to open the instance details page.
. Click the *YAML* tab to show the instance specifications.
. In the `spec:components` section, set the `managementState` field for the `feastOperator` component to `Removed`:
+
----
 feastOperator:
    managementState: Removed
----

. Click *Save*.

.Verification
Check the status of the *feast-operator* pod:

ifdef::self-managed,cloud-service[]
. In the {openshift-platform} console, from the *Project* list, select *redhat-ods-applications*.
endif::[]
ifdef::upstream[]
. In the {openshift-platform} console, from the *Project* list, select *opendatahub*.
endif::[]

. Click *Workloads* -> *Deployments*.
. Search for the *feast-operator-contoller-manager* deployment.


