:_module-type: PROCEDURE

[id='disabling-applications-connected_{context}']
= Disabling applications connected to {productname-short}

[role='_abstract']
You can disable applications and components so that they do not appear on the {productname-short} dashboard when you no longer want to use them, for example, when data scientists no longer use an application or when the application license expires.

Disabling unused applications allows your data scientists to manually remove these application tiles from their {productname-short} dashboard so that they can focus on the applications that they are most likely to use.
ifndef::upstream[]
See link:{rhoaidocshome}{default-format-url}/working_with_connected_applications/removing-disabled-applications_connected-apps[Removing disabled applications from the dashboard] for more information about manually removing application tiles.
endif::[]

ifdef::cloud-service[]
[IMPORTANT]
====
Do not follow this procedure when disabling {org-name} OpenShift API Management. You can only uninstall {org-name} OpenShift API Management from OpenShift Cluster Manager.
endif::[]
====

.Prerequisites
ifdef::upstream,self-managed[]
* You have logged in to the {openshift-platform} web console.
* You are part of the `cluster-admins` user group in {openshift-platform}.
* You have installed or configured the service on your {openshift-platform} cluster.
* The application or component that you want to disable is enabled and appears on the *Enabled* page.
endif::[]
ifdef::cloud-service[]
* You have logged in to the OpenShift web console.
* You are part of the `cluster-admins` or `dedicated-admins` user group in your OpenShift cluster. The `dedicated-admins` user group applies only to OpenShift Dedicated.
* You have installed or configured the service on your OpenShift cluster.
* The application or component that you want to disable is enabled and appears on the *Enabled* page.
endif::[]

.Procedure
ifdef::upstream,self-managed[]
. In the {openshift-platform} web console, switch to the *Administrator* perspective.
endif::[]
ifdef::cloud-service[]
. In the OpenShift web console, switch to the *Administrator* perspective.
endif::[]
ifndef::upstream[]
. Switch to the `redhat-ods-applications` project.
endif::[]
ifdef::upstream[]
. Switch to the `odh` project.
endif::[]
. Click *Operators* -> *Installed Operators*.
. Click on the Operator that you want to uninstall. You can enter a keyword into the *Filter by name* field to help you find the Operator faster.
. Delete any Operator resources or instances by using the tabs in the Operator interface.
+
During installation, some Operators require the administrator to create resources or start process instances using tabs in the Operator interface. These must be deleted before the Operator can uninstall correctly.
. On the *Operator Details* page, click the *Actions* drop-down menu and select *Uninstall Operator*.
+
An *Uninstall Operator?* dialog box is displayed.
. Select *Uninstall* to uninstall the Operator, Operator deployments, and pods. After this is complete, the Operator stops running and no longer receives updates.

[IMPORTANT]
====
Removing an Operator does not remove any custom resource definitions or managed resources for the Operator. Custom resource definitions and managed resources still exist and must be cleaned up manually. Any applications deployed by your Operator and any configured off-cluster resources continue to run and must be cleaned up manually.
====

.Verification
* The Operator is uninstalled from its target clusters.
* The Operator no longer appears on the *Installed Operators* page.
* The disabled application is no longer available for your data scientists to use, and is marked as `Disabled` on the *Enabled* page of the {productname-short} dashboard. This action may take a few minutes to occur following the removal of the Operator.

//[role="_additional-resources"]
//.Additional resources
//* TODO or delete
