:_module-type: PROCEDURE

[id="downloading-the-demo-jupyter-notebooks-from-the-codeflare-sdk_{context}"]
= Downloading the demo Jupyter notebooks from the CodeFlare SDK

[role='_abstract']
The demo Jupyter notebooks from the CodeFlare SDK provide guidelines on how to use the CodeFlare stack in your own Jupyter notebooks.
Download the demo Jupyter notebooks so that you can learn how to run Jupyter notebooks locally.

// If you do not want to download the demo Jupyter notebooks, you can skip this section.

.Prerequisites
ifndef::upstream[]
* You can access a data science cluster that is configured to run distributed workloads as described in link:{rhoaidocshome}{default-format-url}/managing_openshift_ai/managing-distributed-workloads_managing-rhoai[Managing distributed workloads].
endif::[]
ifdef::upstream[]
* You can access a data science cluster that is configured to run distributed workloads as described in link:{odhdocshome}/managing-odh/#managing-distributed-workloads_managing-odh[Managing distributed workloads].
endif::[]

ifndef::upstream[]
* You can access a data science project that contains a workbench, and the workbench is running a default workbench image that contains the CodeFlare SDK, for example, the *Standard Data Science* notebook. 
For information about projects and workbenches, see link:{rhoaidocshome}{default-format-url}/working_on_data_science_projects[Working on data science projects].
endif::[]
ifdef::upstream[]
* You can access a data science project that contains a workbench, and the workbench is running a default workbench image that contains the CodeFlare SDK, for example, the *Standard Data Science* notebook. 
For information about projects and workbenches, see link:{odhdocshome}/working-on-data-science-projects[Working on data science projects].
endif::[]

* You have administrator access for the data science project.
** If you created the project, you automatically have administrator access. 
** If you did not create the project, your cluster administrator must give you administrator access.

* You have logged in to {productname-long}, started your workbench, and logged in to JupyterLab.


.Procedure
. In the JupyterLab interface, click *File > New > Notebook*. 
Specify your preferred Python version, and then click *Select*. 
+
A new Jupyter notebook file is created with the `.ipynb` file name extension.
. Add the following code to a cell in the new notebook:
+
.Code to download the demo Jupyter notebooks
[source,bash]
----
from codeflare_sdk import copy_demo_nbs
copy_demo_nbs()
----

. Select the cell, and click *Run > Run selected cell*.
+
After a few seconds, the `copy_demo_nbs()` function copies the demo Jupyter notebooks that are packaged with the currently installed version of the CodeFlare SDK, and clones them into the `demo-notebooks` folder.

. In the left navigation pane, right-click the new notebook and click *Delete*.
. Click *Delete* to confirm.


.Verification
Locate the downloaded demo Jupyter notebooks in the JupyterLab interface, as follows:

. In the left navigation pane, double-click *demo-notebooks*.
. Double-click *additional-demos* and verify that the folder contains several demo Jupyter notebooks.
. Click *demo-notebooks*.
. Double-click *guided-demos* and verify that the folder contains several demo Jupyter notebooks. 

ifndef::upstream[]
You can run these demo Jupyter notebooks as described in link:{rhoaidocshome}{default-format-url}/working_with_distributed_workloads/running-ray-based-distributed-workloads_distributed-workloads#running-the-demo-jupyter-notebooks-from-the-codeflare-sdk_distributed-workloads[Running the demo Jupyter notebooks from the CodeFlare SDK].
endif::[]
ifdef::upstream[]
You can run these demo Jupyter notebooks as described in link:{odhdocshome}/working-with-distributed-workloads/#running-the-demo-jupyter-notebooks-from-the-codeflare-sdk_distributed-workloads[Running the demo Jupyter notebooks from the CodeFlare SDK].
endif::[]


////
[role='_additional-resources']
.Additional resources
<Do we want to link to additional resources?>


* link:https://url[link text]
////
