:_module-type: PROCEDURE

[id="duplicating-an-active-pipeline-run_{context}"]
= Duplicating an active pipeline run

[role='_abstract']
To make it easier to quickly execute pipeline runs with the same configuration in a pipeline experiment, you can duplicate them.  

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have previously created a data science project that is available and contains a configured pipeline server.
* You have imported a pipeline to an active pipeline server.
* An active run is available to duplicate on the *Active* tab on the *Runs* page.

.Procedure
. From the {productname-short} dashboard, click *Experiments* -> *Experiments and runs*.
. On the *Experiments* page, from the *Project* drop-down list, select the project that contains the pipeline experiment for the pipeline run that you want to duplicate.
. From the list of pipeline experiments, click the experiment that contains the pipeline run that you want to duplicate. 
. Click the action menu (*&#8942;*) beside the relevant active run, and then click *Duplicate*.
. On the *Duplicate run* page, configure the duplicate run:
.. From the *Experiment* list, select the pipeline experiment that contains the pipeline run that you want to duplicate. Alternatively, to create a new pipeline experiment, click *Create new experiment*, and then complete the relevant fields in the *Create experiment* dialog.
.. In the *Name* field, enter a name for the duplicate run.
.. In the *Description* field, enter a description for the duplicate run.
.. From the *Pipeline* list, select a pipeline to contain the duplicate run. Alternatively, to create a new pipeline, click *Create new pipeline*, and then complete the relevant fields in the *Import pipeline* dialog.
.. From the *Pipeline version* list, select a pipeline version to contain the duplicate run. Alternatively, to upload a new version, click *Upload new version*, and then complete the relevant fields in the *Upload new version* dialog.
.. In the *Parameters* section, configure the input parameters for the run that you are duplicating by selecting parameters from the list.
.. Click *Create run*.
+
The details page for the run opens.

.Verification
* The duplicate pipeline run appears on the *Runs* tab on the *Runs* page for the pipeline experiment.

//[role='_additional-resources']
//.Additional resources
