:_module-type: PROCEDURE

[id="duplicating-a-model-server_{context}"]
= Duplicating a model server

[role='_abstract']
To avoid re-creating a model server runtime with similar values, you can duplicate an existing model server runtime and then edit some of its settings.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, `rhods-users` or `rhods-admins`) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, `odh-users` or `odh-admins`) in OpenShift.
endif::[]
* You have created a data science project that has a model server assigned.

.Procedure
. From the {productname-short} dashboard, click *Data Science Projects*.
+
The *Data science projects* page opens.
. Click the name of the project whose model server details you want to duplicate.
+
A project details page opens.
. In the *Models and model servers* section, locate the model server that you want to copy. Click the action menu (*&#8942;*) and then select *Duplicate*.
+
The *Configure model server* dialog opens.
. Update the model server properties as needed.
+
[IMPORTANT]
====
{productname-short} includes two versions of the OpenVINO Model Server (OVMS) runtime by default; a version that supports GPUs and one that does not. To use GPUs, from the *Serving runtime* list, you must select the version whose display name includes `Supports GPUs`.

If you are using a _custom_ model-serving runtime with your model server, you must ensure that your custom runtime supports GPUs and is appropriately configured to use them.
====

. Click *Configure*.

.Verification
* The model server that you created is displayed in the *Models and model servers* section on the project details page.

//[role='_additional-resources']
//.Additional resources
