:_module-type: PROCEDURE

[id="duplicating-an-archived-pipeline-run_{context}"]
= Duplicating an archived pipeline run

[role='_abstract']
To make it easier to reproduce runs with the same configuration as runs in your archive, you can duplicate them.

.Prerequisites
* You have logged in to {productname-long}.
* You have previously created a data science project that is available and contains a configured pipeline server.
* You have imported a pipeline to an active pipeline server.
* An archived run is available to duplicate on the *Archived* tab on the *Runs* page.

.Procedure
. From the {productname-short} dashboard, click *Data science pipelines* -> *Runs*.
. On the *Runs* page, from the *Project* drop-down list, select the project that you want to duplicate a pipeline run for.
. On the *Runs* page, click the *Archive* tab.
. Click the action menu (*&#8942;*) beside the pipeline run that you want to duplicate, and then click *Duplicate*.
. On the *Duplicate run* page, configure the duplicate run:
.. From the *Experiment* list, select a pipeline experiment to contain the duplicate run. Alternatively, to create a new pipeline experiment, click *Create new experiment*, and then complete the relevant fields in the *Create experiment* dialog.
.. In the *Name* field, enter a name for the duplicate run.
.. In the *Description* field, enter a description for the duplicate run.
.. From the *Pipeline* list, select a pipeline to contain the duplicate run. Alternatively, to create a new pipeline, click *Create new pipeline*, and then complete the relevant fields in the *Import pipeline* dialog.
.. From the *Pipeline version* list, select a pipeline version to contain the duplicate run. Alternatively, to upload a new version, click *Upload new version*, and then complete the relevant fields in the *Upload new version* dialog.
.. In the *Parameters* section, configure input parameters for the duplicate run by selecting parameters from the list.
.. Click *Create run*.
+
The details page for the run opens.

.Verification
* The duplicate pipeline run is displayed on the *Runs* tab on the *Runs* page for the pipeline experiment.

//[role='_additional-resources']
//.Additional resources