:_module-type: PROCEDURE

[id="editing-model-version-metadata-in-a-model-registry_{context}"]
= Editing model version metadata in a model registry

[role='_abstract']
You can edit the metadata of model versions that are registered in {productname-short}, such as the version's description, labels, and custom properties.

.Prerequisites
* You have logged in to {productname-long}.
* An available model registry exists in your deployment, and contains at least 1 registered model.
* You have access to the model registry that contains the model version that you want to edit.

.Procedure
. From the {productname-short} dashboard, click *Models* -> *Model registry*.
. From the *Model registry* drop-down menu, select the model registry that contains the model version that you want to edit.
. Click the name of a model to view the model details page.
. Click the *Versions* tab to view the available model versions.
. Click a version name to view the version details page.  
. In the *Versions details* section, you can edit the version metadata.
.. In the *Labels* section, click *Edit* to edit the labels of the version.
.. In the *Description* section, click *Edit* to edit the description of the version.
.. In the *Properties* section, click *Add property* to add a new property to the version. 
... To edit an existing property, click the action menu (*&#8942;*) beside the property, and then click *Edit*. 
... To delete a property, click the action menu (*&#8942;*) beside the property, and then click *Delete*. 
.. In the *Model format* section, click *Edit* to edit the model format of the model version.
.. In the *Model format version* section, click *Edit* to edit the model format version of the model version.

.Verification
* You can view the updated metadata on the details page for the model version.

//[role='_additional-resources']
//.Additional resources
