:_module-type: PROCEDURE

[id="editing-the-dashboard-configuration-file_{context}"]
= Editing the dashboard configuration file

[role='_abstract']
As an administrator, you can customize the interface of the dashboard by editing the dashboard configuration file.

.Prerequisites
* You have cluster administrator privileges for your {openshift-platform} cluster.

.Procedure
. Log in to the {openshift-platform} console as a cluster administrator.
. In the *Administrator* perspective, click *Home* -> *API Explorer*.
. In the search bar, enter `OdhDashboardConfig` to filter by kind.
. Click the `OdhDashboardConfig` custom resource (CR) to open the resource details page.
. Select the `redhat-ods-applications` project from the *Project* list.
. Click the *Instances* tab.
. Click the `odh-dashboard-config` instance to open the details page.
. Click the *YAML* tab. 
. Edit the values of the options that you want to change.
+
For example, to show or hide a menu option in the dashboard navigation menu, update the `spec:dashboardConfig` section to edit the relevant dashboard configuration option. 
If the relevant dashboard configuration option is not included in the default CR, add the entry.
+
ifndef::upstream[]
For more information, see link:{rhoaidocshome}{default-format-url}/managing_openshift_ai/customizing-the-dashboard#ref-dashboard-configuration-options_dashboard[Dashboard configuration options].
endif::[]
ifdef::upstream[]
For more information, see link:{odhdocshome}/managing-resources/#ref-dashboard-configuration-options_dashboard[Dashboard configuration options].
endif::[]
. Click *Save* to apply your changes and then click *Reload* to synchronize your changes to the cluster.

.Verification
Log in to {productname-short} and verify that your dashboard configurations apply.
