:_module-type: PROCEDURE

[id='enabling-the-multi-model-serving-platform_{context}']
= Enabling the multi-model serving platform

[role='_abstract']
To use the multi-model serving platform, you must first enable the platform. 
The multi-model serving platform uses the ModelMesh component.

.Prerequisites
* You have logged in to {productname-short} as a user with {productname-short} administrator privileges.
* The `spec.dashboardConfig.disableModelMesh` dashboard configuration option is set to `false` (the default).
+
ifdef::upstream[]
For more information about setting dashboard configuration options, see link:{odhdocshome}/managing-resources/#customizing-the-dashboard[Customizing the dashboard].
endif::[]
ifndef::upstream[]
For more information about setting dashboard configuration options, see link:{rhoaidocshome}{default-format-url}/managing_resources/customizing-the-dashboard[Customizing the dashboard].
endif::[]

.Procedure
. In the left menu of the {productname-short} dashboard, click *Settings* → *Cluster settings*.
. Locate the *Model serving platforms* section.
. Select the *Multi-model serving platform* checkbox.
. Click *Save changes*.

//[role="_additional-resources"]
//.Additional resources
