:_module-type: PROCEDURE

[id="enabling-a-connection-type_{context}"]
= Enabling a connection type

As an {productname-short} administrator, you can enable or disable a connection type to control whether it is available as an option to your users when they create a connection.

Note that if you disable a connection type, any existing connections that your users created based on that connection type are not effected.

.Prerequisites
* You have logged in to {productname-short} as a user with {productname-short} administrator privileges. 

* The connection type that you want to enable exists in your project, either pre-installed or created by a user with administrator privileges.

.Procedure
. From the {productname-short} dashboard, click *Settings* -> *Connection types*.

. From the list of available connection types, find the connection type that you want to enable or disable. 

. On the row containing the connection type, click the toggle in the *Enable* column.

.Verification

* If you enabled a connection type, it is available for selection when a user adds a connection to a project resource (for example, a workbench or model server).

* If you disabled a connection type, it does not show in the list of available connection types when a user adds a connection to a project resource.
