:_module-type: PROCEDURE

[id="enabling-the-single-model-serving-platform_{context}"]
= Enabling the single model serving platform

[role="_abstract"]
When you have installed KServe, you can use the {productname-long} dashboard to enable the single model serving platform. You can also use the dashboard to enable model-serving runtimes for the platform.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the admin group (for example, {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the admin group (for example, {odh-admin-group}) in OpenShift.
endif::[] 
* You have installed KServe.

.Procedure
. Enable the single model serving platform as follows:
.. In the left menu, click *Settings* -> *Cluster settings*.
.. Locate the *Model serving platforms* section.
.. To enable the single model serving platform for projects, select the *Single model serving platform* checkbox.
.. Click *Save changes*.
. Enable pre-installed runtimes for the single-model serving platform as follows:
.. In the left menu of the {productname-short} dashboard, click *Settings* -> *Serving runtimes*.
.. On the *Serving runtimes* page, set the *Caikit TGIS ServingRuntime for KServe* or *TGIS Standalone ServingRuntime for KServe* runtimes to *Enabled*.
+
The single model serving platform is now available for model deployments. 

// [role="_additional-resources"]
// .Additional resources
