:_module-type: PROCEDURE

[id="enabling-the-model-catalog_{context}"]
= Enabling the model catalog

[role='_abstract']
To allow the data scientists in your organization to register, deploy, and customize models from the model catalog, you must enable the feature in {productname-short}. You can enable the model catalog feature by setting the `disableModelCatalog` dashboard configuration option to `false`. 

ifdef::upstream[]
For more information about setting dashboard configuration options, see link:{odhdocshome}/managing-odh/#customizing-the-dashboard[Customizing the dashboard].
endif::[]
ifndef::upstream[]
For more information about setting dashboard configuration options, see link:{rhoaidocshome}{default-format-url}/managing_openshift_ai/customizing-the-dashboard[Customizing the dashboard].
endif::[]

ifndef::upstream[]
[IMPORTANT]
====
ifdef::self-managed[]
The model catalog feature is currently available in {productname-long} {vernum} as a Technology Preview feature.
endif::[]
ifdef::cloud-service[]
The model catalog feature is currently available in {productname-long} as a Technology Preview feature.
endif::[]
Technology Preview features are not supported with {org-name} production service level agreements (SLAs) and might not be functionally complete.
{org-name} does not recommend using them in production.
These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information about the support scope of {org-name} Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====
endif::[]

ifndef::cloud-service[]
[IMPORTANT]
====
The model catalog feature is not currently supported for disconnected environments.
====
endif::[]

.Prerequisites

* You have cluster administrator privileges for your {openshift-platform} cluster.
* You have installed {productname-short}.
ifdef::upstream[]
* A cluster administrator has configured and enabled the model registry component in your {productname-short} deployment. For more information, see link:{odhdocshome}/working-with-model-registries/#configuring-the-model-registry-component_model-registry[Configuring the model registry component].
endif::[]
ifndef::upstream[]
* A cluster administrator has configured and enabled the model registry component in your {productname-short} deployment. For more information, see link:{rhoaidocshome}{default-format-url}/configuring_the_model_registry_component/configuring-the-model-registry-component_model-registry-config[Configuring the model registry component].
endif::[]

.Procedure

ifdef::upstream[]
. Follow the steps described in link:{odhdocshome}/managing-odh/#customizing-the-dashboard[Customizing the dashboard] to set the `disableModelCatalog` dashboard configuration option to `false`. 
endif::[]
ifndef::upstream[]
. Follow the steps described in link:{rhoaidocshome}{default-format-url}/managing_openshift_ai/customizing-the-dashboard[Customizing the dashboard] to set the `disableModelCatalog` dashboard configuration option to `false`. 
endif::[]


.Verification

Log in to {productname-short} and verify that the *Model catalog* option appears under the *Models* navigation menu section.

