:_module-type: PROCEDURE

[id='enabling-the-multi-model-serving-platform_{context}']
= Enabling the multi-model serving platform

[role='_abstract']
To use the multi-model serving platform, you must first enable the platform.

.Prerequisites
* You have logged in to {productname-short} as a user with {productname-short} administrator privileges.
* Your cluster administrator has _not_ edited the {productname-short} dashboard configuration to disable the ability to select the multi-model serving platform, which uses the ModelMesh component. 
ifndef::upstream[]
For more information, see link:{rhoaidocshome}{default-format-url}/managing_resources/customizing-the-dashboard#ref-dashboard-configuration-options_dashboard[Dashboard configuration options].
endif::[]
ifdef::upstream[]
For more information, see link:{odhdocshome}/managing-resources/#ref-dashboard-configuration-options_dashboard[Dashboard configuration options].
endif::[]

.Procedure
. In the left menu of the {productname-short} dashboard, click *Settings* → *Cluster settings*.
. Locate the *Model serving platforms* section.
. Select the *Multi-model serving platform* checkbox.
. Click *Save changes*.

//[role="_additional-resources"]
//.Additional resources
