:_module-type: PROCEDURE

[id='enabling-data-science-pipelines-v2_{context}']
= Enabling Data Science Pipelines v2

ifdef::upstream[]

Data science pipelines in {productname-long} now use Data Science Pipelines version 2. Previously, data science pipelines used link:https://www.kubeflow.org/docs/components/pipelines/v1/[KubeFlow Pipelines (KFP) version 1].
endif::[]

ifndef::upstream[]

From {productname-short} version 2.9, data science pipelines use Data Science Pipelines (DSP) version 2. 
endif::[]

[IMPORTANT]
====
DSP v2 contains an installation of Argo Workflows. {productname-short} does not support direct customer usage of this installation of Argo Workflows.

If there is an existing installation of Argo workflows that is not managed by {org-name} on your cluster, installations of and upgrades to {productname-short} 2.9 with DSP will fail.

To install or upgrade to {productname-short} 2.9 with DSP, you must ensure that no separate installation of Argo workflows exists on your cluster.
====

== Installing {productname-short} with DSP v2
ifdef::upstream[]
ODH installation
endif::[]

ifndef::upstream[]
ifdef::cloud-service[]
//RHOAI CS
To install {productname-short} 2.9, ensure that there is no installation of Argo workflows that is not managed by {org-name} on your cluster, and follow the installation steps described in link:{rhoaidocshome}{default-format-url}/installing_and_uninstalling_openshift_ai_cloud_service/index[Installing and uninstalling OpenShift AI Cloud Service].
endif::[]

//RHOAI self-managed & disconnected
ifdef::self-managed[]
To install {productname-short} 2.9, ensure that there is no installation of Argo workflows that is not managed by {org-name} on your cluster, and follow the installation steps described in link:{rhoaidocshome}{default-format-url}/installing_and_uninstalling_openshift_ai_self-managed/index[Installing and uninstalling OpenShift AI Self-Managed]. For disconnected environments, see link:{rhoaidocshome}{default-format-url}/installing_and_uninstalling_openshift_ai_self-managed_in_a_disconnected_environment[Installing and uninstalling {productname-long} in a disconnected environment].
endif::[]
endif::[]

== Upgrading to DSP v2

ifdef::upstream[]
=== Upgrading from KFP v1 to DSP v2

To upgrade to x with DSP v2, ensure that there is no installation of Argo workflows that is not managed by {org-name} on your cluster, and follow the upgrade steps described in Y.

endif::[]

ifndef::upstream[]
=== Upgrading from DSP v1 to DSP v2

To upgrade to x with DSP v2, ensure that there is no installation of Argo workflows that is not managed by {org-name} on your cluster, and follow the upgrade steps described in Y.

endif::[]

== Migrating pipelines to DSP v2

ifdef::upstream[]
endif::[]
{productname-short} does not automatically migrate existing KFP v1 instances to DSP v2. To use existing KFP v1 pipelines with DSP v2, you must manually migrate them. For more information about migrating your pipelines to DSP v2, see link:[Migrating pipelines from KFP v1 to DSP v2].
ifndef::upstream[]
{productname-short} does not automatically migrate existing DSP v1 instances to v2. To use existing DSP v1 pipelines with DSP v2, you must manually migrate them. For more information about migrating your pipelines to DSP v2, see link:[Migrating pipelines from DSP v1 to DSP v2].
endif::[]


=== Migrating pipelines from DSP v1 to DSP v2

=== Migrating pipelines from KFP v1 to DSP v2
