:_module-type: PROCEDURE

[id="enabling-the-model-catalog_{context}"]
= Enabling the model catalog

[role='_abstract']
Before data scientists in your organization can register, deploy, and customize models from the model catalog, you must ensure that this feature is enabled in {productname-short}. You can enable the model catalog by setting the `disableModelCatalog` dashboard configuration option to `false`. 

ifdef::upstream[]
For more information about setting dashboard configuration options, see link:{odhdocshome}/managing-resources/#customizing-the-dashboard[Customizing the dashboard].
endif::[]
ifndef::upstream[]
For more information about setting dashboard configuration options, see link:{rhoaidocshome}{default-format-url}/managing_resources/customizing-the-dashboard[Customizing the dashboard].
endif::[]

[NOTE]
====
The model catalog feature is enabled by default in {productname-short} {vernum}. 
ifndef::cloud-service[]
However, if the model catalog was not enabled in a previous version of {productname-short}, it will remain disabled after upgrading to {productname-short} {vernum}.
endif::[]
====

.Prerequisites

* A cluster administrator has installed {productname-short}.
ifdef::upstream[]
* The model registry component is enabled in your {productname-short} deployment. For more information, see link:{odhdocshome}/working-with-model-registries/#enabling-the-model-registry-component_model-registry[Enabling the model registry component].
endif::[]
ifndef::upstream[]
* The model registry component is enabled in your {productname-short} deployment. For more information, see link:{rhoaidocshome}{default-format-url}/enabling_the_model_registry_component/enabling-the-model-registry-component_model-registry-config[Enabling the model registry component].
endif::[]
* You have {productname-short} administrator privileges.


.Procedure

ifdef::upstream[]
. Follow the steps described in link:{odhdocshome}/managing-resources/#customizing-the-dashboard[Customizing the dashboard] to set the `disableModelCatalog` dashboard configuration option to `false`. 
endif::[]
ifndef::upstream[]
. Follow the steps described in link:{rhoaidocshome}{default-format-url}/managing_resources/customizing-the-dashboard[Customizing the dashboard] to set the `disableModelCatalog` dashboard configuration option to `false`. 
endif::[]


.Verification

Log in to {productname-short} and verify that the *Model catalog* option is displayed under the *Models* navigation menu section.

