:_module-type: PROCEDURE

[id='enabling-automatic-authentication-and-publishing-features_{context}']
= Enabling automatic authentication and publishing features

Enable automatic, write access authentication for specific projects.

.Prerequisites
* Your Feature Store has been deployed.
* User Access permissions have been configured.

.Procedure

. From the {productname-short} dashboard, click *Projects*.
+
The *Projects* page opens.
. Click the name of the project that you want to work on.
. Create a new workbench or open an existing workbench with the Feast software development kit (SDK). 
.. In the Feature Store client configuration table, select configmaps associated with the desired repositories.
.. Copy the Python script that is generated on the left of the page.
.. Click the **Workbenches** tab and launch a workbench.
.. Paste the Python script into the workbench cell.

[NOTE]
====
Feast SDK is available in all images except minimal.
====

.Verification 
If the procedure is successful, you will be able to create a new feature, or access existing feature store objects, such as feature views.

