:_module-type: PROCEDURE

[id='enabling-habana-gaudi-devices_{context}']
= Enabling Habana Gaudi devices

[role='_abstract']
Before you can use Habana Gaudi devices in {productname-short}, you install the necessary dependencies and deploy the HabanaAI Operator in your deployment. 

.Prerequisites
* You have logged in to {openshift-platform}.
* You have the `cluster-admin` role in {openshift-platform}.

.Procedure
. To enable Habana Gaudi devices in {productname-short}, follow the instructions at link:https://docs.habana.ai/en/latest/Orchestration/HabanaAI_Operator/index.html[HabanaAI Operator for OpenShift].
. Create an accelerator profile for your Habana Gaudi device. 
.. In the {openshift-platform} web console in the *Administrator* perspective, click *Administration* -> *CustomResourceDefinitions*.
.. In the search bar, enter `acceleratorprofile` to search by name.
+
The *CustomResourceDefinitions* page reloads to display the search results.
+
.. Click the `AcceleratorProfile` custom resource definition (CRD).
+
A details page for the custom resource definition (CRD) opens.
.. Click the *Instances* tab.
.. Click *Create AcceleratorProfile*. 
+ 
The *Create AcceleratorProfile* page opens with an embedded YAML editor.
.. Enter or paste your accelerator profile YAML code directly in the embedded editor. This example shows the code for a Habana Gaudi 1 accelerator profile:
+
[source,yaml]
---
apiVersion: dashboard.opendatahub.io/v1alpha
kind: AcceleratorProfile
metadata:
  name: hpu-profile-first-gen-gaudi
spec:
  displayName: Habana HPU - 1st Gen Gaudi
  description: First Generation Habana Gaudi device
  enabled: true
  identifier: habana.ai/gaudi
  tolerations:
    - effect: NoSchedule
      key: habana.ai/gaudi
      operator: Exists
---
.. Click *Create*.

.Verification
* From the *Administrator* perspective, the following Operators appear on the *Operators* -> *Installed Operators* page.
** HabanaAI
** Node Feature Discovery (NFD)
** Kernel Module Management (KMM)
* The *Accelerator* list displays the Habana Gaudi accelerator on the *Start a notebook server* page.  
* The accelerator profile appears on the *Instances* tab on the details page for the `AcceleratorProfile` custom resource definition (CRD).

[role='_additional-resources']
.Additional resources
* link:https://docs.habana.ai/en/latest/Orchestration/HabanaAI_Operator/index.html[HabanaAI Operator for OpenShift]. 
