:_module-type: PROCEDURE

[id="enabling-the-single-model-serving-platform_{context}"]
= Enabling the single-model serving platform

[role="_abstract"]
When you have installed KServe, you can use the {productname-long} dashboard to enable the single-model serving platform. You can also use the dashboard to enable model-serving runtimes for the platform.

.Prerequisites
* You have logged in to {productname-short} as a user with {productname-short} administrator privileges.
* You have installed KServe.
* The `spec.dashboardConfig.disableKServe` dashboard configuration option is set to `false` (the default).
+
ifdef::upstream[]
For more information about setting dashboard configuration options, see link:{odhdocshome}/managing-resources/#customizing-the-dashboard[Customizing the dashboard].
endif::[]
ifndef::upstream[]
For more information about setting dashboard configuration options, see link:{rhoaidocshome}{default-format-url}/managing_resources/customizing-the-dashboard[Customizing the dashboard].
endif::[]
 
.Procedure
. Enable the single-model serving platform as follows:
.. In the left menu, click *Settings* -> *Cluster settings*.
.. Locate the *Model serving platforms* section.
.. To enable the single-model serving platform for projects, select the *Single-model serving platform* checkbox.
.. Click *Save changes*.
. Enable preinstalled runtimes for the single-model serving platform as follows:
.. In the left menu of the {productname-short} dashboard, click *Settings* -> *Model resources and operations* -> *Serving runtimes*. 
+
The *Serving runtimes* page shows preinstalled runtimes and any custom runtimes that you have added. 
+
ifdef::upstream[]
For more information about preinstalled runtimes, see link:{odhdocshome}/configuring-your-model-serving-platform/#ref-supported-runtimes_odh-user[Supported runtimes].
endif::[]
ifndef::upstream[]
For more information about preinstalled runtimes, see link:{rhoaidocshome}{default-format-url}/configuring_your_model-serving_platform/configuring-your-model-serving-platform_rhoai-admin#supported-model-serving-runtimes_rhoai-admin[Supported runtimes].
endif::[]
.. Set the runtime that you want to use to *Enabled*.
+
The single-model serving platform is now available for model deployments. 

// [role="_additional-resources"]
// .Additional resources
