:_module-type: PROCEDURE

[id="executing-a-pipeline-run_{context}"]
= Executing a pipeline run

[role='_abstract']
By default, a pipeline run executes once immediately after it is created.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have previously created a data science project that is available and contains a configured pipeline server.
* You have imported a pipeline to an active pipeline server.

.Procedure
. From the {productname-short} dashboard, click *Experiments* -> *Experiments and runs*.
. On the *Experiments* page, from the *Project* drop-down list, select the project that contains the pipeline experiment that you want to create a run for.
. From the list of pipeline experiments, click the experiment that you want to create a run for.
. Click *Create run*.
. On the *Create run* page, configure the run:
.. From the *Experiment* list, select the pipeline experiment that you want to create a run for. Alternatively, to create a new pipeline experiment, click *Create new experiment*, and then complete the relevant fields in the *Create experiment* dialog.
.. In the *Name* field, enter a name for the run.
.. In the *Description* field, enter a description for the run.
.. From the *Pipeline* list, select the pipeline that you want to create a run for. Alternatively, to create a new pipeline, click *Create new pipeline*, and then complete the relevant fields in the *Import pipeline* dialog.
.. From the *Pipeline version* list, select the pipeline version to create a run for. Alternatively, to upload a new version, click *Upload new version*, and then complete the relevant fields in the *Upload new version* dialog.
.. Configure the input parameters for the run by selecting the parameters from the list.
.. Click *Create run*.
+
The details page for the run opens.

.Verification
* The pipeline run that you created appears on the *Runs* tab on the *Runs* page for the pipeline experiment.

//[role='_additional-resources']
//.Additional resources
