:_module-type: REFERENCE

[id='guardrails-orchestrator-config-parameters_{context}']
= Orchestrator Configuration Parameters

The first step in deploying the Guardrails framework is to first define your Orchestrator configuration with a Config Map. This serves as a registry of the components in the system, namely by specifying the model-to-be-guardrailed and the available detector servers.

Here is an example version of an Orchestrator configuration file:

.Example `orchestrator_configmap.yaml`
[source,yaml]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: orchestrator-config
data:
  config.yaml: |
    chat_generation:
      service:
        hostname: <generation_hostname>
        port: <generation_service_port>
        api_token: <api_token_env_var>
        tls: <tls_config_1_name>
    detectors:
      <detector_server_1_name>:
        type: text_contents
        service:
            hostname: "127.0.0.1"
            port: 8080
        chunker_id: whole_doc_chunker
        default_threshold: 0.5
      <detector_server_2_name>:
        type: text_contents
        service:
          hostname: <other_detector_hostname>
          port: <detector_server_port>
          api_token: <api_token_env_var>
          tls: <some_other_detector_tls>
        chunker_id: whole_doc_chunker
        default_threshold: 0.5
    tls:
      - <tls_config_1_name>:
          cert_path: /etc/tls/<path_1>/tls.crt
          key_path: /etc/tls/<path_1>/tls.key
          ca_path: /etc/tls/ca/service-ca.crt
      - <tls_config_2_name>:
          cert_path: /etc/tls/<path_2>/tls.crt
          key_path: /etc/tls/<path_2>/tls.key
          ca_path: /etc/tls/ca/service-ca.crt
    passthrough_headers:
      - "authorization"
      - "content-type"
----
.Orchestrator configuration parameters
[cols="1,2a", options="header"]
|===
| Parameter | Description
| *`chat_generation`* | Describes the generation model to be guardrailed. Requires a *`service`* configuration, see below.
| *`service`* | A service configuration. Throughout the Orchestrator config, all external services are described using the
service configuration, which contains the following fields:

* `hostname` - The hostname of the service
* `port` - The port of the service
* `api_token` *(Optional)* - The name of an environment variable that holds the authentication token for the service. The token value is read from the environment variable at runtime. For example, if set to `MODEL_TOKEN`, the Orchestrator reads the token from the `$MODEL_TOKEN` environment variable.
* `tls` *(Optional)* - The name of the TLS configuration (specified later in the configuration) to use for this service. If provided, the Orchestrator communicates with this service with HTTPS.
| *`detectors`* | The `detectors` section is where the detector servers available to the Orchestrator are specified. Provide some unique name for the detector server as the key
to each entry, and then the following values are required:

* `type` - The kind of detector server. For now, the only supported kind within RHOAI is `text_contents`
* `service` - The service configuration for the detector server, see the *`service`* section above for details. Note, if you want to use the built-in detector, the service configuration should always be

    service:
        hostname: "127.0.0.1"
        port: 8080

* `chunker_id`- The chunker to use for this detector server. For now, the only supported chunker is `whole_doc_chunker`
* `default_threshold`- The threshold to pass to the detector server. The threshold can be used by the detector servers to determine their sensitivity, and recommended values vary by detector algorithm. A safe starting point for this is a value of `0.5`.
| *`<detector_server_name>`*| [[detector-server-name-param]] Each key in the detector section defines the *name* of the detector server. This can be any string, but you'll need to reference these names later, so pick memorable and descriptive names.
| *`tls`* | The `tls` section defines TLS configurations. The names of these configurations can then be used as values within `service.tls` in your service configurations (see the *`service`* section above).
A TLS configuration consists of the following fields:

    * `cert_path` - The path to a `.crt` file inside the Guardrails Orchestrator container.
    * `key_path` - The path to a `.key` file inside the Guardrails Orchestrator container.
    * `ca_path` - The path to CA certificate `.crt` file on the Guardrails Orchestrator container. The default Openshift Serving CA will be mounted at `/etc/tls/ca/service-ca.crt`, we recommend using this as your `ca_path`.
+
See the `tlsSecrets` section of the GuardrailsOrchestrator Custom Resource in _Deploying the Guardrails Orchestrator_ to learn how to mount custom TLS files into the Guardrails Orchestrator container.
| *`passthrough_headers`* |  Defines which headers from your requests to the Guardrails Orchestrator get sent onwards to
the various services specified in this configuration. If you want to ensure that the Orchestrator can talk to authenticated services,  include "authorization" and "content-type" in your passthrough header list.
|===