:_module-type: PROCEDURE

ifdef::context[:parent-context: {context}]
[id="querying-using-vllm-guardrails-gateway_{context}"]
= Querying using the vLLM guardrails gateway
[role='_abstract']

The Guardrails Orchestrator vLLM gateway provides the OpenAI `v1/chat/completions` API, which lets you hot swap between models without guardrails and models with guardrails. 

.Prerequisites
* You have configured the regex detector and vLLM guardrails gateway.

.Procedure
. Set up the endpoint for the detectors:
+
[source,terminal]
----
GUARDRAILS_GATEWAY=https://$(oc get routes guardrails-gateway -o jsonpath='{.spec.host}')
----
+
ifdef::upstream[]
Based on the example configurations provided in link:{odhdocshome}monitoring-data-science-models/#guardrails-orchestrator-configuring-regex-vllm_gateway_monitor[Configuring the regex detector and vLLM gateway], the available endpoint for the guardrailed model is `$GUARDRAILS_GATEWAY/pii`.
endif::[]

ifdef::self-managed[]
Based on the example configurations provided in link:{rhoaidocshome}{default-format-url}/monitoring_data_science_models/configuring-the-guardrails-orchestrator-service_monitor#guardrails-orchestrator-configuring-regex-vllm_gateway_monitor[Configuring the regex detector and vLLM gateway], the available endpoint for the model with guardrails is `$GUARDRAILS_GATEWAY/pii`.
endif::[]

ifdef::cloud-service[]
Based on the example configurations provided in link:{rhoaidocshome}{default-format-url}monitoring-data-science-models/#guardrails-orchestrator-configuring-regex-vllm_gateway_monitor[Configuring the regex detector and vLLM gateway], the available endpoint for the model with guardrails is `$GUARDRAILS_GATEWAY/pii`.
endif::[]

. Query the model with guardrails `pii` endpoint:
+
[source,terminal]
----
curl -v $GUARDRAILS_GATEWAY/pii/v1/chat/completions \
-H "Content-Type: application/json" \
-d '{
    "model": $MODEL,
    "messages": [
        {
            "role": "user",
            "content": "btw here is my social 123456789"
        }
    ]
}'
----
+
.Example response
[source,terminal]
----
Warning: Unsuitable input detected. Please check the detected entities on your input and try again with the unsuitable input removed.
Input Detections:
   0) The regex detector flagged the following text: "123-45-6789"
----