:_module-type: PROCEDURE

[id='guardrails-auto-config_{context}']

= Auto-configuring Guardrails

[role='_abstract']
Auto-configuration simplifies the Guardrails setup process by automatically identifying available detector servers in your namespace, handling TLS configuration, and generating configuration files for a Guardrails Orchestrator deployment. For example, if any of the detectors or generation services use HTTPS, their credentials are automatically discovered, mounted, and used. Additionally, the orchestrator is automatically configured to forward all necessary authentication token headers.

.Prerequisites
* Each detector service you intend to use has an OpenShift label applied in the resource metadata. For example, `metadata.labels.<label_name>: 'true'`. Choose a descriptive name for the label as it is required for auto-configuration.
* You have set up the inference service to which you intend to apply guardrails.
* You have installed the {openshift-cli} as described in the appropriate documentation for your cluster:
ifdef::upstream,self-managed[]
** link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI^] for OpenShift Container Platform  
** link:https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws/{rosa-latest-version}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI^] for {rosa-productname}
endif::[]
ifdef::cloud-service[]
** link:https://docs.redhat.com/en/documentation/openshift_dedicated/{osd-latest-version}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI^] for OpenShift Dedicated  
** link:https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws_classic_architecture/{rosa-classic-latest-version}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI^] for {rosa-classic-productname}
endif::[]

.Procedure
. Create a `GuardrailsOrchestrator` CR with the `autoConfig` configuration. For example, create a YAML file named `guardrails_orchestrator_auto_cr.yaml` with the following contents:
+
.Example `guardrails_orchestrator_auto_cr.yaml` CR
[source,yaml]
----
apiVersion: trustyai.opendatahub.io/v1alpha1
kind: GuardrailsOrchestrator
metadata:
  name: guardrails-orchestrator
  annotations:
    security.opendatahub.io/enable-auth: 'true'
spec:
  autoConfig:
    inferenceServiceToGuardrail: <inference_service_name>
    detectorServiceLabelToMatch: <detector_service_label>
  enableBuiltInDetectors: true
  enableGuardrailsGateway: true
  replicas: 1
----
+
* `inferenceServiceToGuardrail`: Specifies the name of the vLLM inference service to protect with Guardrails.
* `detectorServiceLabelToMatch`: Specifies the label that you applied to each of your detector servers in the `metadata.labels` specification for the detector. The Guardrails Orchestrator `ConfigMap` automatically updates to reflect detectors in your namespace that match the label set in the `detectorServiceLabelToMatch` field.

If `enableGuardrailsGateway` is true, a template Guardrails gateway config called `$(ORCHESTRATOR-NAME)-gateway-auto-config` will be generated. This file can be modified to tailor
your Guardrails Gateway setup as desired, and the Guardrails Orchestrator will automatically deploy when changes are detected. Once modified, the label `trustyai/has-diverged-from-auto-config` will be applied.To revert the file back to the auto-generated starting point, simply delete it and the original auto-generate file will be recreated.

If `enableBuiltInDetectors` is true, the built-in detector server is automatically added to your orchestrator configuration under the same `built-in-detector`, and a sample configuration will be included in the auto-generate guardrails gateway config if desired.





. Deploy the orchestrator custom resource. This step creates a service account, deployment, service, and route object in your namespace.
+
[source,terminal]
----
oc apply -f guardrails_orchestrator_auto_cr.yaml -n <your_namespace>
----

.Verification
You can verify that the `GuardrailsOrchestrator` CR and corresponding automatically generated configuration objects were successfully created in your namespace by running the following commands:

. Confirm that the `GuardrailsOrchestrator` CR was created:
+
[source,terminal]
----
$ oc get guardrailsorchestrator -n <your_namespace>
----

. View the automatically generated Guardrails Orchestrator `ConfigMaps`:
+
[source,terminal]
----
$ oc get configmap -n <your_namespace> | grep auto-config
----

. You can then view the automatically generated config:
+
[source,terminal]
----
$ oc get configmap/<auto-generated config map name> -n <your_namespace> -o yaml
----