:_module-type: REFERENCE

[id='guardrails-gateway-config-parameters_{context}']

= Guardrails Gateway Config Parameters

The Guardrails gateway provides a mechanism for defining preset detector pipelines and creating a unique, endpoint-per-pipeline preset. To use the Guardrails gateway, create a Guardrails Gateway configuration with a Config Map.

+
.Example `gateway_configmap.yaml`
[source,yaml]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: guardrails-gateway-config
data:
  config.yaml: |
    detectors:
      - name: <built_in_detector_name>
        server: <built_in_detector_server_name>
        input: <boolean>
        output: <boolean>
        detector_params:
          <detector_taxonomy>:
            - <detector_name>
      - name: <detector_2_name>
        detector_params: {}
    routes:
      - name: <preset_1_name>
        detectors:
          - <detector_name>
          - <detector_name>
          - ...
          - <detector_name>
      - name: passthrough
        detectors:
----

[cols="1,2a", options="header"]
|===
| Parameter | Description
| `detectors` | The list of detector servers and parameters to use inside your Guardrails Gateway presets. The following fields are available:

* `name` - The name of your detector server. This key is later used when defining your preset routes in the `route` section of the configuration. If no `server` value is provided, this name must match a detector server name given in your  <<detector-server-name-param,*Orchestrator Config*>>. If `server` is specified, the `name` field can be any string.
* `server` *(optional)* - The server name from your <<detector-server-name-param,*Orchestrator Config*>> to use for this particular detector config.This field is useful if you want to create multiple detector parameter configurations that use the same underlying detector server, e.g., to use the built-in detector with different algorithms for different presets.
* `input` -  Whether this detector should operate over user inputs (prompts). Available values are `true` or `false`
* `output` - Whether this detector should operate over model outputs.  Available values are `true` or `false`
* `detector_params` - The parameters that should be passed to the detector endpoint. See <<guardrails-detector-server-info, `detector server documentation`>> for more information.

| `routes` | Define Guardrail pipeline presets according to combinations of available detectors. Each preset route requires the following fields:

* `name` - The name of the route preset. A corresponding `/<name>/v1/chat/completions` endpoint is available in the created Guardrails Gateway server. For example, in the example configuration above, `/passthrough/v1/chat/completions/` is an available endpoint.
* `detectors` - The list of detectors that should be used in this particular pipeline preset. Please see the note below regarding using multiple detectors from the same underlying server.
|===

[NOTE]
====
The Guardrails Gateway only provides the `/v1/chat/completions` API for each route preset. The older `/v1/completions` API is not supported.
====

[NOTE]
====
In the `routes` presets configuration, each input and output detector in the `detectors` list must use a unique server. For example, if we have the following detectors, the `routes` preset configuration is invalid because it uses two `input: true` detectors from the `serverA` server:

----
- name: detector1
  server: serverA
  input: true
  output: false
- name: detector2
  server: serverA
  input: true
  output: false
- name: detector3
  server: serverA
  input: false
  output: true
----

----
routes:
  - name: route1
    detectors:
      - detector1
      - detector2
----

However, the following `routes` preset configuration is valid, because while both detectors use `serverA`, `detector1` is only an input detector, while  `detector3` is only an output detector, and therefore does not conflict:
----
routes:
  - name: route1
    detectors:
      - detector1
      - detector3
----

The following `routes` preset is also valid, because, while two input detectors from `serverA` are used, they are not used in the same route preset:
----
routes:
  - name: route1
    detectors:
      - detector1
  - name: route2
    detectors:
      - detector2
----
====