:_module-type: PROCEDURE

[id="hiding-the-default-jupyter-application_{context}"]
= Hiding the default Jupyter application

[role='_abstract']
The {productname-short} dashboard includes Jupyter as an enabled application by default.

To hide the Jupyter tile from the list of Enabled applications, edit the dashboard configuration file.

.Prerequisites

* You have cluster administrator privileges for your {openshift-platform} cluster.
* You know how to edit the dashboard configuration file, as described in xref:editing-the-dashboard-configuration-file[Editing the dashboard configuration file].

.Procedure

. Open the dashboard configuration file.
. In the `spec:notebookController` section, set the value of `enabled` to `false` to hide the Jupyter tile from the list of Enabled applications.
. Click *Save* to apply your changes and then click *Reload* to make sure that your changes are synced to the cluster.

.Verification

In the {productname-short} dashboard, select *Applications> Enabled*. You should not see the Jupyter tile.

