:_module-type: CONCEPT

[id='ibm-spyre-integration_{context}']
= IBM Spyre integration

[role='_abstract']
The IBM Spyre Operator integrates IBM Spyre accelerators directly into {productname-short} workflows.

To enable IBM Spyre in {productname-short}, you must perform the following tasks:

* Install all necessary dependencies before you enable IBM Spyre accelerators in {productname-short}.

* Install the latest version of the IBM Spyre Operator from the software catalog.  

* After you install the IBM Spyre Operator, you must create an accelerator profile or hardware profile in {productname-short} to expose IBM Spyre as an available accelerator resource for workloads.

For more detailed guidance on configuring IBM Spyre accelerators for production-ready deployments, contact IBM support. 

[role="_additional-resources"]
.Additional resources

* link:https://catalog.redhat.com/en/software/containers/ibm-aiu/spyre-operator/688a1121575e62c686a471d4?architecture=amd64[IBM Spyre Operator catalog entry]
* link:https://github.com/ibm/spyre-operator-power-docs[IBM Spyre Operator for IBM Power User's Guide]
