:_module-type: PROCEDURE

[id="identity-metric-request-bias-monitoring_{context}"]
= Scheduling an identity metric request

Furthermore, let's monitor the average values of various data fields over time, to see the average ratio of loan-payback to loan-default predictions, as well as the average ratio of male-identifying to non-male-identifying applicants. We can do this by creating an Identity Metric Request via POST'ing the `/metrics/identity/request` endpoint:

[source]
for model in "demo-loan-nn-onnx-alpha" "demo-loan-nn-onnx-beta"; do
  for field in "Is Male-Identifying?" "Will Default?"; do
      curl -sk -H "Authorization: Bearer ${TOKEN}" -X POST --location $TRUSTY_ROUTE/metrics/identity/request \
       --header 'Content-Type: application/json' \
       --data "{
                 \"columnName\": \"$field\",
                 \"batchSize\": 250,
                 \"modelId\": \"$model\"
               }"
  done
done

The payload is structured as follows:

[disc]
** `columnName`: The name of the field to compute the averaging over
** `batchSize`: The number of previous inferences to include in the average-value calculation
** `modelId`: The name of the model to query