:_module-type: CONCEPT

[id='import-example-notebooks_{context}']
= Import example notebooks

To get started with customizing your models, you can run provided example notebooks and scripts. Table 2.2 lists the Git repositories that provide example notebooks for each model customization component.

For a comprehensive tutorial that demonstrates an AI/ML workflow, see the link:https://github.com/red-hat-data-services/red-hat-ai-examples/tree/main/examples/knowledge-tuning[Knowledge Tuning example]
on the {org-name} AI examples site.

The Knowledge Tuning tutorial is a curated collection of Jupyter notebooks that includes examples of using Docling to process data, training-hub to fine-tune a model on that data, and KServe to deploy the final model for a Question and Answer application.

.Model customization example notebooks
[cols="3,4,2,2"]
|===
|Model customization component | Git clone example repository | Branch | Directory

|Data processing using docling
|`https://github.com/opendatahub-io/data-processing.git`
|`stable-3.0`
|`notebooks/`

|Synthetic data generation
|`https://github.com/Red-Hat-AI-Innovation-Team/sdg_hub.git`
|`main`
|`examples`

|Training
|`https://github.com/Red-Hat-AI-Innovation-Team/training_hub.git`
|`main`
|`examples`

|End-to-end example for model customization with these components
|`https://github.com/red-hat-data-services/red-hat-ai-examples.git`
|`main`
|`knowledge-tuning`
|===