:_module-type: PROCEDURE

[id='installing-the-odh-operator-v2_{context}']
= Installing the Open Data Hub Operator version 2

.Prerequisites
* You are using OpenShift Container Platform {ocp-minimum-version} or later.
* Your OpenShift cluster has a minimum of 16 CPUs and 32GB of memory across all OpenShift worker nodes.
* You have cluster administrator privileges for your OpenShift Container Platform cluster.
* If you are using custom namespaces, you have created and labeled them as required. 
* If you are installing {productname-short} 2.10.0 or later with data science pipelines, ensure your cluster does not have a separate installation of Argo Workflows that was not installed by {productname-short}.
+
[IMPORTANT]
====
Data science pipelines 2.0 includes an installation of Argo Workflows. {org-name} does not support direct customer usage of this installation of Argo Workflows.

If there is an existing installation of Argo Workflows that is not installed by data science pipelines on your cluster, data science pipelines will be disabled after you install {productname-short}.

To enable data science pipelines, remove the separate installation of Argo Workflows from your cluster. Data science pipelines will be enabled automatically. 

Argo Workflows resources that are created by {productname-short} have the following labels in the OpenShift Console under *Administration > CustomResourceDefinitions*, in the `argoproj.io` group:
[source]
----
 labels:
    app.kubernetes.io/part-of: data-science-pipelines-operator
    app.opendatahub.io/data-science-pipelines-operator: 'true'
----
====

.Procedure
. Log in to your OpenShift Container Platform as a user with `cluster-admin` privileges. If you are performing a developer installation on link:http://try.openshift.com[try.openshift.com], you can log in as the `kubeadmin` user.
. Select *Operators* -> *OperatorHub*.
. On the *OperatorHub* page, in the *Filter by keyword* field, enter `Open Data Hub Operator`.
. Click the *Open Data Hub Operator* tile.
. If the *Show community Operator* window opens, read the information and then click *Continue*.
. Read the information about the Operator and then click *Install*.
. On the *Install Operator* page, follow these steps:
.. For *Update* channel, select *fast*.
+
[NOTE]
--
Version 2 of the Open Data Hub Operator represents an alpha release, accessible only on the *fast* channel. Later releases will change to the *rolling* channel when the Operator is more stable.
--
.. For *Version*, select the version of the Operator that you want to install. 
.. For *Installation mode*, leave *All namespaces on the cluster (default)* selected.
.. For *Installed Namespace*, select the *openshift-operators* namespace.
.. For *Update approval*, select automatic or manual updates. 
* *Automatic*: When a new version of the Operator is available, Operator Lifecycle Manager (OLM) automatically upgrades the running instance of your Operator.
* *Manual*: When a new version of the Operator is available, OLM notifies you with an update request that you must manually approve to upgrade the running instance of your Operator.
. Click *Install*. The installation might take a few minutes.

.Verification
* Select *Operators* -> *Installed Operators* to verify that the *Open Data Hub Operator* is listed with *Succeeded* status.

.Next Step
* Install Open Data Hub components.

[role="_additional-resources"]
.Additional resources
* link:{odhdocshome}/installing-open-data-hub/#configuring-the-operator-logger_operator-log[Configuring the {productname-short} Operator logger]
