:_module-type: CONCEPT

[id='installing-trustyai-service_{context}']
= Installing the TrustyAI service for a project

[role='_abstract']

Install the TrustyAI service on a data science project to provide access to its features for all models deployed within that project. An instance of the TrustyAI service is required for each data science project, or namespace, that contains models that the data scientists want to monitor.

ifdef::upstream[]
Use the {productname-short} dashboard or the OpenShift command-line interface (CLI) to install an instance of the TrustyAI service.
endif::[]

[NOTE]
====
Install only one instance of the TrustyAI service in a project. Multiple instances in the same project can result in unexpected behavior.

Installing TrustyAI into a namespace where non-OVMS models are deployed can cause errors in the TrustyAI service.
====

ifdef::upstream[]
include::installing-trustyai-service-using-dashboard.adoc[leveloffset=+1]
endif::[]

include::installing-trustyai-service-using-cli.adoc[leveloffset=+1]