[id="installing-the-llama-stack-operator_{context}"]
= Installing the Llama Stack Operator

You can install the Llama Stack Operator on your {openshift-platform} cluster by applying the latest release manifest from the upstream repository.

.Prerequisites

* You have cluster administrator privileges.
ifdef::upstream,self-managed[]
* You installed the OpenShift command line interface (`oc`) as described in link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI^].
endif::[]
ifdef::cloud-service[]
* You installed the OpenShift command line interface (`oc`) as described in link:https://docs.redhat.com/en/documentation/openshift_dedicated/{osd-latest-version}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI (OpenShift Dedicated)^] or link:https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws/{rosa-latest-version}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI (Red Hat OpenShift Service on AWS)^].
endif::[]
* You are logged in to your {openshift-platform} cluster.

.Procedure

. Open a new terminal window.
. Log in to your {openshift-platform} cluster from the CLI:
.. In the upper-right corner of the OpenShift web console, click your user name and select *Copy login command*.
.. After you have logged in, click *Display token*.
.. Copy the *Log in with this token* command and paste it into the terminal where you are using the OpenShift command-line interface (CLI).
+
[source,subs="+quotes"]
----
$ oc login --token=__<token>__ --server=__<openshift_cluster_url>__
----

. Set the Llama Stack Operator repository URL:
+
[source,terminal]
----
LLAMASTACK_REPO=https://raw.githubusercontent.com/llamastack/llama-stack-k8s-operator
----

. Apply the operator manifest to your cluster:
+
[source,terminal]
----
oc apply -f $LLAMASTACK_REPO/main/release/operator.yaml
----

. Verify that the Llama Stack Operator pods are running:
+
[source,terminal]
----
oc logs -l app.kubernetes.io/name=llama-stack-k8s-operator -n llama-stack-k8s-operator-system -f
----
+
You should see log entries similar to the following, which indicate the operator is running:
+
[source,text]
----
I0512 21:41:07.395981       1 request.go:601] Waited for 1.015570905s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/datasciencepipelinesapplications.opendatahub.io/v1?timeout=32s
1.7470860707506123e+09	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": ":8080"}
1.7470860751704922e+09	INFO	setup	starting manager
I0512 21:41:15.170638       1 leaderelection.go:248] attempting to acquire leader lease llama-stack-k8s-operator-system/54e06e98.llama.x-k8s.io...
1.7470860751706395e+09	INFO	Starting server	{"kind": "health probe", "addr": "[::]:8081"}
1.7470860751706395e+09	INFO	Starting server	{"path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
1.7470860751826112e+09	INFO	Starting Controller	{"controller": "llamastackdistribution", "controllerGroup": "llama.x-k8s.io", "controllerKind": "LlamaStackDistribution"}
1.7470860752835116e+09	INFO	Starting workers	{"controller": "llamastackdistribution", "controllerGroup": "llama.x-k8s.io", "controllerKind": "LlamaStackDistribution", "worker count": 1}
----

