:_module-type: PROCEDURE

[id='installing-the-odh-operator-v2_{context}']
= Installing the Open Data Hub Operator version 2

.Prerequisites
* You are using {openshift-platform} {ocp-minimum-version} or later.
* Your {openshift-platform} cluster has a minimum of 16 CPUs and 32GB of memory across all {openshift-platform} worker nodes.
* You have cluster administrator privileges for your {openshift-platform} cluster.
* If you are using custom namespaces, you have created and labeled them as required. 
* If you are using {productname-short} on a cluster running in FIPS mode, any custom container images for data science pipelines must be based on UBI 9 or RHEL 9. This ensures compatibility with FIPS-approved pipeline components and prevents errors related to mismatched OpenSSL or GNU C Library (glibc) versions.

.Procedure
. Log in to your {openshift-platform} as a user with `cluster-admin` privileges. If you are performing a developer installation on link:http://try.openshift.com[try.openshift.com], you can log in as the `kubeadmin` user.
. Select *Operators* -> *OperatorHub*.
. On the *OperatorHub* page, in the *Filter by keyword* field, enter `Open Data Hub Operator`.
. Click the *Open Data Hub Operator* tile.
. If the *Show community Operator* window opens, read the information and then click *Continue*.
. Read the information about the Operator and then click *Install*.
. On the *Install Operator* page, follow these steps:
.. For *Update* channel, select *fast*.
+
[NOTE]
--
Version 2 of the Open Data Hub Operator represents an alpha release, accessible only on the *fast* channel. Later releases will change to the *rolling* channel when the Operator is more stable.
--
.. For *Version*, select the version of the Operator that you want to install. 
.. For *Installation mode*, leave *All namespaces on the cluster (default)* selected.
.. For *Installed Namespace*, select the *{operator-default-namespace}* namespace or select your custom operator namespace.
.. For *Update approval*, select automatic or manual updates. 
* *Automatic*: When a new version of the Operator is available, Operator Lifecycle Manager (OLM) automatically upgrades the running instance of your Operator.
* *Manual*: When a new version of the Operator is available, OLM notifies you with an update request that you must manually approve to upgrade the running instance of your Operator.
. Click *Install*. The installation might take a few minutes.

.Verification
* Select *Operators* -> *Installed Operators* to verify that the *Open Data Hub Operator* is listed with *Succeeded* status.

.Next step
* link:{odhdocshome}/installing-open-data-hub/#installing-odh-components_installv2[Installing Open Data Hub components]

[role="_additional-resources"]
.Additional resources
* link:{odhdocshome}/installing-open-data-hub/#configuring-the-operator-logger_install[Configuring the {productname-short} Operator logger]