:_module-type: PROCEDURE

[id="introduction-bias-monitoring_{context}"]
== Introduction

We will take on the persona of a dev-ops engineer for a credit lender. Our data scientists have created two candidate neural networks to predict if a borrower will default on the loan they hold with us. Both models use the following information about the applicant to make their prediction:

[disc]
** Number of Children
** Total Income:
** Number of Total Family Members
** Is Male-Identifying?
** Owns Car?
** Owns Realty?
** Is Partnered?
** Is Employed?
** Lives with Parents?
** Age (in days)
** Length of Employment (in days)

What we want to verify is that neither of our models are biased over the gender field of 'Is Male-Identifying?`. To do this, we will monitor our models with Statistical Parity Difference (SPD) metric, which will tell us how the difference between how often male-identifying and non-male-identifying applicants are given favorable predictions (i.e., they are predicted to pay back their loans). Ideally, the SPD value would be 0, indicating that both groups have equal likelihood of getting a good outcome. However, an SPD value between -0.1 and 0.1 is also indicative of reasonable fairness, indicating that the two groups' rates of getting good outcomes only varies by +/-10%.

