:_module-type: PROCEDURE

[id="launching-a-workload-with-a-kueue-hardware-profile_{context}"]
= Launching a workload with a Kueue-enabled hardware profile

[role="_abstract"]
You can launch a workbench or deploy a model from the {productname-short} dashboard using a hardware profile that submits workloads to Kueue.

[IMPORTANT]
====
By default, hardware profiles, including Kueue-enabled profiles, are hidden in the dashboard navigation menu and user interface, while accelerator profiles remain visible. In addition, user interface components associated with the deprecated accelerator profiles functionality are still displayed. To show the *Settings -> Hardware profiles* option in the dashboard navigation menu, and the user interface components associated with hardware profiles and Kueue functionality, set the `disableHardwareProfiles` and `disableKueue` values to `false` in the `OdhDashboardConfig` custom resource (CR) in {openshift-platform}. 

ifdef::upstream[]
For more information about setting dashboard configuration options, see link:{odhdocshome}/managing-resources/#customizing-the-dashboard[Customizing the dashboard].
endif::[]
ifndef::upstream[]
For more information about setting dashboard configuration options, see link:{rhoaidocshome}{default-format-url}/managing_resources/customizing-the-dashboard[Customizing the dashboard].
endif::[]
====

.Prerequisites
* A hardware profile configured for Kueue-based scheduling is available.
* You are working in a data science project that is opted in to Kueue management.

.Procedure

ifdef::upstream[]
. From the {productname-short} dashboard, begin the process to create a workbench or deploy a model, as described in link:{odhdocshome}/working-on-data-science-projects/#creating-a-workbench-select-ide_projects[Creating a workbench and selecting an IDE] and  link:{odhdocshome}/serving-models/#deploying-models-using-the-single-model-serving-platform_serving-large-models[Enabling the single-model serving platform^].
endif::[]

ifndef::upstream[]
. From the {productname-short} dashboard, begin the process to create a workbench or deploy a model, as described in link:link:{rhoaidocshome}{default-format-url}/working_on_data_science_projects/using-project-workbenches_projects#creating-a-workbench-select-ide_projects[Creating a workbench and selecting an IDE] and link:{rhoaidocshome}{default-format-url}/serving_models/serving-large-models_serving-large-models#deploying-models-on-the-single-model-serving-platform_serving-large-models[Deploying models on the single-model serving platform].
endif::[]
. When configuring the resources for your workload, select a hardware profile that is configured for Kueue-based scheduling from the *Hardware profile* list.
. Complete the remaining configuration and launch the workload.

.Verification
* The workload is submitted to the `LocalQueue` specified in the hardware profile.
* The workload starts when the required cluster resources are available and admitted by the queue.
