:_module-type: PROCEDURE

[id="migrating-to-the-rhbok-operator_{context}"]
= Migrating to the {rhbok-productname} Operator

ifdef::upstream[]
The embedded Kueue component for managing distributed workloads is deprecated. You must migrate to the {rhbok-productname} Operator. You cannot install both the embedded Kueue and the {rhbok-productname} Operator on the same cluster because this creates conflicting controllers that manage the same resources.

{productname-short} does not automatically migrate existing workloads to {rhbok-productname}. Cluster administrators must manually migrate from the embedded Kueue to the {rhbok-productname} Operator to ensure workloads continue using queue management after upgrading.
endif::[]

ifndef::upstream[]
ifdef::self-managed[]
Starting with {productname-short} 2.24, the embedded Kueue component for managing distributed workloads is deprecated. 
endif::[]
ifdef::cloud-service[]
The embedded Kueue component for managing distributed workloads is deprecated. 
endif::[]
You must migrate to the {rhbok-productname} Operator. You cannot install both the embedded Kueue and the {rhbok-productname} Operator on the same cluster because this creates conflicting controllers that manage the same resources.

{productname-short} does not automatically migrate existing workloads to {rhbok-productname}. Cluster administrators must manually migrate from the embedded Kueue to the {rhbok-productname} Operator to ensure workloads continue using queue management after upgrading.
endif::[]

.Prerequisites
* You have cluster administrator privileges for your {openshift-platform} cluster.
* You are using {openshift-platform} 4.18 or later.
* You have installed and configured the *cert-manager Operator for {org-name} OpenShift* for your cluster.
* The embedded Kueue component is enabled (that is, the `spec.components.kueue.managementState` field in the `DataScienceCluster` object is set to `Managed`).

.Procedure
. Optional: When you migrate from the embedded Kueue to {rhbok-productname}, the {productname-short} Operator automatically moves your existing Kueue configuration from the `kueue-manager-config` ConfigMap to the `Kueue` custom resource (CR). 
+
To retain the `kueue-manager-config` ConfigMap, run the following command. Replace `<applications-namespace>` with your {productname-short} application namespace (the default is `pass:attributes[{dbd-config-default-namespace}]`):
+
[source,terminal]
----
oc annotate configmap kueue-manager-config -n <applications-namespace> opendatahub.io/managed=false
----

. Log in to the {openshift-platform} web console as a cluster administrator.

. Optional (recommended): To avoid potential configuration conflicts, uninstall the embedded Kueue component before installing {rhbok-productname}.
.. In the web console, click *Operators* → *Installed Operators* and then click the {productname-long} Operator.
.. Click the *Data Science Cluster* tab.  
.. Click the *default-dsc* object.  
.. Click the *YAML* tab.  
.. Set `spec.components.kueue.managementState` to `Removed` as shown:
+
[source,yaml]
----
spec:
  components:
    kueue:
      managementState: Removed
----
.. Click *Save*.  
.. Wait for the {productname-short} Operator to reconcile, and then verify that the embedded Kueue was removed:
* On the *Details* tab of the `default-dsc` object, check that the *KueueReady* condition has a *Status* of `False` and a *Reason* of `Removed`.  
* Go to *Workloads* → *Deployments*, select the project where {productname-short} is installed (for example, `redhat-ods-applications`), and confirm that Kueue-related deployments (for example, `kueue-controller-manager`) are no longer present.  

. Install the {rhbok-productname} Operator on your {openshift-platform} cluster:
.. Follow the steps in link:https://docs.redhat.com/en/documentation/red_hat_build_of_kueue/latest/html/installing_on_openshift_container_platform/install-kueue[Installing Red Hat build of Kueue].  
.. Verify that {rhbok-productname} is installed and running:
* Go to *Workloads* → *Pods*, select the project where {rhbok-productname} is installed (for example, `openshift-kueue-operator`), and confirm that the Kueue Operator pod is running.  
* Go to *Administration* → *CustomResourceDefinitions* and search for the `ClusterQueue` and `LocalQueue` CRDs to confirm that they are installed.  

. Activate the {rhbok-productname} Operator in {productname-short}:
.. In the web console, click *Operators* → *Installed Operators* and then click the {productname-long} Operator.  
.. Click the *Data Science Cluster* tab.  
.. Click the *default-dsc* object.  
.. Click the *YAML* tab.  
.. Set `spec.components.kueue.managementState` to `Unmanaged` as shown. 
+
You can optionally specify custom default names for the cluster queue and local queue. Replace `<example-cluster-queue>` and `<example-local-queue>` in the following example with your custom names. 
+
[source,yaml]
----
spec:
  components:
    kueue:
      managementState: Unmanaged
      defaultClusterQueueName: <example-cluster-queue>
      defaultLocalQueueName: <example-local-queue>
----
.. Click *Save*.  

. Enable Kueue management for existing projects by applying the `kueue.openshift.io/managed=true` label to each project namespace:
+
[source,terminal]
----
oc label namespace <project-namespace> kueue.openshift.io/managed=true --overwrite
----
Replace `<project-namespace>` with the name of your project.
+
[NOTE]
====
Kueue validation and queue enforcement apply only to workloads in namespaces with the `kueue.openshift.io/managed=true` label.
====

.Verification
* Verify that the embedded Kueue is removed.  
* Verify that the `DataScienceCluster` resource shows a healthy `Unmanaged` status for Kueue.  
* Verify that existing workloads in the queue continue to be processed by the new operator-managed Kueue controllers. Submit a new test workload to confirm functionality.  

.Next steps
* Configure quotas by creating and modifying `ResourceFlavor`, `ClusterQueue`, and `LocalQueue` objects. For details, see the link:https://docs.redhat.com/en/documentation/red_hat_build_of_kueue[{rhbok-productname}] documentation.
* Enable Kueue in the dashboard so that users can select Kueue-enabled options when creating workloads. This also enables Kueue management for all new projects created from the dashboard. See _Enabling Kueue in the dashboard_.
* Cluster administrators and {productname-short} administrators can create hardware profiles so that users can submit workloads from the {productname-short} dashboard. 
ifdef::upstream[]
See link:{odhdocshome}/working-with-accelerators/#working-with-hardware-profiles_accelerators[Working with hardware profiles].
endif::[]
ifndef::upstream[]
See link:{rhoaidocshome}{default-format-url}/working_with_accelerators/working-with-hardware-profiles_accelerators[Working with hardware profiles].
endif::[]



