:_module-type: PROCEDURE

[id="migrating-to-the-rhbok-operator_{context}"]
= Migrating to the {rhbok-productname} Operator

ifdef::self-managed[]
Starting with {productname-short} 2.24, the embedded Kueue component for managing distributed workloads is deprecated.
endif::[]
ifdef::upstream,cloud-service[]
The embedded Kueue component for managing distributed workloads is deprecated.
endif::[]

{productname-short} now uses the {rhbok-productname} Operator to provide enhanced workload scheduling for distributed training, workbench, and model serving workloads.

Check if your environment is using the embedded Kueue component by verifying the `spec.components.kueue.managementState` field in the `DataScienceCluster` custom resource. If the field is set to `Managed`, you must migrate to the {rhbok-productname} Operator before upgrading {productname-short} to avoid controller conflicts and ensure continued support for queue-based workloads. 

{productname-short} does not automatically migrate workloads, and you cannot install both the embedded Kueue and the {rhbok-productname} Operator on the same cluster.

.Prerequisites
* Your environment is currently using the embedded Kueue component. That is, the `spec.components.kueue.managementState` field in the `DataScienceCluster` custom resource is set to `Managed`.
+
[NOTE]
====
If `spec.components.kueue.managementState` is set to `Removed` or `Unmanaged`, you do not need to complete this migration.
====
* You have cluster administrator privileges for your {openshift-platform} cluster.
* You are using {openshift-platform} 4.18 or later.
* You have installed and configured the *cert-manager Operator for {org-name} OpenShift* for your cluster.

.Procedure
. Optional: When you migrate from the embedded Kueue to {rhbok-productname}, the {productname-short} Operator automatically moves your existing Kueue configuration from the `kueue-manager-config` ConfigMap to the `Kueue` custom resource (CR). 
+
If you want to keep the `kueue-manager-config` ConfigMap for reference, run the following command. Replace `<applications-namespace>` with your {productname-short} applications namespace. The default namespace is `pass:attributes[{dbd-config-default-namespace}]`.
+
[source,terminal]
----
$ oc annotate configmap kueue-manager-config -n <applications-namespace> opendatahub.io/managed=false
----

. Log in to the {openshift-platform} web console as a cluster administrator.

. Uninstall the embedded Kueue component to avoid potential configuration conflicts.
+
[NOTE]
====
If you need to keep workloads running without interruption, you can skip this step. However, skipping it is not recommended because it might cause temporary configuration issues during the {productname-short} upgrade.
====
.. In the web console, click *Operators* -> *Installed Operators* and then click the {productname-long} Operator.
.. Click the *Data Science Cluster* tab.  
.. Click the *default-dsc* object.  
.. Click the *YAML* tab.  
.. Set `spec.components.kueue.managementState` to `Removed` as shown:
+
[source,yaml]
----
spec:
  components:
    kueue:
      managementState: Removed
----
.. Click *Save*.  
.. Wait for the {productname-short} Operator to reconcile, and then verify that the embedded Kueue was removed:
* On the *Details* tab of the `default-dsc` object, check that the *KueueReady* condition has a *Status* of `False` and a *Reason* of `Removed`.  
* Go to *Workloads* -> *Deployments*, select the project where {productname-short} is installed (for example, `redhat-ods-applications`), and confirm that Kueue-related deployments (for example, `kueue-controller-manager`) are no longer present.  

. Install the {rhbok-productname} Operator on your {openshift-platform} cluster:
.. Follow the steps to install the {rhbok-productname} Operator, as described in the link:{rhbok-docs}[{rhbok-productname} documentation].
.. Go to *Operators* -> *Installed Operators* and confirm that the {rhbok-productname} Operator is listed with *Status* as *Succeeded*.

. Activate the {rhbok-productname} Operator in {productname-short}:
.. In the web console, click *Operators* -> *Installed Operators* and then click the {productname-long} Operator.  
.. Click the *Data Science Cluster* tab.  
.. Click the *default-dsc* object.  
.. Click the *YAML* tab.
.. Set `spec.components.kueue.managementState` to `Unmanaged`. You can either use the predefined names (`default`) for the default cluster queue and default local queue, or specify custom names, as shown in the following examples.  

* To use the predefined queue names, apply the following configuration:
+
[source,yaml]
----
spec:
  components:
    kueue:
      managementState: Unmanaged
----
* To specify custom queue names, apply the following configuration, replacing `<example-cluster-queue>` and `<example-local-queue>` with your custom values:
+
[source,yaml]
----
spec:
  components:
    kueue:
      managementState: Unmanaged
      defaultClusterQueueName: <example-cluster-queue>
      defaultLocalQueueName: <example-local-queue>
----
.. Click *Save*.  

. Enable Kueue management for existing projects by applying the `kueue.openshift.io/managed=true` label to each project namespace:
+
[source,terminal]
----
$ oc label namespace <project-namespace> kueue.openshift.io/managed=true --overwrite
----
Replace `<project-namespace>` with the name of your project.
+
[NOTE]
====
Kueue validation and queue enforcement apply only to workloads in namespaces labeled with `kueue.openshift.io/managed=true`.
====

.Verification
* Verify that the embedded Kueue component was removed.  
* Verify that the `DataScienceCluster` resource shows a healthy `Unmanaged` status for Kueue.  
* Verify that existing workloads in the queue continue to be processed by the {rhbok-productname} controllers. Submit a new test workload to confirm functionality.  

.Next steps
* Configure quotas by creating and modifying `ResourceFlavor`, `ClusterQueue`, and `LocalQueue` objects. For details, see the link:{rhbok-docs}[{rhbok-productname} documentation].
* Enable Kueue in the dashboard so that users can select Kueue-enabled options when creating workloads. When enabled, Kueue management is automatically applied to all new projects created from the dashboard.
ifdef::upstream[]
See link:{odhdocshome}/managing-odh/#enabling-kueue-in-the-dashboard_kueue[Enabling Kueue in the dashboard].
endif::[]
ifndef::upstream[]
See link:{rhoaidocshome}{default-format-url}/managing_openshift_ai/managing-workloads-with-kueue#enabling-kueue-in-the-dashboard_kueue[Enabling Kueue in the dashboard].
endif::[]
* Cluster administrators and {productname-short} administrators can create hardware profiles so that users can submit workloads from the {productname-short} dashboard.
ifdef::upstream[]
See link:{odhdocshome}/working-with-accelerators/#working-with-hardware-profiles_accelerators[Working with hardware profiles].
endif::[]
ifndef::upstream[]
See link:{rhoaidocshome}{default-format-url}/working_with_accelerators/working-with-hardware-profiles_accelerators[Working with hardware profiles].
endif::[]

