:_module-type: REFERENCE
//pv2hash: 3882aee9-15c2-4bb8-963b-7a6918f849a6

[id='notebook-images-for-data-scientists_{context}']
= Notebook images for data scientists

[role='_abstract']
{productname-long} contains Jupyter notebook images optimized with industry-leading tools and libraries required for your data science work. To provide a consistent, stable platform for your model development, all notebook images contain the same version of Python. Notebook images available on {productname-long} are pre-built and ready for you to use immediately after {productname-short} is installed or upgraded. 

ifdef::upstream[]
When a new version of a notebook image is released, the previous version remains available on the cluster. This gives you time to migrate your work to the latest version of the notebook image. Legacy notebook image versions, that is, not the two most recent versions, might still be available for selection. Legacy image versions include a label that indicates that the image is out-of-date. To use the latest package versions, use the most recently added notebook image.
endif::[]

ifndef::upstream[]
Notebook images are supported for a minimum of one year. Major updates to pre-configured notebook images occur about every six months. Therefore, two supported notebook image versions are typically available at any given time. You can use this support period to update your code to use components from the latest available notebook image. Legacy notebook image versions, that is, not the two most recent versions, might still be available for selection. Legacy image versions include a label that indicates the image is out-of-date. To use the latest package versions, {org-name} recommends that you use the most recently added notebook image. If necessary, you can still access older notebook images from the registry, even if they are no longer supported. You can then add the older notebook images as custom notebook images to cater for your project's specific requirements.
endif::[]

ifdef::cloud-service[]
See the table in link:{rhoaidocshome}{default-format-url}/getting_started_with_{url-productname-long}/creating-a-project-workbench_get-started#options-for-notebook-server-environments_get-started[Options for notebook server environments] for a complete list of packages and versions included in these images.
endif::[]
ifdef::self-managed[]
See the table in link:{rhoaidocshome}{default-format-url}/getting_started_with_{url-productname-long}/creating-a-project-workbench_get-started#options-for-notebook-server-environments_get-started[Options for notebook server environments] for a complete list of packages and versions included in these images.
endif::[]

{productname-long} contains the following notebook images that are available by default.

ifndef::upstream[]
[IMPORTANT]
====
Notebook images denoted with `(Technology Preview)` in this table are not supported with {org-name} production service level agreements (SLAs) and might not be functionally complete. {org-name} does not recommend using Technology Preview features in production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process. For more information about the support scope of {org-name} Technology Preview features, see Technology Preview Features Support Scope.
====
endif::[]

.Default notebook images
[cols="1,5"]
|===
| Image name | Description

| CUDA
| If you are working with compute-intensive data science models that require GPU support, use the Compute Unified Device Architecture (CUDA) notebook image to gain access to the NVIDIA CUDA Toolkit. Using this toolkit, you can optimize your work using GPU-accelerated libraries and optimization tools.

| Standard Data Science
| Use the Standard Data Science notebook image for models that do not require TensorFlow or PyTorch. This image contains commonly used libraries to assist you in developing your machine learning models.
// RHODS-1598 - or CUDA or GPU support

| TensorFlow
| TensorFlow is an open source platform for machine learning. With TensorFlow, you can build, train and deploy your machine learning models. TensorFlow contains advanced data visualization features, such as computational graph visualizations. It also allows you to easily monitor and track the progress of your models.

| PyTorch
| PyTorch is an open source machine learning library optimized for deep learning. If you are working with computer vision or natural language processing models, use the Pytorch notebook image.
// RHODS-1598 -  using GPUs and CPUs

| Minimal Python
| If you do not require advanced machine learning features, or additional resources for compute-intensive data science work, you can use the Minimal Python image to develop your models.

| TrustyAI
| Use the TrustyAI notebook image to leverage your data science work with model explainability, tracing, and accountability, and runtime monitoring.

| HabanaAI
| The HabanaAI notebook image optimizes high-performance deep learning (DL) with Habana Gaudi devices. Habana Gaudi devices accelerate DL training workloads and maximize training throughput and efficiency.

ifndef::upstream[]
| code-server (Technology Preview)
endif::[]
ifdef::upstream[]
| code-server 
endif::[]
a| With the code-server notebook image, you can customize your notebook environment to meet your needs using a variety of extensions to add new languages, themes, debuggers, and connect to additional services. Enhance the efficiency of your data science work with syntax highlighting, auto-indentation, and bracket matching, as well as an automatic task runner for seamless automation. See link:https://github.com/coder/code-server[code-server in GitHub] for more information. +

NOTE: Elyra-based pipelines are not available with the code-server notebook image.

ifdef::upstream[]
| RStudio Server 
a| Use the RStudio Server notebook image to access the RStudio IDE, an integrated development environment for R, a programming language for statistical computing and graphics.
See link:https://posit.co/products/open-source/rstudio-server/[the RStudio Server site] for more information. +
endif::[]
ifndef::upstream[]
ifdef::cloud-service[]
| RStudio Server (Technology preview)
a| Use the RStudio Server notebook image to access the RStudio IDE, an integrated development environment for R, a programming language for statistical computing and graphics.
See link:https://posit.co/products/open-source/rstudio-server/[the RStudio Server site] for more information. +

To use the *RStudio Server* notebook image, you must first build it by creating a secret and triggering the BuildConfig, and then enable it in the {productname-short} UI by editing the `rstudio-rhel9` image stream. See link:{rhoaidocshome}{default-format-url}/getting_started_with_{url-productname-long}/configuring-your-ide_get-started#building_the_rstudio_server_notebook_images[Building the RStudio Server notebook images] for more information.

[IMPORTANT] 
====
*Disclaimer:* +
{org-name} supports managing workbenches in {productname-short}. However, {org-name} does not provide support for the RStudio software. RStudio Server is available through link:rstudio.org[https://rstudio.org/] and is subject to their licensing terms. Review their licensing terms before you use this sample workbench.
====
endif::[]
endif::[]

ifdef::upstream[]
| CUDA - RStudio Server
a| Use the CUDA - RStudio Server notebook image to access the RStudio IDE and NVIDIA CUDA Toolkit. RStudio is an integrated development environment for R, a programming language for statistical computing and graphics. With the NVIDIA CUDA toolkit, you can optimize your work using GPU-accelerated libraries and optimization tools.
See link:https://posit.co/products/open-source/rstudio-server/[the RStudio Server site] for more information. +
endif::[]

ifndef::upstream[]
ifdef::cloud-service[]
| CUDA - RStudio Server (Technology preview)
a| Use the CUDA - RStudio Server notebook image to access the RStudio IDE and NVIDIA CUDA Toolkit. RStudio is an integrated development environment for R, a programming language for statistical computing and graphics. With the NVIDIA CUDA toolkit, you can optimize your work using GPU-accelerated libraries and optimization tools.
See link:https://posit.co/products/open-source/rstudio-server/[the RStudio Server site] for more information. +

To use the *CUDA - RStudio Server* notebook image, you must first build it by creating a secret and triggering the BuildConfig, and then enable it in the {productname-short} UI by editing the `cuda-rstudio-rhel9` image stream. See link:{rhoaidocshome}{default-format-url}/getting_started_with_{url-productname-long}/configuring-your-ide_get-started#building_the_rstudio_server_notebook_images[Building the RStudio Server notebook images] for more information.

[IMPORTANT] 
====
*Disclaimer:* +
{org-name} supports managing workbenches in {productname-short}. However, {org-name} does not provide support for the RStudio software. RStudio Server is available through link:rstudio.org[https://rstudio.org/] and is subject to their licensing terms. Review their licensing terms before you use this sample workbench. +

The *CUDA - RStudio Server* notebook image contains NVIDIA CUDA technology. CUDA licensing information is available at link:https://docs.nvidia.com/cuda/[https://docs.nvidia.com/cuda/]. Review their licensing terms before you use this sample workbench.
====
endif::[]
endif::[]
|===

ifndef::upstream[]
[role="_additional-resources"]
.Additional resources
* link:{rhoaidocshome}{default-format-url}/working_on_data_science_projects/working-on-data-science-projects_nb-server#installing-python-packages-on-your-notebook-server_nb-server[Installing Python packages on your notebook server]
* link:{rhoaidocshome}{default-format-url}/getting_started_with_{url-productname-long}/creating-a-project-workbench_get-started#options-for-notebook-server-environments_get-started[Options for notebook server environments]
endif::[]
