:_module-type: REFERENCE

[id='options-for-notebook-server-environments_{context}']
= Options for notebook server environments

[role='_abstract']
When you start Jupyter for the first time, or after stopping your notebook server, you must select server options in the *Start a notebook server* wizard so that the software and variables that you expect are available on your server. This section explains the options available in the *Start a notebook server* wizard in detail.

The *Start a notebook server* page is divided into several sections:

Notebook image:: Specifies the container image that your notebook server is based on. Different notebook images have different packages installed by default. See xref:notebook-image-options_{context}[Notebook image options] for details.

Deployment size:: Specifies the compute resources available on your notebook server.
+
*Container size* controls the number of CPUs, the amount of memory, and the minimum and maximum request capacity of the container.

//See xref:container-size-options[Container size options] for details.
// GPU content was re-added during the 1.5 release work. It was then delayed to 1.6 so commenting this out.
//+
//*Number of GPUs* specifies the number of graphics processing units attached to the container.

Environment variables:: Specifies the name and value of variables to be set on the notebook server. Setting environment variables during server startup means that you do not need to define them in the body of your notebooks, or with the Jupyter command line interface. See xref:recommended-environment-variables_{context}[Recommended environment variables] for a list of reserved variable names for each item in the *Environment variables* list.

[id="notebook-image-options_{context}"]

.Notebook image options
[cols="1,3",header]
|===
| Image name | Preinstalled packages

| CUDA
a| * Python 3.8
* CUDA 11
* JupyterLab 3.2
* Notebook 6.4

| Minimal Python (default)
a| * Python 3.8
* JupyterLab 3.2
* Notebook 6.4

| PyTorch
a| * Python 3.8
* JupyterLab 3.2
* Notebook 6.4
* PyTorch 1.8
* CUDA 11
* TensorBoard 1.15
* Boto3 1.17
* Kafka-Python 2.0
* Matplotlib 3.4
* Numpy 1.19
* Pandas 1.2
* Scikit-learn 0.24
* SciPy 1.6

| Standard Data Science
a| * Python 3.8
* JupyterLab 3.2
* Notebook 6.4
* Boto3 1.17
* Kafka-Python 2.0
* Matplotlib 3.4
* Pandas 1.2
* Numpy 1.19
* Scikit-learn 0.24
* SciPy 1.6

| TensorFlow
a| * Python 3.8
* JupyterLab 3.2
* Notebook 6.4
* TensorFlow 2.7
* TensorBoard 2.6
* CUDA 11
* Boto3 1.17
* Kafka-Python 2.0
* Matplotlib 3.4
* Numpy 1.19
* Pandas 1.2
* Scikit-learn 0.24
* SciPy 1.6

|===


[id="recommended-environment-variables_{context}"]

.Recommended environment variables
[cols="1,4",header]
|===
| Environment variable option | Recommended variable names

| AWS
a| * `AWS_ACCESS_KEY_ID` specifies your Access Key ID for Amazon Web Services.
* `AWS_SECRET_ACCESS_KEY` specifies your Secret access key for the account specified in `AWS_ACCESS_KEY_ID`.

|===

ifndef::upstream[]
[role="_additional-resources"]
.Additional resources
* link:{rhodsdocshome}{default-format-url}/getting_started_with_{url-productname-long}/creating-a-project-workbench_get-started#launching-jupyter-and-starting-a-notebook-server_get-started[Launching Jupyter and starting a notebook server]
endif::[]
