:_module-type: CONCEPT

[id='overview-of-model-registries_{context}']
= Overview of model registries and model catalog

[role='_abstract']

A model registry acts as a central repository for administrators and data scientists to register, version, and manage the lifecycle of AI models before configuring them for deployment. A model registry is a key component for AI model governance.

The model catalog feature provides a curated library where data scientists can discover, compare, and evaluate available generative AI models to find the best fit for their use cases.

== Model registry

A model registry is an important component in the lifecycle of an artificial intelligence/machine learning (AI/ML) model, and is a vital part of any machine learning operations (MLOps) platform or workflow. A model registry acts as a central repository, storing metadata related to machine learning models from development to deployment. This metadata ranges from high-level information like the deployment environment and project, to specific details like training hyperparameters, performance metrics, and deployment events. 

A model registry acts as a bridge between model experimentation and serving, offering a secure, collaborative metadata store interface for stakeholders in the ML lifecycle. Model registries provide a structured and organized way to store, share, version, deploy, and track models. 

ifdef::upstream[]
{productname-short} administrators can create model registries in {productname-short} and grant model registry access to the data scientists that will work with them. For more information, see link:{odhdocshome}/working-with-model-registries/#creating-a-model-registry_model-registry[Creating a model registry] and link:{odhdocshome}/working-with-model-registries/#managing-model-registry-permissions_model-registry[Managing model registry permissions].

Data scientists with access to a model registry can store, share, version, deploy, and track models by using model registry features. For more information, see link:{odhdocshome}/working-with-model-registries/#working-with-model-registries_model-registry[Working with model registries]. 
endif::[]

ifndef::upstream[]
{productname-short} administrators can create model registries in {productname-short} and grant model registry access to the data scientists that will work with them. For more information, see link:{rhoaidocshome}{default-format-url}/managing_model_registries[Managing model registries].

Data scientists with access to a model registry can store, share, version, deploy, and track models by using the model registry feature. For more information, see link:{rhoaidocshome}{default-format-url}/working_with_model_registries[Working with model registries]. 
endif::[]

== Model catalog

Data scientists can use the model catalog to discover the models that are available and ready for their organization to register, deploy, and customize. 

The model catalog provides models from different providers that data scientists can search and discover before they register models in a model registry and deploy them to a model serving runtime. Data science administrators can configure the available repository sources for models displayed in the model catalog. 

{productname-short} provides a default model catalog, which includes models from providers such as {org-name}, IBM, Meta, Nvidia, Mistral AI, and Google, and includes teacher and judge models for the LAB-tuning workflow. 
ifdef::upstream[]
For more information about using the LAB-tuning workflow, see link:{odhdocshome}/customizing-models-with-lab-tuning/[Customizing models with LAB-tuning].
endif::[]
ifndef::upstream[]
For more information about using the LAB-tuning workflow, see link:{rhoaidocshome}{default-format-url}/customizing_models_with_lab-tuning[Customizing models with LAB-tuning].
endif::[]

ifdef::upstream[]
For more information about how data scientists can use the model catalog, see link:{odhdocshome}/working-with-model-registries/#viewing-models-in-the-model-catalog_model-registry[Working with the model catalog].
endif::[]

ifndef::upstream[]
For more information about how data scientists can use the model catalog, see link:{rhoaidocshome}{default-format-url}/working_with_the_model_catalog[Working with the model catalog].
endif::[]


//[role="_additional-resources"]
//.Additional resources
//*