:_module-type: CONCEPT

[id='overview-of-feast_{context}']
= Overview of using {component} for working with machine learning features

[role='_abstract']

A machine learning feature is a measurable property or attribute within a dataset that a machine learning model can analyze to learn patterns and make decisions. Example of features include a customer's purchase history, demographic data like age and location, weather conditions, and financial market data; all of which can be used to train models for tasks like personalized product recommendations, fraud detection, and predictive maintenance.

{component} is an OpenShift AI component that provides a centralized repository that stores, manages, and serves machine learning features for both training and inference purposes. 

{component} provides consistency in model training and inference, promotes collaboration and usability across multiple projects, monitors lineage and versioning of models for data drifts, leaks, and training skews, and seamlessly integrates with other MLOps tools.
