:_module-type: CONCEPT

[id='overview-of-model-registries_{context}']
= Overview of model registries

[role='_abstract']

ifndef::upstream[]
[IMPORTANT]
====
ifdef::self-managed[]
Model registry is currently available in {productname-long} {vernum} as a Technology Preview feature.
endif::[]
ifdef::cloud-service[]
Model registry is currently available in {productname-long} as a Technology Preview feature.
endif::[]
Technology Preview features are not supported with {org-name} production service level agreements (SLAs) and might not be functionally complete.
{org-name} does not recommend using them in production.
These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information about the support scope of {org-name} Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====
endif::[]


A model registry is an important component in the lifecycle of an artificial intelligence/machine learning (AI/ML) model, and a vital part of any machine learning operations (MLOps) platform or ML workflow. A model registry acts as a central repository, holding metadata related to machine learning models from inception to deployment. This metadata ranges from high-level information like the deployment environment and project origins, to intricate details like training hyperparameters, performance metrics, and deployment events. A model registry acts as a bridge between model experimentation and serving, offering a secure, collaborative metadata store interface for stakeholders of the ML lifecycle.

Model registries provide a structured and organized way to store, share, version, deploy, and track models. 

ifndef::upstream[]
To use model registries in {productname-short}, an OpenShift cluster administrator must configure the model registry component in OpenShift. For more information, see link:{rhoaidocshome}{default-format-url}/configuring_the_model_registry_component/configuring-the-model-registry-component_model-registry-config[Configuring the model registry component].

After the model registry component is configured, an {productname-short} administrator can create model registries in {productname-short} and grant model registry access to the data scientists that will work with them. For more information, see link:{rhoaidocshome}{default-format-url}/managing_model_registries/index[Managing model registries].

Data scientists with access to a model registry can store, share, version, deploy, and track models using the model registry feature. For more information, see link:{rhoaidocshome}{default-format-url}/working_with_model_registries/index[Working with model registries]. 
endif::[]

//[role="_additional-resources"]
//.Additional resources
//*