:_module-type: CONCEPT

[id='overview-of-pipeline-experiments_{context}']
= Overview of pipeline experiments

[role='_abstract']
A pipeline experiment is a logical grouping of pipeline runs. As data scientist, you can use {productname-short} to define, manage, and track pipeline experiments. You can view a record of previously created and archived pipeline experiments from the *Experiments* page in the {productname-short} user interface.

Pipeline experiments enable you to introduce repeatability to your pipeline configuration in {productname-short}. Pipeline experiments contain pipeline runs, including recurring runs. This allows you to try different configurations of your pipelines. 

When you work with data science pipelines, it is important to monitor and record your pipeline experiments to track the performance of your data science pipelines. You can compare the results of up to 10 pipeline runs at one time, and view available parameter, scalar metric, confusion matrix, and receiver operating characteristic (ROC) curve data for all selected runs.
  
When you execute a pipeline run within a pipeline experiment, you can view its pipeline artifacts from the {productname-short} dashboard. Pipeline artifacts can help you evaluate the performance of your pipeline runs and make it easier to understand your pipeline components. Pipeline artifacts can range from plain text data or detailed, interactive data visualizations.  

//[role="_additional-resources"]
//.Additional resources
//*
