:_module-type: CONCEPT

[id='overview-of-upgrading-odh_{context}']
= Overview of upgrading {productname-short}

[role='_abstract']
As a cluster administrator, you can configure either automatic or manual upgrades for the {productname-short} Operator.

* If you configure automatic upgrades, when a new version of the Open Data Hub Operator is available, Operator Lifecycle Manager (OLM) automatically upgrades the running instance of your Operator without human intervention.

* If you configure manual upgrades, when a new version of the {productname-short} Operator is available, OLM creates an update request.
+
A cluster administrator must manually approve the update request to update the Operator to the new version.
See link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/operators/administrator-tasks#olm-approving-pending-upgrade_olm-upgrading-operators[Manually approving a pending Operator upgrade] for more information about approving a pending Operator upgrade.

* By default, the {productname-short} Operator follows a sequential update process. This means that if there are several minor versions between the current version and the version that you plan to upgrade to, Operator Lifecycle Manager (OLM) upgrades the Operator to each of the minor versions before it upgrades it to the final, target version. If you configure automatic upgrades, OLM automatically upgrades the Operator to the latest available version, without human intervention. If you configure manual upgrades, a cluster administrator must manually approve each sequential update between the current version and the final, target version.

* When you upgrade {productname-short}, the upgrade process automatically uses the values of the previous version's `DataScienceCluster` object. After the upgrade, you should inspect the default `DataScienceCluster` object to check and optionally update the `managementState` status of the components.
+
[NOTE]
====
New components are not automatically added to the `DataScienceCluster` object during upgrade. If you want to use a new component, you must manually edit the `DataScienceCluster` object to add the component entry.
====

* For any components that you update, {productname-short} initiates a rollout that affects all pods to use the updated image.

* Workbench images are integrated into the image stream during the upgrade and subsequently appear in the {productname-short} dashboard. 
+
NOTE: Workbench images are constructed externally; they are prebuilt images that undergo quarterly changes and they do not change with every {productname-short} upgrade.
