:_module-type: CONCEPT

[id='overview-of-pipeline-experiments_{context}']
= Overview of pipeline experiments

[role='_abstract']
A pipeline experiment is a workspace where you can try different configurations of your pipelines. You can use experiments to organize your runs into logical groups. As a data scientist, you can use {productname-short} to define, manage, and track pipeline experiments. You can view a record of previously created and archived experiments from the *Experiments* page in the {productname-short} user interface. Pipeline experiments contain pipeline runs, including recurring runs. This allows you to try different configurations of your pipelines. 

When you work with data science pipelines, it is important to monitor and record your pipeline experiments to track the performance of your data science pipelines. You can compare the results of up to 10 pipeline runs at one time, and view available parameter, scalar metric, confusion matrix, and receiver operating characteristic (ROC) curve data for all selected runs.
  
You can view artifacts for an executed pipeline run from the {productname-short} dashboard. Pipeline artifacts can help you to evaluate the performance of your pipeline runs and make it easier to understand your pipeline components. Pipeline artifacts can range from plain text data to detailed, interactive data visualizations.  

//[role="_additional-resources"]
//.Additional resources
//*
