:_module-type: CONCEPT

[id='overview-of-component-resource-customization_{context}']
= Overview of component resource customization

[role='_abstract']
You can customize deployment resources that are related to the {productname-long} Operator, for example, CPU and memory limits and requests. For resource customizations to persist without being overwritten by the Operator, the `opendatahub.io/managed: true` annotation must not be present in the YAML file for the component deployment. This annotation is absent by default.

ifdef::upstream[]
The following table shows the deployment names for each component in the `openshift-operators` namespace:
endif::[]
ifndef::upstream[]
The following table shows the deployment names for each component in the `redhat-ods-applications` namespace:
endif::[]
|===
| Component | Deployment names 

| codeflare | codeflare-operator-manager 
| kserve 
a| * kserve-controller-manager 
* odh-model-controller
| trustyai | trustyai-service-operator-controller-manager
| ray | kuberay-operator 
| kueue | kueue-controller-manager
| workbenches
a| * notebook-controller-deployment 
* odh-notebook-controller-manager
| dashboard | rhods-dashboard
| modelmeshserving
a| * modelmesh-controller 
* odh-model-controller
| datasciencepipelines | data-science-pipelines-operator-controller-manager
| trainingoperator | kubeflow-training-operator
|===