:_module-type: CONCEPT

[id='overview-of-machine-learning-features_{context}']
= Overview of machine learning features 

In machine learning, a _feature_, also referred to as a field, is an individual measurable property. A feature is used as an input signal to a predictive model. For example, if a bank's loan department is trying to predict whether an applicant should be approved for a loan, a useful feature might be whether they have filed for bankruptcy in the past or how much credit card debt they currently carry.

.A feature represents a column in a data table
|===
| customer_id | avg_cc_balance | credit_score | bankruptcy 
| 1005 | 500.00 | 730 | 0 
| 982 | 20000.00 | 570 | 2
| 1001 | 1400.00 | 600 | 0
|===

Features are prepared data that help machine learning models understand patterns in the world. Feature engineering is the process of selecting, manipulating, and transforming raw data into features that can be used in supervised learning. As shown in the table, a feature refers to an entire column in a dataset, for example, *credit_score*. A feature value refers to a single value in a feature column, such as *730*.
