:_module-type: CONCEPT

[id='overview-of-monitoring-your-ai-systems_{context}']
= Overview of monitoring your AI systems

[role='_abstract']

Use TrustyAI to monitor your models for data drift and bias. 

ifdef::upstream[]
Learn how your model makes its predictions and decisions using explainers from TrustyAI to provide saliency explanations for model inferences.
endif::[]

These tools help ensure that your data science and machine learning models are transparent, fair, and reliable. 

Configure and set up TrustyAI for your project, and then perform the following checks:

* *Bias:* Check for unfair patterns or biases in data and model predictions to ensure your model's decisions are unbiased.

* *Data drift:* Detect changes in input data distributions over time by comparing the latest real-world data to the original training data. Comparing the data identifies shifts or deviations that could impact model performance, ensuring that the model remains accurate and reliable.

ifdef::upstream[]
* *Explainability:* Understand how your model makes predictions and decisions.
endif::[]
