:_module-type: CONCEPT

[id='overview-of-component-resource-customization_{context}']
= Overview of component resource customization

[role='_abstract']
You can customize deployment resources that are related to the {productname-long} Operator, for example, CPU and memory limits and requests. For resource customizations to persist without being overwritten by the Operator, the `opendatahub.io/managed: true` annotation must not be present in the YAML file for the component deployment. This annotation is absent by default.

ifdef::upstream[]
The following table shows the deployment names for each component in the `opendatahub` namespace:
endif::[]
ifndef::upstream[]
The following table shows the deployment names for each component in the `redhat-ods-applications` namespace:
endif::[]

|===
| Component | Deployment names 

| CodeFlare | codeflare-operator-manager 
| KServe 
a| * kserve-controller-manager 
* odh-model-controller
| TrustyAI | trustyai-service-operator-controller-manager
| Ray | kuberay-operator 
| Kueue | kueue-controller-manager
| Workbenches
a| * notebook-controller-deployment 
* odh-notebook-controller-manager
ifdef::upstream[]
| Dashboard | odh-dashboard
endif::[]
ifndef::upstream[]
| Dashboard | rhods-dashboard
endif::[]
| Model serving
a| * modelmesh-controller 
* odh-model-controller
ifdef::upstream[]
| Model registry | model-registry-operator-controller-manager
endif::[]
| Data science pipelines | data-science-pipelines-operator-controller-manager
| Training Operator | kubeflow-training-operator
|===
