:_module-type: CONCEPT

[id="playground-overview_{context}"]
= Playground overview

[role="_abstract"]

ifndef::upstream[]
[IMPORTANT]
====
ifdef::self-managed[]
This feature is currently available in {productname-long} {vernum} as a Technology Preview feature.
endif::[]
ifdef::cloud-service[]
This feature is currently available in {productname-long} as a Technology Preview feature.
endif::[]
Technology Preview features are not supported with {org-name} production service level agreements (SLAs) and might not be functionally complete.
{org-name} does not recommend using them in production.
These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information about the support scope of {org-name} Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====
endif::[]

The Generative AI (GenAI) playground is an interactive environment within the {productname-long} dashboard where you can prototype and evaluate foundation models, custom models, and Model Control Protocol (MCP) servers before you use them in an application. 

You can test different configurations, including Retrieval-Augmented Generation (RAG), to determine the right assets for your use-case. After you find an effective configuration,  you can retrieve a Python template that serves as a starting point for building and iterating in a local development environment

[NOTE]
====
Important: The playground is a stateless environment. If you refresh your browser or end your session, all chat history and parameter settings will be lost.
====

== Core capabilities

The playground includes a core set of features:

* *Interact with models:* You can chat with both foundational and custom-deployed models.
* *Test with RAG:* You can test prompt engineering with document-based Retrieval-Augmented Generation (RAG) by uploading your own documents for the model to use as context.
* *Integrate MCP servers:* You can authorize and interact with approved Model Control Protocol (MCP) servers and their tools.
* *Export configurations:* You can export prompts and parameter configurations as runnable code (Python) to iterate on them in your local IDE. 
