:_module-type: CONCEPT

[id="about-the-gen-ai-playground_{context}"]
= About the Generative AI (GenAI) playground

[role="_abstract"]
The Generating AI (GenAI) playground is an interactive environment within the {productname-long} dashboard where you can prototype and evaluate foundation models, custom models, and Model Control Plane (MCP) servers before you use them in an application. 

You can test different configurations, including Retrieval-Augmented Generation (RAG), to determine the right assets for your use-case. After you find an effective configuration,  you can retrieve a Python template that serves as a starting point for building and iterating in a local development environment

[NOTE]
====
Important: The playground is a stateless environment. If you refresh your browser or end your session, all chat history and parameter settings will be lost.
====

== Core capabilities

The playground includes a core set of features:

* *Interact with models:* You can chat with both foundational and custom-deployed models.
* *Test with RAG:* You can test prompt engineering with document-based Retrieval-Augmented Generation (RAG) by uploading your own documents for the model to use as context.
* *Integrate MCP servers:* You can authorize and interact with approved Model Control Plane (MCP) servers and their tools.
* *Export configurations:* You can export prompts and parameter configurations as runnable code (Python) to iterate on them in your local IDE. 
