:_module-type: PROCEDURE

[id="preventing-users-from-adding-applications-to-the-dashboard_{context}"]
= Preventing users from adding applications to the dashboard

[role='_abstract']
By default, {productname-short} administrators can add applications to the {productname-short} dashboard *Application → Enabled* page.

As an {productname-short} administrator, you can disable the ability for {productname-short} administrators to add applications to the dashboard.

ifndef::upstream[]
[NOTE]
====
The *Start basic workbench* tile is enabled by default. To disable it, see link:{rhoaidocshome}{default-format-url}/managing_openshift_ai/managing-applications-that-show-in-the-dashboard#hiding-the-default-basic-workbench-application_dashboard[Hiding the default basic workbench application].
====
endif::[]
ifdef::upstream[]
[NOTE]
====
The *Start basic workbench* tile is enabled by default. To disable it, see link:{odhdocshome}/managing-odh/#hiding-the-default-basic-workbench-application_dashboard[Hiding the default basic workbench application].
====
endif::[]

.Prerequisite

* You have {productname-short} administrator privileges.

.Procedure

. Log in to the {openshift-platform} console as an {productname-short} administrator.
. Open the dashboard configuration file:
.. In the *Administrator* perspective, click *Home* -> *API Explorer*.
.. In the search bar, enter `OdhDashboardConfig` to filter by kind.
.. Click the `OdhDashboardConfig` custom resource (CR) to open the resource details page.
.. From the *Project* list, select the {productname-short} application namespace; the default is `pass:attributes[{dbd-config-default-namespace}]`.
.. Click the *Instances* tab.
.. Click the `odh-dashboard-config` instance to open the details page.
.. Click the *YAML* tab. 
. In the `spec.dashboardConfig` section, set the value of `enablement` to `false` to disable the ability for dashboard users to add applications to the dashboard.
. Click *Save* to apply your changes and then click *Reload* to make sure that your changes are synced to the cluster.

.Verification

* Open the {productname-short} dashboard *Application → Enabled* page. 
