:_module-type: REFERENCE

[id='ref-dashboard-configuration-options_{context}']
= Dashboard configuration options

[role='_abstract']
The {productname-short} dashboard includes a set of core features enabled by default that are designed to work for most scenarios. 
{productname-short} administrators can configure the {productname-short} dashboard from the `OdhDashboardConfig` custom resource (CR) in {openshift-platform}. 


If a dashboard configuration option is not included in the `OdhDashboardConfig` CR, the default value is used.
To change the default behavior for such options, edit the `OdhDashboardConfig` CR to add the missing entry to the `spec.dashboardConfig` section, and set the preferred value:

* To show the feature, set the value to `false`
* To hide the feature, set the value to `true`

ifdef::upstream[]
For more information about setting dashboard configuration options, see link:{odhdocshome}/managing-resources/#editing-the-dashboard-configuration_dashboard[Editing the dashboard configuration].
endif::[]
ifndef::upstream[]
For more information about setting dashboard configuration options, see link:{rhoaidocshome}{default-format-url}/managing_resources/customizing-the-dashboard#editing-the-dashboard-configuration_dashboard[Editing the dashboard configuration].
endif::[]

ifndef::upstream[]
[IMPORTANT]
====
Features denoted with `(Technology Preview)` in this table are not supported with {org-name} production service level agreements (SLAs) and might not be functionally complete. 
{org-name} does not recommend using Technology Preview features in production. 
These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process. 
For more information about the support scope of {org-name} Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====
endif::[]


.Dashboard feature configuration options
[cols="28%,7%,65%", options="header"]
|===
| Feature configuration option | Default | Description
| `spec.dashboardConfig.` +
`disableAcceleratorProfiles` | `false`| Shows the *Settings → Accelerator profiles* menu item in the dashboard navigation menu. To hide this menu item, set the value to `true`.

*Note:* The `spec.dashboardConfig.disableAcceleratorProfiles` option is superseded by the `spec.dashboardConfig.disableHardwareProfiles` option.
If both options are set to `false`, the `disableHardwareProfiles` option overrides the `disableAcceleratorProfiles` option, and the *Settings → Hardware profiles* menu item is shown in the dashboard navigation menu.
| `spec.dashboardConfig.` +
`disableAdminConnectionTypes` | `false` | Shows the *Settings → Connection types* menu item in the dashboard navigation menu. To hide this menu item, set the value to `true`.
| `spec.dashboardConfig.` +
`disableBYONImageStream` | `false` | Shows the *Settings → Workbench images* menu item in the dashboard navigation menu. To hide this menu item, set the value to `true`.
| `spec.dashboardConfig.` +
`disableClusterManager` | `false` | Shows the *Settings → Cluster settings* menu item in the dashboard navigation menu. To hide this menu item, set the value to `true`.
| `spec.dashboardConfig.` +
`disableCustomServingRuntimes` | `false` | Shows the *Settings → Serving runtimes* menu item in the dashboard navigation menu. To hide this menu item, set the value to `true`. 
| `spec.dashboardConfig.` +
`disableDistributedWorkloads` | `false` | Shows the *Distributed workloads* menu item in the dashboard navigation menu. To hide this menu item, set the value to `true`.
| `spec.dashboardConfig.` +
`disableFeatureStore` | `false` | Shows the *Feature store* menu item in the dashboard navigation menu. To hide this menu item, set the value to `true`.
| `spec.dashboardConfig.` +
`disableFineTuning` 

(Technology Preview) | `true` | Hides the *Models → Model customization* menu item in the dashboard navigation menu, and the *LAB-tune* menu item and button for registered model versions. 
To show these items, set the value to `false`.

LAB-tuning is a Technology Preview feature in this {productname-short} release.
| `spec.dashboardConfig.` +
`disableKueue` | `true` | Hides Kueue-related options in the dashboard. Set the value to `false` to enable Kueue in the dashboard, which allows users to select Kueue-enabled hardware profiles. When `false`, new projects created from the dashboard are automatically configured for Kueue management with the required label and a default local queue.

| `spec.dashboardConfig.` +
`disableLMEval` 

(Technology Preview) | `true` | Hides the *Model* → *Model evaluation runs* menu item in the dashboard navigation menu. To show these items, set the value to `false`.

Model evaluation is a Technology Preview feature in this {productname-short} release.
| `spec.dashboardConfig.` +
`disableHardwareProfiles` 

(Technology Preview) | `true` | Hides the *Settings → Hardware profiles* menu item in the dashboard navigation menu, and shows the *Settings → Accelerator profiles* menu item if the `spec.dashboardConfig.disableAcceleratorProfiles` value is set to `false`. 
To show the *Settings → Hardware profiles* menu item in the dashboard navigation menu, set the value to `false`.

If both options are set to `false`, the `disableHardwareProfiles` option overrides the `disableAcceleratorProfiles` option, and the *Settings → Hardware profiles* menu item is shown in the dashboard navigation menu.

Hardware profiles is a Technology Preview feature in this {productname-short} release.
| `spec.dashboardConfig.` +
`disableHome` | `false` | Shows the *Home* menu item in the dashboard navigation menu. To hide this menu item, set the value to `true`.
| `spec.dashboardConfig.` +
`disableInfo` | `false` | On the *Applications → Explore* page, when a user clicks on an application tile, an information panel opens with more details about the application. To disable the information panel for all applications on the *Applications → Explore* page , set the value to `true`.
| `spec.dashboardConfig.` +
`disableISVBadges` | `false` | Shows the label on a tile that indicates whether the application is `pass:attributes[{org-name}]-managed`, `Partner managed`, or `Self-managed`. To hide these labels, set the value to `true`. 
| `spec.dashboardConfig.` +
`disableKServe` | `false` | Enables the ability to select KServe as a model-serving platform. To disable this ability, set the value to `true`.
| `spec.dashboardConfig.` +
`disableKServeAuth` | `false` | Enables the ability to use authentication with KServe. To disable this ability, set the value to `true`.
| `spec.dashboardConfig.` +
`disableKServeMetrics` | `false` | Enables the ability to view KServe metrics. To disable this ability, set the value to `true`.
| `spec.dashboardConfig.` +
`disableKServeRaw` | `false` | On the *Settings → Cluster settings* page, in the *Single-model serving platform* section, shows the *Default deployment mode* list. 

On the *Deploy model* dialog when using the single-model serving platform: 

&nbsp; &nbsp; &nbsp; - If the {org-name} OpenShift Serverless Operator and {org-name} OpenShift Service Mesh Operator are installed, shows the *Deployment mode* list.

&nbsp; &nbsp; &nbsp; - If the {org-name} OpenShift Serverless Operator and {org-name} OpenShift Service Mesh Operator are not installed, hides the *Deployment mode* list, and sets the deployment mode to *Standard*.

To hide these deployment-mode lists and set the deployment mode to *Advanced* when using the single-model serving platform, set the `spec.dashboardConfig.disableKServeRaw` value to `true`.
| `spec.dashboardConfig.` +
`disableModelCatalog` 

(Technology Preview) | `true` | Hides the *Models → Model catalog* menu item in the dashboard navigation menu. 
To show this menu item, set the value to `false`.

Model catalog is a Technology Preview feature in this {productname-short} release.
| `spec.dashboardConfig.` +
`disableModelMesh` | `false` | Enables the ability to select ModelMesh as a model-serving platform. To disable this ability, set the value to `true`.
| `spec.dashboardConfig.` +
`disableModelRegistry` 

(Technology Preview) | `false` | Shows the *Models → Model registry* menu item and the *Settings → Model registry settings* menu item in the dashboard navigation menu. To hide these menu items, set the value to `true`.

Model registry is a Technology Preview feature in this {productname-short} release.
| `spec.dashboardConfig.` +
`disableModelRegistrySecureDB` 

(Technology Preview) | `false` | Shows the *Add CA certificate to secure database connection* section in the *Create model registry* dialog and the *Edit model registry* dialog. To hide this section, set the value to `true`.

Model registry is a Technology Preview feature in this {productname-short} release.
| `spec.dashboardConfig.` +
`disableModelServing` | `false` | Shows the *Models → Model deployments* menu item in the dashboard navigation menu, and the *Models* tab in data science projects. To hide these items, set the value to `true`. 
| `spec.dashboardConfig.` +
`disableNIMModelServing` | `false` | Enables the ability to select NVIDIA NIM as a model-serving platform. To disable this ability, set the value to `true`.
| `spec.dashboardConfig.` +
`disablePerformanceMetrics` | `false` | Shows the *Endpoint Performance* tab on the *Model deployments* page. To hide this tab, set the value to `true`.
| `spec.dashboardConfig.` +
`disablePipelines` | `false` | Shows the *Data science pipelines* menu item in the dashboard navigation menu. To hide this menu item, set the value to `true`.
| `spec.dashboardConfig.` +
`disableProjects` | `false` | Shows the *Data science projects* menu item in the dashboard navigation menu. To hide this menu item, set the value to `true`.
| `spec.dashboardConfig.` +
`disableProjectScoped` | `false` | Distinguishes between global items and project-scoped items (if project-scoped items exist) in the {productname-short} web console. This option applies to workbench images, hardware profiles, accelerator profiles, and model-serving runtimes for KServe. To disable this functionality, set the value to `true`.
| `spec.dashboardConfig.` +
`disableProjectSharing` | `false` | Allows users to share access to their data science projects with other users. To prevent users from sharing data science projects, set the value to `true`.
| `spec.dashboardConfig.` +
`disableServingRuntimeParams` | `false` | Shows the *Configuration parameters* section in the *Deploy model* dialog and the *Edit model* dialog when using the single-model serving platform. To hide this section, set the value to `true`.
| `spec.dashboardConfig.` +
`disableStorageClasses` | `false` | Shows the *Settings → Storage classes* menu item in the dashboard navigation menu. To hide this menu item, set the value to `true`.
| `spec.dashboardConfig.` +
`disableSupport` | `false` | Shows the *Support* menu item when a user clicks the Help icon in the dashboard toolbar. To hide this menu item, set the value to `true`.
ifdef::upstream[]
| `spec.dashboardConfig.` +
`disableTracking` | `true` | Disables the collection of data about {productname-short} usage in your cluster. To enable data collection, set the value to `false`. You can also set this option in the {productname-short} dashboard interface from the *Settings → Cluster settings* navigation menu.	
endif::[]
ifndef::upstream[]
| `spec.dashboardConfig.` +
`disableTracking` | `false` | Allows {org-name} to collect data about {productname-short} usage in your cluster. To disable data collection, set the value to `true`. You can also set this option in the {productname-short} dashboard interface from the *Settings → Cluster settings* navigation menu.	
endif::[]
| `spec.dashboardConfig.` +
`disableTrustyBiasMetrics` | `false` | Shows the *Model Bias* tab on the *Models* page. To hide this tab, set the value to `true`. 
| `spec.dashboardConfig.` +
`disableUserManagement` | `false` | Shows the *Settings → User management* menu item in the dashboard navigation menu. To hide this menu item, set the value to `true`.
| `spec.dashboardConfig.` +
`enablement` | `true` | Enables {productname-short} administrators to add applications to the {productname-short} dashboard *Applications* → *Enabled* page. To disable this ability, set the value to `false`.
| `spec.groupsConfig` | No longer used | Read-only. To configure access to the {productname-short} dashboard, use the `spec.adminGroups` and `spec.allowedGroups` options in the {openshift-platform} `Auth` resource in the `services.platform.opendatahub.io` API group.
| `spec.modelServerSizes` | `Small`, `Medium`, `Large` | Allows you to customize names and resources for model servers.
| `spec.notebookController.` +
`enabled` | `true` | Shows the *Start basic workbench* tile in the *Applications* section, and the *Start basic workbench* button on the *Data science projects* page. To hide these items, set the value to `false`.
| `spec.notebookSizes` | `Small`, `Medium`, `Large`, `X Large` | Allows you to customize names and resources for workbenches. 
The Kubernetes-style sizes are shown in the drop-down menu that is displayed when launching a workbench with the Notebook Controller. 

*Note:* These sizes must follow conventions. For example, requests must be smaller than limits.
| `spec.templateOrder` | `[]` | Specifies the order of custom Serving Runtime templates. 
When the user creates a new template, it is added to this list.
|===


//[role="_additional-resources"]
//.Additional resources

