:_module-type: PROCEDURE

[id='registering-a-model-from-the-model-catalog_{context}']
= Registering a model from the model catalog

[role='_abstract']
As a data scientist, you can register models directly from the model catalog and create the first version of the new model.

.Prerequisites
* You are logged in to {productname-long}.
* You have access to an available model registry in your deployment.

.Procedure
. From the {productname-short} dashboard, click *Models* -> *Model catalog*.
. In the drop-down list, select from the available catalog sources that have been configured by your administrator. The *Default Catalog* is displayed by default. 
+
NOTE: OpenShift cluster administrators can configure additional model catalog sources. For more details, see the Kubeflow Model Registry community documentation on https://github.com/kubeflow/model-registry/tree/main/manifests/kustomize/options/catalog#configuring-catalog-sources[Configuring catalog sources]. 

. Use the search bar to find a model in the catalog. You can enter text to search by model name, description, or provider.
. Click the name of a model to view the model details page.
. Click *Register model*.
. From the *Model registry* drop-down list, select the model registry that you want to register the model in.
. In the *Model details* section, configure details to apply to all versions of the model:
.. Optional: In the **Model name** field, update the name of the model. 
.. Optional: In the **Model description** field, update the description of the model.
. In the *Version details* section, enter details to apply to the first version of the model:
.. In the *Version name* field, enter a name for the model version.
.. Optional: In the *Version description* field, enter a description for the first version of the model.
.. In the *Source model format* field, enter the name of the model format, for example, `ONNX`.
.. In the *Source model format version* field, enter the version of the model format.
. In the *Model location* section, the URI of the model is displayed.
. Click *Register model*.

.Verification
* The new model details and version are displayed on the *Overview* tab on the model details page.
* The new model and version are displayed on the *Model registry* page.

// [role="_additional-resources"]
// .Additional resources
// * TODO or delete

