:_module-type: PROCEDURE

[id='registering-an-image-in-the-integrated-openshift-container-registry_{context}']
= Registering an image in the integrated OpenShift container registry

If you want to make your images available to users in your OpenShift cluster, you can register the images in the integrated OpenShift container registry.

.Prerequisites

* You can access the integrated OpenShift container registry.
* You have Podman installed in your local environment, and you have access to a container registry.
For more information about Podman and container registries, see link:https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/building_running_and_managing_containers/index[Building, running, and managing containers].


.Procedure

. In a terminal window, log in to the OpenShift CLI as shown in the following example:
+
[source,subs="+quotes"]
----
$ oc login __<openshift_cluster_url>__ -u __<username>__ -p __<password>__
----

. Set the `IMG` environment variable to the name of your image.
In the example commands in this section, `ray-torch` is the name of the image.
+
.Set the environment variable
[source,subs="+quotes"]
----
export IMG=ray-torch
----


. Expose the integrated container registry: 
+
.Expose the registry
[source,subs="+quotes"]
----
oc patch configs.imageregistry.operator.openshift.io/cluster --patch \'{"spec":{"defaultRoute":true}}' --type=merge
----
 
. Wait for the route to the container registry to be admitted: 
+
.Wait for admission
[source,subs="+quotes"]
----
oc wait -n openshift-image-registry route/default-route --for=jsonpath=\'{.status.ingress[0].conditions[0].status}'=True
----

. Log in to the container registry:
+
[source,subs="+quotes"]
----
podman login -u $(oc whoami) -p $(oc whoami -t) $(oc registry info)
----

. Tag the image for the integrated container registry:
+
.Tag the image
[source,subs="+quotes"]
----
podman tag ${IMG} $(oc registry info)/$(oc project -q)/${IMG}
----

. Push the image to the integrated container registry:
+
.Push the image
[source,subs="+quotes"]
----
podman push $(oc registry info)/$(oc project -q)/${IMG}
----

. Retrieve the image repository location for the tag that you want:
+
.Retrieve the image location
[source,subs="+quotes"]
----
oc get is ${IMG} -o jsonpath=\'{.status.tags[?(@.tag=="_<TAG>_")].items[0].dockerImageReference}'
----

. To use the image, specify the retrieved image location value in the `image` parameter of a notebook or pipeline.
