:_module-type: PROCEDURE

[id='registering-a-model_{context}']
= Registering a model

[role='_abstract']
As a data scientist, you can register a model...

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* An available model registry exists in your deployment.

.Procedure
. From the {productname-short} dashboard, click *Model Registry*.
. From the *Model registry* dropdown menu, select the model registry that you want to register a model in.
. Click *Register model*.
+
The *Register model* page opens.
. In the *Model details* section, configure details to apply to all versions of the model:
.. In the **Model name** field, enter a name for the model.
.. Optional: In the **Model description** field, enter a description for the model.
. In the *Version details* section, enter details to apply to the first version of the model:
.. In the *Version name* field, enter a name for the model version.
.. Optional: In the *Version description* field, enter a description for the first version of the model.
.. In the *Source model format* field, enter the name of the model format, for example, `onnx`.
.. In the *Source model format version* field, enter the version of the model format.
. In the *Model location* section, specify the location of the model by providing either object storage details, or a URI.
. To provide object storage details, ensure that the *Object storage* radio button is selected. 
.. To autofill the details of an existing data connection:
... Click *Autofill from data connection*. 
...In the *Autofill from data connection* dialog that opens, from the *Project* drop-down list, select the data science project that contains the data connection.
... From the *Data connection name* dropdown list, select the data connection that you want to use. 
+
This list contains only object storage types which contain a bucket.
... Click *Autofill*.
.. Alternatively, manually fill out your object storage details:
... In the *Endpoint* field, enter the endpoint of your S3-compatible object storage bucket.
... In the *Bucket* field, enter the name of your S3-compatible object storage bucket.
... In the *Region* field, enter the region of your S3-compatible object storage account.
... In the **Path** field, enter a path to a model or folder. This path cannot point to a root folder.
. To provide a URI, ensure that the *URI* radio button is selected.
.. In the *URI* field, enter the URI for the model.
+
[IMPORTANT]
====
Deployment of models that are registered using a URI is not currently supported for this feature.
====
. Click *Register model*.

.Verification
* The new model appears on the *Model Registry* page.

// [role="_additional-resources"]
// .Additional resources
// * TODO or delete


