:_module-type: PROCEDURE

[id='removing-access-to-a-data-science-project_{context}']
= Removing access to a data science project

[role='_abstract']
If you no longer want to work collaboratively on your data science project, you can restrict access to your project by removing users and groups that you previously provided access to your project.

.Prerequisites
* You have logged in to {productname-long}.
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, `rhods-users`) in OpenShift.
* You have created a data science project.
* You have previously shared access to your project with other users or groups.
* You have administrator permissions or you are the project owner.

.Procedure
. From the {productname-short} dashboard, click *Data Science Projects*.
+
The *Data science projects* page opens.
. Click the name of the project that you want to change the access permissions of.
+
The *Details* page for the project opens.
. Click the *Permissions* tab.
+
The *Permissions* page for the project opens.
. Click the action menu (*&#8942;*) beside the user or group whose access permissions you want to revoke and click *Delete*.

.Verification
* Users whose access you have revoked can no longer perform the actions that were permitted by their access permission level.

//[role="_additional-resources"]
//.Additional resources
