:_module-type: PROCEDURE

[id='removing-access-to-a-project_{context}']
= Removing access to a project

[role='_abstract']
If you no longer want to work collaboratively on your project, you can restrict access to it by removing users and groups to whom you had previously provided access.

.Prerequisites
* You have logged in to {productname-long}.
* You have {productname-short} administrator privileges or you are the project owner.
* You have created a project.
* You have previously shared access to your project with other users or groups.

.Procedure
. From the {productname-short} dashboard, click *Projects*.
+
The *Projects* page opens.
. Click the name of the project that you want to change the access permissions of.
+
A project details page opens.
. Click the *Permissions* tab.
+
The *Permissions* page for the project opens.
. Click the action menu (*&#8942;*) beside the user or group whose access permissions you want to revoke and click *Delete*.

.Verification
* Users whose access you have revoked can no longer perform the actions that were permitted by their access permission level.

//[role="_additional-resources"]
//.Additional resources
