:_module-type: PROCEDURE

[id="removing-a-ca-bundle-from-a-namespace_{context}"]
= Removing a CA bundle from a namespace

[role='_abstract']
You can remove a custom Certificate Authority (CA) bundle from individual namespaces in {productname-short}. This process disables the creation of the `odh-trusted-ca-bundle` configuration file (ConfigMap) for the specified namespace only.

To remove a certificate bundle from all namespaces, see _Removing a CA bundle_.

.Prerequisites
* You have cluster administrator privileges for your {openshift-platform} cluster.
* You installed the OpenShift command line interface (`oc`) as described in link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI^].

.Procedure
* Run the following command to remove a CA bundle from a namespace. In the following command, _example-namespace_ is the non-reserved namespace.
+
[source]
----
$ oc annotate ns example-namespace security.opendatahub.io/inject-trusted-ca-bundle=false
----

.Verification
* Run the following command to verify that the CA bundle has been removed from the namespace. In the following command, _example-namespace_ is the non-reserved namespace.
+
[source]
----
$ oc get configmap odh-trusted-ca-bundle -n example-namespace
----
+
The command should return `configmaps "odh-trusted-ca-bundle" not found`.

//[role='_additional-resources']
//.Additional resources
