:_module-type: PROCEDURE

[id="removing-the-ca-bundle-from-all-namespaces_{context}"]
= Removing the CA bundle from all namespaces

[role='_abstract']

ifdef::upstream[]
You can remove a Certificate Authority (CA) bundle from all non-reserved namespaces in {productname-short}. This process changes the default configuration and disables the creation of the `odh-trusted-ca-bundle` configuration file (ConfigMap), as described in link:{odhdocshome}/installing-open-data-hub/#understanding-certificates_certs[Understanding certificates in {productname-short}].
endif::[]

ifdef::self-managed[]
You can remove a Certificate Authority (CA) bundle from all non-reserved namespaces in {productname-short}. This process changes the default configuration and disables the creation of the `odh-trusted-ca-bundle` configuration file (ConfigMap), as described in link:{rhoaidocshome}{default-format-url}/installing_and_uninstalling_{url-productname-short}/working-with-certificates_certs[Working with certificates] ({productname-short} Self-Managed) or link:{rhoaidocshome}{default-format-url}/installing_and_uninstalling_{url-productname-short}_in_a_disconnected_environment/working-with-certificates_certs[Working with certificates] ({productname-short} Self-Managed in a disconnected environment).
endif::[]

ifdef::cloud-service[]
You can remove a Certificate Authority (CA) bundle from all non-reserved namespaces in {productname-short}. This process changes the default configuration and disables the creation of the `odh-trusted-ca-bundle` configuration file (ConfigMap), as described in link:{rhoaidocshome}{default-format-url}/installing_and_uninstalling_{url-productname-short}/working-with-certificates_certs[Working with certificates].
endif::[]

NOTE: The `odh-trusted-ca-bundle` ConfigMaps are only deleted from namespaces when you set the `managementState` of `trustedCABundle` to `Removed`; deleting the DSC Initialization does not delete the ConfigMaps. 

ifdef::upstream[]
To remove a CA bundle from a single namespace only, see link:{odhdocshome}/installing-open-data-hub/#removing-the-ca-bundle-from-a-single-namespace_certs[Removing the CA bundle from a single namespace].
endif::[]

ifdef::self-managed[]
To remove a CA bundle from a single namespace only, see link:{rhoaidocshome}{default-format-url}/installing_and_uninstalling_openshift_ai_self-managed/working-with-certificates_certs#removing-the-ca-bundle-from-a-single-namespace_certs[Removing the CA bundle from a single namespace] ({productname-short} Self-Managed) or link:{rhoaidocshome}{default-format-url}/installing_and_uninstalling_openshift_ai_self-managed_in_a_disconnected_environment/working-with-certificates_certs#removing-the-ca-bundle-from-a-single-namespace_certs[Removing the CA bundle from a single namespace] ({productname-short} Self-Managed in a disconnected environment).
endif::[]

ifdef::cloud-service[]
To remove a CA bundle from a single namespace only, see link:{rhoaidocshome}{default-format-url}/installing_and_uninstalling_openshift_ai_cloud_service/working-with-certificates_certs#removing-the-ca-bundle-from-a-single-namespace_certs[Removing the CA bundle from a single namespace].
endif::[]


.Prerequisites
* You have cluster administrator privileges for your {openshift-platform} cluster.
* You have installed the {openshift-cli} as described in the appropriate documentation for your cluster:
ifdef::upstream,self-managed[]
** link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI^] for OpenShift Container Platform  
** link:https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws/{rosa-latest-version}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI^] for {rosa-productname}
endif::[]
ifdef::cloud-service[]
** link:https://docs.redhat.com/en/documentation/openshift_dedicated/{osd-latest-version}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI^] for OpenShift Dedicated  
** link:https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws_classic_architecture/{rosa-classic-latest-version}/html/cli_tools/openshift-cli-oc#installing-openshift-cli[Installing the OpenShift CLI^] for {rosa-classic-productname}
endif::[]

.Procedure
. In the {openshift-platform} web console, click *Operators* → *Installed Operators* and then click the {productname-long} Operator.
. Click the *DSC Initialization* tab.
. Click the *default-dsci* object.
. Click the *YAML* tab.
. In the `spec` section, change the value of the `managementState` field for `trustedCABundle` to `Removed`:
+
[source]
----
spec:
  trustedCABundle:
    managementState: Removed
----

. Click *Save*.

.Verification
* Run the following command to verify that the `odh-trusted-ca-bundle` ConfigMap has been removed from all namespaces:
+
[source]
----
oc get configmaps --all-namespaces | grep odh-trusted-ca-bundle
----
+
The command should not return any ConfigMaps.