:_module-type: PROCEDURE

[id="restoring-a-model_{context}"]
= Restoring a model

[role='_abstract']
You can restore an archived model. The model and all of its versions will be restored and returned to the registered models list.

.Prerequisites
* You have logged in to {productname-long}.
* An available model registry exists in your deployment, and contains at least one archived model.
* You have access to the model registry that contains the model that you want to restore.

.Procedure
. From the {productname-short} dashboard, click *Models* -> *Model registry*.
. From the *Model registry* dropdown menu, select the model registry that you want to restore a model in.
. Click the action menu (*&#8942;*) beside the *Register model* drop-down menu, and then click *View archived models*.
+ 
The archived models page for the model registry opens.
. Click the action menu (*&#8942;*) beside the model that you want to restore.
. Click *Restore model*.
. In the *Restore model?* dialog that is displayed, click *Restore*.

.Verification

* The model is displayed on the *Model registry* page.
* The model is no longer displayed on the archived models page for the model registry.

// [role="_additional-resources"]
// .Additional resources
// * TODO or delete
