:_module-type: PROCEDURE

[id="restoring-an-archived-pipeline-experiment_{context}"]
= Restoring an archived pipeline experiment

[role='_abstract']
You can restore an archived pipeline experiment to the active state.

.Prerequisites

* You have logged in to {productname-long}.
* You have previously created a data science project that is available and has a pipeline server.
* An archived pipeline experiment exists in your project. 

.Procedure
. From the {productname-short} dashboard, click *Experiments* -> *Experiments and runs*.
. On the *Experiments* page, from the *Project* drop-down list, select the project that contains the archived pipeline experiment that you want to restore.
. Click the *Archive* tab.
. Click the action menu (*&#8942;*) beside the pipeline experiment that you want to restore, and then click *Restore*.
. In the *Restore experiment* dialog, click *Restore*.

.Verification
* The restored pipeline experiment is displayed on the *Experiments* tab on the *Experiments* page.

//[role='_additional-resources']
//.Additional resources
