:_module-type: PROCEDURE

[id="restoring-default-component-resources-using-web-console_{context}"]
= Restoring default component resources by using the web console

[role='_abstract']
You can restore the default values of component deployment resources that were customized, by adding the `opendatahub.io/managed: true` annotation to the YAML file for the component deployment.

.Prerequisites
* You have cluster administrator privileges for your {openshift-platform} cluster.
* You have admin access to the `DSCInitialization` resources in the {openshift-platform} cluster.

.Procedure
. Log in to the {openshift-platform} console as a cluster administrator.
. In the *Administrator* perspective, click *Workloads* > *Deployments*.
ifdef::upstream[]
. From the *Project* drop-down list, select `openshift-operators`.
endif::[]
ifndef::upstream[]
. From the *Project* drop-down list, select `redhat-ods-applications`.
endif::[]
. In the *Name* column, click the name of the deployment for the component that you want to restore default resources for. For example, to restore default values of customized Codeflare resources, click *codeflare-operator-manager*.
. On the *Deployment details* page that appears, click the *YAML* tab.
. Find the `metadata: annotations:` section.
. Add the `opendatahub.io/managed: true` annotation.
+
[source]
----
metadata:
  annotations:
    `opendatahub.io/managed: true`
----
. Click *Save*.
. Click *Reload*.

.Verification




//[role='_additional-resources']
//.Additional resources