:_module-type: PROCEDURE

[id="restoring-an-archived-pipeline-experiment_{context}"]
= Restoring an archived pipeline experiment

[role='_abstract']
You can restore an archived pipeline experiment to the active state.

.Prerequisites

* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group} ) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have previously created a data science project that is available and has a pipeline server.
* You have imported a pipeline to an active pipeline server.
* An archived pipeline experiment exists in your project. 

.Procedure
. From the {productname-short} dashboard, click *Experiments* -> *Experiments and runs*.
. On the *Experiments* page, from the *Project* drop-down list, select the project that contains the archived pipeline experiment that you want to restore.
. Click the *Archive* tab.
. Click the action menu (*&#8942;*) beside the pipeline experiment that you want to restore and click *Restore*.
. In the *Restore experiment* dialog, click *Restore*.

.Verification
* The restored pipeline experiment appears in the *Experiments* tab on the *Experiments* page.

//[role='_additional-resources']
//.Additional resources
