:_module-type: PROCEDURE

[id="restoring-a-model_{context}"]
= Restoring a model

[role='_abstract']
You can restore an archived model. The model and all of its versions will be restored and returned to the registered models list.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* An available model registry exists in your deployment.

.Procedure
. From the {productname-short} dashboard, click *Model Registry*.
. From the *Model registry* dropdown menu, select the model registry that you want to restore a model in.
. Click the action menu (*&#8942;*) beside the *Register model* drop-down menu, and then click *View archived models*.
+ 
The archived models page for the model registry opens.
. Click the action menu (*&#8942;*) beside the model that you want to restore.
. Click *Restore model*.
. In the *Restore model?* dialog that appears, click *Restore*.

.Verification

* The model appears on the *Model Registry* page.
* The model no longer appears on the archived models page for the model registry.

// [role="_additional-resources"]
// .Additional resources
// * TODO or delete
