:_module-type: PROCEDURE

[id="restoring-an-archived-pipeline-run_{context}"]
= Restoring an archived pipeline run

[role='_abstract']
You can restore an archived run to the active state.

.Prerequisites

* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group} ) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have previously created a data science project that is available and has a pipeline server.
* You have imported a pipeline to an active pipeline server.
* An archived run exists in your project. 

.Procedure
. From the {productname-short} dashboard, click *Experiments* -> *Experiments and runs*.
. On the *Experiments* page, select the *project* that contains the pipeline experiment for the archived pipeline run that you want to restore.
. From the list of pipeline experiments, click the pipeline experiment that contains the archived pipeline run that you want to restore. 
. On the *Runs* page, click the *Archive* tab.
. Click the action menu (*&#8942;*) beside the pipeline run that you want to restore and click *Restore*.
. In the *Restore run* dialog, click *Restore*.

.Verification
* The restored run appears in the *Runs* tab on the *Runs* page for the pipeline experiment.

//[role='_additional-resources']
//.Additional resources
