:_module-type: PROCEDURE

[id="restoring-an-archived-pipeline-run_{context}"]
= Restoring an archived pipeline run

[role='_abstract']
You can restore an archived run to the active state.

.Prerequisites

* You have logged in to {productname-long}.
* You have previously created a data science project that is available and has a pipeline server.
* You have imported a pipeline to an active pipeline server.
* An archived run exists in your project. 

.Procedure
. From the {productname-short} dashboard, click *Experiments* -> *Experiments and runs*.
. On the *Experiments* page, from the *Project* drop-down list, select the project that contains the pipeline experiment that you want to restore.
. From the list of pipeline experiments, click the experiment that contains the archived pipeline run that you want to restore. 
. On the *Runs* page, click the *Archive* tab.
. Click the action menu (*&#8942;*) beside the pipeline run that you want to restore, and then click *Restore*.
. In the *Restore run?* dialog, click *Restore*.

.Verification
* The restored run appears on the *Runs* tab on the *Runs* page for the pipeline experiment.

//[role='_additional-resources']
//.Additional resources
