:_module-type: PROCEDURE

[id="restoring-a-model-version_{context}"]
= Restoring a model version

[role='_abstract']
You can restore an archived model version. The model version will be restored and returned to the versions list for the model.

.Prerequisites
* You have logged in to {productname-long}.
* An available model registry exists in your deployment, and contains at least one archived model version.
* You have access to the model registry that contains the model version that you want to restore.

.Procedure
. From the {productname-short} dashboard, click *Models* -> *Model registry*.
. From the *Model registry* drop-down menu, select the model registry that you want to restore a model in.
. In the *Model name* column, click the name of the model that contains the version that you want to restore.
+
The details page for the model version opens.
. Click the action menu (*&#8942;*) beside the *Register new version* drop-down menu, and then click *View archived versions*.
+ 
The archived versions page for the model opens.
. Click the action menu (*&#8942;*) beside the version that you want to restore.
. Click *Restore version*.
. In the *Restore version?* dialog that is displayed, click *Restore*.
+
The details page for the version opens.

.Verification
* The model version is displayed on the details page for the model.
* The model no longer is displayed on the archived versions page for the model.

// [role="_additional-resources"]
// .Additional resources
// * TODO or delete