:_module-type: PROCEDURE

[id='revoking-user-access-to-jupyter_{context}']
= Revoking user access to Jupyter

[role='_abstract']
You can revoke a user's access to Jupyter by removing them from the specialized user groups that restrict access to {productname-short}. Removing users from specialized user groups will prevent them from accessing the {productname-short} dashboard and using associated services such as Jupyter to run notebook servers and consume resources in your cluster.

IMPORTANT: Follow these steps only if you have implemented specialized user groups to restrict access to {productname-short}. To completely remove a user from {productname-short}, you must remove them from the allowed group in your OpenShift identity provider.

.Prerequisites
* You have stopped any notebook servers owned by the user you want to delete.
ifndef::self-managed[]
* You are part of the `dedicated-admins` user group in {openshift-platform}.
endif::[]
ifdef::self-managed[]
* You are assigned the `cluster-admin` role in {openshift-platform}.
endif::[]
* You are using specialized user groups for {productname-short}, and the user is part of the user group, administrator group, or both.

.Procedure
. In the {openshift-platform} web console, click *User Management* -> *Groups*.
. Click the name of the group that you want to remove the user from.
** For administrative users, click the name of your administrator group, for example, {oai-admin-group}.
** For normal users, click the name of your user group, for example, {oai-user-group}.

+
The *Group details* page for the group appears.

. In the *Users* section on the *Details* tab, locate the user that you want to remove.
. Click the action menu (*&#8942;*) beside the user that you want to remove and click *Remove user*.


.Verification
* Check the *Users* section on the *Details* tab and confirm that the user that you removed is not visible.
* In the `rhods-notebooks` project, check under *Workload* -> *Pods* and ensure that there is no notebook server pod for this user. If you can see a pod named `jupyter-nb-<username>-*` for the user that you have removed, delete that pod to ensure that the deleted user is not consuming resources on the cluster.
* In the {productname-short} dashboard, check the list of data science projects. Delete any projects that belong to the user.

//[role="_additional-resources"]
//.Additional resources
//* TODO or delete
