:_module-type: PROCEDURE

[id='revoking-user-access-to-basic-workbenches_{context}']
= Revoking user access to basic workbenches

[role='_abstract']
You can revoke a user's access to basic workbenches by removing the user from the {productname-short} user groups that define access to {productname-short}. When you remove a user from the user groups, the user is prevented from accessing the {productname-short} dashboard and from using associated services that consume resources in your cluster.

IMPORTANT: Follow these steps only if you have implemented {productname-short} user groups to restrict access to {productname-short}. To completely remove a user from {productname-short}, you must remove them from the allowed group in your OpenShift identity provider.

.Prerequisites
* You have stopped any workbenches owned by the user you want to delete.
ifdef::cloud-service[]
* You are part of the `cluster-admins` or `dedicated-admins` user group in your OpenShift cluster. The `dedicated-admins` user group applies only to OpenShift Dedicated.
endif::[]
ifdef::self-managed[]
* You are assigned the `cluster-admin` role in {openshift-platform}.
endif::[]
* You are using {productname-short} user groups, and the user is part of the user group, administrator group, or both.

.Procedure
. In the {openshift-platform} web console, click *User Management* -> *Groups*.
. Click the name of the group that you want to remove the user from.
** For administrative users, click the name of your administrator group, for example, {admin-group}.
** For non-administrator users, click the name of your user group, for example, {user-group}.

+
The *Group details* page for the group is displayed.

. In the *Users* section on the *Details* tab, locate the user that you want to remove.
. Click the action menu (*&#8942;*) beside the user that you want to remove and click *Remove user*.


.Verification
* In the *Users* section on the *Details* tab of the *Group details* page, confirm that the user that you removed is not visible.
ifdef::cloud-service[]
In *Workloads* -> *Pods*, select the `pass:attributes[{workbench-default-namespace}]` project and ensure that there is no workbench pod for this user. If you see a pod named `jupyter-nb-<username>-*` for the user that you have removed, delete that pod to ensure that the deleted user is not consuming resources on the cluster.
endif::[]
ifdef::self-managed,upstream[]
In *Workloads* -> *Pods*, select the default workbench project (`pass:attributes[{workbench-default-namespace}]` or your custom workbench namespace), and ensure that there is no workbench pod for this user. If you see a pod named `jupyter-nb-<username>-*` for the user that you have removed, delete that pod to ensure that the deleted user is not consuming resources on the cluster.
endif::[]
* In the {productname-short} dashboard, check the list of data science projects. Delete any projects that belong to the user.

//[role="_additional-resources"]
//.Additional resources
//* TODO or delete
