:_module-type: CONCEPT

[id='safeguard-your-AI-application-with-a-guardrails-use-case-scenario_{context}']
= Safeguard your AI application with a Guardrails use case scenario

[role='_abstract']

You can see some of the the models outlined in this section (or similar ones) utilised in a real-world use case created by the TrustyAI team called the 'TrustyAI Lemonade Stand Demo'.  

It is part of the TrustyAI open-source community demonstrations and it contains a Hateful and Profane (HAP) language detection model and a regex detector model.
+
[IMPORTANT]
--
This tutorial covers community-maintained tools and third-party configurations that fall outside the scope of {productname-long} commercial support. While provided as a resource for {productname-long} users, Red Hat does not offer technical assistance for these specific workflows. These procedures and software versions are not covered by Red Hat support service level agreements and should be used for informational or proof-of-concept purposes only.
--
+
The scenario involves creating and deploying an LLM customer service assistant (CSA) to answer queries about your product (lemonade). It uses guardrailing models to ensure the CSA focuses on your brand, avoids inappropriate language, and does not promote any competitor products. In this way, it mitigates risks associated with unstructured text generation.

The models analyze the input (the customer's prompt) and output (the response) and provide guardrailing based on three criteria:

* *Input validation:* Verifies if the user's question is safe and relevant.
* *Business logic:* Checks if the user is asking about restricted topics, such as competitors' products.
* *Output validation:* Ensures the generated response is appropriate for a general audience.

Find the tutorial on the TrustyAI open-source GitHub repository, called link:https://github.com/trustyai-explainability/trustyai-llm-demo/tree/lemonade-stand[TrustyAI Lemonade Stand Demo].