:_module-type: PROCEDURE

[id="starting-a-workbench_{context}"]
= Starting a workbench

[role='_abstract']
You can manually start a data science project's workbench from the *Workbenches* tab on the project details page. By default, workbenches start immediately after you create them.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have created a data science project that contains a workbench.

.Procedure
. From the {productname-short} dashboard, click *Data Science Projects*.
+
The *Data Science Projects* page opens.
. Click the name of the project whose workbench you want to start.
+
A project details page opens.
. Click the *Workbenches* tab.
. Click the action menu (*&#8942;*) beside the workbench that you want to start, and click *Start*.
+
The *Status* column changes from *Stopped* to *Starting* when the workbench server is starting, and then to *Running* when the workbench has successfully started.
* Optional: Click the *Open* link to open the IDE in a new window.

.Verification
* The workbench that you started appears on the *Workbenches* tab for the project, with the status of *Running*.


//[role='_additional-resources']
//.Additional resources
