:_module-type: PROCEDURE

[id='starting-basic-workbenches-owned-by-other-users_{context}']
= Starting basic workbenches owned by other users

[role='_abstract']
{productname-short} administrators can start a basic workbench for another existing user from the administration interface for basic workbenches.

.Prerequisites
* You have logged in to {productname-short} as a user with {productname-short} administrator privileges. 

ifdef::upstream[]
* You have launched the *Start basic workbench* application, as described in link:{odhdocshome}/working-with-connected-applications/#starting-a-basic-workbench_connected-apps[Starting a basic workbench].
endif::[]

ifndef::upstream[]
* You have launched the *Start basic workbench* application, as described in link:{rhoaidocshome}{default-format-url}/working_with_connected_applications/using_basic_workbenches#starting-a-basic-workbench_connected-apps[Starting a basic workbench].
endif::[]

.Procedure
. On the page that opens when you launch a basic workbench, click the *Administration* tab.
. On the *Administration* tab, perform the following actions:
.. In the *Users* section, locate the user whose workbench you want to start.
.. Click *Start workbench* beside the relevant user.
.. Complete the *Start a basic workbench* page.
.. Optional: Select the *Start workbench in current tab* checkbox if necessary.
.. Click *Start workbench*.
+
After the server starts, you see one of the following behaviors:
+
--
* If you previously selected the *Start workbench in current tab* checkbox, the JupyterLab interface opens in the current tab of your web browser.
* If you did not previously select the *Start workbench in current tab* checkbox, the *Workbench status* dialog box prompts you to open the server in a new browser tab or in the current tab. 
+
The JupyterLab interface opens according to your selection.
--

.Verification
* The JupyterLab interface opens.

