:_module-type: PROCEDURE

[id="starting-a-workbench_{context}"]
= Starting a workbench

[role='_abstract']
You can manually start a data science project's workbench from the *Details* page for the project. By default, workbenches start immediately after you create them.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, `rhods-users` or `rhods-admins`) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, `odh-users` or `odh-admins`) in OpenShift.
endif::[]
* You have created a data science project that contains a workbench.

.Procedure
. From the {productname-short} dashboard, click *Data Science Projects*.
+
The *Data science projects* page opens.
. Click the name of the project whose workbench you want to start.
+
The *Details* page for the project opens.
. Click the toggle in the *Status* column for the relevant workbench to start a workbench that is not running.
+
The status of the workbench that you started changes from *Stopped* to *Running*. After the workbench has started, click *Open* to open the workbench's notebook.

.Verification
* The workbench that you started appears on the *Details* page for the project with the status of *Running*.


//[role='_additional-resources']
//.Additional resources
