:_module-type: PROCEDURE

[id='starting-a-basic-workbench_{context}']
= Starting a basic workbench

[role='_abstract']
Using the basic workbench is based on a server-client architecture. The basic workbench runs in a container on the Red Hat OpenShift cluster. The client is the IDE interface that opens in your web browser on your local computer. However, all of the commands that you enter in the IDE are executed by the workbench. This architecture allows you to interact through your local computer in a browser environment, while all processing occurs on the cluster. The cluster provides the benefits of larger available resources and security because the data being processed never leaves the cluster.

From the *Start basic workbench* tile, you can start a basic workbench. If you require extra power for use with large datasets, you can assign accelerators to your workbench to optimize performance. 

.Prerequisites
* You are logged in to {productname-long}.
* You are starting the workbench for the first time or you stopped your workbench.
* You know the names and values you want to use for any environment variables in your workbench environment, for example, `AWS_SECRET_ACCESS_KEY`.
* If you want to work with a large data set, work with your administrator to proactively increase the storage capacity of your workbench. If applicable, also consider assigning accelerators to your workbench. 

.Procedure

. In the left navigation pane, click *Applications* → *Enabled*.
. On the *Enabled* page, locate the *Start basic workbench* tile.

. Click *Open application*.
+
If you see an *Access permission needed* message, you are not in the default user group or the default administrator group for {productname-short}.
ifndef::upstream[]
Ask your administrator to add you to the correct group by using link:{rhoaidocshome}{default-format-url}/managing_openshift_ai/managing-users-and-groups#adding-users-to-user-groups_managing-rhoai[Adding users to {productname-short} user groups].
endif::[]
ifdef::upstream[]
Ask your administrator to add you to the correct group.
endif::[]
+
If your credentials are accepted, the *Workbench control panel* opens displaying the *Start a basic workbench* page.
. Start a basic workbench.

.. In the *Workbench image* section, select the workbench image to use for your workbench. 
+
Different workbench images have different packages installed by default. Click the help icon (?) next to a workbench image name to view a list of its included packages.

.. If the workbench image contains multiple versions, select the version of the workbench image from the *Versions* section.
+
[NOTE]
--
When a new version of a workbench image is released, the previous version remains available and supported on the cluster. This gives you time to migrate your work to the latest version of the workbench image.
--
.. From the *Container size* list, select a suitable container size for your workbench.
.. Optional: From the *Accelerator* list, select an accelerator. 
.. If you selected an accelerator in the preceding step, specify the number of accelerators to use.
+
[IMPORTANT]
--
ifdef::upstream[]
Using accelerators is only supported with specific workbench images. For GPUs, only the AMD ROCm, PyTorch, TensorFlow, and CUDA workbench images are supported. In addition, you can only specify the number of accelerators required for your workbench if accelerators are enabled on your cluster.
endif::[]
ifndef::upstream[]
Using accelerators is only supported with specific workbench images. For GPUs, only the AMD ROCm, PyTorch, TensorFlow, and CUDA workbench images are supported. In addition, you can only specify the number of accelerators required for your workbench if accelerators are enabled on your cluster. To learn how to enable accelerator support, see link:{rhoaidocshome}{default-format-url}/working_with_accelerators/overview-of-accelerators_accelerators[Working with accelerators].
endif::[]
--
.. Optional: Select and specify values for any new *Environment variables*.
+
The interface stores these variables so that you only need to enter them once. Example variable names for common environment variables are automatically provided for frequently integrated environments and frameworks, such as Amazon Web Services (AWS).
+
[IMPORTANT]
====
Select the *Secret* checkbox for variables with sensitive values that must remain private, such as passwords.
====
.. Optional: Check *Start workbench in current tab*.
.. Click *Start workbench*.
+
The *Workbench status* progress indicator appears. Click the *Events log* tab to view additional information about the workbench creation process. Depending on the deployment size and resources you requested, starting the workbench can take up to several minutes. Only click *Cancel* if you want to cancel the workbench creation.
+
After the server starts, you see one of the following behaviors:
+
--
* If you selected *Start workbench in current tab* in the preceding step, the IDE interface opens in the current tab of your web browser.
* If you did not select *Start workbench in current tab* in the preceding step, the *Workbench status* dialog box prompts you to open the server in a new browser tab or in the current browser tab.
--

.Verification
* The IDE interface opens.

.Troubleshooting
* If you see the "Unable to load workbench configuration options" error message, contact your administrator so that they can review the logs associated with your workbench pod and determine further details about the problem.