:_module-type: PROCEDURE

[id='starting-a-jupyter-notebook-server_{context}']
= Starting a Jupyter notebook server

[role='_abstract']
Jupyter is based on a server-client architecture. The Jupyter notebook server runs in a container on the Red Hat OpenShift cluster. The client is the JupyterLab interface that opens in your web browser on your local computer. However, all of the commands that you enter in JupyterLab are executed by the notebook server. This architecture allows you to interact through your local computer in a browser environment, while all processing occurs on the cluster. The cluster provides the benefits of larger available resources and security because the data being processed never leaves the cluster.

From the Jupyter application tile, you can start a Jupyter notebook server. If you require extra power for use with large datasets, you can assign accelerators to your notebook server to optimize performance. 

.Prerequisites
* You are logged in to {productname-long}.
* You are starting Jupyter for the first time or you stopped your notebook server.
* You know the names and values you want to use for any environment variables in your notebook server environment, for example, `AWS_SECRET_ACCESS_KEY`.
* If you want to work with a large data set, work with your administrator to proactively increase the storage capacity of your notebook server. If applicable, also consider assigning accelerators to your notebook server. 

.Procedure

. In the left navigation pane, click *Applications > Enabled*.
. Locate the *Jupyter* tile on the *Enabled applications* page.

. Click *Launch application*.
+
If you see an *Access permission needed* message, you are not in the default user group or the default administrator group for {productname-short}.
ifndef::upstream[]
Ask your administrator to add you to the correct group by using link:{rhoaidocshome}{default-format-url}/managing_users/adding-users_user-mgmt[Adding users].
endif::[]
ifdef::upstream[]
Ask your administrator to add you to the correct group.
endif::[]
+
If you have not previously authorized the `jupyter-nb-<username>` service account to access your account, the *Authorize Access* page appears prompting you to provide authorization. Inspect the permissions selected by default, and click the *Allow selected permissions* button.
+
If your credentials are accepted, the *Notebook server control panel* opens displaying the *Start a notebook server* page.
. Start a notebook server.

.. In the *Notebook image* section, select the notebook image to use for your server. 
+
Different notebook images have different packages installed by default. Click the help icon (?) next to a notebook image name to view a list of its included packages.

.. If the notebook image contains multiple versions, select the version of the notebook image from the *Versions* section.
+
[NOTE]
--
When a new version of a notebook image is released, the previous version remains available and supported on the cluster. This gives you time to migrate your work to the latest version of the notebook image.
--
.. From the *Container size* list, select a suitable container size for your server.
.. Optional: From the *Accelerator* list, select an accelerator. 
.. If you selected an accelerator in the preceding step, specify the number of accelerators to use.
+
[IMPORTANT]
--
ifdef::upstream[]
Using accelerators is only supported with specific notebook images. For GPUs, only the PyTorch, TensorFlow, and CUDA notebook images are supported. For Intel Gaudi AI Accelerators, only the HabanaAI notebook image is supported. In addition, you can only specify the number of accelerators required for your notebook server if accelerators are enabled on your cluster.
endif::[]
ifndef::upstream[]
Using accelerators is only supported with specific notebook images. For GPUs, only the PyTorch, TensorFlow, and CUDA notebook images are supported. For Intel Gaudi AI Accelerators, only the HabanaAI notebook image is supported. In addition, you can only specify the number of accelerators required for your notebook server if accelerators are enabled on your cluster. To learn how to enable GPU support, see link:{rhoaidocshome}{default-format-url}/managing_resources/managing-cluster-resources_cluster-mgmt#enabling-gpu-support_cluster-mgmt[Enabling GPU support in {productname-short}].
endif::[]
--
.. Optional: Select and specify values for any new *Environment variables*.
+
The interface stores these variables so that you only need to enter them once. Example variable names for common environment variables are automatically provided for frequently integrated environments and frameworks, such as Amazon Web Services (AWS).
+
[IMPORTANT]
====
Select the *Secret* checkbox for variables with sensitive values that must remain private, such as passwords.
====
.. Optional: Check *Start server in current tab*.
.. Click *Start server*.
+
The *Starting server* progress indicator appears. Click *Expand event log* to view additional information about the server creation process. Depending on the deployment size and resources you requested, starting the server can take up to several minutes. Only click *Cancel* if you want to cancel the server creation.
+
After the server starts, you see one of the following behaviors:
+
--
* If you selected *Start server in current tab* in the preceding step, the JupyterLab interface opens in the current tab of your web browser.
* If you did not select *Start server in current tab* in the preceding step, the *Starting server* dialog box prompts you to open the server in a new browser tab or in the current browser tab.
--

.Verification
* The JupyterLab interface opens.

.Troubleshooting
* If you see the "Unable to load notebook server configuration options" error message, contact your administrator so that they can review the logs associated with your Jupyter pod and determine further details about the problem.
