:_module-type: PROCEDURE

[id='stopping-a-basic-workbench-console_{context}']
= Stopping a basic workbench through the {productname-long} console

[role='_abstract']

When you have a running workbench, you can stop the workbench to conserve cluster resources, or to make configuration changes that require you to restart the workbench. You can stop your workbench through the {productname-long} console.

.Prerequisites
* You are logged in to {productname-long}.
* You have created a data science project.
* You have a running workbench. 

.Procedure
. From the {productname-short} dashboard, click on  *Projects*.
. Click on the name of the project that contains the workbench you intend to stop.
. On the *Product details* pop-up page, click on the *Workbenches* tab.
. Locate the running workbench that you intend to stop and click on the *Stop* button in the *Status* column.
+
* The status will change from *Running* to *Stopping*. 

.Verification
* The workbench status has changed from *Stopping* to *Stopped*.

