:_module-type: PROCEDURE

[id="stopping-idle-workbenches_{context}"]
= Stopping idle workbenches

[role='_abstract']
You can reduce resource usage in your {productname-short} deployment by stopping workbenches that have been idle (without logged in users) for a period of time. This is useful when resource demand in the cluster is high. By default, idle workbenches are not stopped after a specific time limit.
[NOTE]
====
If you have configured your cluster settings to disconnect all users from a cluster after a specified time limit, then this setting takes precedence over the idle workbench time limit. Users are logged out of the cluster when their session duration reaches the cluster-wide time limit.
====

.Prerequisites
* You have logged in to {productname-short} as a user with {productname-short} administrator privileges.

.Procedure
. From the {productname-short} dashboard, click *Settings* -> *Cluster settings*.
. Under *Idle workbench timeout*, select *Stop idle workbenches after defined period*.
. Enter a time limit, in *hours* and *minutes*, for when idle workbenches are stopped.
. Click *Save changes*.

.Verification
* In {openshift-platform}, go to *Workloads* -> *ConfigMaps* and open the `notebook-controller-culler-config` ConfigMap in the `redhat-ods-applications` project to verify that it contains the following culling configuration settings:
** `ENABLE_CULLING`: Specifies if the culling feature is enabled or disabled (this is `false` by default).
** `IDLENESS_CHECK_PERIOD`: The polling frequency to check for a notebook's last known activity (in minutes).
** `CULL_IDLE_TIME`: The maximum allotted time to scale an inactive notebook to zero (in minutes).

* Idle workbenches stop at the time limit that you set.
//[role='_additional-resources']
//.Additional resources
