:_module-type: PROCEDURE

[id="stopping-an-active-pipeline-run_{context}"]
= Stopping an active pipeline run

[role='_abstract']
If you no longer require an active pipeline run to continue executing, you can stop the run before its defined end date.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* There is a previously created data science project available that contains a pipeline server.
* You have imported a pipeline to an active and available pipeline server.
* You have previously executed a pipeline run that you can stop.

.Procedure   
. From the {productname-short} dashboard, click *Data Science Pipelines* -> *Runs*.
+
The *Runs* page opens.
. From the *Project* list, select the project that contains the pipeline whose active run you want to stop.
+
The page refreshes to show the pipeline's active runs on the *Active* tab.
. Click the action menu (*&#8942;*) beside the active run that you want to delete and click *Stop*.
+
There might be a short delay while the run stops.

.Verification
* The status icon in the *Status* column in the *Active* tab changes to indicate that the run has stopped.

//[role='_additional-resources']
//.Additional resources
