:_module-type: PROCEDURE

[id="stopping-an-active-pipeline-run_{context}"]
= Stopping an active pipeline run

[role='_abstract']
If you no longer require an active pipeline run to continue executing, you can stop the run before its defined end date.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* There is a previously created data science project available that contains a pipeline server.
* You have imported a pipeline to an active pipeline server.
* An active pipeline run is currently executing.

.Procedure   
. From the {productname-short} dashboard, click *Data Science Pipelines* -> *Runs*.
. On the *Runs* page, select the *project* that contains the pipeline whose active run you want to stop.
. In the *Active* tab, click the action menu (*&#8942;*) beside the active run that you want to delete and click *Stop*.
+
There might be a short delay while the run stops.

.Verification
* In the list of active runs, the status of the run is "stopped".
//[role='_additional-resources']
//.Additional resources
