:_module-type: REFERENCE

[id="troubleshooting-common-problems-with-distributed-workloads-for-users_{context}"]
= Troubleshooting common problems with distributed workloads for users

[role='_abstract']
If you are experiencing errors in {productname-long} relating to distributed workloads, read this section to understand what could be causing the problem, and how to resolve the problem.

ifndef::upstream[]
If the problem is not documented here or in the release notes, contact {org-name} Support.
endif::[]

== My Ray cluster is in a suspended state

.Problem
The resource quota specified in the cluster queue configuration might be insufficient, or the resource flavor might not yet be created.

.Diagnosis
The Ray cluster head pod or worker pods remain in a suspended state.

.Resolution

ifdef::upstream,self-managed[]
. In the {openshift-platform} console, select your project from the *Project* list. 
endif::[]
ifdef::cloud-service[]
. In the OpenShift console, select your project from the *Project* list.
endif::[]
. Check the workload resource:
.. Click *Search*, and from the *Resources* list, select *Workload*.
.. Select the workload resource that is created with the Ray cluster resource, and click the *YAML* tab.
.. Check the text in the `status.conditions.message` field, which provides the reason for the suspended state, as shown in the following example:
+
[source,bash]
----
status:
 conditions:
   - lastTransitionTime: '2024-05-29T13:05:09Z'
     message: 'couldn''t assign flavors to pod set small-group-jobtest12: insufficient quota for nvidia.com/gpu in flavor default-flavor in ClusterQueue'
----
. Check the Ray cluster resource:
.. Click *Search*, and from the *Resources* list, select *RayCluster*.
.. Select the Ray cluster resource, and click the *YAML* tab.
.. Check the text in the `status.conditions.message` field.
. Check the cluster queue resource:
.. Click *Search*, and from the *Resources* list, select *ClusterQueue*.
.. Check your cluster queue configuration to ensure that the resources that you requested are within the limits defined for the project.
.. Either reduce your requested resources, or contact your administrator to request more resources. 


== My Ray cluster is in a failed state

.Problem
You might have insufficient resources.

.Diagnosis
The Ray cluster head pod or worker pods are not running.
When a Ray cluster is created, it initially enters a `failed` state. 
This failed state usually resolves after the reconciliation process completes and the Ray cluster pods are running.

.Resolution
If the failed state persists, complete the following steps:

ifdef::upstream,self-managed[]
. In the {openshift-platform} console, select your project from the *Project* list. 
endif::[]
ifdef::cloud-service[]
. In the OpenShift console, select your project from the *Project* list.
endif::[]
. Click *Search*, and from the *Resources* list, select *Pod*.
. Click your pod name to open the pod details page.
. Click the *Events* tab, and review the pod events to identify the cause of the problem.
. If you cannot resolve the problem, contact your administrator to request assistance.


== I see a "failed to call webhook" error message for the CodeFlare Operator

.Problem
After you run the `cluster.apply()` command, the following error is shown:

[source,bash]
----
ApiException: (500)
Reason: Internal Server Error
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Internal error occurred: failed calling webhook \"mraycluster.ray.openshift.ai\": failed to call webhook: Post \"https://codeflare-operator-webhook-service.redhat-ods-applications.svc:443/mutate-ray-io-v1-raycluster?timeout=10s\": no endpoints available for service \"codeflare-operator-webhook-service\"","reason":"InternalError","details":{"causes":[{"message":"failed calling webhook \"mraycluster.ray.openshift.ai\": failed to call webhook: Post \"https://codeflare-operator-webhook-service.redhat-ods-applications.svc:443/mutate-ray-io-v1-raycluster?timeout=10s\": no endpoints available for service \"codeflare-operator-webhook-service\""}]},"code":500}
----

.Diagnosis
The CodeFlare Operator pod might not be running.

.Resolution
Contact your administrator to request assistance.


== I see a "failed to call webhook" error message for Kueue

.Problem
After you run the `cluster.apply()` command, the following error is shown:

[source,bash]
----
ApiException: (500)
Reason: Internal Server Error
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Internal error occurred: failed calling webhook \"mraycluster.kb.io\": failed to call webhook: Post \"https://kueue-webhook-service.redhat-ods-applications.svc:443/mutate-ray-io-v1-raycluster?timeout=10s\": no endpoints available for service \"kueue-webhook-service\"","reason":"InternalError","details":{"causes":[{"message":"failed calling webhook \"mraycluster.kb.io\": failed to call webhook: Post \"https://kueue-webhook-service.redhat-ods-applications.svc:443/mutate-ray-io-v1-raycluster?timeout=10s\": no endpoints available for service \"kueue-webhook-service\""}]},"code":500}

----

.Diagnosis
The Kueue pod might not be running.

.Resolution
Contact your administrator to request assistance.


== My Ray cluster does not start

.Problem
After you run the `cluster.apply()` command, when you run either the `cluster.details()` command or the `cluster.status()` command, the Ray Cluster remains in the `Starting` status instead of changing to the `Ready` status.
No pods are created.

.Diagnosis

ifdef::upstream,self-managed[]
. In the {openshift-platform} console, select your project from the *Project* list. 
endif::[]
ifdef::cloud-service[]
. In the OpenShift console, select your project from the *Project* list.
endif::[]
. Check the workload resource:
.. Click *Search*, and from the *Resources* list, select *Workload*.
.. Select the workload resource that is created with the Ray cluster resource, and click the *YAML* tab.
.. Check the text in the `status.conditions.message` field, which provides the reason for remaining in the `Starting` state.
. Check the Ray cluster resource:
.. Click *Search*, and from the *Resources* list, select *RayCluster*.
.. Select the Ray cluster resource, and click the *YAML* tab.
.. Check the text in the `status.conditions.message` field.

.Resolution
If you cannot resolve the problem, contact your administrator to request assistance.


== I see a "Default Local Queue not found" error message 

.Problem
After you run the `cluster.apply()` command, the following error is shown:

[source,bash]
----
Default Local Queue with kueue.x-k8s.io/default-queue: true annotation not found please create a default Local Queue or provide the local_queue name in Cluster Configuration.
----

.Diagnosis
No default local queue is defined, and a local queue is not specified in the cluster configuration.

.Resolution
ifdef::upstream,self-managed[]
. In the {openshift-platform} console, select your project from the *Project* list. 
endif::[]
ifdef::cloud-service[]
. In the OpenShift console, select your project from the *Project* list.
endif::[]
. Click *Search*, and from the *Resources* list, select *LocalQueue*.
. Resolve the problem in one of the following ways:

* If a local queue exists, add it to your cluster configuration as follows:
+
[source,bash,subs="+quotes"]
----
local_queue="_<local_queue_name>_"
----

* If no local queue exists, contact your administrator to request assistance.


== I see a "local_queue provided does not exist" error message

.Problem
After you run the `cluster.apply()` command, the following error is shown:

[source,bash]
----
local_queue provided does not exist or is not in this namespace. Please provide the correct local_queue name in Cluster Configuration.
----

.Diagnosis
An incorrect value is specified for the local queue in the cluster configuration, or an incorrect default local queue is defined.
The specified local queue either does not exist, or exists in a different namespace.

.Resolution
ifdef::upstream,self-managed[]
. In the {openshift-platform} console, select your project from the *Project* list. 
endif::[]
ifdef::cloud-service[]
. In the OpenShift console, select your project from the *Project* list.
endif::[]
. Click *Search*, and from the *Resources* list, select *LocalQueue*.
. Resolve the problem in one of the following ways:

* If a local queue exists, ensure that you spelled the local queue name correctly in your cluster configuration, and that the `namespace` value in the cluster configuration matches your project name.
If you do not specify a `namespace` value in the cluster configuration, the Ray cluster is created in the current project.

* If no local queue exists, contact your administrator to request assistance.


== I cannot create a Ray cluster or submit jobs

.Problem
After you run the `cluster.apply()` command, an error similar to the following error is shown:

[source,bash]
----
RuntimeError: Failed to get RayCluster CustomResourceDefinition: (403)
Reason: Forbidden
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"rayclusters.ray.io is forbidden: User \"system:serviceaccount:regularuser-project:regularuser-workbench\" cannot list resource \"rayclusters\" in API group \"ray.io\" in the namespace \"regularuser-project\"","reason":"Forbidden","details":{"group":"ray.io","kind":"rayclusters"},"code":403}
----

.Diagnosis
The correct OpenShift login credentials are not specified in the `TokenAuthentication` section of your notebook code.

.Resolution
. Identify the correct OpenShift login credentials as follows:

ifdef::upstream,self-managed[]
.. In the {openshift-platform} console header, click your username and click *Copy login command*.
endif::[]
ifdef::cloud-service[]
.. In the OpenShift console header, click your username and click *Copy login command*.
endif::[]

.. In the new tab that opens, log in as the user whose credentials you want to use.
.. Click *Display Token*.
.. From the *Log in with this token* section, copy the `token` and `server` values.

. In your notebook code, specify the copied `token` and `server` values as follows:
+
[source,bash,subs="+quotes"]
----
auth = TokenAuthentication(
    token = "_<token>_",
    server = "_<server>_",
    skip_tls=False
)
auth.login()
----


== My pod provisioned by Kueue is terminated before my image is pulled

.Problem
Kueue waits for a period of time before marking a workload as ready for all of the workload pods to become provisioned and running.
By default, Kueue waits for 5 minutes. 
If the pod image is very large and is still being pulled after the 5-minute waiting period elapses, Kueue fails the workload and terminates the related pods.

.Diagnosis
ifdef::upstream,self-managed[]
. In the {openshift-platform} console, select your project from the *Project* list. 
endif::[]
ifdef::cloud-service[]
. In the OpenShift console, select your project from the *Project* list.
endif::[]
. Click *Search*, and from the *Resources* list, select *Pod*.
. Click the Ray head pod name to open the pod details page.
. Click the *Events* tab, and review the pod events to check whether the image pull completed successfully.

.Resolution
If the pod takes more than 5 minutes to pull the image, contact your administrator to request assistance.


[role='_additional-resources']
== Additional resources

ifdef::upstream[]
* link:{odhdocshome}/
managing-odh/#troubleshooting-common-problems-with-distributed-workloads-for-administrators_managing-odh[Troubleshooting common problems with distributed workloads for administrators]
* link:{odhdocshome}/managing-odh/#troubleshooting-common-problems-with-Kueue_kueue[Troubleshooting common problems with Kueue]
endif::[]
ifndef::upstream[]
* link:{rhoaidocshome}{default-format-url}/managing_openshift_ai/managing-distributed-workloads_managing-rhoai#troubleshooting-common-problems-with-distributed-workloads-for-administrators_managing-rhoai[Troubleshooting common problems with distributed workloads for administrators]
* link:{rhoaidocshome}{default-format-url}/managing_openshift_ai/managing-workloads-with-kueue#troubleshooting-common-problems-with-Kueue_kueue[Troubleshooting common problems with Kueue]
endif::[]