:_module-type: REFERENCE

[id="troubleshooting-common-problems-in-jupyter-for-administrators_{context}"]
= Troubleshooting common problems in Jupyter for administrators

[role='_abstract']
If your users are experiencing errors in {productname-long} relating to Jupyter, their notebooks, or their notebook server, read this section to understand what could be causing the problem, and how to resolve the problem.

ifndef::upstream[]
If you cannot see the problem here or in the release notes, contact Red Hat Support.
endif::[]

== A user receives a *404: Page not found* error when logging in to Jupyter

.Problem
If you have configured specialized {productname-short} user groups, the user name might not be added to the default user group for {productname-short}.

.Diagnosis
Check whether the user is part of the default user group.

. Find the names of groups allowed access to Jupyter.
ifndef::upstream[]
--
.. Log in to {openshift-platform} web console.
--
endif::[]
ifdef::upstream[]
.. Log in to {productname-short} web console.
endif::[]
.. Click *User Management* -> *Groups*.
.. Click the name of your user group, for example, `rhods-users`.
+
The *Group details* page for that group appears.

. Click the *Details* tab for the group and confirm that the *Users* section for the relevant group, contains the users who have permission to access Jupyter.

.Resolution
ifndef::upstream[]
* If the user is not added to any of the groups allowed access to Jupyter, follow link:{rhodsdocshome}{default-format-url}/managing_users/#adding-users-for-openshift-data-science_useradd[Adding users for {productname-short}] to add them.
* If the user is already added to a group that is allowed to access Jupyter, contact Red Hat Support.
endif::[]

ifdef::upstream[]
If the user is not added to any of the groups allowed access to Jupyter, add them.
endif::[]

== A user's notebook server does not start

.Problem

The {openshift-platform} cluster that hosts the user's notebook server might not have access to enough resources, or the Jupyter pod may have failed.

.Diagnosis
ifndef::upstream[]
--
ifndef::self-managed[]
. Log in to {openshift-platform} web console.
endif::[]
ifdef::self-managed[]
. Log in to {openshift-platform} web console.
endif::[]
--
endif::[]
ifdef::upstream[]
. Log in to {productname-short} web console.
endif::[]
. Delete and restart the notebook server pod for this user.
.. Click *Workloads* -> *Pods* and set the *Project* to `rhods-notebooks`.

.. Search for the notebook server pod that belongs to this user, for example, `jupyter-nb-<username>-*`.
+
If the notebook server pod exists, an intermittent failure may have occurred in the notebook server pod.
+
If the notebook server pod for the user does not exist, continue with diagnosis.
. Check the resources currently available in the OpenShift cluster against the resources required by the selected notebook server image.
+
If worker nodes with sufficient CPU and RAM are available for scheduling in the cluster, continue with diagnosis.
. Check the state of the Jupyter pod.


.Resolution
* If there was an intermittent failure of the notebook server pod:
.. Delete the notebook server pod that belongs to the user.
.. Ask the user to start their notebook server again.
* If the notebook server does not have sufficient resources to run the selected notebook server image, either add more resources to the OpenShift cluster, or choose a smaller image size.
ifndef::upstream[]
* If the Jupyter pod is in a *FAILED* state:
.. Retrieve the logs for the `jupyter-nb-*` pod and send them to Red Hat Support for further evaluation.
.. Delete the `jupyter-nb-*` pod.
* If none of the previous resolutions apply, contact Red Hat Support.
endif::[]

== The user receives a *database or disk is full* error or a *no space left on device* error when they run notebook cells

.Problem
The user might have run out of storage space on their notebook server.

.Diagnosis
. Log in to Jupyter and start the notebook server that belongs to the user having problems. If the notebook server does not start, follow these steps to check whether the user has run out of storage space:
ifndef::upstream[]
--
.. Log in to {openshift-platform} web console.
--
endif::[]
ifdef::upstream[]
. Log in to {productname-short} web console.
endif::[]
.. Click *Workloads* -> *Pods* and set the *Project* to `rhods-notebooks`.
.. Click the notebook server pod that belongs to this user, for example, `jupyter-nb-<idp>-<username>-*`.
.. Click *Logs*. The user has exceeded their available capacity if you see lines similar to the following:
+
----
Unexpected error while saving file: XXXX database or disk is full
----

.Resolution
ifndef::upstream[]
* Increase the user's available storage by expanding their persistent volume: link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.13/html/storage/expanding-persistent-volumes[Expanding persistent volumes]
endif::[]
ifdef::upstream[]
* Increase the user's available storage by expanding their persistent volume.
endif::[]

* Work with the user to identify files that can be deleted from the `/opt/app-root/src` directory on their notebook server to free up their existing storage space.


// [role='_additional-resources']
// == Additional resources
// * TODO
