:_module-type: REFERENCE
:stem:

[id="trustyai-service-cr_{context}"]
= The TrustyAI Service custom resource

Here is the default schema for the TrustyAI service custom resource (CR):

----
apiVersion: trustyai.opendatahub.io.trustyai.opendatahub.io/v1alpha1
kind: TrustyAIService
metadata:
  name: trustyai-service
spec:
  storage:
	format: "PVC"
	folder: "/inputs"
	size: "1Gi"
  data:
	filename: "data.csv"
	format: "CSV"
  metrics:
	schedule: "5s"
	batchSize: 5000 # Optional, default is 5000
----

.Description of the TrustyAI service CR fields

`metadata.name`:: The name of the TrustyAI service instance.
`spec.storage.format`:: The storage format for the data. Currently, only persistent volume control (PVC) is supported.
`spec.storage.folder`:: The location within the PVC where the data will be stored.
`spec.storage.size`:: The size of the PVC to request.
`spec.data.filename`:: The suffix for the stored data files.
`spec.data.format`:: The format of the data. Currently, only comma-separated value (CSV) format is supported.
`spec.metrics.schedule`:: The interval at which the metrics are calculated. The default is 5s. . The duration is specified with the ISO-8601 format. For example, `5s` for 5 seconds, `5m` for 5 minutes, and `5h` for 5 hours.
`spec.metrics.batchSize`:: The observation’s historical window size to use for metrics calculation. The default is `5000` (that is, the metrics are calculated by using the latest 5000 inferences).
