:_module-type: PROCEDURE

[id="updating-cluster-storage_{context}"]
= Updating cluster storage

[role='_abstract']
If your data science work requires you to change the identifying information of a project's cluster storage or the workbench that the storage is connected to, you can update your project's cluster storage to change these properties.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, `{odh-user-group}` or `{odh-admin-group}`) in OpenShift.
endif::[]
* You have created a data science project that contains cluster storage.

.Procedure
. From the {productname-short} dashboard, click *Data Science Projects*.
+
The *Data science projects* page opens.
. Click the name of the project whose storage you want to update.
+
The *Details* page for the project opens.
. Click the action menu (*&#8942;*) beside the storage that you want to update in the *Cluster storage* section and click *Edit storage*.
+
The *Edit storage* page opens.
. Update the storage's properties.
.. Update the *name* for the storage, if applicable.
.. Update the *description* for the storage, if applicable.
.. Increase the *Persistent storage size* for the storage, if applicable. 
+
Note that you can only increase the storage size. Updating the storage size restarts the workbench and makes it unavailable for a period of time that is usually proportional to the size change.
.. Update the *workbench* that the storage is connected to, if applicable.
.. If you selected a new workbench to connect the storage to, enter the storage directory in the *Mount folder* field.
. Click *Update storage*.

If you increased the storage size, the workbench restarts and is unavailable for a period of time that is usually proportional to the size change.

.Verification
* The storage that you updated appears in the *Cluster storage* section on the *Details* page for the project.


//[role='_additional-resources']
//.Additional resources
