:_module-type: PROCEDURE

[id="updating-a-connected-data-source_{context}"]
= Updating a connected data source

[role='_abstract']
To use an existing data source with a different workbench, you can change the data source that is connected to your project's workbench.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have created a data science project, created a workbench, and you have defined a data connection.

.Procedure
. From the {productname-short} dashboard, click *Data Science Projects*.
+
The *Data Science Projects* page opens.
. Click the name of the project whose data source you want to change.
+
A project details page opens.
. Click the *Data connections* tab.
. Click the action menu (*&#8942;*) beside the data source that you want to change and then click *Edit data connection*.
+
The *Edit data connection* dialog opens.
. In the *Connected workbench* section, select an existing workbench from the list.
. Click *Update data connection*.

.Verification
* The updated data connection is displayed on the *Data connections* tab for the project.
* You can access your S3 data source using environment variables in the connected workbench.

//[role='_additional-resources']
//.Additional resources
