:_module-type: PROCEDURE

[id="updating-the-deployment-properties-of-a-deployed-model_{context}"]
= Updating the deployment properties of a deployed model

[role='_abstract']
You can update the deployment properties of a model that has been deployed previously. For example, you can change the model's connection and name.

.Prerequisites
* You have logged in to {productname-long}.
* You have deployed a model on {productname-short}.

.Procedure
. From the {productname-short} dashboard, click *Models* -> *Model deployments*. 
+
The *Model deployments* page opens.
. Click the action menu (*&#8942;*) beside the model whose deployment properties you want to update and click *Edit*.
+
The *Edit model* dialog opens.
. Update the deployment properties of the model as follows:
.. In the *Model name* field, enter a new, unique name for your model.
.. From the *Model servers* list, select a model server for your model.
.. From the *Model framework* list, select a framework for your model. 
+
NOTE: The *Model framework* list shows only the frameworks that are supported by the model-serving runtime that you specified when you configured your model server.

.. Optionally, update the connection by specifying an existing connection or by creating a new connection.

.. Click *Redeploy*.

.Verification
* The model whose deployment properties you updated is displayed on the *Model deployments* page of the dashboard.
