:_module-type: PROCEDURE

[id="updating-a-model-server_{context}"]
= Updating a model server

[role='_abstract']
You can update your data science project's model server by changing details, such as the number of deployed replicas, the server size, the token authentication, and how to access the project. If you require extra power for use with large datasets, you can update you can assign accelerators to your model server to optimize performance.

.Prerequisites
* You have logged in to {productname-long}.
* You have created a data science project that has a model server assigned.

.Procedure
. From the {productname-short} dashboard, click *Data science projects*.
+
The *Data science projects* page opens.
. Click the name of the project whose model server details you want to update.
+
A project details page opens.
. Click the *Models* tab.
. Locate the model server you want to update. Click the action menu (*&#8942;*) and select *Edit model server*.
+
The *Edit model server* dialog opens.
. Update the model server properties, as follows:
+
NOTE: You cannot change the *Serving runtime* selection for a model server that is already configured. This protects against changing to a runtime that does not support already-deployed models.

.. In the *Model server name* field, enter a new, unique name for the model server.
.. In the *Number of model replicas to deploy* field, specify a value.
.. From the *Hardware profile* list, select a hardware profile.
If project-scoped hardware profiles exist, the *Hardware profile* list includes subheadings to distinguish between global hardware profiles and project-scoped hardware profiles.
+
[IMPORTANT]
====
By default, hardware profiles are hidden in the dashboard navigation menu and user interface, while accelerator profiles remain visible. In addition, user interface components associated with the deprecated accelerator profiles functionality are still displayed. If you enable hardware profiles, the *Hardware profiles* list is displayed instead of the *Accelerator profiles* list. To show the *Settings -> Hardware profiles* option in the dashboard navigation menu, and the user interface components associated with hardware profiles, set the `disableHardwareProfiles` value to `false` in the `OdhDashboardConfig` custom resource (CR) in {openshift-platform}. 
ifdef::upstream[]
For more information about setting dashboard configuration options, see link:{odhdocshome}/managing-resources/#customizing-the-dashboard[Customizing the dashboard].
endif::[]
ifndef::upstream[]
For more information about setting dashboard configuration options, see link:{rhoaidocshome}{default-format-url}/managing_resources/customizing-the-dashboard[Customizing the dashboard].
endif::[] 
====
.. Optional: Click *Customize resource requests and limit* and update the following values:
... In the *CPUs requests* field, specify the number of CPUs to use with your model server. Use the list beside this field to specify the value in cores or millicores.
... In the *CPU limits* field, specify the maximum number of CPUs to use with your model server. Use the list beside this field to specify the value in cores or millicores.
... In the *Memory requests* field, specify the requested memory for the model server in gibibytes (Gi).
... In the *Memory limits* field, specify the maximum memory limit for the model server in gibibytes (Gi).
.. Optional: In the *Model route* section, select the *Make deployed models available through an external route* checkbox to make your deployed models available to external clients.
.. Optional: In the *Token authentication* section, select the *Require token authentication* checkbox to require token authentication for your model server. To finish configuring token authentication, perform the following actions:
... In the *Service account name* field, enter a service account name for which the token will be generated. The generated token is created and displayed in the *Token secret* field when the model server is configured.
... To add an additional service account, click *Add a service account* and enter another service account name.
. Click *Configure*.

.Verification
* The model server that you updated is displayed on the *Models* tab for the project.

//[role='_additional-resources']
//.Additional resources
