:_module-type: PROCEDURE

[id="updating-the-deployment-properties-of-a-deployed-model_{context}"]
= Updating the deployment properties of a deployed model

[role='_abstract']
You can update the deployment properties of a model that has been deployed previously. This allows you to change the model's data connection and name.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, `rhods-users`) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, `odh-users`) in OpenShift.
endif::[]
* You have deployed a model on {productname-short}.

.Procedure
. From the {productname-short} dashboard, click *Model serving*.
+
The *Model Serving* page opens.
. Click the action menu (*&#8942;*) beside the model whose deployment properties you want to update and click *Edit*.
+
The *Deploy model* dialog opens.
. Update the deployment properties of the model as follows:
.. In the *Model Name* field, enter a new, unique name for the model.
.. From the *Model framework* list, select a framework for your model. 
+
NOTE: The *Model framework* list shows only the frameworks that are supported by the model-serving runtime that you specified when you configured your model server.

.. To update how you have specified the location of your model, perform one of the following sets of actions:
+
--
* *If you previously specified an existing data connection*
... In the *Folder path* field, update the folder path that contains the model in your specified data source.

* *If you previously specified a new data connection*
... In the *Name* field, update the name of the data connection.
... In the *Access key* field, update your access key ID for Amazon Web Services (AWS).
... In the *Secret key* field, update your secret access key for the AWS account you specified.
... In the *Endpoint* field, update the endpoint of your AWS S3 storage.
... In the *Region* field, update the default region of your AWS account.
... In the *Bucket* field, update the name of the AWS S3 bucket.
... In the *Folder path* field, update the folder path in your AWS S3 bucket that contains your data file. 
--

.. Click *Configure*.

.Verification
* The model whose deployment properties you updated is displayed on the *Model Serving* page.

//[role='_additional-resources']
//.Additional resources
