:_module-type: PROCEDURE

[id="updating-a-hardware-profile_{context}"]
= Updating a hardware profile

[role='_abstract']
You can update the existing hardware profiles in your deployment. You can change important identifying information, such as the display name, the identifier, or the description. 

.Prerequisites
* You have logged in to {productname-short} as a user with {productname-short} administrator privileges.
* The hardware profile exists in your deployment.

.Procedure
. From the {productname-short} dashboard, click *Settings* -> *Hardware profiles*.
+
The *Hardware profiles* page opens. Existing hardware profiles are displayed. To enable or disable a hardware profile, on the row containing the relevant hardware profile, click the toggle in the *Enabled* column.
. Click the action menu (&#8942;) and select *Edit* from the list.
+
The *Edit hardware profile* dialog opens.
. Make your changes.
. Click *Update hardware profile*.

.Verification
* If your hardware profile has new identifying information, this information is displayed in the *Hardware profile* list on the *Create workbench* page. 

[role='_additional-resources']
.Additional resources
* link:https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#toleration-v1-core[Toleration v1 core]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/nodes/controlling-pod-placement-onto-nodes-scheduling#nodes-scheduler-taints-tolerations-about_nodes-scheduler-taints-tolerations[Understanding taints and tolerations]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/operators/understanding-operators#crd-managing-resources-from-crds[Managing resources from custom resource definitions]