:_module-type: PROCEDURE

ifdef::context[:parent-context: {context}]
[id="updating-lmeval-job-configuration-using-the-web-console_{context}"]
= Updating LMEval job configuration using the web console

[role='_abstract']
Follow these steps to enable online access (`allowOnline`) and remote code execution (`allowCodeExecution`) modes through the {productname-short} web console for LMEval jobs. 

[IMPORTANT]
====
Enabling online access or code execution involves a security risk. Only use these configurations if you trust the source(s).
====

.Prerequisites

* You have cluster administrator privileges for your {productname-long} cluster.

.Procedure
. Navigate to *Workloads → ConfigMaps*.

. Select the *`pass:attributes[{dbd-config-default-namespace}]`* namespace.

. Open the *`trustyai-service-operator-config`* ConfigMap.

. Under *Annotations*, add:
+
[source, yaml]
----
opendatahub.io/managed: "false"
----
. Under *Data*, add or update:
+
[source, yaml]
----
lmes-allow-online: "true"
lmes-allow-code-execution: "true"
----
. Save the ConfigMap.

. Navigate to *Workloads → Deployments*.

. Select the *`pass:attributes[{dbd-config-default-namespace}]`* namespace.

. Locate *`trustyai-service-operator-controller-manager`*.

. Click the *Actions* menu and select *Restart rollout*.
+
[NOTE]
--
Each LMEval job must explicitly be set to allow online access and code execution.
--
. Ensure that the following fields are set to `true` to enable online access and code execution for this job when writing your `LMEvalJob` custom resource:
+
[source,yaml]
----
apiVersion: trustyai.opendatahub.io/v1alpha1
kind: LMEvalJob
metadata:
  name: example-lmeval
spec:
  allowOnline: true
  allowCodeExecution: true
  
----


.Configuration keys for LMEvalJob custom resource
[cols="3,2,5", options="header"]
|===
| Field
| Default
| Description

| `spec.allowOnline`
| `false`
| Enables this job to access the internet (e.g., to download datasets or tokenizers).

| `spec.allowCodeExecution`
| `false`
| Allows this job to run code included with downloaded resources.
|===
