:_module-type: PROCEDURE

[id='updating-the-deployment-properties-of-a-deployed-model-version-from-a-model-registry_{context}']
= Updating the deployment properties of a deployed model version from a model registry

[role='_abstract']
You can update the deployment details of model versions that were deployed from a model registry.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* An available model registry exists in your deployment, and contains at least 1 registered model with a deployed model version.
* You have access to the model registry that contains the model version deployment that you want to edit.

.Procedure
. From the {productname-short} dashboard, click *Model Registry*.
. From the *Model registry* drop-down menu, select the model registry that contains the model that you want to edit.
. The *Model Registry* page provides a high-level view of registered models, including the model name, labels, last modified timestamp, and owner of each model.
. Click the name of a model to view more details.
+
The details page for the model opens.
. Click the name of the model version with the deployment that you want to update.
+
The details page for the mode version opens.
. Click *Deployments*.
. To update the details of a deployment, click the action menu (*&#8942;*) beside the deployment, and then click *Edit*. 
+
The *Edit model* dialog opens.
ifdef::upstream[]
. Configure the remaining properties for deploying your model, as described in link:{odhdocshome}/serving-models/#deploying-a-model-using-the-multi-model-serving-platform_model-serving[Deploying a model by using the multi-model serving platform] or link:{odhdocshome}/serving-models/#deploying-models-using-the-single-model-serving-platform_serving-large-models[Deploying a model by using the single-model serving platform].
endif::[]
ifndef::upstream[]
. Configure the remaining properties for deploying your model, as described in link:{rhoaidocshome}{default-format-url}/serving_models/serving-small-and-medium-sized-models_model-serving#deploying-a-model-using-the-multi-model-serving-platform_model-serving[Deploying a model by using the multi-model serving platform] or link:{rhoaidocshome}{default-format-url}/serving_models/serving-large-models_serving-large-models#deploying-models-on-the-single-model-serving-platform_serving-large-models[Deploying a model by using the single-model serving platform].
endif::[]
. Click *Redeploy*.


.Verification
* The updated deployment appears on the *Deployments* page for the model version.

//[role='_additional-resources']
//.Additional resources