:_module-type: PROCEDURE

[id="updating-a-data-science-project_{context}"]
= Updating a data science project

[role='_abstract']
You can update the project details by changing the project name and description.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have created a data science project.

.Procedure
. From the {productname-short} dashboard, click *Data Science Projects*.
+
The *Data Science Projects* page opens.
. Click the action menu (*&#8942;*) beside the project whose details you want to update and click *Edit project*.
+
The *Edit project* dialog opens.
. Optional: Edit the *Name* field to change the display name for your project.
. Optional: Edit the *Description* field to change the description of your project.
. Click *Update*.

.Verification
* You can see the updated project details on the *Data Science Projects* page.

//[role='_additional-resources']
//.Additional resources
