:_module-type: PROCEDURE

[id="updating-a-connected-data-source_{context}"]
= Updating a connected data source

[role='_abstract']
To use an existing data source with a different workbench, you can change the data source that is connected to your project's workbench.

.Prerequisites
* You have logged in to {productname-long}.
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, `rhods-users`) in OpenShift.
* You have created a data science project, created a workbench, and you have defined a data connection.

.Procedure
. From the {productname-short} dashboard, click *Data Science Projects*.
+
The *Data science projects* page opens.
. Click the name of the project whose data source you want to change.
+
A project details page opens.
. Click the action menu (*&#8942;*) beside the data source that you want to change in the *Data connections* section and click *Change connected workbenches*.
+
The *Update connected workbenches* dialog opens.
. Select an existing *workbench* to connect the data source to from the list.
. Click *Update connected workbenches*.

.Verification
* The data connection that you changed is displayed in the *Data connections* section on the project *Details* page.
* You can access your S3 data source using environment variables in the connected workbench.

//[role='_additional-resources']
//.Additional resources
