:_module-type: PROCEDURE

[id="updating-your-playground-configuration_{context}"]
= Updating your playground configuration

[role="_abstract"]

You can update the configuration of your playground instance to add new models, re-register models that were stopped, or change the existing configuration.

[WARNING]
====
Updating the playground configuration will permanently delete the inline vector database for *all users* in your project.
====

.Prerequisites
* You have configured a playground for your project.

.Procedure
. From the {productname-short} dashboard, click *Gen AI studio* -> *Playground*.
. Select the project containing your model deployment from the *Project* dropdown list.
. In the upper-right corner of your playground, click the action menu (⋮) and select *Update configuration*.
. On the configuration screen, select or clear the checkboxes for the models you want to make available.
. Click *Update*.

.Verification

* The playground configuration is updated with a new selection of models.

