:_module-type: PROCEDURE

[id="updating-a-project-workbench_{context}"]
= Updating a project workbench

[role='_abstract']
If your data science work requires you to change your workbench's notebook image, container size, or identifying information, you can update the properties of your project's workbench. If you require extra power for use with large datasets, you can assign accelerators to your workbench to optimize performance.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you use {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you use {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have created a data science project that has a workbench.

.Procedure
. From the {productname-short} dashboard, click *Data science projects*.
+
The *Data science projects* page opens.
. Click the name of the project whose workbench you want to update.
+
A project details page opens.
. Click the *Workbenches* tab.
. Click the action menu (*&#8942;*) beside the workbench that you want to update and then click *Edit workbench*.
+
The *Edit workbench* page opens.
. Update any of the workbench properties and then click *Update workbench*.

.Verification
* The workbench that you updated appears on the *Workbenches* tab for the project.

//[role='_additional-resources']
//.Additional resources
