:_module-type: PROCEDURE

[id="updating-the-deployment-properties-of-a-deployed-model_{context}"]
= Updating the deployment properties of a deployed model from a model registry

[role='_abstract']
You can update the deployment properties of a model that has was deployed from a model registry. For example, you can change the model's connection and name.

.Prerequisites
* An available model registry exists in your deployment, and contains at least 1 registered and deployed model version.

.Procedure
. From the {productname-short} dashboard, click *Model Registry*.
. From the *Model registry* drop-down menu, select the model registry that contains the model deployment that you want to edit.
. In the *Model name* column, click the name of the model that contains the deployment that you want to edit.
+
The details page for the model opens.
. Click the name of the model version with the deployment that you want to edit.
. Click *Deployments*.
. Click the action menu (*&#8942;*) beside the model deployment that you want to edit.
. Click *Edit*.
. In the *Edit model* dialog, update the model deployment properties:
.. From the *Project* drop-down list, select a project in which to deploy your model.
.. Optional: In the *Model deployment name* field, enter a name for the model deployment. 
+
Each deployment is named in the following format by default:
+
`<model name> <model version name> <deployment creation timestamp>`
+
This will be the name of the inference service that is created when the model is deployed.
ifdef::upstream[]
. Configure the remaining properties for deploying your model, as described in link:{odhdocshome}/serving-models/#deploying-a-model-using-the-multi-model-serving-platform_model-serving[Deploying a model by using the multi-model serving platform] or link:{odhdocshome}/serving-models/#deploying-models-using-the-single-model-serving-platform_serving-large-models[Deploying a model by using the single-model serving platform].
endif::[]
ifndef::upstream[]
. Configure the remaining properties for deploying your model, as described in link:{rhoaidocshome}{default-format-url}/serving_models/serving-small-and-medium-sized-models_model-serving#deploying-a-model-using-the-multi-model-serving-platform_model-serving[Deploying a model by using the multi-model serving platform] or link:{rhoaidocshome}{default-format-url}/serving_models/serving-large-models_serving-large-models#deploying-models-on-the-single-model-serving-platform_serving-large-models[Deploying a model by using the single-model serving platform].
endif::[]
.. Click *Redeploy*.			 

.Verification
* The model version appears with updated details on the *Deployments* tab for the model version.
* The model version deployment restarts ?

// [role="_additional-resources"]
// .Additional resources
// * TODO or delete
