:_module-type: PROCEDURE

[id="updating-a-project-workbench_{context}"]
= Updating a project workbench

[role='_abstract']
If your data science work requires you to change your workbench's notebook image, container size, or identifying information, you can modify the properties of your project's workbench.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, `rhods-users`) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, `odh-users`) in OpenShift.
endif::[]
* You have created a data science project that contains a workbench.

.Procedure
. From the {productname-short} dashboard, click *Data Science Projects*.
+
The *Data science projects* page opens.
. Click the name of the project whose workbench you want to update.
+
The *Details* page for the project opens.
. Click the action menu (*&#8942;*) beside the workbench that you want to update in the *Workbenches* section and click *Edit workbench*.
+
The *Edit workbench* page opens.
. Update the workbench's properties.
.. Update the *name* for your workbench, if applicable.
.. Update *description* for your workbench, if applicable.
.. Select a new *notebook image* to use for your workbench server, if applicable.
.. Select a new *container size* for your server, if applicable.
. Click *Update workbench*.

.Verification
* The workbench that you updated appears on the *Details* page for the project.

//[role='_additional-resources']
//.Additional resources
