:_module-type: PROCEDURE

[id="updating-a-data-science-project_{context}"]
= Updating a data science project

[role='_abstract']
You can update your data science project's details by changing your project's name and description text.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have created a data science project.

.Procedure
. From the {productname-short} dashboard, click *Data Science Projects*.
+
The *Data science projects* page opens.
. Click the action menu (*&#8942;*) beside the project whose details you want to update and click *Edit project*.
+
The *Edit data science project* dialog opens.
. Optional: Update the *name* for your data science project.
. Optional: Update the *description* for your data science project.
. Click *Update*.

.Verification
* The data science project that you updated is displayed on the *Data science projects* page.

//[role='_additional-resources']
//.Additional resources
