:_module-type: PROCEDURE

[id="updating-a-model-server_{context}"]
= Updating a model server

[role='_abstract']
You can update your data science project's model server by changing details, such as the number of deployed replicas, the server size, the token authentication, and how to access the project. If you require extra power for use with large datasets, you can update you can assign accelerators to your model server to optimize performance.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you use {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you use {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have created a data science project that has a model server assigned.

.Procedure
. From the {productname-short} dashboard, click *Data Science Projects*.
+
The *Data Science Projects* page opens.
. Click the name of the project whose model server details you want to update.
+
A project details page opens.
. Click the *Models* tab.
. Locate the model server you want to update. Click the action menu (*&#8942;*) and select *Edit model server*.
+
The *Edit model server* dialog opens.
. Update the model server properties, as follows:
+
NOTE: You cannot change the *Serving runtime* selection for a model server that is already configured. This protects against changing to a runtime that does not support already-deployed models.

.. In the *Model server name* field, enter a new, unique name for the model server.

.. In the *Number of model replicas to deploy* field, specify a value.
.. From the *Model server size* list, select a value.
.. Optional: If you selected *Custom* in the preceding step, configure the following settings in the *Model server size* section to customize your model server:
... In the *CPUs requested* field, specify the number of CPUs to use with your model server. Use the list beside this field to specify the value in cores or millicores.
... In the *CPU limit* field, specify the maximum number of CPUs to use with your model server. Use the list beside this field to specify the value in cores or millicores.
... In the *Memory requested* field, specify the requested memory for the model server in gibibytes (Gi).
... In the *Memory limit* field, specify the maximum memory limit for the model server in gibibytes (Gi).
.. Optional: From the *Accelerator* list, select an accelerator.
.. If you selected an accelerator in the preceding step, specify the number of accelerators to use.
.. Optional: In the *Model route* section, select the *Make deployed models available through an external route* checkbox to make your deployed models available to external clients.
.. Optional: In the *Token authentication* section, select the *Require token authentication* checkbox to require token authentication for your model server. To finish configuring token authentication, perform the following actions:
... In the *Service account name* field, enter a service account name for which the token will be generated. The generated token is created and displayed in the *Token secret* field when the model server is configured.
... To add an additional service account, click *Add a service account* and enter another service account name.
. Click *Configure*.

.Verification
* The model server that you updated appears on the *Models* tab for the project.

//[role='_additional-resources']
//.Additional resources
