:_module-type: PROCEDURE

[id="updating-the-deployment-properties-of-a-deployed-model_{context}"]
= Updating the deployment properties of a deployed model

[role='_abstract']
You can update the deployment properties of a model that has been deployed previously. This allows you to change the model's data connection and name.

.Prerequisites
* You have logged in to {productname-long}.
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, `rhods-users`) in OpenShift.
* You have deployed a model on {productname-short}.

.Procedure
. From the {productname-short} dashboard, click *Model serving*.
+
The *Model Serving* page opens.
. Click the action menu (*&#8942;*) beside the model whose deployment properties you want to update and click *Edit*.
+
The *Deploy model* dialog opens.
. Update the deployment properties of the model.
.. Update the *name* of the model.
.. Select an option to specify the location of your model.
... If you selected *Existing data connection*, update the *folder path* of your existing data connection.
... If you selected *New data connection*, update the relevant fields to add a new data connection.
.... Update the data connection *name*.
.... Update your access key ID for Amazon Web Services in the *AWS_ACCESS_KEY_ID* field.
.... Update your secret access key for the account you specified in the *AWS_ACCESS_KEY_ID* field.
.... Update the endpoint of your AWS S3 storage in the *AWS_S3_ENDPOINT* field.
.... Update the default region of your AWS account in the *AWS_DEFAULT_REGION* field.
.... Update the name of the AWS S3 bucket in the *AWS_S3_BUCKET* field.
.... Update the *folder path* of the file containing the data.
.. Click *Configure*.

.Verification
* The model whose deployment properties you updated is displayed on the *Model Serving* page.

//[role='_additional-resources']
//.Additional resources
