:_module-type: PROCEDURE

[id="updating-an-accelerator-profile_{context}"]
= Updating an accelerator profile

[role='_abstract']
You can update the existing accelerator profiles in your deployment. You might want to change important identifying information, such as the display name, the identifier, or the description. 

.Prerequisites
* You have logged in to {productname-long}.
ifdef::cloud-service[]
* You are part of the `cluster-admins` or `dedicated-admins` user group in your OpenShift cluster. The `dedicated-admins` user group applies only to OpenShift Dedicated.
endif::[]
ifdef::self-managed[]
* You are assigned the `cluster-admin` role in {openshift-platform}.
endif::[]
* The accelerator profile exists in your deployment.

.Procedure
. From the {productname-short} dashboard, click *Settings* -> *Notebook images*.
+
The *Notebook images* page appears. Previously imported notebook images are displayed. To enable or disable a previously imported notebook image, on the row containing the relevant notebook image, click the toggle in the *Enable* column.
. Click the action menu (&#8942;) and select *Edit* from the list.
+
The *Edit accelerator profile* dialog opens.
. In the *Name* field, update the accelerator profile name.
. In the *Identifier* field, update the unique string that identifies the hardware accelerator associated with the accelerator profile, if applicable.
. Optional: In the *Description* field, update the accelerator profile.
. To enable or disable the accelerator profile immediately after creation, click the toggle in the *Enable* column.
. Optional: Add a toleration to schedule pods with matching taints.
.. Click *Add toleration*. 
+
The *Add toleration* dialog opens.
.. From the *Operator* list, select one of the following options:
* *Equal* - The *key/value/effect* parameters must match. This is the default.
* *Exists* - The *key/effect* parameters must match. You must leave a blank value parameter, which matches any.
.. From the *Effect* list, select one of the following options:
* *None* 
* *NoSchedule* - New pods that do not match the taint are not scheduled onto that node. Existing pods on the node remain.
* *PreferNoSchedule* - New pods that do not match the taint might be scheduled onto that node, but the scheduler tries not to. Existing pods on the node remain.
* *NoExecute* - New pods that do not match the taint cannot be scheduled onto that node. Existing pods on the node that do not have a matching toleration are removed.
.. In the *Key* field, enter a toleration key. The key is any string, up to 253 characters. The key must begin with a letter or number, and may contain letters, numbers, hyphens, dots, and underscores.
.. In the *Value* field, enter a toleration value. The value is any string, up to 63 characters. The value must begin with a letter or number, and may contain letters, numbers, hyphens, dots, and underscores.
.. In the *Toleration Seconds* section, select one of the following options to specify how long a pod stays bound to a node that has a node condition. 
** *Forever* - Pods stays permanently bound to a node. 
** *Custom value* - Enter a value, in seconds, to define how long pods stay bound to a node that has a node condition.
.. Click *Add*.
. If your accelerator profile contains existing tolerations, you can edit them.
.. Click the action menu (&#8942;) on the row containing the toleration that you want to edit and select *Edit* from the list.
.. Complete the applicable fields to update the details of the toleration.
.. Click *Update*.
. Click *Update accelerator profile*.

.Verification
* If your accelerator profile has new identifying information, this information appears in the *Accelerator* list on the *Start a notebook server* page. 

[role='_additional-resources']
.Additional resources
* link:https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#toleration-v1-core[Toleration v1 core]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/nodes/controlling-pod-placement-onto-nodes-scheduling#nodes-scheduler-taints-tolerations-about_nodes-scheduler-taints-tolerations[Understanding taints and tolerations]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/operators/understanding-operators#crd-managing-resources-from-crds[Managing resources from custom resource definitions]