:_module-type: PROCEDURE

[id="uploading-training-data-to-trustyai_{context}"]
= Uploading training data to TrustyAI

[role='_abstract']
Upload training data to use with TrustyAI for bias monitoring or data drift detection.

.Prerequisites

* Your cluster administrator added you as a user to the {openshift-platform} cluster and has installed the TrustyAI service for the data science project that contains the deployed models.

* You have model training data to upload.

ifndef::upstream[]
* You authenticated the TrustyAI service as described in link:{rhoaidocshome}{default-format-url}/monitoring_data_science_models/
setting-up-trustyai-for-your-project_monitor#authenticating-trustyai-service_monitor[Authenticating the TrustyAI service]. 
endif::[]
ifdef::upstream[]
* You authenticated the TrustyAI service as described in link:{odhdocshome}/monitoring-data-science-models/#authenticating-trustyai-service_monitor[Authenticating the TrustyAI service].
endif::[]


.Procedure

. Set the `TRUSTY_ROUTE` variable to the external route for the TrustyAI service in your project:
+
----
TRUSTY_ROUTE=https://$(oc get route/trustyai-service --template={{.spec.host}})
----

. Send the training data to the `/data/upload` endpoint:
+
----
curl -sk $TRUSTY_ROUTE/data/upload  \
  --header 'Authorization: Bearer ${TOKEN}' \
  --header 'Content-Type: application/json' \
  -d @data/training_data.json
----

+
The following message appears if the upload was successful: `1000 datapoints successfully added to gaussian-credit-model data`.

.Verification

* Verify that TrustyAI has received the data via the `/info` endpoint by inputting this query:
+
----
curl -H 'Authorization: Bearer ${TOKEN}' \
    $TRUSTY_ROUTE/info | jq ".[0].data"
----

+
The output returns a json file containing the following information for the model:

** The names, data types, and positions of fields in the input and output.

** The observed values that these fields take. This value is usually `null` because there are too many unique feature values to enumerate.

** The total number of input-output pairs observed. It should be `1000`.

