:_module-type: PROCEDURE

[id="using-custom-workbench-images-using-elyra_{context}"]
= Using custom workbench images with Elyra

[role='_abstract']
Elyra can be used to customize {productname-short} default workbench images.

[NOTE]
====
Elyra is only available as an extension of JupyterLab, and is not available for code-server or RStudio. For more information about the Elyra JupyterLab extension, see link:https://elyra.readthedocs.io/en/stable/getting_started/overview.html[Elyra Documentation].
====

.Prerequisites
* You know which default image you want to use as the base for your custom image. 
ifndef::upstream[]
+
See link:https://access.redhat.com/articles/rhoai-supported-configs[Supported Configurations] for a list of the {productname-short} default workbench images and their preinstalled packages.
endif::[]

* You have `cluster-admin` access to the OpenShift console for the cluster where {productname-short} is installed. 

* 

.Procedure
. Start from one of the default images, as described in link:{odhdocshome}/managing-odh/#creating-a-custom-image-from-default-image_custom-images[Creating a custom image from a default {productname-short} image].
. 

.Verification
* 