:_module-type: PROCEDURE

[id='using-the-cluster-CA-bundle-for-single-model-serving_{context}']
= Using the cluster-wide CA bundle for the single-model serving platform

By default, the single-model serving platform in {productname-short} uses a self-signed certificate generated at installation for the endpoints that are created when deploying a server. 

If you have configured cluster-wide certificates on your OpenShift cluster, they are used by default for other types of endpoints, such as endpoints for routes.

The following procedure explains how to use the same certificate that you already have for your OpenShift cluster.

.Prerequisites

* You have cluster administrator access for the OpenShift cluster where {productname-long} is installed.
* You have configured cluster-wide certificates in OpenShift.

ifndef::upstream[]
ifdef::self-managed[]
* You have configured the single-model serving platform, as described in link:{rhoaidocshome}{default-format-url}/installing_and_uninstalling_openshift_ai_self-managed/installing-the-single-model-serving-platform_component-install[Installing the single-model serving platform].
endif::[]
ifdef::cloud-service[]
* You have configured the single-model serving platform, as described in link:{rhoaidocshome}{default-format-url}/installing_and_uninstalling_openshift_ai_cloud_service/installing-the-single-model-serving-platform_component-install[Installing the single-model serving platform].
endif::[]
endif::[]

.Procedure
. Log in to the OpenShift console. 
. From the list of projects, open the `openshift-ingress` project.
. Click *YAML*.
. Search for "cert" to find a secret with a name that includes "cert". For example, `rhods-internal-primary-cert-bundle-secret`. The contents of the secret should contain two items that are used for all OpenShift Routes: `tls.cert` (the certificate) and `tls.key` (the key).
. Copy the reference to the Secret.
. From the list of projects, open the `istio-system` project.
. Create a new YAML file and paste the reference to the Secret that you copied from the `openshift-ingress` YAML file.
. Edit the YAML code to keep only the relevant content, as shown in the following example. Replace `rhods-internal-primary-cert-bundle-secret` with the name of your secret (the secret name is normally related to your cluster name):
+
[.lines_space]
[source, yaml]
----
kind: Secret
apiVersion: v1
metadata:
name: rhods-internal-primary-cert-bundle-secret
data:
tls.crt: >-
    LS0tLS1CRUd...
tls.key: >-
    LS0tLS1CRUd...
type: kubernetes.io/tls
----

. Save the YAML file in the `istio-system` project.
. Navigate to *Operators* -> *Installed Operators* -> *{productname-long}*. 
. Click *Data* Science Cluster*, and then click *default-dsc* -> *YAML*.
. Edit the kserve configuration section to refer to your secret as shown in the following example. Replace `rhods-internal-primary-cert-bundle-secret` with the name of the secret that you created in Step 8.
+
[.lines_space]
[source, yaml]
----
kserve:
devFlags: {}
managementState: Managed
serving:
    ingressGateway:
    certificate:
        secretName: rhods-internal-primary-cert-bundle-secret
        type: Provided
    managementState: Managed
    name: knative-serving
----