:_module-type: PROCEDURE

[id='viewing-data-science-users_{context}']
= Viewing {productname-short} users
If you have defined specialized user groups for {productname-short}, you can view the users that belong to these groups.

.Prerequisites
* The {productname-long} user group, administrator group, or both exist.
ifndef::self-managed[]
* You have the `cluster-admin` role or you are part of the `dedicated-admins` administrator group.
endif::[]
ifdef::self-managed[]
* You have the `cluster-admin` role in {openshift-platform}.
endif::[]
* You have configured a supported identity provider for {openshift-platform}.


.Procedure

. In the {openshift-platform} web console, click *User Management* -> *Groups*.
. Click the name of the group containing the users that you want to view.
** For administrative users, click the name of your administrator group. for example, {oai-admin-group}.
** For normal users, click the name of your user group, for example, {oai-user-group}.
+
The *Group details* page for the group appears.

.Verification
* In the *Users* section for the relevant group, you can view the users who have permission to access {productname-long}.

