:_module-type: PROCEDURE

[id="viewing-archived-pipeline-runs_{context}"]
= Viewing archived pipeline runs

[role='_abstract']
You can view a list of pipeline runs that you have archived. You can view details for your archived pipeline runs, such as the pipeline version, run status, duration, and execution start date.

.Prerequisites

* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group} ) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have previously created a data science project that is available and has a pipeline server.
* You have imported a pipeline to an active pipeline server.
* An archived pipeline run exists.

.Procedure
. From the {productname-short} dashboard, click *Data Science Pipelines* -> *Runs*.
. On the *Runs* page, select the *project* for the archived pipeline runs that you want to view.
. Click the *Archived* tab.

.Verification
* A list of archived runs appears in the *Archived* tab on the *Runs* page.

//[role='_additional-resources']
//.Additional resources
