:_module-type: PROCEDURE

[id="viewing-a-deployed-model_{context}"]
= Viewing a deployed model

[role='_abstract']
To analyze the results of your work, you can view a list of deployed models on {productname-long}. You can also view the current statuses of deployed models and their endpoints.

.Prerequisites
* You have logged in to {productname-long}.

.Procedure
. From the {productname-short} dashboard, click *AI hub* -> *Deployments*. 
+
The *Deployments* page opens.
+
For each model, the page shows details such as the model name, the project in which the model is deployed, the model-serving runtime that the model uses, and the deployment status.
. Optional: For a given model, click the link in the *Inference endpoints* column to see the inference endpoints for the deployed model.

.Verification
* A list of previously deployed data science models is displayed on the *Deployments* page.

ifdef::upstream[]
[role='_additional-resources']
.Additional resources

* To learn how to monitor your model for bias, see link:{odhdocshome}/monitoring-data-science-models[Monitoring data science models].
endif::[]
