:_module-type: PROCEDURE

[id="viewing-archived-pipeline-runs_{context}"]
= Viewing archived pipeline runs

[role='_abstract']
You can view a list of pipeline runs that you have retained in your run archive. From your run archive you can view details relating to your archived pipeline runs, such as the such as the pipeline version that the run belongs to, along with the run status, duration, and execution start date.

.Prerequisites

* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group} ) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* You have previously created a data science project that is available and has a pipeline server.
* You have imported a pipeline to an active and available pipeline server.
* An archived pipeline run exists and is available to view.

.Procedure
. From the {productname-short} dashboard, click *Data Science Pipelines* -> *Runs*.
+
The *Runs* page opens.
. From the *Project* list, select the project whose archived pipeline runs you want to view.
+
The *Runs* page displays the active pipeline runs for the project.
. Click the *Archived* tab.
+
A table opens that shows list of archived runs. 

.Verification
* A list of archived runs is displayed in the *Archived* tab on the *Runs* page.

//[role='_additional-resources']
//.Additional resources
