:_module-type: PROCEDURE
//pv2hash: 55b41598-ac2e-4719-a284-ceda9bb94b19

[id="viewing-python-packages-installed-on-your-notebook-server_{context}"]
= Viewing Python packages installed on your notebook server

[role='_abstract']
You can check which Python packages are installed on your notebook server and which version of the package you have by running the `pip` tool in a notebook cell.

.Prerequisites
* Log in to Jupyter and open a notebook.

.Procedure

. Enter the following in a new cell in your notebook:
+
[source,role="execute"]
----
!pip list
----
. Run the cell.

.Verification
* The output shows an alphabetical list of all installed Python packages and their versions. For example, if you use this command immediately after creating a notebook server that uses the *Minimal* image, the first packages shown are similar to the following:
+
[source,subs="+quotes"]
----
Package                           Version
--------------------------------- ----------
aiohttp                           3.7.3
alembic                           1.5.2
appdirs                           1.4.4
argo-workflows                    3.6.1
argon2-cffi                       20.1.0
async-generator                   1.10
async-timeout                     3.0.1
attrdict                          2.0.1
attrs                             20.3.0
backcall                          0.2.0
----

[role="_additional-resources"]
.Additional resources
ifndef::upstream[]
* link:{rhodsdocshome}{default-format-url}/working_on_data_science_projects/working-on-data-science-projects_nb-server#installing-python-packages-on-your-notebook-server_nb-server[Installing Python packages on your notebook server]
endif::[]
