:_module-type: PROCEDURE

[id='viewing-accelerator-profiles_{context}']
= Viewing accelerator profiles
If you have defined accelerator profiles for {productname-short}, you can view them from the *Accelerator profiles* page. You can also  enable or disable an accelerator profile from this page. 

.Prerequisites
* You have logged in to {productname-long}.
ifndef::self-managed[]
* You are part of the `dedicated-admins` user group in {openshift-platform}.
endif::[]
ifdef::self-managed[]
* You are assigned the `cluster-admin` role in {openshift-platform}.
endif::[]
* Your deployment contains existing accelerator profiles. 

.Procedure
. From the {productname-short} dashboard, click *Settings* -> *Accelerator profiles*.
+
The *Accelerator profiles* page appears that shows existing accelerator profiles. 
. Inspect the list of accelerator profiles. To enable or disable an accelerator profile, on the row containing the relevant accelerator profile, click the toggle in the *Enable* column.

.Verification
* The *Accelerator profiles* page appears that shows existing accelerator profiles.

