:_module-type: PROCEDURE

[id="viewing-pipeline-artifacts_{context}"]
= Viewing pipeline artifacts

[role='_abstract']
After a pipeline run executes, you can view its pipeline artifacts from the {productname-short} dashboard. Pipeline artifacts can help you to evaluate the performance of your pipeline runs and make it easier to understand your pipeline components. Pipeline artifacts can range from plain text data to detailed, interactive data visualizations.  

.Prerequisites
* You have logged in to {productname-long}.
* You have previously created a project that is available and contains a pipeline server.
* You have imported a pipeline to an active pipeline server.
* You have previously triggered a pipeline run.

.Procedure
. From the {productname-short} dashboard, click *Develop & train* -> *Pipelines* -> *Artifacts*.
. On the *Artifacts* page, from the *Project* drop-down list, select the project that contains the pipeline experiment for the pipeline artifacts that you want to view.
. Click an artifact name in the list to view additional information about the artifact, including its original run, original execution, and properties.
. To view or download the content of an artifact stored in S3-compatible object storage, click the preview icon, the download icon, or the active artifact URI link.
+
Clicking the preview icon or the URI link for content that your browser can display (such as plain text, HTML, or markdown) opens the artifact in a new browser tab. Clicking the download icon or the URI link for content that your browser cannot display (such as a model file) downloads the artifact. To download an artifact that is displayed in a browser tab, right-click the content and then click *Save as*. 

.Verification
* On the *Artifacts* page, you can view the details of each pipeline artifact, such as its name, unique ID, type, and URI. 

//[role='_additional-resources']
//.Additional resources
