:_module-type: PROCEDURE

[id="viewing-registered-model-versions_{context}"]
= Viewing registered model versions

[role='_abstract']
You can view the details of model versions that are registered in {productname-short}, such as the version metadata and deployment information.

.Prerequisites
* You have logged in to {productname-long}.
* An available model registry exists in your deployment, and contains at least 1 registered model.
* You have access to the model registry that contains the model version that you want to view.

.Procedure
. From the {productname-short} dashboard, click *AI hub* -> *Registry*.
. From the *Model registry* drop-down list, select the model registry that contains the model version that you want to view.
. Click the name of a model to view *Overview* tab on the model details page, which includes the latest model versions and deployments. 
. On the *Versions* tab, you can view the registered versions of the model.
+
Versions are sorted by their *Last modified* timestamp by default.
. Use the search bar to find a version in the list. You can filter with a keyword by default by entering a model name, description, or label. Alternatively, click the search bar drop-down list and select *Author* to filter by entering a model owner.
+
Searching by keyword performs a search across the name, description, and labels of registered models and their versions.
. Click the name of a version to view the version details page.
. On the *Details* tab, you can view the *Version details* metadata, such as labels, description, custom properties, version ID, author, and last modified and registered timestamps. This also includes where the model is registered from, model location, and model format information. 
+
You can also click *Model details* to view non-version metadata, such as labels, description, owner, model ID, last modified and created timestamps, and custom properties.
. On the *Deployments* tab, you can view deployments initiated from the model registry for this version.
.. Click the name of a deployment to open its metrics page. 
+
ifndef::upstream[]
For information about model metrics, see link:{rhoaidocshome}{default-format-url}/deploying_models/deploying_models_on_the_model_serving_platform#viewing-performance-metrics-for-deployed-model_rhoai-user[Viewing performance metrics for a deployed model]. 
endif::[]
ifdef::upstream[]
For information about model metrics, see link:{odhdocshome}/managing-and-monitoring-models/#_monitoring_model_performance_2[Managing and monitoring models: Monitoring model performance]. 
endif::[]

.Verification
* You can view the details of registered model versions on the *Model registry* page.

//[role='_additional-resources']
//.Additional resources
