:_module-type: PROCEDURE

[id="viewing-bias-metrics_{context}"]
= Viewing bias metrics for a model

[role='_abstract']
When you configure your model for bias monitoring, you can use the {productname-short} dashboard to view and update the metrics you have configured.

.Prerequisites
* You have configured bias metrics for your model. See 

.Procedure
. In the {productname-short} dashboard, click *Model Serving*.
+
The *Model serving* page opens.

. On the *Model serving* page, click the name of a model that you want to want to view bias metrics for.
+
A metrics page for the model opens. By default, the *Endpoint Performance* tab is selected.

. To update the metrics shown on the page, perform the following actions:
.. In the *Metrics to display* section, use the *Select a metric* list to select a metric to show on the page.
+
NOTE: Each time you select a metric to show on the page, an additional *Select a metric* list appears. This enables you to show multiple metrics on the page.
.. From the *Time range* list in the upper-right corner, select a value.
.. From the *Refresh interval* list in the upper-right corner, select a value.
+
The metrics page shows the metrics you selected.
. Optional: To remove one or more metrics from the page, in the *Metrics to display* section, perform one of the following actions:
* To remove an individual metric, click the cancel icon (&#10006;) next to the metric name.
* To remove all metrics, click the cancel icon (&#10006;) in the *Select a metric* list.
. Optional: To return to configuring bias metrics for the model, on the metrics page, click *Configure* in the upper-right corner.

.Verification
* The metrics page shows the metrics selctions you made.


