:_module-type: PROCEDURE

[id="viewing-models-in-the-catalog_{context}"]
= Viewing models in the model catalog
[role='_abstract']
You can discover and evaluate the available generative AI models in the model catalog to find the best fit for your use cases.

.Prerequisites
* You are logged in to {productname-long}.
ifdef::upstream[]
* The model registry component is enabled in your {productname-short} deployment. For more information, see link:{odhdocshome}/working-with-model-registries/#enabling-the-model-registry-component_model-registry[Enabling the model registry component].
endif::[]
ifdef::self-managed[]
* The model registry component is enabled in your {productname-short} deployment. For more information, see link:{rhoaidocshome}{default-format-url}/enabling_the_model_registry_component[Enabling the model registry component].
endif::[]

.Procedure
. From the {productname-short} dashboard, click *Models* -> *Model catalog*.
. The *Model Catalog* page provides a high-level view of available models, including the model name, description, and labels such as task, license, and provider.

. In the drop-down list, select from the available catalog sources that have been configured by your administrator. The *Default Catalog* is displayed by default. 
+
NOTE: OpenShift cluster administrators can configure additional model catalog sources. For more details, see the Kubeflow Model Registry community documentation on link:https://github.com/kubeflow/model-registry/tree/main/manifests/kustomize/options/catalog#configuring-catalog-sources[configuring catalog sources]. 

. Use the search bar to find a model in the catalog. You can enter text to search by model name, description, or provider.

. Click the name of a model to view the model details page. This page displays the model description and the *Model card* information supplied by the model provider. This includes details such as the model's intended use and potential limitations, training parameters and datasets, and evaluation results.  

. You can click *Load more models* to scroll and view additional models available in the catalog. Repeat this step until all models are loaded.

.Verification
* You can view the information about a selected model on the model details page.

//[role='_additional-resources']
//.Additional resources

