:_module-type: PROCEDURE

[id="viewing-bias-metrics_{context}"]
= Viewing bias metrics for a model

[role='_abstract']
After you configure your model for bias monitoring, you can use the {productname-short} dashboard to view and update the metrics that you configured.

.Prerequisite

ifndef::upstream[]
* You configured bias metrics for your model as described in link:{rhoaidocshome}{default-format-url}/monitoring_data_science_models/configuring-bias-metrics-for-a-model_bias-monitoring#creating-a-bias-metric_bias-monitoring[Creating a bias metric].

endif::[]
ifdef::upstream[]
* You configured bias metrics for your model as described in link:{odhdocshome}/monitoring_data_science_models/#creating-a-bias-metric_bias-monitoring[Creating a bias metric].
endif::[]

.Procedure

////
Admin view

== Viewing bias metrics for a model 

When you configure your model for bias monitoring, you can view the metrics that you configured.

.Prerequisites

* You configured bias metrics for your model as described in link:{odhdocshome}/monitoring_data_science_models/#creating-bias-monitoring_bias-monitoring[Configuring bias monitoring for a model].

* You have admin access to the OpenShift web console.

.Procedure

* From the *Administrator* perspective within the OpenShift web console, select *Observe* -> *Metrics*.
////

. In the {productname-short} dashboard, click *Model Serving*.
. On the *Deployed models* page, click the name of a model that you want to view bias metrics for.
. To update the metrics shown on the page, follow these steps:
.. In the *Metrics to display* section, use the *Select a metric* list to select a metric to show on the page.
+
NOTE: Each time you select a metric to show on the page, an additional *Select a metric* list appears. This enables you to show multiple metrics on the page.
.. From the *Time range* list in the upper-right corner, select a value.
.. From the *Refresh interval* list in the upper-right corner, select a value.
+
The metrics page shows the metrics that you selected.
. Optional: To remove one or more metrics from the page, in the *Metrics to display* section, perform one of the following actions:
* To remove an individual metric, click the cancel icon (&#10006;) next to the metric name.
* To remove all metrics, click the cancel icon (&#10006;) in the *Select a metric* list.
. Optional: To return to configuring bias metrics for the model, on the metrics page, click *Configure* in the upper-right corner.

.Verification
* The metrics page shows the metrics selections that you made.


