:_module-type: PROCEDURE

[id="viewing-pipeline-task-executions_{context}"]
= Viewing pipeline task executions

[role='_abstract']
When a pipeline run executes, you can view details of executed tasks in each step in a pipeline run from the {productname-short} dashboard. A step forms part of a task in a pipeline.

.Prerequisites
* You have logged in to {productname-long}.
* You have previously created a project that is available and contains a pipeline server.
* You have imported a pipeline to an active pipeline server.
* You have previously triggered a pipeline run.

.Procedure
. From the {productname-short} dashboard, click *Experiments* -> *Executions*.
. On the *Executions* page, from the *Project* drop-down list, select the project that contains the experiment for the pipeline task executions that you want to view.

.Verification
* On the *Executions* page, you can view the execution details of each pipeline task execution, such as its name, status, unique ID, and execution type. The execution status indicates whether the pipeline task has successfully executed. For further information about the details of the task execution, click the execution name. 


//[role='_additional-resources']
//.Additional resources
