:_module-type: PROCEDURE

[id="viewing-the-performance-metrics-of-a-deployed-model_{context}"]
= Viewing the performance metrics of a deployed model

[role='_abstract']

ifndef::upstream[]
[IMPORTANT]
====
This feature is for Technology Preview only. Technology Preview features are not supported with {org-name} production service level agreements (SLAs), might not be functionally complete, and {org-name} does not recommend using them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process. 			
For more information on {org-name} Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/ [Technology Preview Features Scope]. 		
====
endif::[]

To ensure that your deployed model is functioning correctly, you can monitor the model's performance metrics. The following metrics are tracked in {productname-short}:

* Requests per day (x100)
* Average response time (ms)
* CPU utilization (%)
* Memory utilization (%)




.Prerequisites
* You have installed {productname-long}.

* On the OpenShift cluster where {productname-short} is installed, you have enabled user workload monitoring as described in link:https://docs.openshift.com/container-platform/{ocp-latest-version}/monitoring/enabling-monitoring-for-user-defined-projects.html[Enabling monitoring for user-defined projects].

* You have logged in to {productname-short}.
ifndef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, `{oai-user-group}` or `{oai-admin-group}`) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using specialized {productname-short} groups, you are part of the user group or admin group (for example, `{odh-user-group}` or `{odh-admin-group}`) in OpenShift.
endif::[]
* There are deployed data science models available on the *Model Serving* page.

.Procedure
. From the {productname-short} dashboard, click *Model Serving*.
+
The *Model Serving* page opens.
. Click the model whose performance metrics you want to view.
+
The *Metrics* page opens.

.Verification
* The *Metrics* page displays the performance metrics for the relevant model.


