:_module-type: PROCEDURE

[id='viewing-accelerator-profiles_{context}']
= Viewing accelerator profiles
If you have defined accelerator profiles for {productname-short}, you can view, enable, and disable them from the *Accelerator profiles* page.

.Prerequisites
* You have logged in to {productname-long}.
ifdef::cloud-service[]
* You are part of the `cluster-admins` or `dedicated-admins` user group in your OpenShift cluster. The `dedicated-admins` user group applies only to OpenShift Dedicated.
endif::[]
ifdef::self-managed[]
* You are assigned the `cluster-admin` role in {openshift-platform}.
endif::[]
* Your deployment contains existing accelerator profiles. 

.Procedure
. From the {productname-short} dashboard, click *Settings* -> *Accelerator profiles*.
+
The *Accelerator profiles* page appears, displaying existing accelerator profiles. 
. Inspect the list of accelerator profiles. To enable or disable an accelerator profile, on the row containing the accelerator profile, click the toggle in the *Enable* column.

.Verification
* The *Accelerator profiles* page appears appears, displaying existing accelerator profiles.

