:_module-type: PROCEDURE

[id="viewing-registered-model-versions_{context}"]
= Viewing registered model versions

[role='_abstract']
You can view the details of model versions that are registered in {productname-short}, such as the version metadata and deployment information.

.Prerequisites
* You have logged in to {productname-long}.
* You have previously created a data science project that contains an available model registry.
*

.Procedure
. From the {productname-short} dashboard, click *Model Registry*.
. From the *Model registry* dropdown menu, select the model registry that contains the models that you want to view.
. Click the name of a model to view its versions.
+
The details page for the model opens.
. On the *Versions* tab, you can view registered versions of the model.
. Click the name of a version to view more details.
+
The details page for the version opens.
. On the *Details* tab, you can view
** *Description*
** *Labels*
** *Properties*
** *Version ID*
** *Model location*:    
*** *Endpoint*
*** *Region*
*** *Bucket*
*** *Path*
*** *Source model format*
*** *Author*
*** *Last modified at*
*** *Registered*
.. On the *Deployments* tab, you can view deployments initiated from model registry for this model version.

.Verification
* You can view the details of registered model versions on the *Model Registry* page.

//[role='_additional-resources']
//.Additional resources
