:_module-type: PROCEDURE

[id="viewing-registered-model-versions_{context}"]
= Viewing registered model versions

[role='_abstract']
You can view the details of model versions that are registered in {productname-short}, such as the version metadata and deployment information.

.Prerequisites
* You have logged in to {productname-long}.
ifndef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {oai-user-group} or {oai-admin-group}) in OpenShift.
endif::[]
ifdef::upstream[]
* If you are using {productname-short} groups, you are part of the user group or admin group (for example, {odh-user-group} or {odh-admin-group}) in OpenShift.
endif::[]
* An available model registry exists in your deployment, and contains at least one registered model.

.Procedure
. From the {productname-short} dashboard, click *Model Registry*.
. From the *Model registry* dropdown menu, select the model registry that contains the models that you want to view.
. Click the name of a model to view its versions.
+
The details page for the model opens.
. On the *Versions* tab, you can view registered versions of the model.
. Click the name of a version to view more details.
+
The details page for the version opens.
. On the *Details* tab, you can view the description, labels, custom properties, version ID, author, and *Last modified* and *Registered* timestamps for the model. You can also view the source model format, and location information for the model.
. On the *Deployments* tab, you can view deployments initiated from the model registry for this version.
.. Click the name of a deployment to open its metrics page. 
+
ifndef::upstream[]
For information about model metrics on the single-model serving platform, see link:{rhoaidocshome}{default-format-url}/serving_models/serving-large-models_serving-large-models#viewing-performance-metrics-for-deployed-model_serving-large-models[Serving large models: Monitoring model performance]. For information about model metrics on the multi-model serving platform, see link:{rhoaidocshome}{default-format-url}
/serving_models/serving-small-and-medium-sized-models_model-serving#viewing-performance-metrics-for-model-server_model-serving[Serving small and medium sized models: Monitoring model performance]. 
endif::[]
ifdef::upstream[]
For information about model metrics on the single-model serving platform, see link:{odhdocshome}/serving-models/#_monitoring_model_performance_2[Serving large models: Monitoring model performance]. For information about model metrics on the multi-model serving platform, see link:{odhdocshome}/serving-models/#_monitoring_model_performance[Serving small and medium sized models: Monitoring model performance]. 
endif::[]

.Verification
* You can view the details of registered model versions on the *Model Registry* page.

//[role='_additional-resources']
//.Additional resources
