:_module-type: PROCEDURE

[id="viewing-registered-models_{context}"]
= Viewing registered models

[role='_abstract']
You can view the details of models registered in {productname-short}, such as the models's x and y.

.Prerequisites
* You have logged in to {productname-long}.
* You have previously created a data science project that contains an active and available model registry.
*

.Procedure
. From the {productname-short} dashboard, click *Model Registry*.
. From the *Model registry* dropdown menu, select the model registry that contains the models that you want to view.
. On the *Model Registry* page, you can see
>>a high-level view of registered models - model name, any labels, last modified timestamp, and the owner of the model.
. Click the name of a model to view more details.
+
The details page for the model opens.
. On the *Versions* tab, you can view registered versions of the model

.Verification
* You can view the details of registered models on the *Model Registry* page.

//[role='_additional-resources']
//.Additional resources
