:_module-type: CONCEPT

[id='working-with-accelerator-profiles_{context}']
= Working with accelerator profiles

[role='_abstract']
To configure accelerators for your data scientists to use in {productname-short}, you must create an associated accelerator profile. An accelerator profile is a custom resource definition (CRD) on OpenShift that has an AcceleratorProfile resource, and defines the specification of the accelerator. You can create and manage accelerator profiles by selecting *Settings* -> *Accelerator profiles* on the {productname-short} dashboard.

For accelerators that are new to your deployment, you must manually configure an accelerator profile for each accelerator. If your deployment contains an accelerator before you upgrade, the associated accelerator profile remains after the upgrade. You can manage the accelerators that appear to your data scientists by assigning specific accelerator profiles to your custom notebook images. This example shows the code for a Habana Gaudi 1 accelerator profile:
[source,yaml]
---
apiVersion: dashboard.opendatahub.io/v1alpha
kind: AcceleratorProfile
metadata:
  name: hpu-profile-first-gen-gaudi
spec:
  displayName: Habana HPU - 1st Gen Gaudi
  description: First Generation Habana Gaudi device
  enabled: true
  identifier: habana.ai/gaudi
  tolerations:
    - effect: NoSchedule
      key: habana.ai/gaudi
      operator: Exists
---

The accelerator profile code appears on the *Instances* tab on the details page for the `AcceleratorProfile` custom resource definition (CRD). For more information about accelerator profile attributes, see the following table: 

[id="table-accelerator-profile-attributes_{context}"]

.Accelerator profile attributes
[cols="1,1,1,5",header]
|===
| Attribute | Type | Required | Description  

| displayName
| String
| Required
| The display name of the accelerator profile.

| description
| String
| Optional
| Descriptive text defining the accelerator profile.

| identifier
| String
| Required
| A unique identifier defining the accelerator resource.

| enabled
| Boolean
| Required
| Determines if the accelerator is visible in {productname-short}.

| tolerations
| Array
| Optional
| The tolerations that can apply to notebooks and serving runtimes that use the accelerator. For more information about toleration attributes in {productname-short}, see link:https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#toleration-v1-core[Toleration v1 core].

|===

[role="_additional-resources"]
.Additional resources
* link:https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#toleration-v1-core[Toleration v1 core]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/nodes/controlling-pod-placement-onto-nodes-scheduling#nodes-scheduler-taints-tolerations-about_nodes-scheduler-taints-tolerations[Understanding taints and tolerations]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-latest-version}/html/operators/understanding-operators#crd-managing-resources-from-crds[Managing resources from custom resource definitions]
