---
layout: docs
title: Monitoring Data Science Models
permalink: /docs/monitoring-data-science-models
custom_css: asciidoc.css
---
//:self-managed:
:upstream:
include::_artifacts/document-attributes-global.adoc[]

:doctype: book
:toc: left
:compat-mode:
:context: monitor-models

= Monitoring data science models

ifndef::upstream[]
[IMPORTANT]
====
The TrustyAI features are for Technology Preview only. Technology Preview features are not supported with {org-name} production service level agreements (SLAs), might not be functionally complete, and {org-name} does not recommend using them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process. 			
For more information on {org-name} Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/ [Technology Preview Features Scope]. 		
====
endif::[]

The TrustyAI service provides data scientists with value-added capabilities, such as explainability (enriching model execution information through XAI algorithms) and model bias detection.

include::modules/enabling-trustyai-service-cli.adoc[leveloffset=+1]

include::assemblies/monitoring-models-for-bias.adoc[leveloffset=+1]


