---
layout: docs
title: Working On Data Science Projects
permalink: /docs/working-on-data-science-projects
custom_css: asciidoc.css
---

:upstream:
include::_artifacts/document-attributes-global.adoc[]

:doctype: book
:toc: left
:compat-mode:
:context: projects

= Working on data science projects

[role='_abstract']
As a data scientist, you can organize your data science work into a single project. A data science project in {productname-short} can consist of the following components:

Workbenches:: Creating a workbench allows you to work with models in your preferred IDE, such as JupyterLab.
Cluster storage:: For data science projects that require data retention, you can add cluster storage to the project.
Connections:: Adding a connection to your project allows you to connect data sources and sinks to your workbenches.
Pipelines:: Standardize and automate machine learning workflows to enable you to further enhance and deploy your data science models.
Models and model servers:: Deploy a trained data science model to serve intelligent applications. Your model is deployed with an endpoint that allows applications to send requests to the model.
ifdef::upstream[]
Bias metrics for models:: Creating bias metrics allows you to monitor your machine learning models for bias.
endif::[]

include::assemblies/using-data-science-projects.adoc[leveloffset=+1]

include::assemblies/using-project-workbenches.adoc[leveloffset=+1]

include::assemblies/using-connections.adoc[leveloffset=+1]

include::assemblies/configuring-cluster-storage.adoc[leveloffset=+1]

include::assemblies/managing-access-to-data-science-projects.adoc[leveloffset=+1]





