---
layout: docs
title: Working with model registries
permalink: /docs/working-with-model-registries
custom_css: asciidoc.css
---
:upstream:
include::_artifacts/document-attributes-global.adoc[]

:doctype: book
:toc: left
:compat-mode:
:context: model-registry

include::modules/overview-of-model-registries.adoc[leveloffset=+1]

= Enabling the model registry component

As an OpenShift cluster administrator, after upgrading, you can enable the model registry component for {productname-short} administrators and data scientists to use, if this component was not enabled in a previous {productname-short} version. 

include::modules/enabling-the-model-registry-component.adoc[leveloffset=+1]

= Managing model registries

As an {productname-short} administrator, you can create, delete, and manage permissions for model registries in {productname-short}.

include::modules/creating-a-model-registry.adoc[leveloffset=+1]
include::modules/editing-a-model-registry.adoc[leveloffset=+1]
include::modules/managing-model-registry-permissions.adoc[leveloffset=+1]
include::modules/deleting-a-model-registry.adoc[leveloffset=+1]


= Working with model registries

As a data scientist in {productname-short}, you can store, share, version, deploy, and track models by using the model registry feature. 

include::assemblies/working-with-model-registries.adoc[leveloffset=+1]

= Working with the model catalog
As a data scientist in {productname-short}, you can discover, compare, and evaluate the generative AI models that are available in the model catalog for your organization to register, deploy, and customize. 

include::modules/viewing-models-in-the-catalog.adoc[leveloffset=+1]
include::modules/registering-a-model-from-the-model-catalog.adoc[leveloffset=+1]
include::modules/deploying-a-model-from-the-model-catalog.adoc[leveloffset=+1]


