---
layout: docs
title: Working with connected applications
permalink: /docs/working-with-connected-applications
custom_css: asciidoc.css
---

:upstream:
include::_artifacts/document-attributes-global.adoc[]

:doctype: book
:toc: left
:compat-mode:
:context: connected-apps

= Working with connected applications

You can extend {productname-long} capabilities by connecting to a wide range of open source and third-party applications, such as Starburst, Intel AI Tools, Anaconda, and IBM watsonx.ai.

You can also remove unused applications from your {productname-short} dashboard so that you can focus on the applications that you are most likely to use. 

include::modules/viewing-connected-applications.adoc[leveloffset=+1]

include::modules/enabling-applications-connected.adoc[leveloffset=+1]

include::modules/removing-disabled-applications.adoc[leveloffset=+1]

== Using the Jupyter application
{productname-long} provides access to Jupyter as an enabled application for situations where, for example, you do not want users to have their own data science projects or you want to open a notebook that was developed outside of {productname-short} and has no dependencies on other environments. 

ifndef::upstream[] 
Note that the preferred way to access Jupyter on {productname-short} is through a data science project, as described in link:{rhoaidocshome}{default-format-url}/working_on_data_science_projects/working-on-data-science-projects_nb-server#creating-a-workbench-select-ide_nb-server[Creating a workbench and selecting an IDE]. The advantages to using an {productname-short} data science project and creating a workbench that includes Jupyter, is that your project organizes your data science work in one place and adds functionality such as data connections so that you can access data and save your models and pipelines for automating your ML workflow.
endif::[]
ifdef::upstream[]
Note that the preferred way to access Jupyter on {productname-short} is through a data science project, as described in link:{odhdocshome}/working_on_data_science_projects/#_using_project_workbenches[Creating a workbench and selecting an IDE]. The advantages to using an {productname-short} data science project and creating a workbench that includes Jupyter, is that your project organizes your data science work in one place and adds functionality such as data connections so that you can access data and save your models and pipelines for automating your ML workflow.
endif::[]


include::modules/starting-a-jupyter-notebook-server.adoc[leveloffset=+2]

=== Creating and importing notebooks

[role='_abstract']
You can create a blank notebook or import a notebook from several different sources.

include::modules/creating-a-new-notebook.adoc[leveloffset=+3]

include::modules/uploading-an-existing-notebook-file-from-local-storage.adoc[leveloffset=+3]

include::assemblies/collaborating-on-notebooks-using-git.adoc[leveloffset=+2]

=== Managing Python packages

In JupyterLab, you can view the Python packages that are installed on your notebook image and install additional packages.

include::modules/viewing-python-packages-installed-on-your-notebook-server.adoc[leveloffset=+3]

include::modules/installing-python-packages-on-your-notebook-server.adoc[leveloffset=+3]

include::modules/updating-notebook-server-settings-by-restarting-your-server.adoc[leveloffset=+2]

