---
layout: docs
title: Working in your data science IDE
permalink: /docs/serving-models
custom_css: asciidoc.css
---

:upstream:
include::_artifacts/document-attributes-global.adoc[]

:doctype: book
:toc: left
:compat-mode:
:context: ide

= Working in your data science IDE

In {productname-long}, when you create a workbench, you select a workbench image that includes an IDE for developing your machine learning models. 

{productname-short} supports the following data science IDEs for developing ML models:

* JupyterLab
* code-server (Technology Preview feature)
ifdef::cloud-service[]
* RStudio Server (Technology Preview feature) 
endif::[]

include::modules/accessing-your-workbench-ide.adoc[leveloffset=+1]

== Working in JupyterLab

JupyterLab is the latest web-based interactive development environment for notebooks, code, and data. You can configure and arrange workflows in data science and machine learning. JupyterLab is an open-source web application that supports over 40 programming languages, including Python and R.

include::assemblies/creating-and-importing-notebooks.adoc[leveloffset=+2]

include::assemblies/collaborating-on-notebooks-using-git.adoc[leveloffset=+2]

=== Managing Python packages

In JupyterLab, you can view the Python packages that are installed on your notebook image and install additional packages.

include::modules/viewing-python-packages-installed-on-your-notebook-server.adoc[leveloffset=+3]

include::modules/installing-python-packages-on-your-notebook-server.adoc[leveloffset=+3]

include::modules/troubleshooting-common-problems-in-jupyter-for-users.adoc[leveloffset=+2]

include::modules/working-in-code-server.adoc[leveloffset=+1]

include::modules/working-in-rstudio-server.adoc[leveloffset=+1]