---
layout: docs
title: Working in your data science IDE
permalink: /docs/working-in-your-data-science-ide
custom_css: asciidoc.css
---

:upstream:

include::_artifacts/document-attributes-global.adoc[]

= Working in your data science IDE
:doctype: book
:toc: left
:compat-mode:
:context: ide
 
In {productname-long}, when you create a workbench, you select a workbench image that includes an IDE (integrated development environment) for developing your machine learning models. 

{productname-short} supports the following data science IDEs for developing ML models:

* JupyterLab
* code-server
//* RStudio Server

include::modules/accessing-your-workbench-ide.adoc[leveloffset=+1]

== Working in JupyterLab

JupyterLab is a web-based interactive development environment for workbenches, code, and data. You can configure and arrange workflows in data science and machine learning. JupyterLab is an open source web application that supports over 40 programming languages, including Python and R.

include::assemblies/creating-and-importing-notebooks.adoc[leveloffset=+2]

include::assemblies/collaborating-on-notebooks-by-using-git.adoc[leveloffset=+2]

include::assemblies/managing-python-packages.adoc[leveloffset=+2]

include::modules/troubleshooting-common-problems-in-jupyter-for-users.adoc[leveloffset=+2]

== Working in code-server

{productname-long} includes the code-server workbench image. For more information, see link:https://github.com/coder/code-server[code-server in GitHub^].

NOTE: Elyra-based pipelines are not available with the code-server workbench image. 

include::modules/creating-a-project-workbench.adoc[leveloffset=+2]

include::assemblies/collaborating-on-workbenches-in-code-server-by-using-git.adoc[leveloffset=+2]

include::assemblies/managing-python-packages-in-code-server.adoc[leveloffset=+2]

include::modules/installing-extensions-with-code-server.adoc[leveloffset=+2]
