---
layout: docs
title: Working in your data science IDE
permalink: /docs/working-in-your-data-science-ide
custom_css: asciidoc.css
---

:upstream:

include::_artifacts/document-attributes-global.adoc[]

= Working in your data science IDE
:doctype: book
:toc: left
:compat-mode:
:context: ide
 
In {productname-long}, when you create a workbench, you select a workbench image that includes an IDE (integrated development environment) for developing your machine learning (ML) models. 

You can use the following data science IDEs for developing ML models with {productname-short}: 

* JupyterLab
* code-server
//* RStudio Server

include::modules/accessing-your-workbench-ide.adoc[leveloffset=+1]

== Working in JupyterLab

JupyterLab is a web-based interactive development environment for Jupyter notebooks, code, and data. You can configure and arrange workflows in data science and machine learning. JupyterLab is an open source web application that supports over 40 programming languages, including Python and R.

include::assemblies/creating-and-importing-jupyter-notebooks.adoc[leveloffset=+2]

include::assemblies/collaborating-on-jupyter-notebooks-by-using-git.adoc[leveloffset=+2]

include::assemblies/managing-python-packages.adoc[leveloffset=+2]

include::modules/troubleshooting-common-problems-in-workbenches-for-users.adoc[leveloffset=+2]

== Working in code-server

Code-server is a web-based interactive development environment supporting multiple programming languages, including Python, for working with Jupyter notebooks. With the code-server workbench image, you can customize your workbench environment to meet your needs using a variety of extensions to add new languages, themes, debuggers, and connect to additional services. For more information, see link:https://github.com/coder/code-server[code-server in GitHub^]. 

NOTE: Elyra-based pipelines are not available with the code-server workbench image. 

include::assemblies/creating-code-server-workbenches.adoc[leveloffset=+2]

include::assemblies/collaborating-on-workbenches-in-code-server-by-using-git.adoc[leveloffset=+2]

include::assemblies/managing-python-packages-in-code-server.adoc[leveloffset=+2]

include::modules/installing-extensions-with-code-server.adoc[leveloffset=+2]
