---
layout: docs
title: Working with model registries and model catalog
permalink: /docs/working-with-model-registries
custom_css: asciidoc.css
---
:upstream:
include::_artifacts/document-attributes-global.adoc[]

:doctype: book
:toc: left
:compat-mode:
:context: model-registry

include::modules/overview-of-model-registries.adoc[leveloffset=+1]

= Enabling the model registry

As an OpenShift cluster administrator, if the model registry was not enabled in a previous {productname-short} version, after upgrading, you must enable this component for {productname-short} administrators, data scientists, and AI engineers to use. 

include::modules/enabling-the-model-registry-component.adoc[leveloffset=+1]


= Working with the model catalog

As a data scientist or AI engineer in {productname-short}, you can discover and evaluate the generative AI models that are available in the model catalog. From the model catalog, you can select models that you want to register, deploy, and customize.

include::assemblies/working-with-the-model-catalog.adoc[leveloffset=+1]

= Managing model registries

As an {productname-short} administrator, you can create, delete, and manage permissions for model registries in {productname-short}.

include::modules/creating-a-model-registry.adoc[leveloffset=+1]
include::modules/editing-a-model-registry.adoc[leveloffset=+1]
include::modules/managing-model-registry-permissions.adoc[leveloffset=+1]
include::modules/deleting-a-model-registry.adoc[leveloffset=+1]

= Working with model registries

As a data scientist or AI engineer in {productname-short}, you can store, share, version, deploy, and track models by using the model registry. 

include::assemblies/working-with-model-registries.adoc[leveloffset=+1]

