:_module-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

[id="configuring-distributed-workloads_{context}"]
= Configuring distributed workloads

[role='_abstract']
ifdef::self-managed,cloud-service[]
To configure the distributed workloads feature for your data scientists to use in {productname-short}, you must enable several components in the {productname-long} {install-package}, create the required Kueue resources, and optionally configure the CodeFlare Operator.
endif::[]
ifdef::upstream[]
To configure the distributed workloads feature for your data scientists to use in {productname-short}, you must enable several components in the {productname-long} Operator, create the required Kueue resources, and optionally configure the CodeFlare Operator.
endif::[]

include::modules/configuring-the-distributed-workloads-components.adoc[leveloffset=+1]
include::modules/configuring-quota-management-for-distributed-workloads.adoc[leveloffset=+1]
include::modules/configuring-the-codeflare-operator.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
