:_module-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

:context: permission-based-roles

[id="creating-resource-based-permissions"]
= Creating resource-based permissions for your project

When you are creating a project, there are two default permissions that are provided by {productname-long} depending on your access level: *contributor* and *admin*. These permissions affect the actions you are able to take within a project.

You are also able to create custom permission-based roles for your project that are more specifically tailored to your needs, which allows you to manage who can view, edit, connect to, or delete specific workbench instances within a shared project. 

If you are a {productname-short} or {openshift-platform} cluster administrator, you can create permissions in any project. If you are not an administrator, you can still create permissions in the projects that you own.

.Additional resources

For more information about resource-based permissions, see the following resources:

* link:https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/{ocp-latest-version}/html/managing_openshift_ai/managing-users-and-groups#overview-of-user-types-and-permissions_managing-rhoai[Overview of user types and permissions]

//determining if we need more resources

include::modules/applying-resource-based-roles-cli.adoc[leveloffset=+1]