:_module-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

:context: dashboard

[id="customizing-the-dashboard"]
= Customizing the dashboard
:upstream:
//:preview:

ifdef::preview[]
include::../_artifacts/document-attributes-global.adoc[]
endif::preview[]

The {productname-short} dashboard provides features that are designed to work for most scenarios. 
These features are configured in the `OdhDashboardConfig` custom resource (CR).

To see a description of the options in the {productname-short} dashboard configuration, see link:{odhdocshome}/managing-resources/#ref-dashboard-configuration-options_dashboard[Dashboard configuration options].

As an administrator, you can customize the interface of the dashboard.
For example, you can show or hide some of the dashboard navigation menu items. 
To change the default settings of the dashboard, edit the `OdhDashboardConfig` CR as described in link:{odhdocshome}/managing-resources/#editing-the-dashboard-configuration_dashboard[Editing the dashboard configuration].

include::modules/editing-the-dashboard-configuration.adoc[leveloffset=+1]
include::modules/ref-dashboard-configuration-options.adoc[leveloffset=+1]


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
