:_module-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

:context: dashboard

[id="customizing-the-dashboard"]
= Customizing the dashboard
:upstream:
//:preview:

ifdef::preview[]
include::../_artifacts/document-attributes-global.adoc[]
endif::preview[]

The {productname-short} dashboard provides features that are designed to work for most scenarios. These features are configured in the OdhDashboardConfig custom resource (CR) file.

To see a description of the options in the {productname-short} dashboard configuration file, see xref:ref-dashboard-configuraion-options[Dashboard configuration options].

As an administrator, you can customize the interface of the dashboard, for example to show or hide some of the dashboard’s navigation menu options. To change the default settings of the dashboard, edit the `OdhDashboardConfig` custom resource (CR) file as described in xref:editing-the-dashboard-configuration-file[Editing the dashboard configuration file].

include::modules/editing-the-dashboard-configuration-file.adoc[leveloffset=+1]
include::modules/ref-dashboard-configuration-options.adoc[leveloffset=+1]


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
