:_module-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

[id="enabling-external-resource-access-for-lmeval-jobs_{context}"]
= Enabling external resource access for LMEval Jobs

[role='_abstract']
LMEval Jobs do not allow internet access or remote code execution by default. When configuring an `LMEvalJob`, it may require access to external resources, for example task datasets and model tokenizers, usually hosted on link:https://huggingface.co[Hugging Face]. If you trust the source and have reviewed the content of these artifacts, `LMEvalJob` can be configured to automatically download them.

Follow the steps below to enable online access and remote code execution for LMEval Jobs. Choose to update these settings by using either the CLI or in the console.

include::modules/updating-lmeval-job-configuration-using-the-cli.adoc[leveloffset=+1]

include::modules/updating-lmeval-job-configuration-using-the-console.adoc[leveloffset=+1]









// Incl NOTE ? Opt in to online/code access per LMEvalJob

// . Option 1/2: Enabling allowOnline and allowCodeExecution modes in your cluster




////
In an `LMEvalJob`, there are two configuration options that might require access to external resources: the task dataset and model tokenizer.
You can set your `LMEvalJob` to access online content by updating and patching the TrustyAI operator `ConfigMap`. 

. In the `ConfigMap`, change the `opendatahub.io/managed` setting to `'false'`. 

. Patch the TrustyAI operator `ConfigMap` with the following code: 
+
[source]
----
 oc patch configmap trustyai-service-operator-config -n redhat-ods-applications \
--type merge -p '{"data":{"lmes-allow-online":"true","lmes-allow-code-execution":"true"}}'
----
+
. Restart the TrustyAI operator with the following command: 
+
[source]
----
oc rollout restart deployment trustyai-service-operator-controller-manager -n redhat-ods-applications
----

////


