:_module-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

:context: installv2

[id="installing-odh-v2_{context}"]
= Installing Open Data Hub version 2

[role='_abstract']
You can install Open Data Hub version 2 on your OpenShift Container Platform from the OpenShift web console. 
For information about upgrading the Open Hub Operator, see link:{odhdocshome}/upgrading_open_data_hub[Upgrading Open Data Hub].
 
Installing Open Data Hub involves the following tasks:

. Installing the Open Data Hub Operator.
. Installing Open Data Hub components.
. Accessing the Open Data Hub dashboard.

[NOTE]
--
Version 2 of the Open Data Hub Operator represents an alpha release, accessible only on the *fast* channel. Later releases will change to the *rolling* channel when the Operator is more stable.
--

[IMPORTANT]
----
Data Science Pipelines (DSP) 2.0 contains an installation of Argo Workflows. {productname-short} does not support direct customer usage of this installation of Argo Workflows.

If there is an existing installation of Argo Workflows that is not installed by DSP on your cluster, installations of and upgrades to {productname-short} 2.10.0 with DSP will fail.

To install or upgrade to {productname-short} 2.10.0 with DSP, you must ensure that no separate installation of Argo Workflows exists on your cluster.
----

include::modules/installing-the-odh-operator-v2.adoc[leveloffset=+1]

include::modules/installing-odh-components.adoc[leveloffset=+1]

include::modules/accessing-the-odh-dashboard.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
