:_module-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

:context: installv2

[id="installing-odh-v2_{context}"]
= Installing Open Data Hub version 2

[role='_abstract']
You can install Open Data Hub version 2 on your OpenShift Container Platform from the OpenShift web console. 
For information about upgrading the Open Hub Operator, see link:{odhdocshome}/upgrading-open-data-hub[Upgrading Open Data Hub].
 
Installing Open Data Hub involves the following tasks:

. Installing the Open Data Hub Operator.
. Installing Open Data Hub components.
. Accessing the Open Data Hub dashboard.

[NOTE]
--
Version 2 of the Open Data Hub Operator represents an alpha release, accessible only on the *fast* channel. Later releases will change to the *rolling* channel when the Operator is more stable.
--
[NOTE]
--
After you install {productname-short} {vernum}, pipelines created with DSP 1.0 continue to run, but are inaccessible from the {productname-short} dashboard. If you are a current DSP user, do not install {productname-short} with DSP 2.0 until you are ready to migrate to the new pipelines solution.
--
[IMPORTANT]
====
Data Science Pipelines (DSP) 2.0 contains an installation of Argo Workflows. {productname-short} does not support direct customer usage of this installation of Argo Workflows. To install {productname-short} 2.10.0 with DSP, ensure that no separate installation of Argo Workflows exists on your cluster.

If there is an existing installation of Argo Workflows that is not installed by DSP on your cluster, DSP will be disabled after you install {productname-short} 2.10.0 with DSP.

To enable data science pipelines, remove the separate installation of Argo Workflows from your cluster. Data Science Pipelines will be enabled automatically. 
====

include::modules/installing-the-odh-operator-v2.adoc[leveloffset=+1]

include::modules/installing-odh-components.adoc[leveloffset=+1]

include::modules/accessing-the-odh-dashboard.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
