:_module-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

[id="managing-workloads-with-kueue_{context}"]
= Managing workloads with Kueue

[role='_abstract']

As a cluster administrator, you can manage AI/ML workloads at scale by integrating the {rhbok-productname} with {productname-long}. This integration provides capabilities for quota management, resource allocation, and prioritized job scheduling.

ifndef::upstream[]
[IMPORTANT]
====
ifdef::self-managed[]
{rhbok-productname} is currently available in {productname-long} {vernum} as a Technology Preview feature.
endif::[]
ifdef::cloud-service[]
{rhbok-productname}  is currently available in {productname-long} as a Technology Preview feature.
endif::[]
Technology Preview features are not supported with {org-name} production service level agreements (SLAs) and might not be functionally complete.
{org-name} does not recommend using them in production.
These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information about the support scope of {org-name} Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====
endif::[]

include::modules/overview-of-managing-workloads-with-kueue.adoc[leveloffset=+1]

include::modules/migrating-to-the-rhbok-operator.adoc[leveloffset=+1]

include::modules/configuring-workload-management-with-kueue.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]