:_module-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

[id="managing-connection-types"]
= Managing connection types
:upstream:
//:preview:

ifdef::preview[]
include::../_artifacts/document-attributes-global.adoc[]
endif::preview[]

In {productname-long}, a connection comprises environment variables along with their respective values. Data scientists can add connections to project resources, such as workbenches and model servers. 

When a data scientist creates a connection, they start by selecting a connection type. Connection types are essentially templates that include customizable fields and optional default values. Starting with a connection type decreases the time required by a user to add connections to data sources and sinks. {productname-short} includes pre-installed connection types for S3-compatible object storage databases and URI-based repositories. 

As an {productname-short} administrator, you can manage connection types for users in your organization as follows:

* View connection types and preview user connection forms
* Create a connection type
* Duplicate an existing connection type
* Edit a connection type
* Delete a custom connection type
* Enable or disable a connection type in a project, to control whether it is available as an option to users when they create a connection

include::modules/viewing-connection-types.adoc[leveloffset=+1]

include::modules/creating-a-connection-type.adoc[leveloffset=+1]

include::modules/duplicating-a-connection-type.adoc[leveloffset=+1]

include::modules/editing-a-connection-type.adoc[leveloffset=+1]

include::modules/enabling-a-connection-type.adoc[leveloffset=+1]

include::modules/deleting-a-connection-type.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
