:_module-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

:productname-long: Open Data Hub
:productname-short: Open Data Hub

:context: bias-monitoring

[id="monitoring-models-for-bias_{context}"]
= Monitoring models for bias
:upstream:
//:preview:

ifdef::preview[]
include::../_artifacts/document-attributes-global.adoc[]
endif::preview[]

As a data scientist, you might need to monitor your machine learning models for bias. This means monitoring for algorithmic deficiencies that might skew the outcomes or decisions that the model produces. Importantly, this type of monitoring helps you to ensure that the model is not biased against particular protected groups or features.

{productname-long} provides a set of metrics that help you to monitor your models for bias. You can use the {productname-short} interface to choose an available metric and then configure model-specific details such as a protected attribute, the privileged and unprivileged groups, the outcome you want to monitor, and a threshold for bias. You then see a chart of the calculated values for a specified number of model inferences.

The sections that follow describe how to configure your models for bias monitoring and how to view and interpret the resulting metrics.

include::modules/configuring-bias-monitoring-cli.adoc[leveloffset=+1]

//include::modules/viewing-bias-metrics.adoc[leveloffset=+1]
== Viewing bias metrics for a model 

When you configure your model for bias monitoring, you can view the metrics that you configured.

.Prerequisites

* You configured bias metrics for your model as described in link:{odhdocshome}/monitoring-data-science-models/#configuring-bias-monitoring-for-a-model-cli_bias-monitoring[Configuring bias monitoring for a model].

* You have admin access to the OpenShift web console.

.Procedure

* From the *Administrator* perspective within the OpenShift web console, select *Observe* -> *Metrics*.

include::modules/supported-bias-metrics.adoc[leveloffset=+1]


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
