:_module-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

:productname-long: Open Data Hub
:productname-short: Open Data Hub

:context: bias-monitoring

[id="monitoring-model-bias_{context}"]
= Monitoring model bias
:upstream:
//:preview:

ifdef::preview[]
include::../_artifacts/document-attributes-global.adoc[]
endif::preview[]

As a data scientist, you might want to monitor your machine learning models for bias. This means monitoring for algorithmic deficiencies that might skew the outcomes or decisions that the model produces. Importantly, this type of monitoring helps you to ensure that the model is not biased against particular protected groups or features.

{productname-long} provides a set of metrics that help you to monitor your models for bias. You can use the {productname-short} interface to choose an available metric and then configure model-specific details such as a protected attribute, the privileged and unprivileged groups, the outcome you want to monitor, and a threshold for bias. You then see a chart of the calculated values for a specified number of model inferences.

The sections that follow describe how to configure and view your models for bias monitoring.

include::modules/creating-a-bias-metric.adoc[leveloffset=+1]

include::modules/duplicating-a-bias-metric.adoc[leveloffset=+2]

include::modules/deleting-a-bias-metric.adoc[leveloffset=+1]

include::modules/viewing-bias-metrics.adoc[leveloffset=+1]

include::modules/supported-bias-metrics.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
