:_module-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

:context: drift-monitoring

[id="monitoring-data-drift_{context}"]
= Monitoring data drift

[role='_abstract']

As a data scientist, you might want to monitor your deployed models for data drift. Data drift refers to changes in the distribution or properties of incoming data that differ significantly from the data on which the model was originally trained. Detecting data drift helps ensure that your models continue to perform as expected and that they remain accurate and reliable.

You can use data drift monitoring metrics from TrustyAI in {productname-long} to provide a quantitative measure of the alignment between the training data and the inference data. 

For information about the specific data drift metrics, see link:https://opendatahub.io/docs/monitoring-data-science-models/#supported-drift-metrics_drift-monitoring[Supported drift metrics].

include::modules/creating-a-drift-metric.adoc[leveloffset=+1]

include::modules/deleting-a-drift-metric-using-cli.adoc[leveloffset=+1]

include::modules/viewing-drift-metrics.adoc[leveloffset=+1]

include::modules/supported-drift-metrics.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
