:_module-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

[id="overview-of-ml-features-and-feature-store.adoc_{context}"]
= Overview of machine learning features and Feature Store

[role='_abstract']

ifndef::upstream[]
[IMPORTANT]
====
ifdef::self-managed[]
Feature Store is currently available in {productname-long} {vernum} as a Technology Preview feature.
endif::[]
ifdef::cloud-service[]
Feature Store is currently available in {productname-long} as a Technology Preview feature.
endif::[]
Technology Preview features are not supported with {org-name} production service level agreements (SLAs) and might not be functionally complete.
{org-name} does not recommend using them in production.
These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information about the support scope of {org-name} Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====
endif::[]

A machine learning (ML) feature is a measurable property or attribute within a data set that a machine learning model can analyze to learn patterns and make decisions. Examples of features include a customer's purchase history, demographic data like age and location, weather conditions, and financial market data. You can use these features to train models for tasks such as personalized product recommendations, fraud detection, and predictive maintenance.

Feature Store is a {productname-long} component that provides a centralized repository that stores, manages, and serves machine learning features for both training and inference purposes.

include::modules/audience-for-feature-store.adoc[leveloffset=+1]

include::modules/overview-of-ml-features.adoc[leveloffset=+1]

include::modules/overview-of-feature-store.adoc[leveloffset=+1]

include::modules/feature-store-workflow.adoc[leveloffset=+1]

include::modules/setting-up-feature-store-UI.adoc[leveloffset=+1]

== Additional resources

* For example Feature Store CRD configurations, see the
link:https://github.com/feast-dev/feast/tree/master/infra/feast-operator/config/samples[Feast Operator configuration samples^].

* For details about the Feast CRD APIs, see the 
link:https://github.com/feast-dev/feast/blob/stable/infra/feast-operator/docs/api/markdown/ref.md[Feast API documentation^].

* For information on how to implement machine learning features, see the
link:https://docs.feast.dev/getting-started/concepts[Feast documentation^].

* For end-to-end use case examples of how Feature Store can benefit your AI/ML workflows, see https://docs.feast.dev/getting-started/use-cases[Feast Getting Started: Use Cases].

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]

