:_module-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

[id="prepare-your-data-for-ai-consumption_{context}"]
= Prepare your data for AI consumption

[role='_abstract']
To prepare your data, use Docling to transform unstructured data (such as text documents, images, and audio files) into structured formats that models can consume. 

To automate data processing tasks, you can build Kubeflow Pipelines (KFP). For examples of pre-built pipelines for unstructured data processing with Docling, see link:https://github.com/opendatahub-io/data-processing[https://github.com/opendatahub-io/data-processing].

== Process data by using Docling

Docling is the Python library that you use to prepare unstructured data (like PDFs and images) for consumption by large language models. 

include::modules/explore-the-data-processing-examples.adoc[leveloffset=+1]

== Automate data processing steps by building AI pipelines

With Kubeflow Pipelines (KFP), you can automate complex, multi-step Docling data processing tasks into scalable workflows.

With the KFP Software Development Kit (SDK), you can define custom components and stitch them together into a complete pipeline. The SDK allows you to fully control and automate Docling conversion tasks with specific parameters.

*Note:* You can build a custom runtime image to ensure that all required Docling dependencies are present for pipeline execution. For information on how to run a Docling pipeline with a custom image see the link:https://github.com/opendatahub-io/data-processing/tree/main/kubeflow-pipelines[Docling Pipeline documentation].

include::modules/explore-the-kubeflow-pipeline-examples.adoc[leveloffset=+1]


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
