:_module-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

[id="setting-up-model-monitoring_{context}"]
= Setting up model monitoring

[role='_abstract']

To set up the TrustyAI feature for data scientists to use in {productname-short}, a cluster administrator must do the following tasks:

* Configure monitoring for the model serving platform
* Enable the TrustyAI component in the {productname-long} {install-package}
* Install the TrustyAI service on each data science project that contains models that the data scientists want to monitor

[NOTE]
====
Model monitoring (the TrustyAI feature) is supported only on a _multi-model serving platform_ that is based on the ModelMesh component. It is not supported on a _single-model serving platform_ that is based on the KServe component.
====

include::modules/configuring-monitoring-for-the-multi-model-serving-platform.adoc[leveloffset=+1]

include::modules/enabling-trustyai-component.adoc[leveloffset=+1]

include::modules/installing-trustyai-service.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]