:_module-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

:context: upgradev1

[id="upgrading-odh-v1-to-v2_{context}"]
= Upgrading Open Data Hub version 1 to version 2

[role='_abstract']
You can upgrade the Open Data Hub Operator from version 1 to version 2 by using the OpenShift console. 
For information about installing the Open Hub Operator, see link:{odhdocshome}/installing-open-data-hub[Installing Open Data Hub].

Upgrading Open Data Hub involves the following tasks:

. Upgrading the Open Data Hub Operator version 1.
. Installing Open Data Hub components.
. Accessing the Open Data Hub dashboard.

[NOTE]
--
Version 2 of the Open Data Hub Operator represents an alpha release, accessible only on the `fast` channel. Later releases will change to the `rolling` channel when the Operator is more stable.
--

include::modules/upgrading-the-odh-operator-v1.adoc[leveloffset=+1]

include::modules/installing-odh-components.adoc[leveloffset=+1]

include::modules/accessing-the-odh-dashboard.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]