:_module-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

:context: upgradev2

[id="upgrading-odh-v2_{context}"]
= Upgrading Open Data Hub version 2.0 to version 2.2

[role='_abstract']
You can upgrade the Open Data Hub Operator from version 2.0 or 2.1 to version 2.2 or later by using the OpenShift console. 

For information about upgrading from version 1 to version 2, see link:{odhdocshome}/upgrading-open-data-hub/#upgrading-the-odh-operator-v1_upgradev1[Upgrading Open Data Hub version 1 to version 2].

Upgrading Open Data Hub involves the following tasks:

//. Cleaning up resources from the previous version of {productname-short}.
. Reviewing and understanding the requirements for upgrading Open Data Hub version 2.
. Installing version 2.2 or later of {productname-short}.
. If you are using self-signed certificates, link:{odhdocshome}/upgrading-open-data-hub/#adding-a-ca-bundle-after-upgrading_upgradev2[adding a CA bundle].

//include::modules/cleaning-up-resources.adoc[leveloffset=+1]

include::modules/requirements-for-upgrading-odh-v2.adoc[leveloffset=+1]

include::installing-odh-v2.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]