:_mod-docs-content-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

[id="use-models-as-a-service_{context}"]
= Use models-as-a-service

:context: maas-user

[role='_abstract']
Use Models-as-a-Service (MaaS) to access large language models with built-in authentication, rate limiting, and governance. You can discover available models, generate authentication credentials, and integrate models into your applications using OpenAI-compatible APIs.

[IMPORTANT]
====
Models-as-a-service is currently available in {productname-long} {vernum} as a Technology Preview feature. Technology Preview features are not supported with {org-name} production service level agreements (SLAs) and might not be functionally complete.
{org-name} does not recommend using them in production.
These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information about the support scope of {org-name} Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====

include::modules/understanding-the-maas-dashboard-interface.adoc[leveloffset=+1]
include::modules/access-models-with-maas.adoc[leveloffset=+1]
include::modules/maas-user-access-troubleshooting.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
