:_module-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

[id="using-basic-workbenches_{context}"]
= Using basic workbenches

{productname-long} provides access to *Start basic workbench* as an enabled application for situations where, for example, you do not want users to have their own data science projects or you want to open a Jupyter notebook that was developed outside of {productname-short} and has no dependencies on other environments. 

ifndef::upstream[]
Note that the preferred way to access workbenches on {productname-short} is through a data science project, as described in link:{rhoaidocshome}{default-format-url}/working_on_data_science_projects/using-project-workbenches_projects#creating-a-workbench-select-ide_projects[Creating a workbench and selecting an IDE]. The advantages to using an {productname-short} data science project and creating a workbench that includes Jupyter, is that your project organizes your data science work in one place and adds functionality such as connections so that you can access data and save your models and pipelines for automating your ML workflow.
endif::[]
ifdef::upstream[]
Note that the preferred way to access workbenches on {productname-short} is through a data science project, as described in link:{odhdocshome}/working-on-data-science-projects/#creating-a-workbench-select-ide_projects[Creating a workbench and selecting an IDE]. The advantages to using an {productname-short} data science project and creating a workbench that includes Jupyter, is that your project organizes your data science work in one place and adds functionality such as connections so that you can access data and save your models and pipelines for automating your ML workflow.
endif::[]

include::modules/starting-a-basic-workbench.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
