:_module-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

[id='using-lab-tuning_{context}']
= Using LAB-tuning

ifndef::upstream[]
[IMPORTANT]
====
ifdef::self-managed[]
LAB-tuning is currently available in {productname-long} {vernum} as a Technology Preview feature.
endif::[]
ifdef::cloud-service[]
LAB-tuning is currently available in {productname-long} as a Technology Preview feature.
endif::[]
Technology Preview features are not supported with {org-name} production service level agreements (SLAs) and might not be functionally complete.
{org-name} does not recommend using them in production.
These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information about the support scope of {org-name} Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====
endif::[]

To customize a model with LAB-tuning in {productname-short}, complete the following tasks:

* Register a base model from the model catalog.
* Start a LAB-tuning run from the registered model.
* Monitor the run's progress.
* Review and deploy the fine-tuned model from the registry.

include::modules/registering-a-base-model.adoc[leveloffset=+1]

include::modules/starting-a-lab-tuning-run-from-the-registered-model.adoc[leveloffset=+1]

include::modules/monitoring-your-lab-tuning-run.adoc[leveloffset=+1]

include::modules/reviewing-and-deploying-your-lab-tuned-model.adoc[leveloffset=+1]
