:_module-type: ASSEMBLY

ifdef::context[:parent-context: {context}]

[id="using-the-jupyter-application"]
= Using the Jupyter application
:upstream:
//:preview:

ifdef::preview[]
include::../_artifacts/document-attributes-global.adoc[]
endif::preview[]

:context: jupyterapp
//for Jupyter tile
//other context that uses these files is jupyterwb for workbench

== Using the Jupyter application
{productname-long} provides access to Jupyter as an enabled application for situations where, for example, you do not want users to have their own data science projects or you want to open a notebook that was developed outside of {productname-short} and has no dependencies on other environments. 

ifndef::upstream[]
Note that the preferred way to access Jupyter on {productname-short} is through a data science project, as described in link:{rhoaidocshome}{default-format-url}/working_on_data_science_projects/working-on-data-science-projects_nb-server#creating-a-project-workbench_nb-server[Creating a workbench]. The advantages to using an {productname-short} data science project and creating a workbench that includes Jupyter, is that your project organizes your data science work in one place and adds functionality such as data connections so that you can access data and save your models and pipelines for automating your ML workflow.
endif::[]
ifdef::upstream[]
Note that the preferred way to access Jupyter on {productname-short} is through a data science project, as described in link:{odhdocshome}/working_on_data_science_projects/#creating_a_project_workbench[Creating a workbench]. The advantages to using an {productname-short} data science project and creating a workbench that includes Jupyter, is that your project organizes your data science work in one place and adds functionality such as data connections so that you can access data and save your models and pipelines for automating your ML workflow.
endif::[]


include::assemblies/creating-and-importing-notebooks.adoc[leveloffset=+1]


include::assemblies/collaborating-on-notebooks-by-using-git.adoc[leveloffset=+1]

== Managing Python packages

include::modules/viewing-python-packages-installed-on-your-notebook-server.adoc[leveloffset=+2]

include::modules/installing-python-packages-on-your-notebook-server.adoc[leveloffset=+2]

include::modules/troubleshooting-common-problems-in-jupyter-for-users.adoc[leveloffset=+1]


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
