:_module-type: ASSEMBLY

:context: certs

[id="working-with-certificates_{context}"]
= Working with certificates

//:preview:

ifdef::preview[]
include::../_artifacts/document-attributes-global.adoc[]
endif::preview[]

[role='_abstract']

Certificates are used by various components in {openshift-platform} to validate access to the cluster. For clusters that rely on self-signed certificates, you can add those self-signed certificates to a cluster-wide Certificate Authority (CA) bundle and use the CA bundle in {productname-long}. You can also use self-signed certificates in a custom CA bundle that is separate from the cluster-wide bundle. Administrators can xref:adding-a-CA-bundle_certs[add a CA bundle], remove a CA bundle xref:removing-a-ca-bundle_certs[from all namespaces] or xref:removing-a-ca-bundle-from-a-namespace_certs[from individual namespaces], or xref:managing-certificates_certs[manually manage certificate changes] instead of the system.

include::modules/understanding-certificates.adoc[leveloffset=+1]

include::modules/adding-a-ca-bundle.adoc[leveloffset=+1]

include::modules/removing-a-ca-bundle.adoc[leveloffset=+1]

include::modules/removing-a-ca-bundle-from-a-namespace.adoc[leveloffset=+1]

include::modules/managing-certificates.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
